### ISSUE TITLE
Router VPN

### ISSUE THREAD

**Issue by hoang-himself** [AdguardTeam/AdGuardVPNForWindows#101]
This doesn't really fit in any repository so I decided to post here.

I am wondering if the VPN will be available for routers, via openvpn, l2tp or any protocol possible.

**Comment by Chinaski1** [comment]
Hello @Smithienious 

It's definitely a good idea. In the future, we will consider the possibility of implementing it.

**Comment by Eugene-Savenko** [comment]
https://github.com/AdguardTeam/AdGuardVPNForAndroid/issues/18

**Comment by sererinn** [comment]
I also want to take the chance to ask for this to be considered.
Running an opnsense appliance at home and would love to be able to configure AdGuardVPN from there centrally for all my devices at home.
