### ISSUE TITLE
VPN gets detected

### ISSUE THREAD

**Issue by Tschoran** [AdguardTeam/AdGuardVPNForWindows#111]
Several sites detect that a VPN is used and block content.
Are there any techniques to avoid that? If so, please implement them.

**Comment by Chinaski1** [comment]
Hello @Tschoran 

Unfortunately, many popular websites try to block VPN providers or their data centres.
As a temporary solution, you can try to use another location to bypass the blocking.

And also please specify the list of sites where you encountered this sitation.

**Comment by Aydinv13** [comment]
Closed due to no response. You can reopen it anytime
