### ISSUE TITLE
AdGuardVPN for Linux

### ISSUE THREAD

**Issue by itsnotsaved** [AdguardTeam/AdGuardVPNForWindows#12]
AdGuard offer less support for linux (only AGH)
atleast provide command line tool as protonvpn
https://protonvpn.com/support/linux-vpn-tool/
https://github.com/ProtonVPN/linux-cli

**Comment by gistsy** [comment]
https://github.com/ProtonVPN/linux-gui

**Comment by Aydinv13** [comment]
Hi there! Thanks for feature request, we are planning to implement this feature in the future, but terms are undefined.

**Comment by Aikatsui** [comment]
@Aydinv13 @zzebrum A single build, all popular Linux distributions https://snapcraft.io/store
You may able to make only snap store app
