### ISSUE TITLE
Turkish language

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNForWindows#121]
Can you add Turkish language? I'm installing in Turkish, but the application doesn't work cause there is no Turkish language pack.
https://imgur.com/a/F7Wyui8

**Comment by Aydinv13** [comment]
Hi there!
We'll add it soon, thanks!

**Comment by Aydinv13** [comment]
@gork7777 we have fixed the problem with launch AdGuard VPN on Turkish system language, please check it on your side. Adding it to application is planned for the one of the next builds.

**Comment by gork7777** [comment]
Its working, thanks!
