### ISSUE TITLE
Exclusions not working for sub sub-domains

### ISSUE THREAD

**Issue by sd3993** [AdguardTeam/AdGuardVPNForWindows#122]
If an exclusion is added like *.gov.in'

The following sites are working - epfindia.gov.in, uidai.gov.in

The following sites are not working - passbook.epfindia.gov.in, ask.uidai.gov.in

**Comment by Aydinv13** [comment]
@sd3993 Have these subdomains been unblocked before with AdGuard VPN? Now I have **passbook.epfindia.gov.in** blocked due to security reasons both using VPN and not

**Comment by sd3993** [comment]
Yeah passbook.epfindia.gov.in seems to be suffering from a temporary issue but these 2 websites "https://ask.uidai.gov.in" and "https://unifiedportal-mem.epfindia.gov.in" work fine without VPN but don't load when connected to VPN even with the *.gov.in exclusion.
Screenshots attached.

![image](https://user-images.githubusercontent.com/5208748/128001599-e4a81474-6e2f-4a1a-8c15-d109aee7c2a3.png)

![image](https://user-images.githubusercontent.com/5208748/128001568-a892d80c-be2c-4af7-a706-0cd8f75aadeb.png)

**Comment by Aydinv13** [comment]
We can't reproduce your issue so we need you to send us tracelogs:

1. Shut down AdGuard VPN. Make sure that the service is not running as well. Open Task Manager → Services → Make sure that AdGuard VPN is turned off.
2. Open the console (type 'cmd' in search (WIN + S) or 'run' command (WIN + R).
3. Run the following command: `"Program Files (x86)"\AdguardVpn\AdguardVpn.exe /trace`
4. Go to Settings → General → Advanced settings → Logging level → Write everything.
5. Export logs via Settings → Main Actions → Export Logs.
6. Send us these logs to devteam@adguard.com 
Also remember the time you reproduced the issue, please.
