### ISSUE TITLE
System tray icon and pop-up notification icon is blurred

### ISSUE THREAD

**Issue by saurane** [AdguardTeam/AdGuardVPNForWindows#123]
VPN version: 1.0.286.0 stable
tray icon ss: https://imgur.com/a/2Jh0alP , https://imgur.com/a/WdTe1OF
pop-up notify ss: https://imgur.com/a/ZdTQlbT

Note: The pop-up icon problem is also present in the adguard windows version.

**Comment by northis** [comment]
Thank you for the report, we will fix this in future versions.

**Comment by northis** [comment]
@saurane Please, check out the latest release version 1.1.1. It should be ok now.

**Comment by saurane** [comment]
> @saurane Please, check out the latest release version 1.1.1. It should be ok now.

Not fixed.

**Comment by northis** [comment]
If you zoom the screenshot, you definitely get not really good images. But they aren't supposed to be zoomed actually.
Can you please give us another screenshot like this, with another apps in the same row:
![win-northgmuf7](https://user-images.githubusercontent.com/20269126/146915658-eefc60c7-159a-44e2-9677-4720c540c196.png)

**Comment by saurane** [comment]
> If you zoom the screenshot, you definitely get not really good images. But they aren't supposed to be zoomed actually. Can you please give us another screenshot like this, with another apps in the same row: ![win-northgmuf7](https://user-images.githubusercontent.com/20269126/146915658-eefc60c7-159a-44e2-9677-4720c540c196.png)
![ss](https://user-images.githubusercontent.com/87908352/147045110-849aedcc-cc5b-4528-a71a-fbcca959b246.png)

**Comment by northis** [comment]
@saurane Because we cannot reproduce the appearance from the screenshot you provided, we prepared a special test build, could you please check the tray icons in it?
https://uploads.adguard.com/AdGuardVpn-bug_AG-9484.exe

**Comment by saurane** [comment]
> @saurane Because we cannot reproduce the appearance from the screenshot you provided, we prepared a special test build, could you please check the tray icons in it? https://uploads.adguard.com/AdGuardVpn-bug_AG-9484.exe

The tray icon is fixed but the notification icon is not fixed.
![ss1](https://user-images.githubusercontent.com/87908352/147195499-9248c341-6032-4283-886c-5c708700eb1b.png)
