### ISSUE TITLE
Allow disabling splash screen in settings

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardVPNForWindows#129]
A splash screen appears on every Windows start-up. The option to turn this off seems to be missing in AdGuard VPN for Windows v1.0.2.

Helpdesk ID: 527287

**Comment by Aydinv13** [comment]
Does user mean the splash screen which appears after each launch of AdGuard VPN and not Windows? Screenshots would help us as well. If it's about Windows start up everything is ok on the latest build.
