### ISSUE TITLE
The app incorrectly shows the license

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/AdGuardVPNForWindows#134]
The app incorrectly shows the license when there is a premium license linked to the AdGuard account

Version: 1.1 nightly 3

![image](https://user-images.githubusercontent.com/16819380/129955664-897a6686-5693-4381-bd8a-3bb3078106dc.png)
![image](https://user-images.githubusercontent.com/16819380/129955841-7ff57bd5-7610-4bdd-89ea-0d6f04986d15.png)

**Comment by Aydinv13** [comment]
@eduardoaddad Hello!
Yes it's a known problem and it will be fixed asap) Thanks for your report.

**Comment by Aydinv13** [comment]
@eduardoaddad it was fixed.

**Comment by Aydinv13** [comment]
comment was updated in order to preserve privacy
