### ISSUE TITLE
Can't add subdomains e.g "*.int.example.com"

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardVPNForWindows#147]
Hi,

I have the corporate VPN based on OpenVPN (443/tcp). The task of this tunnel is routing traffic only to hosts *.int.example.com. Is it possible to make compatible this VPN and AdGuard VPN? Adding the IP and VPN domains to the exclusion list (including the wildcard) does not solve the problem. Maybe need to add a some private subnet? Please, advise!

Thank you.
Cheers😁

**Comment by Aydinv13** [comment]
@ammnt does excluding prefixes of your VPN from adguard vpn help (to find out use netstat -rn in terminal)?
As an alternative option try to add OpenVPN to AdGuard VPN's apps exclusions.

**Comment by ammnt** [comment]
@Aydinv13, no, it doesn't help - I already tried. But now i found a solution - I had to add IP records of these hosts to exclusions (DNS records type A), not domains. After that it worked! Maybe it's a bug. It is also possible that the bug is something I could not add to the wildcard exclusions level four domain - * .int.example.com. Only * .example.com.

**Comment by Aydinv13** [comment]
@ammnt seems like a bug, thank you for finding it.

**Comment by Aydinv13** [comment]
Сlarified this issue with the developers in more detail, it's not exactly a bug. For now it's our solution to add subdomains (e.g `*.int.example.com`- it will be enough to exclude all subdomains)and other configurations are not supported for this. The changes are not planned yet so I close this issue.
