### ISSUE TITLE
All login methods not working

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/AdGuardVPNForWindows#151]
All alternative login methods and the login method with Adgurd is not workingt the problem here.

![Captura de tela 2021-09-24 205734](https://user-images.githubusercontent.com/16819380/134750563-3c2b1545-f22d-41f1-9bb1-f75b7cb9b52b.png)

https://user-images.githubusercontent.com/16819380/134750570-88972c2d-361f-497a-a2be-b0cfb63827d1.mp4

**Comment by AleksandrShulgin** [comment]
Tell me please, which version of AdGuard do you use?

**Comment by AleksandrShulgin** [comment]
@eduardoaddad 
To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

1. Go to Settings --> General --> Advanced settings --> Logging level --> **Record everything**;
2. Reproduce the problem and remember the exact time it was reproduced at. We will need it to find the corresponding entries in the log file;
3. Go to Settings -> General -> **Export logs**;
4. Send the archive to `devteam@adguard.com` and mention this issue number in the subject. Don't forget to include the time of reproduction.
5. Set the logging level back to **Record by default**.
