### ISSUE TITLE
Login error when not connected to internet

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/AdGuardVPNForWindows#156]
When the internet connection is lost, the application disconnects from the account and asks to login again

![image](https://user-images.githubusercontent.com/16819380/136571310-a430c3d1-4323-453a-8f39-e5b18f2323e8.png)

**Comment by Aydinv13** [comment]
@eduardoaddad Hi!
The problem is related to [this one](https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/95) 
I'm closing this issue as a duplicate
