### ISSUE TITLE
Exceptions don't work for`baidu.com` and its subdomains

### ISSUE THREAD

**Issue by AleksandrShulgin** [AdguardTeam/AdGuardVPNForWindows#161]
### Precondition
VPN is OFF

### STR
1. Go to https://fanyi.baidu.com/ and https://baike.baidu.com/ --> Sites loaded well
2. Connect to a location with high ping and reload https://fanyi.baidu.com/ and https://baike.baidu.com/  --> UI loaded badly
3. Add these sites to the exclusion and reload them again

### Expected Behavior

Sites loaded well

### Actual Behavior

UI loaded badly

### Screenshots

![](https://uploads.adguard.com/shulgin2tlxq.png)

### Additional Information

This happens for`baidu.com` and its subdomains

**Comment by adbuker** [comment]
related to https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/128
