### ISSUE TITLE
AdGuard crashes when trying to update with Portuguese languages

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/AdGuardVPNForWindows#168]
When you try to get update while downloading causes the application to close abruptly (happens when changing the languages of English for Brazilian Portuguese or European Portuguese)

 Version: 1.1 nightly 10

![image](https://user-images.githubusercontent.com/16819380/139729402-debe5599-7059-4941-854d-c385c68c090c.png)

The language file is missing although it appears in the language selector in AdGrd VPN

```
ERROR, AdGuardVpn, 1, 01.11.2021 15:50:06.428, Cannot load assembly C:\Program Files (x86)\AdGuardVpn\langs\AdGuardVpn.UI.resources.pt-BR.dll
INFO, AdGuardVpn, 1, 01.11.2021 15:50:06.429, Fallback from pt-BR to pt
ERROR, AdGuardVpn, 1, 01.11.2021 15:50:06.429, Cannot load assembly C:\Program Files (x86)\AdGuardVpn\langs\AdGuardVpn.UI.resources.pt.dll
INFO, AdGuardVpn, 1, 01.11.2021 15:50:06.434, Assembly C:\Program Files (x86)\AdGuardVpn\AdGuardVpn.UI.dll has been loaded
```

**Comment by Aydinv13** [comment]
It's definitely an issue, thank you
