### ISSUE TITLE
Can't close an app properly when system dialog window is opened 

### ISSUE THREAD

**Issue by Aydinv13** [AdguardTeam/AdGuardVPNForWindows#173]
### Issue Details
1. Install the latest version AG VPN for Windows
2. Go to Settings-> General-> Export logs
3. Leave system window open and close an app via tray menu "Exit AdGuard VPN"

### Expected Behavior

App is closed 
### Actual Behavior

App is not closed with any system dialog window is open
### Video

<details><summary>Video:</summary>

https://uploads.adguard.com/Aydini3kwp.mp4

</details>

**Comment by ameshkov** [comment]
Tbh, this is expected
