### ISSUE TITLE
AdGuard VPN freezes when disconnecting

### ISSUE THREAD

**Issue by Aydinv13** [AdguardTeam/AdGuardVPNForWindows#175]
Some users face this problem

https://user-images.githubusercontent.com/73467237/141297158-5a2f99b6-cd7b-4ea0-b040-455d60e9df86.mov

### Additional Information

Ticket numbers 551651, 543744, 553596, 553197, 554049, 587524, 587414

**Comment by AlKulagin23** [comment]
Solution:

1) Stop AG VPN process in Task Manager;
2) Copy with replacement to `%programfiles%/adguardvpn` (the directory where AG VPN is located) the file from the archive attached;
3) Run AG VPN and check it.

[AGIpHelperClose.zip](https://github.com/AdguardTeam/AdGuardVPNForWindows/files/7607445/AGIpHelperClose.zip)

**Comment by Aydinv13** [comment]
The latest nightly version includes the fix of this problem. Should work fine [here](https://agrd.io/windows_vpn_nightly).

**Comment by keshapudelev** [comment]
> The latest nightly version includes the fix of this problem. Should work fine [here](https://agrd.io/windows_vpn_nightly).

Not working at all from Russia

**Comment by keshapudelev** [comment]
Btw, after several reboots, the production version of app seems like works ok, may be local OS bugs or smth... Sorry for my report.

**Comment by adbuker** [comment]
@keshapudelev, feel free to bother us about any problems

**Comment by raykai** [comment]
When I try to disconnect the VPN It stays looping on Disconnecting…  
Testing the IP on what’s my IP is also showing I’m still on the VPN. 
The only way to disconnect from the VPN is to either kill the VPN process or reboot the system. 

I’m running the **AdGuard VPN Version 1.2.519.0**
On newly installed windows 11 (fully new reinstall) Version: 
Edition  Windows 11 Pro
Version 21H2
Installed on         ‎6/‎20/‎2022
OS build               22000.739
Experience         Windows Feature Experience Pack 1000.22000.739.0

![Snipaste_2022-06-25_12-02-10](https://user-images.githubusercontent.com/8138894/175782492-2617f0c4-97ac-40ca-b581-dbb244d5fdbf.png)


![Snipaste_2022-06-25_12-02-24](https://user-images.githubusercontent.com/8138894/175782510-9038ab89-69dc-43ff-92a1-e6dcbba9c157.png)

**Comment by Aydinv13** [comment]
@raykai  Could you try the latest nightly [build](https://agrd.io/windows_vpn_nightly) and check if the problem persists?

**Comment by spectj** [comment]
До сих пор зависает при отключении. Ничего не исправили. У меня весь июль зависает. Вырубаю через процессы

**Comment by Aydinv13** [comment]
по этой проблеме создана еще одна задача https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/263

**Comment by northis** [comment]
@spectj Пожалуйста, можете прислать нам на почту devteam@adguard.com логи последней версии (1.3 nightly 11)? Нужны файлы из папки `%programdata%\AdguardVpn\Logs`. Будет идеально, если перед воспроизведением проблемы выставить настройку "Записывать всё" в "Расширенных настройках".
