### ISSUE TITLE
the latest nightly version 1.2 nightly 3 doesn't work

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/AdGuardVPNForWindows#180]
the latest nightly version 1.2 nightly 3 doesn't work

**Comment by adbuker** [comment]
@eduardoaddad , could you please specify, what the issue is more precisely?

**Comment by offhub** [comment]
AdguardVpn.exe crashes at start.

**Comment by adbuker** [comment]
@offhub, @eduardoaddad, unfortunately, we can't repro it on our end. Could you please grab and send detailed logs (log-level "everything") once the issue occurs. Btw, do you use "socks5" mode or the "vpn" one?

**Comment by adbuker** [comment]
Seems, we've found a bug, today we'll publish a fix

**Comment by offhub** [comment]
I did a clean install and it still crashes at start. (AdGuardVpn.exe)

Windows 10 Pro
cFosSpeed 11/12

**Comment by ameshkov** [comment]
@adbuker 

```
00000000 00000001 mscorlib_ni!System.Reflection.RuntimeAssembly.nLoadFile+0xffffffff8c86f3a1
00afe5f8 72985cb6 mscorlib_ni!System.Reflection.Assembly.LoadFile+0x4e
00afe60c 068cd1cd AdGuardVpn_UI!taVilRkjInUH6JDmiYV.CpiS1EJuY+0xd
00afe614 068cce12 AdGuardVpn_UI!AdGuardVpn.UI.Properties.SingleFolderResourceManager.Jd6yV0HJbe+0x7a
00afe630 068cc466 AdGuardVpn_UI!AdGuardVpn.UI.Properties.SingleFolderResourceManager.gnCywLJSb8+0x356
00afe690 068ca679 AdGuardVpn_UI!AdGuardVpn.UI.Properties.SingleFolderResourceManager.InternalGetResourceSet+0xb9
00afe6b0 721fbd09 mscorlib_ni!System.Resources.ResourceManager.GetString+0x199
00afe70c 068ca5a7 AdGuardVpn_UI!M0RJwuxhniaadJGHR2M.CpiS1EJuY+0x17
00afe720 068c9c3f AdGuardVpn_UI!AdGuardVpn.UI.Properties.Resources.get_PopupVpnConnected+0x3f
00afe730 068c931c AdGuardVpn!AdGuardVpn.Tray.TrayPopupManager..ctor+0x3c
00afe758 05773713 UNKNOWN!DynamicClass.lambda_method+0x2b
00afe760 058b5c9e AdGuard_Utils!TinyIoC.TinyIoCContainer.SWIWtsiVy+0x56
```

Is it fixed?

**Comment by adbuker** [comment]
@eduardoaddad, do you use [nightly 4](https://static.adguard-vpn.com/windows/nightly/installer-1.2.381.0.exe)?

**Comment by ameshkov** [comment]
It's @offhub who has the issue now.

**Comment by adbuker** [comment]
my bad, @offhub, could you please also send the logs, located in `%programdata%/adguardvpn/logs`

**Comment by adbuker** [comment]
@offhub, thanks for the logs, we've found the bug and the fix will be published today
