### ISSUE TITLE
Is there a way to backup/restore Split tunneling settings?

### ISSUE THREAD

**Issue by offhub** [AdguardTeam/AdGuardVPNForWindows#181]
Configuring the 'Split tunneling' settings manually is time consuming after new installation or reinstallation.

Windows 10
AdGuard VPN Nightly 1.2.371.0

**Comment by Aydinv13** [comment]
We are going to significantly rework the Split tunneling feature in the nearest future. It will also be possible to export and import settings, which applies to split tunneling as well.
