### ISSUE TITLE
When adding an app to Split tunneling a "Something went wrong" error occurs

### ISSUE THREAD

**Issue by Aydinv13** [AdguardTeam/AdGuardVPNForWindows#194]
Ticket number: 560473, 554701, 562088

**Comment by InputOutputs** [comment]
Quite a big issue for me as can't really use the VPN until fixed :-)

**Comment by Aydinv13** [comment]
Please check the problem on the latest [Nightly](https://agrd.io/windows_vpn_nightly). This should no longer be reproduced
