### ISSUE TITLE
VPN not working after reconnect

### ISSUE THREAD

**Issue by antek821** [AdguardTeam/AdGuardVPNForWindows#195]
### Issue Details

- **AdGuard VPN version:**
 1.1.366.0
- **VPN mode:**
VPN
- **Operating system and version:**
Windows 10 (21H2, compilation: 19044.1415)
- **Other network-level software:**
None

### Expected Behavior

VPN still working after reconnect in app (the appropriate VPN status on test page in the eighth step from the "Actual behavior" section)

### Actual Behavior

Steps to reproduce:
1. Open Adguard VPN
2. Connect to any VPN server
3. Open browser (e.g. Edge, Chrome), then open page: [https://adguard.com/en/test.html](https://adguard.com/en/test.html). Now network traffic from browser goes through Adguard VPN
4. DIsconnect VPN server
5. Refresh Adguard test page. You will see that there is no connection to the VPN server and that's ok
6. Try connect again with VPN server in Adguard VPN.
7. Refresh Adguard test page.
8. And there is still information, that browser traffic does not go through VPN. Even after hard refresh (Ctrl + F5)

### Video

I recorded these videos by testing the problem in a virtual machine:
[Chrome](https://streamable.com/dy9g5y)
[Edge](https://streamable.com/6fx81j)

**Comment by Aydinv13** [comment]
You can launch the browser in a stealth mode to make sure VPN is working. I don't see any problems on my side. By the way, Gifs you provided show that the status on the test page changes after every connecting/disconnecting.

**Comment by antek821** [comment]
@Aydinv13 I've edited first post, because GIF's were shortened by accident. Please watch it again

And yes, you have right. When in step 7 I launch browser in stealth mode or restart browser, VPN work properly.
But this is about the situation where the browser loses its redirect through the VPN server without restarting or opening new window/session. This probably happens with other programs, and after reconnect in the Adgurad VPN, all programs without restarting lose VPN tunneling

**Comment by antek821** [comment]
Can anyone confirm the occurrence of this error?

**Comment by Aydinv13** [comment]
If the info on the test webpage is not as expected it doesn't mean that browser loses its redirect through the VPN server. Due to the nature of the browser, it may take a long time before the information on the page is updated. You can simply use different webpage to make sure that VPN tunnel is starting up after reconnect.

**Comment by antek821** [comment]
@Aydinv13 
Ok if you prefer an example of something that is not a browser:
1. Connect to VPN Server in AdGuard VPN for Windows
2. Open Windows PowerShell as administrator
3. Paste command: `(Invoke-WebRequest ifconfig.me/ip).Content.Trim()` and run it - will return VPN server IP
4. Disconnect with VPN
5. Run command from 3. step - now you see your real IP
6. Connect to VPN server
7. Run command from 3. step, and... again you will see your real IP address

This is proof that every application after VPN disconnect loses VPN tunneling (without restart the app) when we try reconnect with VPN server

**Comment by antek821** [comment]
Another anomaly which I reproduced on my private computer with Network Monitor tool from Kaspersky Internet Security 21:
1. Connect to VPN Server in AdGuard VPN for Windows
2. Open Network Monitor from Kaspersky
3. Open Telegram Desktop - everything works fine
4. Look at Network Monitor: there is no any Telegram connection visible, because it's tunneling by Adguard VPN client, and that's allright - i suppose
5. Disconnect VPN server
6. Look at Network Monitor: now you will see some Telegram connection
7. Connect to VPN server
8. Look at Network Monitor: Telegram connections is still here, so I understand that Telegram Desktop now is not tunneling and not using VPN connection.

Can you explain how it should works?

**Comment by Aydinv13** [comment]
Thanks for your examples, we'll check it out.

**Comment by northis** [comment]
@antek821
> 3. Paste command: `(Invoke-WebRequest ifconfig.me/ip).Content.Trim()` and run it - will return VPN server IP

There are some possible explanations of this behavior. First of all, we've caught a situation when 
`curl ifconfig.me/ip` gets the IP from the VPN endpoint and `(Invoke-WebRequest ifconfig.me/ip)` still returns the real IP.

This can be because of caching. It would be better to check with curl utility.
To be sure the traffic goes through the VPN, you can run `tracert example.org` command. Without VPN you will see a real route from your computer to the server. If you connect the VPN, you won't see such route.

**Comment by antek821** [comment]
@northis Ok, and what with visible connections in Kaspersky tool?  This is quite strange, and i am not sure if the traffic is really tunneled by the vpn server. Is there any tool/way to make sure everything is working as it should?
