### ISSUE TITLE
Change name of `System default` and its description

### ISSUE THREAD

**Issue by Aydinv13** [AdguardTeam/AdGuardVPNForWindows#199]
### Issue Details

1. The latest AG VPN is installed
2. Turn on VPN (any location)
3. Check your DNS (https://adguard.com/en/test.html or [dnsleaktest.com](https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/dnsleaktest.com))- it should be your ISP
4. Go to Settings-> General-> Add custom DNS server
5. Add tls://dns.adguard.com
6. Check that it's detected as expected (https://adguard.com/en/test.html or [dnsleaktest.com](https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/dnsleaktest.com))
7. Switch to System default and check DNS status

### Expected Behavior

DNS is defined as your ISP

### Actual Behavior

Non-filtering DNS server is displayed

**Comment by northis** [comment]
We only will rename `System default` to just `Default`. The behavior is by design, this isn't a bug. We use AdGuard Unfiltered DNS server as default one while connected.
