### ISSUE TITLE
Add 'selective' mode for app split tunneling.

### ISSUE THREAD

**Issue by deNoor** [AdguardTeam/AdGuardVPNForWindows#211]
I want to use VPN for specific app only.

**Comment by Aydinv13** [comment]
Thanks for the request, it'll be implemented

**Comment by MatyCZ** [comment]
This is the only feature I miss in AdGuard VPN, I hope it will be implemented soon.

**Comment by Aga-C** [comment]
This missing feature is the only reason why I have to use Adguard VPN add-on in my browser, unlike my phone, where it's necessary to use Adguard VPN app almost for all apps.

**Comment by KevinGu0611** [comment]
I also very much hope that developers will develop this feature.
