### ISSUE TITLE
AdGuard VPN causes The Elder Scrolls Online to disconnect

### ISSUE THREAD

**Issue by offhub** [AdguardTeam/AdGuardVPNForWindows#212]
AdGuard VPN causes The Elder Scrolls Online (eso64.exe) game to disconnect from time to time.

You can reproduce this issue with by simply clicking disconnect from the app.

### Issue Details

- **AdGuard VPN version:**
  - AdGuard VPN 1.2 nightly 14 (the issue was happening with previous versions too, like about a month?)
- **VPN mode:**
  - SOCKS5
- **Operating system and version:**
  - Windows 10
- **Other network-level software:**
  - Adguard 7.9 nightly 17
  - cFosSpeed 12.00.2512

### Expected Behavior

Not to disconnect.

### Actual Behavior

Causes game to disconnect from time to time.

</details>

### Additional Information

If I close the application, I can play without any problems.

I don't know if it's related to the issue but in the logs I have these entries:

**Comment by Aydinv13** [comment]
Closed due to no response. Reopen anytime, please.
