### ISSUE TITLE
Change kill-switch behavior

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardVPNForWindows#213]
### Expected Behavior

Drop network if the VPN connection is not established regardless of the cause.
Same for Mac and Android.

**Comment by adbuker** [comment]
If the VPN connection fails due to so-called "inner " causes (connectivity problem, etc.), kill-switch option of course blocks the network, but if the user disconnects from any endpoint manually it's better to allow him to use the internet without our interruptions
