### ISSUE TITLE
Gmail added to Inbox Windows 10 doesn't sync

### ISSUE THREAD

**Issue by Perfectlynk** [AdguardTeam/AdGuardVPNForWindows#214]
### Issue Details

- **AdGuard VPN version:**
  - (1.2.441.0)
- **VPN mode:**
  - (Local VPN)
- **Operating system and version:**
  - (Windows 10 19043.1526)
- **Other network-level software:**
  - (Adguard, Emsisoft Anti-Malware and Glasswire)

### Expected Behavior

Adding Gmail to Inbox doesn't update/sync

### Actual Behavior

Adding Gmail for Inbox when opened won't sync (nothing happens), clicking the sync in Inbox just has the moving loading dots.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

Turning off the VPN fixes the issue.

**Comment by Aydinv13** [comment]
Sorry for the late response. We were able to reproduce the problem so we'll work it out. Thank you
