### ISSUE TITLE
Location isn't saved in the left section after disconnecting

### ISSUE THREAD

**Issue by Aydinv13** [AdguardTeam/AdGuardVPNForWindows#243]
### Issue Details

1. Clean install of the latest version
2. Connect to any location
3. Click on Disconnect button

### Expected Behavior

The used location is displayed in the left section
### Actual Behavior

It disappears
### Screenshots

<details><summary>Video:</summary>

https://user-images.githubusercontent.com/73467237/161570689-73dfb931-52b4-4ee7-9eb3-2988a92eadf2.mp4
</details>

**Comment by adbuker** [comment]
In fact it's not a bug. By clicking on "Connect" button without selecting location you force AdGuard VPN to connect to fastest location. In case of disconnecting from the fastest location, AdGuard VPN should provide you an ability to choose the fastest location next time. So the first fastest location doesn't saved in left-bottom corner.
