### ISSUE TITLE
Different server speeds

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNForWindows#245]
The extension also has slower speeds, but the windows app has higher speeds. For example, Turkey's(nearest location to me) speeds are almost very different. Are different servers being used?

Windows:
![image](https://user-images.githubusercontent.com/35523759/162072236-39c244b4-8966-4cc8-94e6-12226f56b831.png)

Extension:

![image](https://user-images.githubusercontent.com/35523759/162072304-f5434d4e-25ac-4c5a-82a2-3d21dcd5713b.png)

**Comment by Aydinv13** [comment]
The servers that being used are the same. Our devs are looking into this issue.
