### ISSUE TITLE
Conflict with Kaspersky antiviruses

### ISSUE THREAD

**Issue by NUser2018** [AdguardTeam/AdGuardVPNForWindows#248]
Обнаружил у Adguard VPN для Windows серьёзный конфликт с антивирусами от Kaspersky (в моем случае это Kaspersky Internet Security (текущая релизная версия 21.3.10.391) (на всякий случай укажу и текущий актуальный патч у антивируса - это патч i). Но наверняка конфликт одинаков и для других продуктов от Kaspersky где есть проверка\контроль сетевого трафика.

Adguard VPN для Windows текущая актуальная релизная версия, которая устанавливается при установке через веб-установщик скачиваемый с официального сайта Adguard VPN (на данный момент это версия 1.2.497.0).

Windows 10 Pro 21H2 x64 (64-битная). Обновления ОС устанавливаются регулярно.

Проблема актуальна для Adguard VPN для Windows и не актаульна для дополнений Adguard VPN для браузеров, проверял только на примере дополнения для Firefox.

Суть проблемы в том что несмотря на то что приложение Adguard VPN для Windows показывает что VPN-соединение подключено к выбранному VPN-серверу, но по факту вероятно подключение всё же не установлено, поскольку сайты заблокированные провайдером остаются заблокированными и сервисы проверки IP-адреса (например [2ip.ru](https://2ip.ru/)) показывают мой реальный IP-адрес и провайдера а не данные от VPN-сервиса.

Кроме того наблюдаются странности при подключении VPN-соединения: а именно при нажатии на кнопку подключения VPN-соединения начинается процесс соединения с VPN-сервером в ходе которого сначала показывается уведомление что  VPN-соединение **отключено** (хотя оно ранее не было ещё подключено!) затем что VPN-соединение подключено. Такое же "пермаргивание" происходит у статуса VPN-соединения (типа подключено\отключено\подключено) и в самом приложении Adguard VPN для Windows. В конечном итоге VPN-соединение отстается в статусе подключено но по факту видимо всё же не подключается (подробные симптомы описаны выше).

Как удалось выяснить решить проблему помогает либо выгрузка\закрытие антивируса (приостановку защиты в антивирусе без полной его выгрузки честно говоря пока не пробовал) либо настройка в антивирусе исключения проверки зашифрованного трафика для службы Adguard VPN в системе Windows (Adguard VPN Service) (её файл находится по пути C:\Program Files (x86)\AdGuardVpn\AdGuardVpnSvc.exe).

Настройка такого исключения хотя и решает проблему, но конечно является нежелательной, поскольку скорее всего исключает трафик проходящий через Adguard VPN  при его работе из-под контроля\проверки антивирусом на вредоносные\опасные объекты\контент\трафик. Возможно в этом случае вредоносные\опасные объекты\контент будут всё-равно блокироватся но уже не на уровне трафика а на уровне браузера и т.д., но это ещё нужно проверять и в любом случае снижает уровень антивирусной защиты\безопасности и соответственно является нежелательным. 

В качестве основного я использую другой VPN-сервис (не буду его здесь указывать, не хочу, да и реклама конкурента здесь ни к чему) и у него такой прблемы\конфликта не наблюдается. Также ранее пользовался и другими  VPN-сервисами и никогда ранее с такой проблемой\конфликтом я не сталкивался.

Adguard VPN использую в бесплатном варианте.
Решил попробовать пока в качестве запасного\дополнительного варинта поскольку давно уже использую **блокировшик рекламы** от Adguard (Adguard для Windows) и очень доволен как качеством и работой продукта так и качеством работы команды поддержки и разработки продуктов Adguard, включая помощь в решении возникающих ранее вопросов\проблем.

Проблема\конфликт на мой взгляд является серьёзной и требует как можно более оперативного изучения и исправления.

Настройка данного исключения в антивирусе выполняется следующим образом:
Главное окно антивируса->кнопка Больше функций->Управление программами->Контроль программ->кнопка-ссылка Управление программами->в открывшемся списке находим подруппу ADGUARD а уже внутри неё из вариантов Adguard VPN for Windows (поскольку Adguard VPN состоит из нескольких модулей\процессов) находим именно тот что соответствует AdGuardVpnSvc.exe и в его свойствах (пункт Подробности и правила в контекстном меню у данного пункта в списке в антивирусе) на вкладке Исключения включаем (установив галочку) исключение Не проверять зашифрованный трафик после чего нажимем кнопку сохранения внесенных изменений и дополнительно выбираем\нажимаем Да в дополнительном запросе подтверждения применения этого изменения.

Со своей стороны готов оказать разумную посильную помощь в изучении и решении этой проблемы.
Если что пишите здесь в этой задаче на GitHub, я подпишусь на уведомления на эл. почту по ней.

**UPDATE 19.04.2022: Нашёл особое условие\настройку антивируса, которая влияет на воспроизведение проблемы, подробнее в новом отдельном сообщении [ЗДЕСЬ](https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/248#issuecomment-1102733835).**

**Comment by Aydinv13** [comment]
Спасибо за детальную информацию, мы изучаем этот вопрос, но пока что на нашей стороне воспроизвести проблему не удалось. 
Подскажите, насколько стабильно повторяется проблема, при которой показывается ваш реальный IP-адрес? Вы проверяли IP только на одном тестовом сайте (2ip.ru)? Это стало происходить именно в данной версии Adguard VPN (1.2.497.0)? По проблеме со странностями при подключении VPN-соединения не могли бы вы записать короткое видео?
Просьба проверить поведение AdGuard VPN на [этом билде](https://uploads.adguard.com/AdGuardVpn-feature_AG-12605.exe) (в котором мы обновили драйвера) и в случае, если проблема повторится, пришлите трейсовые логи, пожалуйста:
1) Переключитесь детальный на уровень логирования в приложении AdGuard VPN (Настройки - Основные - Расширенные настройки - Записывать все)
2) Завершите процесс AdGuard VPN через трей меню
3) Откройте командную строку `cmd` и вставьте команду `C:\"Program Files (x86)"\AdguardVpn\AdguardVpn.exe /trace`
4) Воспроизведите проблему и запомните время воспроизведения
5) Завершите процесс AdGuard VPN
6) Пришлите логи на почту devteam@adguard.com

**Comment by NUser2018** [comment]
Здравствуйте, уважаемый @Aydinv13

> Подскажите, насколько стабильно повторяется проблема, при которой показывается ваш реальный IP-адрес?

Постоянно. Но суть проблемы же не только в этом. Как я уже писал ранее:

"Суть проблемы в том что несмотря на то что приложение Adguard VPN для Windows показывает что VPN-соединение подключено к выбранному VPN-серверу, но по факту вероятно подключение всё же не установлено, поскольку _**сайты заблокированные провайдером остаются заблокированными**_ и сервисы проверки IP-адреса (например [2ip.ru](https://2ip.ru/)) показывают мой реальный IP-адрес и провайдера а не данные от VPN-сервиса."

Т.е. по сути VPN как-будто бы и вовсе не работает, несмотря на то что показывает что подключено.

> Вы проверяли IP только на одном тестовом сайте (2ip.ru)?

На других тоже аналогично. Но и как я уже напомнил выше основная суть проблемы не только в отображении реального IP-адреса.

> Это стало происходить именно в данной версии Adguard VPN (1.2.497.0)?

Не могу сказать точно. Давно уже не использовал Adguard VPN. Поскольку в качестве основного пока как уже и писал ранее я использую другой VPN.

Когда-то давно уже пробовал Adguard VPN и тогда вообще при подключении Adguard VPN в системе просто отрубался весь Интернет вообще. Но это сейчас пожалуй можно и не учитывать поскольку сейчас симптомы воспроизведения проблемы другие и кроме того это было давно и с тех пор уже выполнялась полная переустановка Windows (в связи с заменой аварийного системного HDD) и всего софта.

> По проблеме со странностями при подключении VPN-соединения не могли бы вы записать короткое видео?

Записал.  Будет приложено в письме вместе с логами.

> Просьба проверить поведение AdGuard VPN на [этом билде](https://uploads.adguard.com/AdGuardVpn-feature_AG-12605.exe) (в котором мы обновили драйвера) и в случае, если проблема повторится, пришлите трейсовые логи, пожалуйста

Собрал, Пришлю в письме на указанную Вами почту.
Обращаю внимание что после  установки программы по Вашей ссылке (1.2.505.0) программой была также показана информация о том что уже доступна более новая версия (1.2.507.0), поэтому сначала я проверил наличие проблемы на предоставленной Вами версии, потом обновл её до более новой и уже на этой версии (1.2.507.0) собрал терйсы\логи по Вашей инструкции.

Кроме того в сценарий воспроизвдения проблемы при сборе логов помимо симптома\сценария проверки и отображения реального IP-адреса я включил\воспроизвел также симптом\сценарий "сайты заблокированные провайдером остаются заблокированными" на пример одного такого сайта.

Спасибо что ответили здесь на ГитХабе но я также писал Вам и в личку на официальном форуме Adguard (мой ник там **ADGUser2017**), так что если что можете писать не только здесь (что лучше всего конечно наверное) но и\или там в личке на форуме и\или на почту с которой будет отправлено письмо с видео и логами.

Некоторое время назад нам с Вами кстати напомню удалось успешно вместе решить проблему обновления фильтров у блокировщика рекламы Adguard для Windows, надеюсь что и эту проблему теперь уже с Adguard VPN нам также вместе удастся решить.

**_P.S.: когда отправлю письмо на почту с логами и видео то напишу здесь дополнительно отдельное сообщение об этом._**

**Comment by NUser2018** [comment]
> P.S.: когда отправлю письмо на почту с логами и видео то напишу здесь дополнительно отдельное сообщение об этом.

Отправил письмо на указанную Вами эл. почту.

**Comment by NUser2018** [comment]
Почему до сих пор стоит метка **waiting for data**? 
Ведь все запрошенные данные уже давно мною были предоставлены (как здесь так и на указанную Вами почту). Только вот никакой реакции\комментариев со стороны сотрудников Adguard об их обработке\получении почему-то так и не было до сих пор.

**Comment by NUser2018** [comment]
**ВАЖНО!** От [сотрудника](https://forum.adguard.com/index.php?members/aydin.43313/) Adguard через личные сообщения на официальном форуме Adguard получено сообщение что моё письмо на указанную ранее здесь почту почему-то не получено\не пришло. Поэтому логи и видео упоминавшиеся здесь ранее отправлены повторно но уже не на почту а к нему в личные сообщения на официальном форуме Adguard.

**Comment by Aydinv13** [comment]
Спасибо за предоставленную информацию, логи получили, будем изучать.

**Comment by Aydinv13** [comment]
@NUser2018 проблема повторяется на нашей стороне, постараемся исправить ее в одном из ближайших релизов.

**Comment by NUser2018** [comment]
@Aydinv13 Ну пишите тогда когда хотя бы на nightly-канале появится фикс который можно и нужно будет мне проверить. Пока откачусь на релизную версию.

**Comment by NUser2018** [comment]
> проблема повторяется на нашей стороне, постараемся исправить ее в одном из ближайших релизов.

Ну тогда пишите когда хотя бы на nightly-канале появится фикс который можно и нужно будет мне проверить.

**Comment by Aydinv13** [comment]
@NUser2018 само собой, как появится апдейт, напишем сразу.

**Comment by NUser2018** [comment]
По данной проблеме есть какие-то подвижки\новости? Её собираются исправлять? А то пока вижу здесь только перенос с версии 1.3 аж на 2.0. На текущей актуальной релизной версии Adguard VPN 1.3.2 (1.3.603) проблема всё ёщё актуальна разумеется.

**Comment by adbuker** [comment]
@NUser2018 , 2.0 - это следующая релизная версия, мы обновим UI движок и много изменений под капотом. Не могли бы вы проверить на последней доступной [найтли](https://static.adguardvpn.com/windows/nightly/installer-2.0.664.0.exe)

**Comment by NUser2018** [comment]
> Не могли бы вы проверить на последней доступной [найтли](https://static.adguardvpn.com/windows/nightly/installer-2.0.664.0.exe)

ОК, хорошо, постараюсь проверить на этой неделе и напишу конечно же здесь о результате, но скорее всего пока не смогу проверить и сегодня и завтра, т.е. скорее всего не ранее чем послезавтра (т.е. не ранее чем в среду), но если смогу проверить раньше, то конечно же сразу напишу об этом здесь.

**Comment by NUser2018** [comment]
> Не могли бы вы проверить на последней доступной [найтли](https://static.adguardvpn.com/windows/nightly/installer-2.0.664.0.exe)

@adbuker Проверил и на nightly v.2.x к сожалению проблема ожидаемо пока сохраняется и там тоже. Когда будут ещё какие-то комментарии\новости по проблеме пишите здесь, чем смогу обязательно помогу.

**Comment by adbuker** [comment]
@NUser2018 , спасибо, обязательно отпишусь как только решим проблему!

**Comment by NUser2018** [comment]
Adguard VPN (у меня для Windows) обновился до версии 2.0 (2.0.765.0) и я решил проверить эту проблему снова, тем более ещё пришло уведомление на электронную почту о закрытии данной задачи здесь на ГитХабе.

Результат проверки неоднозначный... 

Да, с одной стороны проблема совместимости с антивирусом от Kaspersky вроде как исправлена и теперь не требуется обязательно настраивать в настройках антивируса для службы Adguard VPN исключение из проверки антивирусом защищенных соединений (настройка данного исключения была описана ранее в [ЭТОМ](https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/248#issue-1200247274) сообщении) чтобы подключение к VPN-серверам было успешным...

Но... зато теперь антивирус (когда Adguard VPN подключается к серверам) ругается на ошибку\проблему проверки защещенного соединения и выдаёт вот такой запрос пользователю (скриншот прилагается)... Чтобы Adguard VPN успешно подключился к VPN-серверу требуется выбрать вариант (нажать кнопку) **Добавить в исключения**... Причём подобный запрос выдается для каждой страны\локации\сервера отдельно и их требуется добавить в исключения антивируса каждый отдельно... Возможно (я не в курсе деталей работы Adguard VPN настолько) в каждой стране\локации не один сервер а несколько и поэтому возможно может требоватся добавить в исключения для антивируса не один а несколько VPN-серверов Adguard в каждой конкретной стране\локации...

После добавленияVPN-серверов Adguard в исключения в антивирусе они попдают в особый список в настройках антивруса который находится в настройках антивируса по следующему пути:

Главное окно антивируса->Настройка (шестеренка в левом нижнем углу)->Настройки сети (в списке разделов настроек в меню слева) ->Домены с ошибками проверки (открывает соотвествующий список) (на всякий случай уточню что в этом списке нельзя отредактировать\отключить\удалить какой-то отдельный конкретный пункт, а можно только очистить данный список при помощи соотвествующей кнопки внизу под списком, что позже соответственно приведёт к появлению снова повторных соответсвующих запросов от антивруса)...

Не знаю что уж не нравится антивирусу в защищенных соединениях Adguard VPN, но вполне возможно что тут уже причина не в Adguard VPN и\или в его серверах и\или что это уже нельзя исправить на стороне Adguard, я же не специалист и могу только рассказать, описать и постаратся помочь чем смогу насколько могу... Но...

В принципе подобные проблемы совместимости бывают у антивируса и с некоторым другим сторонним ПО когда без настройки\добавления соответствующих исключений в настройках антивируса то или иное ПО не может подключиться к своим серверам, например чтобы проверить наличие обновлений и загрузить и установить их... Но повторюсь как правило это бывает (как я уже и писал ранее и здесь для Adguard VPN) если в настройках антивируса настройка проверки защищённых соединений (Настройка->Настройки сети->блок Проверка защищенных соединений) настроена не в режиме по умолчанию ("Проверять защещнные соединения по запросу компонентов защиты") а включен режим "Всегда проверять защищенные соединения."... В режиме же по умолчанию ("Проверять защещнные соединения по запросу компонентов защиты") таких проблем совместимости между антивирусом и сторонним ПО как правило не бывает ну или во всяком случае бывает значительно меньше и реже... Но повторюсь что не факт что это уже проблема в стороннем ПО (в данном случае в Adguard VPN) и она должна и может быть исправлена именно на стороне стороннеего ПО а не на стороне антивируса...

Все настройки антивируса расписаны на примере текущей актуальной (во всяком случае для РФ) релизной версии антивируса (в моём случае это Kaspersky Internet Security) 21.3.10.391

Итог... с одной стороны проблема вроде как исправлена и ситуация улучшилась, но с другой стороны вроде как не до конца и проблема теперь воспроизводится но по другому... В любом случае я решил на всякий случай всё это описать и сообщить об этом здесь... Если что пишите здесь... Эту задачу я продолжаю отслеживать на всякий случай...

![AdguardVPN2 0+KasperskyAllScanHTTPS](https://user-images.githubusercontent.com/43743908/209673081-9d818c00-1e55-410b-bf6e-ef871ff834b0.jpg)
