### ISSUE TITLE
Unable to disconnect from VPN server

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardVPNForWindows#263]
### Issue Details

- **AdGuard VPN version:**
  - v1.1.1, 1.3 nightly 1
- **Operating system and version:**
  - Windows NT 10.0.19043.0
- **Other network-level software:**
  - n/a

### Expected Behavior

VPN disconnects when you click on the Disconnect button

### Actual Behavior

The app sits in the Disconnecting... state, but does not disconnect

### Screenshot

<details>

![image](https://user-images.githubusercontent.com/15856304/167599395-82b37307-fef9-4038-8024-4d307fc869dc.png)

</details> 

### Additional Information

Logs in zendesk, ID 600781, 578899, 588496, 618712, 618713, 618714‬

**Comment by Aydinv13** [comment]
@Eugene-Savenko ask users to record trace logs please.

**Comment by AnthonyBe** [comment]
Added Split Tunneling for **Google Drive** and **Dropbox** via 'Add Applications'. **Microsoft OneDrive** wasn't in list so had to add via browse executable %LOCALAPPDATA%\Microsoft\OneDrive\OneDrive.exe.

Rebooted. Tried to disconnect VPN - same result.

Logs:
[adg_logs_1.3.578.0_0706_1820.zip](https://github.com/AdguardTeam/AdGuardVPNForWindows/files/9053019/adg_logs_1.3.578.0_0706_1820.zip)

Will try nightly build next.

**Comment by AnthonyBe** [comment]
Tried current nightly build (v1.3.581.0) with above-mentioned split tunnel applications still in place.

Same result.

Logs:
[adg_logs_1.3.581.0_0706_1834.zip](https://github.com/AdguardTeam/AdGuardVPNForWindows/files/9053133/adg_logs_1.3.581.0_0706_1834.zip)
 
Let me know if there is anything specific you'd like me to try next.

**Comment by eukislov** [comment]
I had the same problem when I used the NordPass password manager. Adding **NordPass.exe executable file** to Split Tunneling didn't work for me. However, in the Processes section of the Task Manager, in addition to the NordPass process (NordPass.exe executable file), there was a process called nordpass-background-app with the nordpass-background-app.exe executable file. Adding both of them to Split Tunneling helped me solve the problem. It is possible that the applications that you are using are running in the background some other processes. 
Maybe this will be useful for you.

**Comment by adbuker** [comment]
> I had the same problem when I used the **NordPass** password manager. Adding **NordPass.exe executable file** to Split Tunneling didn't work for me. However, in the Processes section of the Task Manager, in addition to the **NordPass** process (**NordPass.exe executable file**), there was a process called **nordpass-background-app** with the **nordpass-background-app.exe executable file**. Adding both of them to Split Tunneling helped me solve the problem. It is possible that the applications that you are using are running in the background some other processes. Maybe this will be useful for you.

Thanks a lot, it's very useful info

**Comment by AnthonyBe** [comment]
> > Tried current nightly build (v1.3.581.0) with above-mentioned split tunnel applications still in place.
> > Same result.
> > Logs: [adg_logs_1.3.581.0_0706_1834.zip](https://github.com/AdguardTeam/AdGuardVPNForWindows/files/9053133/adg_logs_1.3.581.0_0706_1834.zip)
> > Let me know if there is anything specific you'd like me to try next.
> 
> please add `CoreSync.exe` along with `Enpass.exe` processes too. The matter is all the cloud-related or cloud-based applications play a role

I added **Enpass Password Manager** application (password manager that uses public clouds for database sync; in my case Microsoft OneDrive) and **coresync.exe** (part of **Adobe Creative Cloud**, did this by browsing to the executable and adding).
Rebooted.
Issue still persists.
Fresh logs: 
[adg_logs_1.3.581.0_0707_1307.zip](https://github.com/AdguardTeam/AdGuardVPNForWindows/files/9060077/adg_logs_1.3.581.0_0707_1307.zip)

**Comment by Aydinv13** [comment]
@AnthonyBe could you try [this](https://uploads.adguard.com/AdGuardVpn-bug_AG-14190-1_1.exe) build? Feedback will be helpful, thank you!

**Comment by Aydinv13** [comment]
@AnthonyBe please send your logs to devteam@adguard.com

**Comment by AnthonyBe** [comment]
> @AnthonyBe could you try [this](https://uploads.adguard.com/AdGuardVpn-bug_AG-14190-1_1.exe) build? Feedback will be helpful, thank you!

Installed new nightly build 1.3.582.0 from above link.
Rebooted.
Issue still persists. Waited 5 mins, app still stuck in 'Disconnecting...' state.
Have emailed fresh logs to devteam@adguard.com

**Comment by AnthonyBe** [comment]
Replaced `AGIpHelperClose.dll` in `C:\Program Files (x86)\AdGuardVpn` with version downloaded from above.
Rebooted and repro'd.
No change - issue still persists.
New logs captured and emailed to [devteam@adguard.com](mailto:devteam@adguard.com)

**Comment by adbuker** [comment]
@AnthonyBe, could you please send the process dumps for both processes to [devteam@adguard.com](mailto:devteam@adguard.com). 
1. repro the issue
2. once application becomes to hang (or "infinite" state) please open "Task manager"
3. ..select "adguardVpnSvc.exe"/"adguardAvpn.exe", 
4. ...right-click mouse
5. and select "Create dump" option
6. As all the dumps created compress them to the archive and send to us

**Comment by AnthonyBe** [comment]
Done.
Files for you to download:
AdGuardVpn.zip - https://1drv.ms/u/s!AhbwEI22K05brp8B53J1aqjepRfn7Q?e=rRYsnI
AdGuardVpnSvc.zip - https://1drv.ms/u/s!AhbwEI22K05brp8AOMgH-H1KWGvxWw?e=RI7elB

**Comment by adbuker** [comment]
@AnthonyBe, thanks a lot for the dumps. We've made some changes, could you please try another one [dll](https://uploads.adguard.com/AGIpHelperClose_2.zip), but please try it with the latest nightly version you can obtain from [link](https://static.adguard-vpn.com/windows/nightly/installer-1.3.581.0.exe). Could you please also grab the dumps in case of persisting the issue again.
P.S. Your previous message with the dumps links was deleted for privacy reasons

**Comment by AnthonyBe** [comment]
Because the nightly link below meant retrograding my AGVPN version, it reset my settings, so I ran 2 tests; one with no Split Tunnel apps configured (because we really shouldn't have to set exclusion for this), and one with the same apps I've had configured as before (Google Drive, Microsoft OneDrive, Dropbox, Adobe Coresync, Enpass).
Issue still persisted in both scenarios.
AGVPNProcDumps-noSplitTunnel.zip - https://1drv.ms/u/s!AhbwEI22K05brp8GCW9Awbk4WKEctQ?e=n5Rp7U
AGVPNProcDumps.zip - https://1drv.ms/u/s!AhbwEI22K05brp8H1Ko1e_L_ndZ8TA?e=0yguXJ

Cheers,
Anthony

**Comment by ihurin** [comment]
In addition, one more customer have reported this. Ticket number 616355 with logs attached.

**Comment by AnthonyBe** [comment]
Are there any updates on this issue? Thanks!

**Comment by Eugene-Savenko** [comment]
In case you need another set of trace logs, you can find them in helpdesk (ID 617966).

**Comment by ihurin** [comment]
One more customer reported this in ticket number 620478.

**Comment by SkyRexHUN** [comment]
Having the same problem, both on my laptop and PC. I am unable to switch / disconnect from servers, I am only able to connect to one when the app starts and that's it.

**Comment by AnthonyBe** [comment]
I'm finally starting to see good results with a nightly update I got a few days ago, v1.3.584.0 (1.3 nightly 11).
It's only been 1 day, but I'm able to cleanly connect and disconnect from different end-points.

**Comment by eukislov** [comment]
I confirm that on the latest build (Nightly 1.3.584) everything seems to be working well, no problems have been observed since the release

**Comment by Alexandr82** [comment]
Problem exists on 1.3.584.0

**Comment by northis** [comment]
@Alexandr82 Please, send your logs to devteam@adguard.com

**Comment by Alexandr82** [comment]
> @Alexandr82 Please, send your logs to [devteam@adguard.com](mailto:devteam@adguard.com)

Done

**Comment by Alexandr82** [comment]
Problem exists on 1.3.596.0

**Comment by SkyRexHUN** [comment]
Problem exists on 1.3.593.0

**Comment by SkyRexHUN** [comment]
Problem exists on 1.3.603.0

**Comment by adbuker** [comment]
@Alexandr82 , @SkyRexHUN , please follow instructions below:
1. download and install [this build](https://uploads.adguard.org/AdGuardVpn-bug_AG-14190-3.exe)
2. in the `%programfiles(x86)%/adguardvpn` on x64 and `%programfiles%/adguardvpn` on x86 machine please replace [this file](https://uploads.adguard.org/AGIpHelperClose.dll)
3. start the AdGuardVpn and connect to any location you want
4. press "disconnect" button. If the issue still persist you'll fall into the hang
5. cut and grab the file `AGIpHelperClose.log` (from step 2's location), and name it `AGIpHelperClose_1.log`
6. repeat steps 1-5 about 5 times (in the step 5 the names  will be `AGIpHelperClose_2.log`, `AGIpHelperClose_3.log`, etc), so in the end you'll have 5 different files `AGIpHelperClose_X.log`
7. compress all the files to the archive, because files can be quite huge
8.  send the archive to the devteam@adguard.com with the reference to this issue in the title

**Comment by SkyRexHUN** [comment]
@adbuker Issue resolved on nightly build 2.0.612.0

**Comment by adbuker** [comment]
@SkyRexHUN, nice to read!

**Comment by gork7777** [comment]
Resolved for me too, issue can be closed.

**Comment by Alexandr82** [comment]
Problem exists on 2.0.612.0

**Comment by Aydinv13** [comment]
@Alexandr82 could you please collect your logs again following the [instructions](https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/263#issuecomment-1218213560) above (use current nightly build instead of the one in the first step).

**Comment by cableghost** [comment]
New user, having this issue. Additionally, same behavior when attempting to change servers.... just freezes, requires an End Task in Task Manager to close/restart it.

In review of this thread, I have added cloud services such as Dropbox, but still have the issue.

Note, I do not have this issue using Torguard.net VPN.

Windows 11 22H2
Adguard for Windows (latest version) also installed.

**Comment by adbuker** [comment]
Hello everybody, who more or less were affected by the issue. In 2.0 Beta 2 we've totally enhanced very important bottleneck causes the hangs, please try this version
