### ISSUE TITLE
Unable to connect to Japanese website

### ISSUE THREAD

**Issue by OR-7264** [AdguardTeam/AdGuardVPNForWindows#264]
### Issue Details

- **AdGuard VPN version:**
  - 1.2.519.0
- **VPN mode:**
  - Local VPN
- **Operating system and version:**
  - Windows 10 64bit
- **Other network-level software:**
  - AdGuard, Windows Defender
- **Browser:**
  - Firefox 100.0.1

### Expected Behavior

Successful connection.

### Actual Behavior

Errors in connection only for Japanese sites.

`PR_CONNECT_RESET_ERROR`

### Steps to Reproduce

1.Connect to any location VPN 
2.Access to:
  - https://sukiburo.jp/  : Cloud review website.
  - https://2week.net/ : Smartphone review website.
  - https://gatbuun.com/ : Blog

### Additional Information

Some sites can be connected normally.

Example:
  - https://www.yahoo.co.jp/ : Yahoo in Japanese
  - https://animate.co.jp/ : Anime Goods Shop Website
  - https://medicalnote.jp/ : Healthcare Website

**Comment by maxikuzmin** [comment]
@OR-7264 sometimes some endpoints can be blocked. We try to change them to avoid blocking. At this moment, unfortunately, you need to wait
