### ISSUE TITLE
Internet does not work after disconnecting

### ISSUE THREAD

**Issue by Smithienious** [AdguardTeam/AdGuardVPNForWindows#266]
### Issue Details

- **AdGuard VPN:**
  - v1.2.519.0
  - Local VPN
  - Use QUIC enabled
  - Custom DNS server: quic://dns.adguard.com
- **Operating system and version:**
  - Windows 11 22621.1
- **Other network-level software:**
  - AdGuard 7.10 Beta 1
    - DNS server: AdGuard DNS DoQ

### Expected Behavior

1. Enable VPN
2. Open Steam and download any game
3. While downloading, disconnect from VPN
4. Internet works

### Actual Behavior

4.1. All connections are dropped, new connections cannot be made

### Workaround

4.2. Go to AdGuard's DNS protection and switch to another protocol

**Comment by Aydinv13** [comment]
Cannot reproduce the problem. Could you check it with the latest nightly versions of AdGuard and AdGuard VPN? If it still reproducible please send your logs (from AdGuard VPN) to us:
Here's what we need you to do:
1. Go to Settings --> General --> Advanced settings --> Logging level --> **Record everything**;
2. Reproduce the problem and remember the exact time it was reproduced at. We will need it to find the corresponding entries in the log file;
3. Go to Settings -> General -> **Export logs**;
4. Send the archive to `devteam@adguard.com` and mention this issue number in the subject. Don't forget to include the time of reproduction.
5. Set the logging level back to **Record by default**.

**Comment by Smithienious** [comment]
Cannot reproduce on AdGuard 7.10 nightly 12.

**Comment by Aydinv13** [comment]
Thanks for feedback. Reopen this issue if the problem occurs again please.
