### ISSUE TITLE
Unable to add OpenSSH Client to the Split tunnelling

### ISSUE THREAD

**Issue by MatyCZ** [AdguardTeam/AdGuardVPNForWindows#267]
### Issue Details

- **AdGuard VPN version:**
  - 1.2.3
- **VPN mode:**
  - VPN
- **Operating system and version:**
  - Windows 11
- **Other network-level software:**
  - AdGuard, BitDefender

### Expected Behavior

Allow to add OpenSSH Client application from Windows optional features to the Split tunnelling.

### Actual Behavior

I am unable to select OpenSSH client in the Split tunnelling because this folder is not visible in File explorer. There is no problem in Proton VPN.

Path to the location of Windows OpenSSH is `"C:\Windows\System32\OpenSSH\ssh.exe"` and when I use this path in File explorer, I got message: `You can't open this location using this program. Please try a different location`.

### Screenshots

<details>
<summary>Screenshot:</summary>

**Error message:**
![AdGuard VPN Error](https://user-images.githubusercontent.com/318575/171803332-a497b8b8-fbdc-4c8f-8f5c-be110a4abb7f.jpg)

**AdGuard VPN:**
![AdGuard VPN](https://user-images.githubusercontent.com/318575/171799292-8ee9e267-6606-4261-b648-29362c9778db.jpg)

**Proton VPN:**
![ProtonVPN](https://user-images.githubusercontent.com/318575/171799274-3707a9f9-33f7-4546-aa3a-76198020e99f.jpg)

</details>

**Comment by northis** [comment]
@MatyCZ This is a feature of windows in case of some x64 apps. Like a workaround, you can copy the folder `C:\Windows\System32\OpenSSH` to `C:\Windows\SysWOW64\OpenSSH`. After that you will be able to locate the folder `C:\Windows\System32\OpenSSH` on the open file dialog.

**Comment by MatyCZ** [comment]
@northis Thank you very much. But, can you please open this issue again? Workaround is a nice thing, but more useful will be to fix this problem. More users may have a similar problem and BFU does not know about workarounds.

**Comment by Aydinv13** [comment]
@MatyCZ we'll try to find a solution, thank you.

**Comment by adbuker** [comment]
related to https://github.com/AdguardTeam/AdguardForWindows/issues/2831

**Comment by northis** [comment]
@MatyCZ Now the 64 bit nightly version is available, you can check it out https://agrd.io/windows_vpn_nightly
