### ISSUE TITLE
Make the All locations and Fastest locations headers slightly larger and bold

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNForWindows#271]
I think it will be seen as beautiful and easier to understand. I make a suggest like that:

<details><summary>Screenshot:</summary>

![vpn](https://user-images.githubusercontent.com/35523759/173135523-45f91fc8-a07d-43cf-b671-024afac713a7.png)
</details>

**Comment by maxikuzmin** [comment]
@gork7777 we will definitely think about your suggestion. Thank you!

**Comment by gork7777** [comment]
@maxikuzmin Any updates for this?

**Comment by Aydinv13** [comment]
@gork7777,

unfortunately, this improvement brings a disadvantage, because then the user's attention will be attracted by many large elements, the most important of which is Connect button.

**Comment by gork7777** [comment]
@Aydinv13 @maxikuzmin Thank you for adding this suggestion!
