### ISSUE TITLE
Unable to switch servers / disconnect from a server (beta)

### ISSUE THREAD

**Issue by SkyRexHUN** [AdguardTeam/AdGuardVPNForWindows#278]
- **AdGuard VPN version:**
1.3.553.0
- **VPN mode:**
Standard
- **Operating system and version:**
Windows 11 Pro 64bit 22H1
- **Other network-level software:**
AdGuard

### Expected Behavior

Being able to switch / disconnect from server

### Actual Behavior

Infinite loading saying Connecting...

### Screenshots

![image](https://user-images.githubusercontent.com/92554890/175351906-796b35c8-9944-4e96-b2c8-72e09d7e5351.png)
![image](https://user-images.githubusercontent.com/92554890/175351938-08226ff7-7387-4aa5-b984-6b311dbf623c.png)

**Comment by eukislov** [comment]
I can confirm this problem.

In my case, the infinite disconnection or saying Connecting when switching server is related to the fact that I use the **NordPass** password manager. As soon as I kill the NordPass process through the Task Manager, the connection behaves correctly. Previously, such a problem was observed when using cloud storage applications, such **Google Drive for Desktop**, for example, but now the VPN behaves correctly with it.
If you use applications associated with cloud storage facilities or password managers, such a problem can be observed.

**Comment by gork7777** [comment]
Same for me too, using nightly build.

**Comment by Aydinv13** [comment]
@eukislov @gork7777 can you please collect debug logs from the latest [nightly](https://agrd.io/windows_vpn_nightly) version?
Here's what we need you to do:
1. Go to Settings --> General --> Advanced settings --> Logging level --> **Record everything**;
2. Reproduce the problem and remember the exact time it was reproduced at. We will need it to find the corresponding entries in the log file;
3. Go to Settings -> General -> **Export logs**;
4. Send the archive to `devteam@adguard.com` and mention this issue number in the subject. Don't forget to include the time of reproduction.
5. Set the logging level back to **Record by default**.

**Comment by gork7777** [comment]
@Aydinv13 Sent it.

**Comment by eukislov** [comment]
Done.

**Comment by gork7777** [comment]
@Aydinv13 This problem is relates to that issue: https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/263

**Comment by Aydinv13** [comment]
Unfortunately, the only temporary solution for now is explained here:
https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/263#issuecomment-1147604113

>@Aydinv13 This problem is relates to that issue: https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/263

thanks for reminding, I'm gonna close current issue. All updates will be found [there](https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/263)
