### ISSUE TITLE
Outdated application's interface and background images

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNForWindows#280]
I'm using AdGuard VPN nightly 7. The application's interface and background images are outdated. In the media kits on the website, a newer one is used in the windows application screenshots. Here's the screetshots of the media kits:
<details><summary>Screenshots</summary>

[windows.zip](https://github.com/AdguardTeam/AdGuardVPNForWindows/files/8978961/windows.zip)
</details>

**Comment by mozartinio** [comment]
@gork7777
 Hello! Can you please sent us your logs ? (We checked applications on the same tabs and they are fine so we need to know whats went wrong with your vpn)

**Comment by gork7777** [comment]
@mozartinio I have specified the currently used user interface below. This is the formerly used interface. I have specified the new and required user interface below. Likewise, the interface used to be like this in the extension, and then the interface was changed, but it has not been changed for Windows yet.

<details><summary>Current UI</summary>

![image](https://user-images.githubusercontent.com/35523759/176891249-c24ac339-1094-45dc-b820-b8b8fb3d48b3.png)
</details>

<details><summary>New UI</summary>

<img width="400" alt="home-on@2x" src="https://user-images.githubusercontent.com/35523759/176894091-871cbf47-1c85-4763-8544-9831a542b07c.png">
</details>

<details><summary>New UI</summary>

<img width="400" alt="home-off@2x" src="https://user-images.githubusercontent.com/35523759/176894102-230bc2bf-b50b-45ef-9d0d-a3aba279762a.png">
</details>

**Comment by mozartinio** [comment]
@gork7777 Got this! So in the next major update you will see the new application interface.
