### ISSUE TITLE
Some server locations default to Russian language although physical location matches the connected server

### ISSUE THREAD

**Issue by olavinto** [AdguardTeam/AdGuardVPNForWindows#294]
### Issue Details

- **AdGuard VPN version:**
  - 1.3.581.0 Nightly
- **VPN mode:**
  - Local VPN
- **Operating system and version:**
  - Windows 11 Insider Preview Dev channel build 25158.1000
- **Other network-level software:**
  - Windows Defender
  - AdGuard
### Expected Behavior

Websites open to the local version of the connected VPN server. In this case this would be the Finnish sites when connected to the VPN server in Finland.

### Actual Behavior

Websites open to the Russian version when connected to the VPN server in Finland. Browser settings can partly override this but they do not apply to all situations or they apply only partly. Google, for example, tells me that I'm connected from Russia and defaults to the Russian site unless I am logged in to my account (which changes all Google services to Finnish regardless of location or browser settings) and/or I have set the preferred page display language settings of my browsers to something else (like English and Finnish in my case). My location is detected as being in Finland though so for some reason I get Russian locales although I am told as connecting from Finland.

This is frustrating because many sites the open in Russian which I can't understand a single word of. I do not know if this happens with other locations as well but at least when I use the Swedish or US servers, I get either the Swedish or US version of Google respectively. But with the Finnish server I get Russian for some reason.

This is currently one of the main reasons why I currently use ProtonVPN instead of AdGuard VPN. I do not want to change the website locales to Finnish or English constantly. I have never experienced similar problems with ProtonVPN and ExpressVPN. :(

This actually seems to happen with the Germany/Frankfurt server also and I am placed to Germany but get the Russian version of Google.

I find this behavior strange because I would expect to get Finnish sites when connected to Finland, German sites when connected to Germany and so on.

This also happens on Android so it probably has something to do with the servers and this probably applies to virtually server locations.

So: 
- I have cleared my browsers language settings so those do not affect this
- I have used mainly Google to test this out and I have opened it in a separate container tab so browser history does not affect this
- System (Windows) language is English (with Finnish units and stuff) so that does not affect this
- My physical location is correctly detected as being in Finland (or whatever server location I am connected to) but I get Russian language versions of websites
- Other locations seem to work fine, namely Sweden and United States (they give me Swedish and US sites)

**Comment by mozartinio** [comment]
@olavinto Hello! Thank you for your issue details. We got this and very soon will fix it (by changing IP).

**Comment by mozartinio** [comment]
@olavinto 
Hello!
Im about to close the issue but firstly want to ask you - does it still reproduce on your side?

**Comment by olavinto** [comment]
@mozartinio Hi! Seems to work at least now. 👍

**Comment by mozartinio** [comment]
@olavinto
Very glad to hear it
If the problem repeats - feel free to reopen the task

**Comment by olavinto** [comment]
This seems to happen still, on desktop and on mobile. Not always but usually.
