### ISSUE TITLE
Faulty icon for program installer

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNForWindows#297]
It seems that the icon looks old and incompatible. The icon looks newer in the Nightly build.

<details><summary>Nightly build</summary>

![image](https://user-images.githubusercontent.com/35523759/180504748-12dea39d-ea4f-419f-987e-67fb932f448c.png)
</details>

<details><summary>Release build</summary>

![image](https://user-images.githubusercontent.com/35523759/180505502-adde6185-f227-4d94-9c4c-d80323570618.png)
</details>

**Comment by mozartinio** [comment]
@gork7777 Hello! 
Thank you a lot! We will fix it for sure!

**Comment by gork7777** [comment]
@mozartinio @Danila-Arg Hey, I just tried now and there is still same problem. I have downlaoded from [this](https://adguard-vpn.com/en/welcome.html) and [this](https://adguard-vpn.com/en/windows/overview.html) website from "Download" button for AdGuard VPN for Windows.
![image](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/35523759/cf996411-74f8-4514-a711-c8ccf5767be7)
