### ISSUE TITLE
Adding "Favourites" function for servers

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardVPNForWindows#301]
Hello,

please let us add servers to favourites. And thus also increase their priority when connecting🙏🏼

Thank you.
Best regards😀

**Comment by gork7777** [comment]
I made similar request for the extension, maybe you can check the design for that if you add this function. [#48](https://github.com/AdguardTeam/AdGuardVPNExtension/issues/48)

**Comment by gork7777** [comment]
Well, now that the saved feature has finally been added and you can add locations there.

**Comment by ammnt** [comment]
@gork7777, yeah. I saw this function today. Thanks a lot!
