### ISSUE TITLE
Exclusions don't work for vk.com 

### ISSUE THREAD

**Issue by Dimedro11** [AdguardTeam/AdGuardVPNForWindows#305]
Подскажите пожалуйста, как работает белый список доменов и поддоменов в десктопном adguard vpn? Почему занеся вк со всеми доменами и поддоменами я вижу это??? Ещё один момент, проблема с интернетом проявляется, если устройство подключено к Wi-Fi сети, проверил с телефона в мобильной сети данная проблема не возникает, а при подключении к Wi-Fi проявляется, в мобильной версии приложения тоже самое. Роутер Mi Router 4A Giga Version | MiWiFi Стабильно 3.0.24. Провайдер Ростелеком. По поводу отключения интернета особо нечего сказать - при подключении к ЛЮБОЙ сети интернет включаю впн и через минут 5-15 интернет вместе с самим впном начинают БЕСКОНЕЧНО переподключаться.
![photo_2022-08-12_11-55-00](https://user-images.githubusercontent.com/111146046/184416091-76a5c67e-c22c-4771-90c3-c7f43b325ee2.jpg)
![photo_2022-08-12_11-55-03](https://user-images.githubusercontent.com/111146046/184416097-f4d27a1f-0933-4127-9888-a907b9692735.jpg)
*Логи удалены в целях приватности*

**Comment by mozartinio** [comment]
@Dimedro11 Здравствуйте! Какая у вас версия ВПН? С нашей стороны баг с ВК и музыкой не воспроизвелся (Попробуйте выбрать ВК из списка: exclusions tab -> add a website -> from the list). Что касаемо отключения от сети - так же не воспроизводится, отправьте, пожалуйста, логи, и мы посмотрим чем это может быть вызвано.

**Comment by Dimedro11** [comment]
> @Dimedro11Здравствуйте! Какая у вас версия ВПН? С нашей стороны баг с ВК и музыка не воспроизвелся (Попробуйте выбрать ВК из списка: вкладка исключения -> добавить сайт -> из списка). Что касается восприятия от сети - так же не образуется, отпишите, пожалуйста, логи, и мы наблюдаем, чем это может быть вызвано.

Проблема с исключением сайта vk.com проявилась в 11:44 по мск, версия adguard vpn (nightly) 1.3.605.0 , на стабильной версии ВПНа теже самые ошибки проявляются, адекватно исключения работаю только в мобильной версиии и в расширении. Скрин + логи прикрепляю.
[adg_logs_1.3.605.0_0817_1145.zip](https://github.com/AdguardTeam/AdGuardVPNForWindows/files/9358003/adg_logs_1.3.605.0_0817_1145.zip)
![Bug](https://user-images.githubusercontent.com/111146046/185077105-aedb591d-2122-4e5d-9e14-d6bf63af988a.jpg)

**Comment by mozartinio** [comment]
@Dimedro11 Интересно ... Проверили на 3-ех устройствах и все работает корректно. Вы точно добавляли домен ВК из списка, а не сами вводили? Как посмотрим логи - сразу дадим обратную связь

**Comment by Dimedro11** [comment]
> @Dimedro11 Интересно ... Проверили на 3-ех устройствах и все работает корректно. Вы точно добавляли домен ВК из списка, а не сами вводили? Как посмотрим логи - сразу дадим обратную связь

Здравствуйте, вроде получилось победить проблему с музыкой вконтакте путем переустановки десктопного впн и блокировщика, + переустановил все имеющиеся на компьютере библиотеки. Но появилась другая проблема после выхода из спящего режима стал пропадать интернет.

**Comment by bogachenko** [comment]
@mozartinio привет, точно такая же проблема (только переустановка не помогает). Я заметил, что подобная ошибка возникает при использовании VPN, а не SOCKS5. Помимо тебя и 3х твоих устройств, может ли еще кто-то проверить 3-4 человека, пожалуйста, потому что программой на этом сайте (разумеется все нужные правила были добавлены в исключения, у вас кстати не хватает в исключениях еще двух доменов `vkuseraudio.net` и `mycdn.me`) пользоваться невозможно из-за этой ошибки.

**Comment by mozartinio** [comment]
@bogachenko 
Не воспроизводится уже на 5-ти устойствах с России (проверили и за пределами)
Отправьте, пожалуйста, ваши логи, разберемся с чем это может быть связано
Логи, пожалуйста, запишите расширенные
settings -> app settings -> advanced settings -> logging level (record everything)
Затем воспроизведите проблему и отправьте на почту devteam@adguard.com

**Comment by shark696969** [comment]
Solved

Pada tanggal Sel, 28 Mar 2023 12.23 PM, AdGuard GitHub Bot <
***@***.***> menulis:

**Comment by mozartinio** [comment]
@bogachenko 
Пока мы разбираемся с вашим кейсом, подскажите пожалуйста - воспроизводится ли проблема, если все другие расширения в браузере будут отключены? Так же у вас мобильный интернет или Wi Fi?

**Comment by bogachenko** [comment]
> Так же у вас мобильный интернет или Wi Fi?

На записе, которую я прислал, Интернет-центр Yota (иногда использую шнур, а иногда WiFi). Дома у меня установлен роутер TP Link от интернет провайдера Солнце Телеком (использую, только шнур).

Мобильным интернетом не пользуюсь, в смысле не раздаю его на компьютер, но могу проверить если надо (думаю результат тот же будет)

>воспроизводится ли проблема, если все другие расширения в браузере будут отключены

Да. Отключил все, даже программу ваш AdGuard отключил, результат - Вы используете VPN.
Кроме того, проблема воспроизводится не только в приложении ADG VPN, но и в расширении для браузера (проверял на Хромогом браузере).

**Comment by bogachenko** [comment]
Если интересно, вход в `https://id.vk.com` определяется как из под VPN.
Могу видео записать, любой сервер подключаешь, включаешь исключение для vk.com и идешь в "Историю активности" выходит это =>https://user-images.githubusercontent.com/8535285/229489068-0326301e-fff3-4366-a99c-6911342c7814.jpg

**Comment by AlexandrPkhm** [comment]
@bogachenko Здравствуйте!

Пожалуйста, примите наши извинения за задержку с ответом. 

Нам не удалось воспроизвести данную проблему. Пожалуйста, уточните повторяется ли она в данный момент и, если да, то какую версию AdGuard VPN вы используете на устройстве.
