### ISSUE TITLE
Some flags icon is broken in system tray

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNForWindows#307]
Flag icons with particularly detailed textures are broken. I was able to find these from servers that are free. You can check other flags.
Versions: AdGuard VPN v2.0.612.0 nightly 1 - Windows 10

<details><summary>Turkey</summary>

![Turkey](https://user-images.githubusercontent.com/35523759/185771990-a62375fd-31ac-4eb3-b1ef-c06532bde3df.png)
</details>

<details><summary>United Kingdom</summary>

![Kingdom](https://user-images.githubusercontent.com/35523759/185771992-f0653422-babb-4df6-bded-afb84a2b8876.png)
</details>

<details><summary>USA</summary>

![USA](https://user-images.githubusercontent.com/35523759/185771994-d84b2ed6-cb05-46d1-a021-8ba12ccb281c.png)
</details>

**Comment by mozartinio** [comment]
@gork7777 Hi! Thank you for letting us know! Will fix it pretty soon!

**Comment by gork7777** [comment]
Issue looks fixed in v2.0.646.0
