### ISSUE TITLE
Faulty localizations for English

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNForWindows#309]
"Check updates" should be "Check for updates".
String: [Check update](https://crowdin.com/translate/adguard-applications/19200/en-en#4024782)

"System" should be "System default"
String: [System](https://crowdin.com/translate/adguard-applications/18182/en-en#3936380)

"System" should be "System default"
String: [System](https://crowdin.com/translate/adguard-applications/19200/en-en#4024658)

"Autoupdate" should be "Auto-update"
String: [Autoupdate](https://crowdin.com/translate/adguard-applications/18182/en-en#3933948)

"Autoupdate" should be "Auto-update"
String: [Autoupdate](https://crowdin.com/translate/adguard-applications/19200/en-en#4024642)

"Attach detailed system info on running processes, installed applications, memory, CPU, battery state, and app log" should be "Send detailed system information about running processes, installed applications, memory, CPU, battery state and application log"
String: [Attach detailed system info on running processes, installed applications, memory, CPU, battery state, and app log](https://crowdin.com/translate/adguard-applications/19200/en-en#4024946)

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/35523759/186919962-e0f1459c-9d41-46b0-8f37-45e4b3732086.png)
</details>

<details><summary>Screenshot</summary>

![Faulty1](https://user-images.githubusercontent.com/35523759/189498258-f2db1151-9cc9-4d06-b345-ce78eb1793ab.png)
</details>

**Comment by adbuker** [comment]
related to https://github.com/AdguardTeam/AdguardForWindows/issues/4154

**Comment by gork7777** [comment]
These are not resolved yet?

**Comment by mozartinio** [comment]
@gork7777 resolved

**Comment by gork7777** [comment]
@mozartinio `System` and `Autoupdate` strings are still same. Not fixed.

**Comment by el-termikael** [comment]
@gork7777 thanks for noticing and sorry for closing the issue, we'll fix these strings soon

**Comment by gork7777** [comment]
@el-termikael You're welcome and it's okay. Thanks!
