### ISSUE TITLE
System tray is Light theme when selected Dark theme

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNForWindows#310]
The system tray should be Light theme when we select Light theme and should be Dark theme when we select Dark theme, without restarting the application like in the Ad Blocker application.
Version: AdGuard VPN v2.0.612.0 nightly 1

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/35523759/186960966-03e1cf06-4ef3-4ec1-97f6-cd275c5516cb.png)
</details>

**Comment by Aydinv13** [comment]
Thank you, it will be fixed in one of the next updates.

**Comment by gork7777** [comment]
Problem is fixed in v2.0.629.0 I guess.
