### ISSUE TITLE
Scrollbar half disappear while scrolling all the way down

### ISSUE THREAD

**Issue by mozartinio** [AdguardTeam/AdGuardVPNForWindows#321]
### Issue Details
Scroll "all location" section all the way down and you will see that scrollbar half disappear 

- **AdGuard VPN version:**
2.0.647.0
### Expected Behavior

Scrollbar have to be clearly visible in any position 

### Actual Behavior

Scrollbar half disappear while scrolling all the way down

### Screenshots
![VPN](https://user-images.githubusercontent.com/107266093/191225920-064800cc-09e2-46c1-b11f-bf3f658fdea5.png)

**Comment by gork7777** [comment]
In v2.0.673.0 nightly, scrollbar scrolls down a lot and disappears in the monthly remaining data section.

<details><summary>Video</summary>

https://user-images.githubusercontent.com/35523759/195624202-a28dff0d-e1e1-4c7d-a8bf-0d89377b30a0.mp4
</details>

**Comment by gork7777** [comment]
Looks like fixed in v2.0.709.0.
