### ISSUE TITLE
coub.com

### ISSUE THREAD

**Issue by jellizaveta** [AdguardTeam/AdGuardVPNForWindows#322]
<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a href="https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fcoub.com%2F" rel="nofollow" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">https://coub.com/</a></p><h3 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: 600; line-height: 1.25; color: rgb(36, 41, 47); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Comment</h3><blockquote style="box-sizing: border-box; margin: 0px 0px 16px; padding: 0px 1em; color: var(--color-fg-muted); border-left: 0.25em solid var(--color-border-default); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px;">Здравствуйте, некоторые сайты при работе приложения AdGuard VPN стали вести себя некорректно. При попытке запроса данных с сайта выдаёт сообщение что соединение сброшено. Когда выключаю программу AdGuard VPN сайт загружается нормально. Пробовал менять DNS адрес, но не помогает. Наверное, опять что-то химичат из РКН. Прикрепляю пример в виде скрина</p></blockquote><h3 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: 600; line-height: 1.25; color: rgb(36, 41, 47); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Screenshots</h3><details open="" style="box-sizing: border-box; display: block; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><summary style="box-sizing: border-box; display: list-item; cursor: pointer;">Screenshot 1</summary><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px;"><a target="_blank" rel="noopener noreferrer nofollow" href="https://camo.githubusercontent.com/f0c88187c4e0dacc56592ecca9d0373ae0b236765354c18c0777a5aeb07ebc93/68747470733a2f2f7265706f7274732d696d672e616467756172642e636f6d2f7349626159544b2e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;"><img src="https://camo.githubusercontent.com/f0c88187c4e0dacc56592ecca9d0373ae0b236765354c18c0777a5aeb07ebc93/68747470733a2f2f7265706f7274732d696d672e616467756172642e636f6d2f7349626159544b2e706e67" alt="Screenshot 1" data-canonical-src="https://reports-img.adguard.com/sIbaYTK.png" style="box-sizing: content-box; border-style: none; max-width: 100%; background-color: var(--color-canvas-default);"></a></p></details><details open="" style="box-sizing: border-box; display: block; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><summary style="box-sizing: border-box; display: list-item; cursor: pointer;">Screenshot 2</summary><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px;"><a target="_blank" rel="noopener noreferrer nofollow" href="https://camo.githubusercontent.com/4f4a786b95433d613bb52fbe9adb610946945c104f854aa490a2226c9bd512e4/68747470733a2f2f7265706f7274732d696d672e616467756172642e636f6d2f656a32444938572e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;"><img src="https://camo.githubusercontent.com/4f4a786b95433d613bb52fbe9adb610946945c104f854aa490a2226c9bd512e4/68747470733a2f2f7265706f7274732d696d672e616467756172642e636f6d2f656a32444938572e706e67" alt="Screenshot 2" data-canonical-src="https://reports-img.adguard.com/ej2DI8W.png" style="box-sizing: content-box; border-style: none; max-width: 100%; background-color: var(--color-canvas-default);"></a></p></details><h3 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: 600; line-height: 1.25; color: rgb(36, 41, 47); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">System configuration</h3>

Information | value
-- | --
Platform: | AdGuard VPN
Browser: | Chrome
Filters: | Ad Blocking:AdGuard BaseOther:Filter unblocking search ads and self-promotionLanguage-specific:AdGuard Russian,AdGuard German,Bulgarian list
Other extensions used: | AdGuard VPN

related to https://github.com/AdguardTeam/AdguardFilters/issues/130224

**Comment by mozartinio** [comment]
Здравствуйте! А какая у вас версия AdGuard VPN? На нашей стороне ситуация не повторяется. Пробовали ли вы переустановить AdGuard VPN? Если да, то поменялось ли поведение или все так же?

**Comment by mozartinio** [comment]
На нашей стороне не воспроизводится
Если проблема еще актуальна, то пришлите, пожалуйста, логи и можете переоткрыть данный кейс.
Here's what we need you to do:

Go to Settings --> General --> App settings -->Advanced settings --> Logging level --> Record everything;
Reproduce the problem and remember the exact time it was reproduced at. We will need it to find the corresponding entries in the log file;
Go to Support -> Export logs and system info;
Send the archive to devteam@adguard.com and mention this issue number in the subject. Don't forget to include the time of reproduction.
Set the logging level back to Record by default.
