### ISSUE TITLE
Adguard DNS conflict with Adguard VPN

### ISSUE THREAD

**Issue by Perfectlynk** [AdguardTeam/AdGuardVPNForWindows#324]
- **AdGuard VPN version:**
  - 1.3.600.0 (Beta)
  - 2.0.646.0 (Nightly)
- **VPN mode:**
  - VPN 
- **Operating system and version:**
  - Windows 10 
- **Other network-level software:**
  - AdGuard, Emsisoft Anti-Malware & Glasswire)

### Expected Behavior

Beta & Nightly: Network connection lost & Internal error

### Actual Behavior

Beta: Start up crash, Internal error, Network lost reconnect many times or trying to restore connection. Adguard service check says it's working.

Nightly: Multiple reconnects, Internal error, Network lost   

### Screenshots
![image](https://user-images.githubusercontent.com/72349391/191726938-06fc7daf-5d88-4ce7-aed2-ccd17d3914eb.png)
Beta

![image](https://user-images.githubusercontent.com/72349391/191733965-d631520c-4dc3-4892-a5b3-71c901d120d2.png)
Nightly: switched to UK servers 

![image](https://user-images.githubusercontent.com/72349391/191734600-c38efee9-9598-4596-bc1e-156df5cee841.png)
Nightly: Close the app and reopened crashed like above then I scrolled down

![image](https://user-images.githubusercontent.com/72349391/191735161-1df73dbb-ad88-4f58-a500-7a590547d220.png)
Nightly: clicked try to recover and selected Netherlands. Same crashing and reconnection loop

### Additional Information

B & N: Adding Adguard DNS causes crashes.  I'm using QUIC. Using nightly same thing happens except instead of just trying to connect like the beta, nightly keep switching to connection lost, reconnected, internal error. During that I managed to switched from United Kingdom to the Luxembourg it stopped and everything seemed fine. I then switched to Netherlands error began again closed the application but happened again. Used try to recover and everything seems fine again. 

Seems I cannot use UK or Netherlands. Only Luxembourg or the crash and error begins.

*Logs were deleted due to privacy reasons*

**Comment by adbuker** [comment]
@Perfectlynk , could you please install the latest [nightly version](https://static.adguardvpn.com/windows/nightly/installer-2.0.646.0.exe) and try with it

**Comment by Perfectlynk** [comment]
Done. Same thing happens. I updated issue.

**Comment by Aydinv13** [comment]
@Perfectlynk 
Does disabling Emsisoft Anti-Malware and/or Glasswire help?

**Comment by Perfectlynk** [comment]
@Aydinv13 No it doesn't. Also checked the logs from Emsisoft, nothing has been blocked and Glasswire is set to click to block meaning only notifies me if what goes on and out. 

I managed to restart my PC with Nightly VPN on Luxembourg from the UK and no crashes. I'll update again if anything happens.

**Comment by Aydinv13** [comment]
@Perfectlynk 
In this case we need to get the app logs.
Here's what we need you to do:
1. Go to Settings --> General --> App settings -->Advanced settings --> Logging level --> **Record everything**;
2. Reproduce the problem and remember the exact time it was reproduced at. We will need it to find the corresponding entries in the log file;
3. Go to Support -> **Export logs and system info**;
4. Send the archive to `devteam@adguard.com` and mention this issue number in the subject. Don't forget to include the time of reproduction.
5. Set the logging level back to **Record by default**.

**Comment by Perfectlynk** [comment]
@Aydinv13 Sent the logs.

**Comment by Aydinv13** [comment]
@Perfectlynk 
A possible fix will be provided in one of the next nightly versions.

**Comment by Perfectlynk** [comment]
Downloaded the update but the issue is still happening. Internal error again.

**Comment by adbuker** [comment]
@Perfectlynk, thanks, seems we've found the clue and will publish the nightly again. Tomorrow

**Comment by northis** [comment]
@Perfectlynk please, check the latest nightly version

**Comment by Perfectlynk** [comment]
@adbuker @northis It's been about a week since I updated from 2.0.664 to 2.0673 and now currently 2.0.678. I got one start-up crash but everything is seems to working as intended. The only thing though is it always connects to Germany even though I might change it to the UK then come back the next day, it will connect to Germany again. Is this intended?

**Comment by Perfectlynk** [comment]
Just updated Adguard Beta from 2.0.678 to 2.0.692 and the VPN had two internal errors once when I updated and one when I restarted. It seems to have fixed itself right now.

**Comment by northis** [comment]
@Perfectlynk please, send your logs to devteam@adguard.com

**Comment by Perfectlynk** [comment]
@northis Done.

**Comment by northis** [comment]
@Perfectlynk looks like these errors was because of some temporary issues on the server side.

**Comment by Perfectlynk** [comment]
VPN internal error. Sending logs to dev team.

**Comment by Perfectlynk** [comment]
Accidently closed, sorry

**Comment by Perfectlynk** [comment]
Adguard VPN connects multiple times at start up. 
1. It connects at windows start up before Adguard. 
2. reconnects again after Adguard enables. 
3. reconnects again after few seconds. 
4. again after a few seconds it connects again. 

If I try to use the web browser before step 4 it reconnects 5th time and then I can use the web browser. Doesn't seem as quick to connect as it once did but don't seem to get the internal errors.

**Comment by Perfectlynk** [comment]
Adguard VPN nightly 2.0.709.0 connected but service check says other wise.
![Adguard VPN connected not connected](https://user-images.githubusercontent.com/72349391/202488117-29a1fdb9-2095-4c7f-856c-4cf953ffc167.png)

**Comment by Perfectlynk** [comment]
It connects up to six times.
![Connection 6 times](https://user-images.githubusercontent.com/72349391/204091990-caa32ea6-780f-4a8f-a4fd-0c430fdcccbf.png)

**Comment by mozartinio** [comment]
@Perfectlynk Hello! 
Does your problem still persist?

**Comment by Perfectlynk** [comment]
The problem seems to be fixed. The only thing is the VPN must connect and reconnect 3-4 times before connecting. Other than that no problems.
