### ISSUE TITLE
Login error when signing in via Google account

### ISSUE THREAD

**Issue by nerd-architect** [AdguardTeam/AdGuardVPNForWindows#328]
i have an account but i cant sign in i live in iran and i use adguard on my phone but now i want to use it on windows ,guess what! you cant sign in because it's filtered.
easy fix:
change some policies let us connect to vpn then ask up to sign up its that easy.

**Comment by Aydinv13** [comment]
@nerd-architect 
What error do you see when signing into AdGuard VPN for Windows? What do you mean by `it's filtered`?

**Comment by nerd-architect** [comment]
The error says "Something went wrong!"
I used Google signin and it opens the browser let's me sign in because I have a chrome add on vpn and opens ad guard site but then because my PC is not connected to vpn yet the windows app doesn't yeald any results.

**Comment by nerd-architect** [comment]
And as you might know Iranian government blockes access to some sites like face book telegram Instagram Twitter and well ad guard site so we can't sign in before being connected to a vpn witch is the whole point of ad guard for us 😉

**Comment by adbuker** [comment]
Could you please login directly using your email/password and no via gmail?

**Comment by Aydinv13** [comment]
@nerd-architect 
we will look into this problem.

**Comment by adbuker** [comment]
@nerd-architect , have you ever faced the issue since 2022 October?

**Comment by adbuker** [comment]
@nerd-architect , could you please try to repro the issue with the latest nightly?

**Comment by Aydinv13** [comment]
Issue was closed due to no response.
