### ISSUE TITLE
No section showing remaining traffic data on main screen

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNForWindows#330]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:**
  -  V2.0.664.0 nightly
- **VPN mode:** 
  -  Local VPN
- **Operating system and version:**
  -  Windows 10
- **Other network-level software:**
  - 

### Expected Behavior

There should be section showing the remaining traffic data per month.

### Actual Behavior

There's no section showing the remaining traffic data per month.

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/35523759/193784631-7cb8684d-fd29-4f98-ba33-34c2350e290b.png)
</details>

**Comment by Aydinv13** [comment]
@gork7777 yes, you are right, thank you :)
