### ISSUE TITLE
No animation for checkbox if you click on the domain name

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNForWindows#336]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:**
  -  v2.0.664.0
- **VPN mode:**
  -  Local VPN
- **Operating system and version:**
  -  Windows 10
- **Other network-level software:**
  - 

### Expected Behavior

Clicking on both the checkbox and the middle of the domain name should there's animation.

### Actual Behavior

Clicking on the checkbox has animation, but if you click in the middle of the domain name there's no animation. This is same for the subdomain name too.

### Screenshots

<details><summary>Screenshot:</summary>

https://user-images.githubusercontent.com/35523759/194835096-38438bce-22bf-4e65-9ad5-2764f3f3100f.mp4
</details>

**Comment by mozartinio** [comment]
@gork7777 Hello! We know about it, we have researched it earlier and came to the conclusion that it is not a problem, because it is a feature of the display. By the way thank you for that!
