### ISSUE TITLE
"Actions" alignment is faulty in any domain

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNForWindows#338]
Using v2.0.664.0 nightly. The "Actions" has shifted to the right when you add any domain to the Exclusions and click on the domain.

<details><summary>Bug:</summary>

![Bug1](https://user-images.githubusercontent.com/35523759/194967622-7ca21512-ba57-4f7f-a0dd-b44afd67190a.png)
</details>

<details><summary>Should be:</summary>

![Should](https://user-images.githubusercontent.com/35523759/194967624-5af9ca2e-e299-4976-bd81-52da5293789d.png)
</details>

**Comment by mozartinio** [comment]
@gork7777
Hello! Thank you! (will fix it)

**Comment by gork7777** [comment]
Looks like fixed in v2.0.763.0
