### ISSUE TITLE
Include popular DNS servers to DNS servers section

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNForWindows#339]
As with AdGuard VPN extension and Android, can you add them for Windows(also for AdGuard VPN for Mac product) app too?

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/35523759/194972427-b33231f5-6e86-4597-8340-c9867497ecff.png)
</details>

**Comment by mozartinio** [comment]
@gork7777 
Hello!
We already have a plan about adding popular DNS servers to VPN desktop, thank you!
