### ISSUE TITLE
City name for current location not showing properly for dark theme

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNForWindows#340]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:**
  -  v2.0.673.0 nightly
- **VPN mode:**
  -  Local VPN
- **Operating system and version:**
  -  Windows 10

### Expected Behavior

Make city name more readable for dark theme.

### Actual Behavior

City name appears dark gray in dark theme and cannot be read properly.

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/35523759/195415697-a4867e91-29a2-4866-bbe3-a69df9fcc6a6.png)
</details>

**Comment by mozartinio** [comment]
@gork7777 Hello!
 Already working on this. Thank you!
