### ISSUE TITLE
Cannot scroll scrollbar with cursor in From the list tab in Exclusion

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNForWindows#341]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:**
  -  v2.0.673.0 nightly
- **VPN mode:**
  -  Local VPN
- **Operating system and version:**
  -  Windows 10

### Expected Behavior

Scrollbar should be scrollable with cursor for From the list tab.
### Actual Behavior

You can just scroll with mouse mid button in the From the list tab.
### Screenshots

<details><summary>Screenshot:</summary>

https://user-images.githubusercontent.com/35523759/195626238-7a8614d2-d7ee-47a9-b2c0-7917e049f81f.mp4
</details>

**Comment by mozartinio** [comment]
@gork7777 Thank you !

**Comment by gork7777** [comment]
Fixed in v2.0.700.0 nightly.
