### ISSUE TITLE
DNS_PROBE_POSSIBLE, no connectivity with DNS-over-TLS

### ISSUE THREAD

**Issue by jmeeter** [AdguardTeam/AdGuardVPNForWindows#348]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:**
2.0 beta 1
- **VPN mode:**
 Local VPN
- **Operating system and version:**
Windows 11
- **Other network-level software:**
Standard Windows firewall

### Expected Behavior

Configured Adguard VPN to use my VPS running Adguard Home as DNS via DNS-over-TLS, expected to surf web.

### Actual Behavior

immediately lost connectivity and got a DNS_PROBE_POSSIBLE error in Chrome.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by adbuker** [comment]
@jmeeter , thanks for the report. Could you please grab the trace logs ([instruction](https://kb.adguard.com/windows/solving-problems/adguard-logs)), repro the issue, and send the grabbed files to devteam@adguard.com with reference to this task. Could you please also specify issue's occurrence time and domain you were going to load

**Comment by jmeeter** [comment]
Absolutely, I will do that. For what it's worth, the iOS and Windows VPN app work with DNS-over-TLS when using Adguard VPN so the issue seems to be when using my Adguard Home hosted on VPS. AFAIK the AGH installation is working and configured correctly, but I'm no expert.

**Comment by ameshkov** [comment]
Maybe the port 853 is not open on your VPS?

**Comment by jmeeter** [comment]
> Maybe the port 853 is not open on your VPS?

I have confirmed port 853 is open.

**Comment by ameshkov** [comment]
@jmeeter confirmed with `dnslookup`?

**Comment by Aydinv13** [comment]
@jmeeter any news?

**Comment by mozartinio** [comment]
@jmeeter 
Hello.
I'm about to close the issue if your problem still exist please reopen it. Thank you!
