### ISSUE TITLE
Show bandwidth amount

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNForWindows#349]
It would be great if you add a feature that shows the amount of bandwidth for AG VPN apps. Thus, when we connect to any server we can see how much bandwidth is used.
It would be nice if a general bandwidth statistic is shown. The bandwidth used will be shown whenever we watch any video or do anything else while connected any server.

**Comment by mozartinio** [comment]
@gork7777  Hello!
We were thinking about it earlier and came to the conclusion that we dont really need this
Anyway thank you for your feature request!
