### ISSUE TITLE
~800-1200 connections in TimeWait from AdguardVPN service.

### ISSUE THREAD

**Issue by deNoor** [AdguardTeam/AdGuardVPNForWindows#367]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:**
  - 1.3.2 release
- **VPN mode:**
  - SOCKS5 mode
- **Operating system and version:**
  - Windows 10

### Expected Behavior

Not sure what to expect.
Reuse connections instead of close-open cycles?
Spam a bit less with new connections?
Allow users to disable automatic technical connections? I don't think that I need hardcore ping detection to all the servers in background. Typical use case is constant connection to a single server or several preferred servers to switch between.

### Actual Behavior

If AdguardVPN service is running, Windows has more than 800 connections (TCP IPv4+IPv6 443) in TIME_WAIT state to adguard vpn servers.
As soon as AdguardVPN is closed and when TimeWait interval expires my regular amount of TIME_WAIT connections is 0-10.

AdguardVPN is idle: has no connection redirected to its local socks5 listener. All these TIME_WAITs are from _passive_ AgVPN activity. It seems each "round" of some AG activity opens ~400 new connections. With default Windows interval for TimeWait at least ~800 connections are opened constantly with bursts to ~1200 when a new round comes.

### Reproduce

0. Prepare
    - you are on Windows 10,
    - AdguardVPN is not running,
    - run [TCPView](https://learn.microsoft.com/en-us/sysinternals/downloads/tcpview) for easier visual representation,
    - check current amount of connections in TIME_WAIT state.
1. Act
    - launch AdguardVPN service in socks5 mode. Redirecting any connection is not required.
    - check current amount of connections in TIME_WAIT state.
2. Observe
    - plus several hundreds new connections to AG servers in TIME_WAIT state, You'll get more if IPv6 is available from ISP.
    - hundreds of TIME_WAIT connections persists as long as AdguardVPN is running.
3. Restore
    - shutdown AdguardVPN service (regular right click and quit from tray icon is enough),
    - wait for TimeWait interval (default is 2 mins),
    - check current amount of connections in TIME_WAIT state.
4. Verify
    - the number of connections in TIME_WAIT state is back to what if was before the test.

### Additional Information

Also home router has to maintain +800 extra connections when AgVPN is running. Number of active tracked by router connections drops significantly when AgVPN is closed.

**Comment by ngorskikh** [comment]
Can confirm, with the default [TcpTimedWaitDelay](https://learn.microsoft.com/en-us/biztalk/technical-guides/settings-that-can-be-modified-to-improve-network-performance) of 120 seconds, I can see > 1000 sockets in TIME_WAIT when AdGuard "pings" all of the endpoints.

It technically could cause issues with routers, depending on how they track open connections and what kinds of timeouts/limits they have, but we haven't seen any yet.

@ameshkov @adbuker What if we rethunk the way the app is "pinging" the locations? I think it needs to be greatly simplified: ping the locations only when the ping results are actually needed (i.e. when rendering the list of locations), and only if more than some reasonable amount of time (like 30 minutes) has passed since the last ping (otherwise, use the previous ping result). Also, give the user a button to manually trigger the pings.

**Comment by adbuker** [comment]
@ngorskikh ,in fact we've did a step in the described direction for mitigating pinging process - now we are:
1. pinging the location only when UI is open
2. storing ping's results into the persistent cache
3. increasing pinging interval up to 5 minutes
4. dividing locations to "batches" (no more than 10 locations in the "batch") and pings them step by step

**Comment by ameshkov** [comment]
@ngorskikh have you used the nightly build or the stable build when checking this?

**Comment by ngorskikh** [comment]
@ameshkov Nightly, `2.0.709.0`

**Comment by adbuker** [comment]
@deNoor ,have you faced the issue with the latest release/nightly? we've made a lot of changes in the relevant part, so I guess it's no more actual issue, isn't it?

**Comment by deNoor** [comment]
@adbuker I'm using 2.1.10 (1046) now and have no issues. :)
AdguardVPN is much more relaxed with the connections.

**Comment by adbuker** [comment]
@deNoor , yes, we've worked on it.... hard worked :)
