### ISSUE TITLE
CTRL+F for bringing the cursor focus to the text box

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardVPNForWindows#372]
May I also suggest a keyboard shortcut like Ctrl+f on Windows or cmd+f on Mac for bringing the cursor focus to the text box where one can type and search for server locations? 

This is to help visually impaired users find locations quicker—it can be a long way if you are in the middle of the server list and have to press tabulator until you reach the search box again.

**Comment by mozartinio** [comment]
@Eugene-Savenko  
Hello! Thank you!
That is pretty good idea and we will think how to make it better!
