### ISSUE TITLE
Settings section starts flashing after pressing "Check for updates" button

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNForWindows#378]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:**
  -  v2.0.738.0 nightly
- **VPN mode:**
  -  Local VPN
- **Operating system and version:**
  -  Windows 10
- **Other network-level software:**
  -  None

### Expected Behavior

Tabs' highlights should not blink when checking for updates.

### Actual Behavior

Highlights of tabs blinking when checking for updates.

### Screenshots

<details><summary>Screenshot:</summary>

https://user-images.githubusercontent.com/35523759/206791494-06e88f9e-d954-4b95-9777-eed1a64d1a15.mp4
</details>

**Comment by mozartinio** [comment]
@gork7777 Hello!
We already fix this issue and on the next build you can see the difference!
By the way thank you so much for your attention to details!

**Comment by gork7777** [comment]
@mozartinio Oh didn't know that, I will test again on the next build then. Thanks and you're welcome!
