### ISSUE TITLE
Add the ability to reverse split tunnels.

### ISSUE THREAD

**Issue by KevinGu0611** [AdguardTeam/AdGuardVPNForWindows#384]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ Yes] I am running the latest version
- [ Yes] I checked the documentation and found no answer
- [Yes ] I checked to make sure that this issue has not already been filed

### Problem Description

I hope you can add the function of reversing the separation tunnel. This means that only the selected software will use VPN, and no other software will use VPN.

### Proposed Solution

It is recommended to add the function of reversing the separation tunnel.

### Alternatives Considered

add the function of reversing the separation tunnel

### Additional Information

Please add this function as soon as possible. This function is very useful.

**Comment by mozartinio** [comment]
@KevinGu0611
Hello! 
We already have a feature that you can found in the settings -> app exclusions
There you can add those applications where you do not want to use VPN
Did I understand you right?

**Comment by mozartinio** [comment]
@KevinGu0611 Got you!
We already doing this and probably in the next 2.1 version you will see that !

**Comment by KevinGu0611** [comment]
> 

@mozartinio Ok thanks! Thank you very much for taking my advice!
