### ISSUE TITLE
Unable to login in China

### ISSUE THREAD

**Issue by block-fly** [AdguardTeam/AdGuardVPNForWindows#386]
AdGuard VPN (v2.0) cannot be logged in in China. Loading all the time. Unable to log in. It displays "no server", but the Browser extension version can be used

(This issue is machine translation. It was originally in Chinese)

**Comment by block-fly** [comment]
> AdGuard VPN cannot be logged in in China. It displays "no server", but the Browser extension version can be used

(This issue is machine translation. It was originally in Chinese)

**Comment by Aydinv13** [comment]
@block-fly could you check if it's now possible to login?

**Comment by mozartinio** [comment]
@block-fly 
By the way we got hotfix 
When you will check that build out please let us know is everything alright
