### ISSUE TITLE
WHAT?! russian server?!

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardVPNForWindows#389]
I did not expect a company that fights for privacy to have servers in/on Russia. It would be nice to remove this server. This is necessary because of the law which forces every ISP to install special systems to track every user. Thus, everyone who would be connected to Russian nodes would be bugged and possibly record traffic.

Proof: https://en.wikipedia.org/wiki/Yarovaya_law

No, in countries like Mordor (the correct name for modern Russia), even encrypting the entire disk will not help.

Proof: https://en.m.wikipedia.org/wiki/SORM

Do you think that absence of logs is worthless? Well, it isn't!

Proof: https://en.m.wikipedia.org/wiki/Mass_surveillance_in_Russia

**Comment by ameshkov** [comment]
The server is located outside Russia, but has a russian IP address.
