### ISSUE TITLE
Add more languages to the program

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/AdGuardVPNForWindows#39]
Add more languages to the program (The program could support languages that already have translations outside of English and Russian)

**Comment by Aydinv13** [comment]
Thank you for your feature request. Actually, we are working on implementation of languages and we plan to do it in near future)

**Comment by adbuker** [comment]
@eduardoaddad, please try the latest nightly, we've added some languages already.

**Comment by eduardoaddad** [comment]
@adbuker 

Brazilian Portuguese and European Portuguese will be added?
