### ISSUE TITLE
Add support for the AdGuard app

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/AdGuardVPNForWindows#40]
Add support for the AdGuard app (Run the AdGuard VPN and AdGuard normail without a problem)

**Comment by Aydinv13** [comment]
What exactly support do you propose? These two apps work together well

**Comment by eduardoaddad** [comment]
support of the AdGuard ad blocking app

**Comment by Aydinv13** [comment]
Please tell me what kind of problem do you have using both apps together? Your operating system and browser would be also useful.

**Comment by zzebrum** [comment]
@eduardoaddad do you mean compatibility between AdGuard adblocker and AdGuard VPN?

**Comment by Aydinv13** [comment]
Closed due to no response
