### ISSUE TITLE
A blank page opens when trying to log in to AdGuard For Windows in Chinese

### ISSUE THREAD

**Issue by nyfyzkl** [AdguardTeam/AdGuardVPNForWindows#406]
It is always normal for me to log in to my account when I use the AdGuard VPN browser plug-in. However, I always cannot log in using the AdGuard VPN on the Windows platform. When I enter my account in the software and click Next, I always enter a blank page. Once I suspected that it was the network blocking that made the page unable to open, so I used other VPN software to help me break through the blocking when all network traffic was proxied. But the result is still to enter the blank page. The process of logging in to the AdGuard VPN on the Windows platform using Google account is normal (when I use other VPN programs to help the network). In addition, when I randomly enter an unknown account to log in, the software will jump to the new user registration page. That is to say, there is no problem in the process of registering new users in the AdGuard VPN on the Windows platform. Only the old users have problems in the process of logging in. The version of AdGuard VPN on the Windows platform is the latest version. The system is Windows 10 and keeps updated.
![1](https://user-images.githubusercontent.com/124302594/216427504-edcfdc2d-37ae-446b-8119-f2dcee9531d1.png)
![2](https://user-images.githubusercontent.com/124302594/216427519-74942963-f5b8-4f71-ad4b-ec709d73e815.png)

**Comment by mozartinio** [comment]
@nyfyzkl 
Hello!
Thank you for your report!
We will fix it for sure

**Comment by adbuker** [comment]
@nyfyzkl could you please try to repro the issue with [this build](https://uploads.adguard.org/AdGuardVpn-bugfix_AG-18166.exe). It's an unpublished build (yet), and it see the light only on the next week, but if you try it - we'll be very thankful

**Comment by nyfyzkl** [comment]
> @nyfyzkl could you please try to repro the issue with [this build](https://uploads.adguard.org/AdGuardVpn-bugfix_AG-18166.exe). It's an unpublished build (yet), and it'll see the light only on the next week, but if you try it - we'll be very thankful

Sorry, the problem still exists. At present, my region cannot open the website of adguard VPN through direct connection, including login and registration, and I need to use other VPN software to help me log in to adguard VPN (based on proxy mode, not based on virtual network card mode). If I do not use other VPN software, when I use the adguard VPN, I will be prompted with "unknown error" after entering the e-mail user name. If you use other VPN software to help break through the network blockade, you will still jump to the blank page after entering the email user name in the adguard VPN login interface. At present, there is no login problem when I use the browser plug-in version. If I can't find the reason for this problem, it doesn't matter. I guess it may have something to do with the blocking of the network and the inability to directly link to the adguard VPN login server. I tried to ask questions from some forums, and the answer I got was that if I used the English version of adguard VPN, this problem would not occur. However, I don't know how to get the English version of the adguard VPN software, so I didn't try this method.

**Comment by adbuker** [comment]
@nyfyzkl, seems we've found the clue, and the nightly with the fix will be published asap

**Comment by nyfyzkl** [comment]
> @nyfyzkl, seems we've found the clue, and the nightly with the fix will be published asap

This is worth looking forward to.

**Comment by zubrRB** [comment]
> I tried to ask questions from some forums, and the answer I got was that if I used the English version of adguard VPN, this problem would not occur. However, I don't know how to get the English version of the adguard VPN software...

![-](https://user-images.githubusercontent.com/50718960/220641208-876933da-916c-43ed-997d-b435b7468b10.png)

**Comment by nyfyzkl** [comment]
> > I tried to ask questions from some forums, and the answer I got was that if I used the English version of adguard VPN, this problem would not occur. However, I don't know how to get the English version of the adguard VPN software...
> 
> ![-](https://user-images.githubusercontent.com/50718960/220641208-876933da-916c-43ed-997d-b435b7468b10.png)

If the software can switch languages only after logging in, it seems that the answer of this forum is invalid for me who cannot log in.

**Comment by nyfyzkl** [comment]
> > I tried to ask questions from some forums, and the answer I got was that if I used the English version of adguard VPN, this problem would not occur. However, I don't know how to get the English version of the adguard VPN software...
> 
> ![-](https://user-images.githubusercontent.com/50718960/220641208-876933da-916c-43ed-997d-b435b7468b10.png)

[https://forum.adguard.com/index.php?threads/adguard-vpn-login-page-jumps-to-blank.51397/](url)

**Comment by zubrRB** [comment]
@nyfyzkl What if by two-factor authentication (2FA) code?

**Comment by nyfyzkl** [comment]
> @nyfyzkl What if by two-factor authentication (2FA) code?

I found that this option in the adguard account settings is not enabled. When I click Open, I will be prompted to use the 2FA application to scan the QR code. What is the name of this 2FA application? Do I need to download it to Android phone?

**Comment by nyfyzkl** [comment]
> @nyfyzkl What if by two-factor authentication (2FA) code?

The software is already known. I am trying to login in this circumstances.

**Comment by zubrRB** [comment]
To activate the Adguard VPN, you can enter your e-mail and temporary 2FA code.

**Comment by nyfyzkl** [comment]
> To activate the Adguard VPN, you can enter your e-mail and temporary 2FA code.

I just tried to turn on the 2FA option. I have turned this option on through the web login test. However, after entering the email in the computer version of adguard VPN, it still jumps to blank, and there is no way to continue to enter the password or 2FA code.

**Comment by zubrRB** [comment]
Use a third-party VPN service at this point.

**Comment by nyfyzkl** [comment]
> Use a third-party VPN service at this point.

yes. At this time, I did use other VPN software to help me break through the network blockade. If other VPN software is not used for assistance, the software will prompt "error occurred" after entering the email.

**Comment by zubrRB** [comment]
@nyfyzkl Does the new version work?

**Comment by nyfyzkl** [comment]
> @nyfyzkl Does the new version work?

Thank you. Now the latest official version on the official website has solved this problem!!

**Comment by mozartinio** [comment]
@nyfyzkl Nice!
Im closing the issue if it will happen again feel free to reopen it
