### ISSUE TITLE
Unstable internet connection after resuming from hibernation

### ISSUE THREAD

**Issue by eukislov** [AdguardTeam/AdGuardVPNForWindows#407]
### Issue Details

- **AdGuard VPN version:**
  - 2.1.791.0
- **VPN mode:**
  - Local VPN
- **Operating system and version:**
  - Windows 11 Build 25290

### Actual Behavior
When the VPN is connected, after the laptop wakes up from hibernation, the Internet connection starts to work unstable: the icon on the taskbar once a minute shows that the WI-Fi connection is lost. Disconnecting from the server, restarting the laptop and connecting to the server after booting helps fix the problem. If you close and open the laptop again, the Internet connection will become unstable again.

При подлючении к любому серверу после выхода ноутбука из режима гибернации интернет начинает работать нестабильно: значок на панели задач с периодичностью раз в минуту показывает, что потеряно WI-Fi соединение. Исправить проблему помогает отключение от сервера, перезагрузка ноутбука и повторное подключение к серверу после загрузки системы. Если закрыть и снова открыть ноутбук, соединение с интернетом теряется.
Проблема наблюдается достаточно давно, казалось, что виновата функция Kill Switch, но даже если ее выключить ситуация не меняется.

**Comment by mozartinio** [comment]
@eukislov 
Hello!
It is not reproduce on our side so i need you to give us more information please
For how long you put your windows into hibernation?
Here's what we need you to do:

Collect the debug log as it's explained here -> (https://kb.adguard.com/en/windows/solving-problems/adguard-logs).
Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file.
Send the archive to devteam@adguard.com and mention this issue number in the subject.

**Comment by mozartinio** [comment]
@eukislov Thank you!
We will look into the problem

**Comment by eukislov** [comment]
@mozartinio,
Is there any news on my problem?

Did you manage to establish the cause and when to wait for the fix?
Is there anything I need to do (settings change or something else) to prevent this from happening again?

**Comment by mozartinio** [comment]
@eukislov 
There is no news yet
We will let you know when we will figure out
Stay tuned!

**Comment by Batman2814** [comment]
I had this problem to when I was on a zoom call and I had Adguard VPN for Windows enabled I would get a means saying "your Internet connection is unstable which caused my zoom call to freeze so I had to turn off Adgaurd VPN for Windowsin order for my zoom call to resume. My internet is fast and even says in adguard when connect says 38-43 ms

**Comment by adbuker** [comment]
can be partially related to https://github.com/AdguardTeam/AdguardForWindows/issues/4551

**Comment by mozartinio** [comment]
@eukislov 
Hi!
Can you please update to the latest nightly in both products? (AdGuard VPN, AdGuard AdBlocker)
How often does this happen? Is there a pattern?
Can you record **trace logs** on both products (in that time when you got the problem). The format of the logs where you wrote the time codes was very convenient so thank you)
As for the **trace logs** we got instruction here https://adguard.com/kb/adguard-for-windows/solving-problems/adguard-logs/

**Comment by eukislov** [comment]
@mozartinio, 
Hello,

I re-send logs for the problem to devteam@adguard.com.

As I indicated in the letter, I was able to trace the problem only once, after starting the VPN and opening and closing the laptop lid for the first time. After that the problem did not appear.

In addition, a little earlier than this moment (literally a two or three minutes earlier), the problem manifested itself at the moment when the VPN was not connected to the server. I have not been able to repeat this again. Therefore, I cannot identify any repetitive patterns for this problem.

I also note that despite the fact that the WiFi connection did not break, after each login for some time (for about two minutes, I guess) the connection was unstable, some elements on the pages were not displayed. After a couple of minutes everything was fine.

**Comment by mozartinio** [comment]
@eukislov 
Got it! Thank you! Looking for the cause of the problem

**Comment by mozartinio** [comment]
@eukislov 
Sorry for the long answer
1. According to the logs from the moment "53 seconds" you had attempts to automatically connect to the location. What happens if you don't do it manually?
2. Does this only happen if both products are working? Is everything fine without AdGuard adblocker? 
3. Update to the latest nightly version and check does it reproduce or no
4. If the problem repeats on the last nightly version please send trace logs as it explained here https://adguard.com/kb/adguard-for-windows/solving-problems/adguard-logs/#trace-logs

**Comment by mozartinio** [comment]
@eukislov 
Thank you! We are looking for the cause

**Comment by vankos** [comment]
@eukislov, 
Hi!
Could you please disable "Use QUIC" option and try to reproduce the problem? 
You can find it in Settings → App settings → Advanced Settings

**Comment by eukislov** [comment]
@vankos,
Hello!
I can't reproduce the problem on the latest Adguard and Adguard VPN nightly versions. It is probably possible that the problem was on my side: I did not encounter it after I unchecked "Allow the computer to turn off this device to save power" in the router settings in Device Manager.
I think the problem is solved. If I run into a problem again, I will return the ticket to work.

**Comment by vankos** [comment]
Great!
Thanks for the update!
