### ISSUE TITLE
On Windows, login always turn to black screen

### ISSUE THREAD

**Issue by Tungdiel** [AdguardTeam/AdGuardVPNForWindows#408]
Hi When using a Windows version, I login will always show "error" or completely black screen, I use VPN, will appear the same again. Please repair. Thanks
[adg_logs_2.0.784.0_0204_1700.zip](https://github.com/AdguardTeam/AdGuardVPNForWindows/files/10608293/adg_logs_2.0.784.0_0204_1700.zip)

**Comment by gork7777** [comment]
Duplicate I guess: https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/406
