### ISSUE TITLE
AdGuard VPN doesn't install

### ISSUE THREAD

**Issue by sanchezho** [AdguardTeam/AdGuardVPNForWindows#410]
### Issue Details

- [X ] I am running the latest version
- [ X] I checked the documentation and found no answer
- [ X] I checked to make sure that this issue has not already been filed

- **AdGuard VPN version:**
  - 2.0.784.0
- **Operating system and version:**
  - Windows 11
  - 
- **Other network-level software:**
  - AdGuard and WindowsDefender

### Expected Behavior

To run Webinstaller or Installer .exe file and AdGuard VPN to install and run as standalone on computer. 

### Actual Behavior

When trying to install via the Webinstaller, it opens the splashscreen, a progress bar fills up and that's it. When trying to run it again it says an unexpected error occurred, and to download manually showing a link, clicking the link downloads and installer.exe file.
When trying to install via the installer.exe file, the installation screen appears, a progress bar shows and it never fills up, it hangs there.

**Comment by mozartinio** [comment]
@sanchezho 
Hello!
Did you try to download with another network?
Can you please sent %tmp% logs to us?
Also we need your dump file (try to install VPN and while you got splashscreen do next -> open task manager -> right click on AdGuard VPN -> create dump file and sent it to devteam@adguard.com)

**Comment by mozartinio** [comment]
@sanchezho 
Any news?

**Comment by sanchezho** [comment]
After a Windows Update the installer worked fine.

**Comment by mozartinio** [comment]
@sanchezho 
Nice!
I'm closing the issue 
If you will got something like this again  - feel free to reopen the issue
