### ISSUE TITLE
License validation process relies on a system time instead of a server

### ISSUE THREAD

**Issue by DBotThePony** [AdguardTeam/AdGuardVPNForWindows#413]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.0.784

### Operating mode

VPN

### Environment

```markdown
- OS: Windows 10.0.19044
- Other network-level software: AdGuard
```

### Issue Details

Steps to reproduce:
1. Obtain VPN subscription from AdGuard website
2. Attempt to use the subscription within 'narrow' expiration period due to UTC timezones (any UTC+2 and up should work)
3. Experience weird program behavior (pressing Connect will display 'Connecting...' and then 'Disconnected' without any clues what happened) while being unable to connect to VPN

### Expected Behavior

Being able to connect to VPN until current subscription end

### Actual Behavior

Unable to connect, service logs contain next lines:

```
WARNING, AdGuardVpnSvc.exe, Logger, 18, 27.02.2023 9:45:51.366, Cannot complete the operation due to license status 'VALID' and/or time expire `27.02.2023 5:18:23`
INFO, AdGuardVpnSvc.exe, Logger, 18, 27.02.2023 9:45:51.367, Auth configuration is not specified: False, False, True
WARNING, AdGuardVpnSvc.exe, Logger, 18, 27.02.2023 9:45:51.368, Cannot update vpn token and credential
INFO, AdGuardVpnSvc.exe, Logger, 18, 27.02.2023 9:45:51.369, Auth configuration is not specified: False, False, True
WARNING, AdGuardVpnSvc.exe, Logger, 18, 27.02.2023 9:45:51.369, Cannot connect to VPN, auth configuration is not specified
```

On machine with UTC+7 timezone (license expires by 5:18:23 UTC+7 or UTC+0?; AdGuard website says license is still valid)

### Screenshots

<details><summary>Screenshot 1:</summary>

![rSklJJjQgk](https://user-images.githubusercontent.com/6339511/221462612-edb05be4-ee52-4e63-b243-7878e3631af4.gif)

</details>

### Additional Information

This issue is not present on Adguard for Android, Android app successfully connects to VPN servers despite having the same timezone settings.

**This also prevents connecting to VPN even if you made new subscription** (different payment method), but the latter not being active due to current still being valid (not expired)

**Comment by DBotThePony** [comment]
Switching timezone to UTC+1 AND restarting AdGuard VPN service does allow me to connect to VPN servers normally.

**Comment by mozartinio** [comment]
@DBotThePony Hi!
Does it reproduce on the new VPN version 2.0.789.0 (2.0.3) ?

**Comment by DBotThePony** [comment]
At time of writing the issue report, client was on latest, so unless you fixed the bug in `2.0.789.0` it should still be reproducible

**Comment by mozartinio** [comment]
@DBotThePony 
Sorry for the long answer
I need more information about your issue
So as i understand you bought subscription and in the end of your yearly subscription you changed time zone and after that VPN cant be in status "connected". And if you change your time zone back the problem still reproduced?
Am i right?

**Comment by shark696969** [comment]
Repostory

Pada tanggal Jum, 24 Mar 2023 16.53, Maxim ***@***.***>
menulis:

**Comment by DBotThePony** [comment]
> Sorry for the long answer
I need more information about your issue
So as i understand you bought subscription and in the end of your yearly subscription you changed time zone and after that VPN cant be in status "connected". And if you change your time zone back the problem still reproduced?
Am i right?

The root cause of issue is basically desktop client checking whenever license has experied using **local** timezone, while server sends timestamp without timezone. So, for example, if license expires at 05:00 UTC+0, and your PC' local time is 07:00 UTC+7, VPN client will (locally) incorrectly assume license has experied. If you change your PC' clock to 04:00 UTC+7 or 04:00 UTC+0, VPN client will successfully connect.

> Also can you please leave you email address so i could check your subscriprion

roboderpy at gmail dot com

**Comment by shark696969** [comment]
Privacy&police android conmid
Mustofa



Pada tanggal Jum, 24 Mar 2023 20.52, DBotThePony ***@***.***>
menulis:

**Comment by adbuker** [comment]
@DBotThePony , сould you please update to the latest nightly and check whether the issue remains
