### ISSUE TITLE
Missing string in browse app popup in Apps exclusions

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNForWindows#423]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

v2.1.818.0 nightly

### Operating mode

VPN

### Environment

```markdown
- OS: Windows 10
```

### Issue Details

Steps to reproduce:
1. Go to `Settings`. 
2. Go to `Apps exclusions` and click `Add application`.
3. Click `Browse` button, you can see the screenshot.

### Expected Behavior

`Select file:` should be localizable. String is missing.

### Actual Behavior

`Select file:` not localizable. You can add this string for localization.

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/35523759/226495448-b600b4a3-8389-4cf1-89b1-fdd15649d7f3.png)
</details>

**Comment by mozartinio** [comment]
@gork7777 
Thank you!
