### ISSUE TITLE
Windows Sandbox bypasses AdGuard VPN

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardVPNForWindows#426]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.0.6

### Operating mode

VPN

### Environment

```markdown
- OS: Windows 10, 11
- Other network-level software: n/a
```

### Issue Details

Steps to reproduce:
1. Run Windows Sandbox
2. Check if it connects through VPN

### Expected Behavior

It does connect through VPN

### Actual Behavior

It ignores VPN and connects directly

### Additional Information

The task has been moved here from the Triage Queue, as requested

**Comment by northis** [comment]
This is imposible using WFP driver. This will be possible after migrating to TUN interface in the next release.

**Comment by northis** [comment]
It works now with `Use Wintun` option enabled (in advanced settings) in 2.2 nightly 3.

**Comment by oldshensheep** [comment]
@northis how can I download it? There is no download button https://adguard-vpn.com/en/versions/windows/nightly.html

**Comment by Aydinv13** [comment]
@oldshensheep download via this [link](https://agrd.io/windows_vpn_nightly), please.
