### ISSUE TITLE
Notification about unavailable DNS server appears when waking from sleep mode

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardVPNForWindows#429]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

Version 2.0.795.0

### Operating mode

VPN

### Environment

```markdown
- OS: Windows 11 22H2
- Other network-level software: Bitdefender Total Security (but I have Adguard VPN/Adguard Adblocker in exclusions where it's called Manage Exceptions).
```

### Issue Details

Steps to reproduce:
1. laptop is in sleep mode all night
2. next morning I wake my computer from sleep mode
3. I get that notification pop-up about the server 

### Expected Behavior

should work without any problems with the server.

### Screenshots

![20230331_07300156_Edited](https://user-images.githubusercontent.com/96619913/229127408-9faec0a6-c0b2-4e42-93e5-98cfb3934d53.png)

**Comment by VladisLoveZh** [comment]
@Batman2814 
Hi, 
Could you please set your settings to default and install AdGuard VPN Nightly? Reproduce the issue and collect logs for us. Then send them over via email at devteam@adguard.com and attach this link: https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/429

**Comment by Batman2814** [comment]
Installed Adgaurd VPN Nightly for Windows. So I will get you the logs and send them to the email.
