### ISSUE TITLE
AdGuard VPN starts with a blank screen in the Japanese language of the system

### ISSUE THREAD

**Issue by Aydinv13** [AdguardTeam/AdGuardVPNForWindows#431]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.0.6

### Operating mode

None

### Environment

```markdown
- OS:
- Other network-level software:
```

### Issue Details

Steps to reproduce:
1. Set Japanese system language
2. Install AdGuard VPN (should be a clean install)

### Expected Behavior

After installation, the application runs as usual

### Actual Behavior

The app starts with a blank screen

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by ihurin** [comment]
the issue is also reported in ZD ticket #745782
