### ISSUE TITLE
Allow to search by country code (ISO format, e.g. `US`)

### ISSUE THREAD

**Issue by contribucious** [AdguardTeam/AdGuardVPNForWindows#434]
## Issue Details

Hi. As [requested](https://github.com/AdguardTeam/AdGuardVPNExtension/issues/85#issuecomment-1519630931) by the AdGuard team …

↪️ **Please refer to:** https://github.com/AdguardTeam/AdGuardVPNExtension/issues/85

Thanks in advance! 🙂

**Comment by VladisLoveZh** [comment]
> ## Issue Details
> Hi. As [requested](https://github.com/AdguardTeam/AdGuardVPNExtension/issues/85#issuecomment-1519630931) by the AdGuard team …
> 
> ↪️ **Please refer to:** [AdguardTeam/AdGuardVPNExtension#85](https://github.com/AdguardTeam/AdGuardVPNExtension/issues/85)
> 
> Thanks in advance! 🙂


Hi, 
Thank you. Acknowledged, we'll consider adding this in our future updates.

**Comment by contribucious** [comment]
Perfect! Thank you very much! ✌️
