### ISSUE TITLE
Do not close the 'Add an app' window, if user opened and closed the "Browse" window

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardVPNForWindows#435]
### Issue Details

If the user could not find the EXE manually before loading the appls list, the apps list window closes when the file selection window closes.

This request arose because the list of programs takes a very long time to load and the user may try to find an application manually without waiting for the list to load.

### Proposed solution

Do not close the 'Add an app' window, if user opened and closed the "Browse" window

**Comment by adbuker** [comment]
The full flow will be reworked in 8.0 version
