### ISSUE TITLE
Unable to buy RZD tickets using Windows VPN or Windows browser extension

### ISSUE THREAD

**Issue by alextallinn** [AdguardTeam/AdGuardVPNForWindows#436]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.0.847.0

### Operating mode

VPN

### Environment

```markdown
- OS:Windows 10 Pro
- Other network-level software: Try to do it using Egde, Slimjet, Firefox
Also was try to use SOCKS5 + Firefox + FoxyProxy
No use.
```

### Issue Details

Steps to reproduce:
1. Try to open rzd.ru - OK, select ticket, try to buy it
2. Redirected to page, where entering back card data https://paygate.multicarta.ru/
3. Browser response:
Hmmm… can't reach this page
It looks like the webpage at https://paygate.multicarta.ru/index.jsp?ORDERID=405301546&SESSIONID=1C2B650A3DF9A27FCE5F77B56B247B40 might be having issues, or it may have moved permanently to a new web address.
ERR_TUNNEL_CONNECTION_FAILED"

### Expected Behavior

Should be redirected to page https://paygate.multicarta.ru/
enter card data and pay for the ticket.

### Actual Behavior

error code returned: strict-orign-when-cross-origin

Hmmm… can't reach this page
It looks like the webpage at https://paygate.multicarta.ru/index.jsp?ORDERID=405301546&SESSIONID=1C2B650A3DF9A27FCE5F77B56B247B40 might be having issues, or it may have moved permanently to a new web address.
ERR_TUNNEL_CONNECTION_FAILED"

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/131755402/234779219-2a185876-5777-4b0d-b18c-c9c58bee08a9.png)

</details>

**Comment by alextallinn** [comment]
[adg_logs_2.0.847.0_0420_2158.zip](https://github.com/AdguardTeam/AdGuardVPNForWindows/files/11340322/adg_logs_2.0.847.0_0420_2158.zip)

**Comment by VladisLoveZh** [comment]
> ### Please answer the following questions for yourself before submitting an issue.
> * [x]  I am running the latest version
> * [x]  I checked the documentation and found no answer
> * [ ]  I checked to make sure that this issue has not already been filed
> 
> ### AdGuard VPN version
> 2.0.847.0
> 
> ### Operating mode
> VPN
> 
> ### Environment
> ```gfm
> - OS:Windows 10 Pro
> - Other network-level software: Try to do it using Egde, Slimjet, Firefox
> Also was try to use SOCKS5 + Firefox + FoxyProxy
> No use.
> ```
> 
> ### Issue Details
> Steps to reproduce:
> 
> 1. Try to open rzd.ru - OK, select ticket, try to buy it
> 2. Redirected to page, where entering back card data https://paygate.multicarta.ru/
> 3. Browser response:
>    Hmmm… can't reach this page
>    It looks like the webpage at https://paygate.multicarta.ru/index.jsp?ORDERID=405301546&SESSIONID=1C2B650A3DF9A27FCE5F77B56B247B40 might be having issues, or it may have moved permanently to a new web address.
>    ERR_TUNNEL_CONNECTION_FAILED"
> 
> ### Expected Behavior
> Should be redirected to page https://paygate.multicarta.ru/ enter card data and pay for the ticket.
> 
> ### Actual Behavior
> error code returned: strict-orign-when-cross-origin
> 
> Hmmm… can't reach this page It looks like the webpage at https://paygate.multicarta.ru/index.jsp?ORDERID=405301546&SESSIONID=1C2B650A3DF9A27FCE5F77B56B247B40 might be having issues, or it may have moved permanently to a new web address. ERR_TUNNEL_CONNECTION_FAILED"
> 
> ### Screenshots
> Screenshot 1:
> ### Additional Information
> _No response_

@alextallinn hi, 
What if you use Kazakhstan location to make a purchase? Will it work for you?

**Comment by VladisLoveZh** [comment]
> Kazahstan? How I can know that? Why not Egept or Hong Kong? Choose one of 47 locations, it may work? Really I have found similar solution, but its have some other problems, was it rzd.ru blocked or some others blocs present... But this is not logical, straight forward and simple solution.

@alextallinn use Kazakhstan location instead while we're working on availability of RZD from Moscow location. 

CIS ip's are usually eligible to use Russia services like RZD, so I was able to reach RZD purchasing page without a hitch using Kazakhstan location. 
Nothing else was mentioned in my previous response: nor Egypt, Hong Kong or any other locations besides Kazakhstan. It is a back-up solution that works for me and it may work out for you as well.

**Comment by VladisLoveZh** [comment]
We're working on the fix, therefore closing the issue.

**Comment by alextallinn** [comment]
Thank you.
