### ISSUE TITLE
`Internal error` after a password change on another device

### ISSUE THREAD

**Issue by biomednet** [AdguardTeam/AdGuardVPNForWindows#445]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.1 nightly 13 for Vindows

### Operating mode

VPN

### Environment

```markdown
- OS:Windows 8.1 x64 SL
- Other network-level software: Adguard Antibanner 7.13 nightly 12
```

### Issue Details

Steps to reproduce:
1. Change password in mobile browser
2. Do not log out of the client on the computer and leave the computer on for 24 hours
3. Error client (foto 1 and 2)

Итак, я на с мобильника сменил пароль, при этом компьютер с VPN клиентом остался включенным примерно сутки без движения.  Сейчас я нажал на значок VPN на рабочем столе, чтобы его загрузить и может быть, обновить. 
Но в результате черный экран и сообщение об ошибке. Выгрузка/загрузка/перезагрузка не помогли. 
Логи собрал сразу и после работы автоматического восстановителя. от клиента VPN.
Куда отправить, не знаю.  

### Screenshots

![а2](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/29819868/7a508a00-443d-4a89-818e-202e202d9e6f)
![а1](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/29819868/ea806059-8eb3-484e-99cf-63dee1f47029)

**Comment by AlexandrPkhm** [comment]
@biomednet 

К сожалению, нам не удалось воспроизвести проблему. Для диагностики и решения данной проблемы, нам понадобятся логи приложения AdGuard.

Соберите и отправьте указанные файлы, используя данную инструкцию:

1. Зайдите в Настройки --> Настройки приложения --> Расширенные настройки --> Уровень логирования --> **Записывать все**;
2. Воспроизведите проблему и запомните точное время её воспроизведения. Оно понадобится
нам, чтобы найти соответствующие записи в лог-файле;
3. Зайдите в Настройки --> Поддержка --> Выберите **Экспортировать логи и информацию о системе**;
4. Отправьте полученный архив по адресу `devteam@adguard.com`. Также укажите номер задачи в Github и время воспроизведения проблемы.
5. Не забудьте вернуть значение уровня логирования на **Записывать по умолчанию**.

**Comment by AlexandrPkhm** [comment]
К сожалению, нам не удалось воспроизвести данную проблему. Если вы вновь столкнетесь с ней, пожалуйста, сообщите нам и мы продолжим искать решение.
