### ISSUE TITLE
App interface soft-locks after signing in to AdGuard account

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardVPNForWindows#45]
### Issue Details

- **AdGuard VPN version:**
  - 0.0 nightly 16
- **VPN mode:**
  - Local VPN
- **Operating system and version:**
  - Windows 10, version 20H2
- **Other network-level software:**
  - Unspecified

### Actual Behavior

Attempting to log in to your AdGuard accounts results in user interface soft-locking. Force killing the process and restarting it results in immediate UI soft-locking. App is basically unusable.

### Additional Information

Debug logs: see ticket 1518164.

**Comment by im3or** [comment]
Other network-level software: Adguard for Windows 7.5.3, Kaspersky Total Security 21.2

**Comment by ameshkov** [comment]
Yeah, this is definitely an issue and it can be solved.

**Comment by adbuker** [comment]
@akmLaVx, could you please ask to repro issue with the latest nightly build

**Comment by im3or** [comment]
> 
> 
> @akmLaVx, could you please ask to repro issue with the latest nightly build

I download the build from [here](https://adguard-vpn.com/en/beta.html). Still hangs after signing in. I have the new logs how should i send it?

**Comment by northis** [comment]
@im3or yeah, please send your logs to our email devteam@adguard.com and specify this issue number in the subject

**Comment by im3or** [comment]
> 
> 
> @im3or yeah, please send your logs to our email [devteam@adguard.com](mailto:devteam@adguard.com) and specify this issue number in the subject

Just send. Let me know if anything else is needed.

**Comment by northis** [comment]
> Just send. Let me know if anything else is needed.

From logs you've sent:
`The remote name could not be resolved: 'api.adguard.io'` . (`account.adguard.com` couldn't be resolved either)

Looks like this address isn't available in your system.
Please, try to open them in browser or execute ping command `ping account.adguard.com` and `ping account.adguard.com`.
AdGuard VPN cannot work without access to these addresses.
You also can disable Kaspersky AV for a while and check these addresses and AdGuard VPN. The AV can block them, if it does, we will fix this in future versions.

**Comment by im3or** [comment]
> > Just send. Let me know if anything else is needed.
> 
> From logs you've sent:
> `The remote name could not be resolved: 'api.adguard.io'` . (`account.adguard.com` couldn't be resolved either)
> 
> Looks like these addresses aren't available in your system.
> Please, try to open them in browser or execute ping command `ping account.adguard.com` and `ping account.adguard.com`.
> AdGuard VPN cannot work without access to these addresses.
> You also can disable Kaspersky AV for a while and check these addresses and AdGuard VPN. The AV can block them, if it does, we will fix this in future versions.
![Screenshot00022](https://user-images.githubusercontent.com/30718972/106737775-1964b280-663d-11eb-80a7-a4af41eaaf83.jpg)
Are you referring to this? I can access them alright with Kaspersky enabled. 
NOTE: I have AdGuardVPN uninstalled right now, should i install it & then ping these addresses?

**Comment by northis** [comment]
> NOTE: I have AdGuardVPN uninstalled right now, should i install it & then ping these addresses?
Yes, please. Another option - try to disable Kaspersky and check how the AdGuard VPN works.

**Comment by im3or** [comment]
> > NOTE: I have AdGuardVPN uninstalled right now, should i install it & then ping these addresses?
> 
> Yes, please. Another option - try to disable Kaspersky and check how AdGuard VPN works.

Checked with AdGuardVPN installed & Kaspersky disabled both, no issues accessing these addresses.
I checked one more thing, GUI basically hangs when i try to access settings, about, exclusion, etc. When i am on main tab page & selecting different servers GUI is not hanging. If you need these recent logs, i can send them.

**Comment by northis** [comment]
> Checked with AdGuardVPN installed & Kaspersky disabled both, no issues accessing these addresses.
> I checked one more thing, GUI basically hangs when i try to access settings, about, exclusion, etc. When i am on main tab page & selecting different servers GUI is not hanging. If you need these recent logs, i can send them.

Yes, please send us logs of GUI hanging moment. But the VPN connection itself works normal, doesn't it?

**Comment by im3or** [comment]
> > Checked with AdGuardVPN installed & Kaspersky disabled both, no issues accessing these addresses.
> > I checked one more thing, GUI basically hangs when i try to access settings, about, exclusion, etc. When i am on main tab page & selecting different servers GUI is not hanging. If you need these recent logs, i can send them.
> 
> Yes, please send us logs of GUI hanging moment. But the VPN connection itself works normal, doesn't it?

Just sent the recent logs. Yes, even though GUI hangs, if the VPN connection was made, it stays that way, i checked. I can't change anything (servers) or close the GUI.

**Comment by northis** [comment]
> Just sent the recent logs. Yes, even though GUI hangs, if the VPN connection was made, it stays that way, i checked. I can't change anything (servers) or close the GUI.

So the VPN works fine even Kaspersky AV is enabled?
Please, send us files from `%programdata%\AdguardVpn\Logs` folder. You sent us installer logs instead. Thank you.

**Comment by im3or** [comment]
> > Just sent the recent logs. Yes, even though GUI hangs, if the VPN connection was made, it stays that way, i checked. I can't change anything (servers) or close the GUI.
> 
> So the VPN works fine even Kaspersky AV is enabled?
> Please, send us files from `%programdata%\AdguardVpn\Logs` folder. You've sent us installer logs instead. Thank you.

Yes, VPN itself is working fine with Kaspersky enabled as well.
Didn't know. Sent the actual logs this time, please check!

**Comment by northis** [comment]
Thanks for the logs, we will investigate the problem.

**Comment by northis** [comment]
@im3or Could you please record a short video with these hangs? Thank you.

**Comment by im3or** [comment]
> @im3or Could you please record a short video with these hangs? Thank you.

Already sent along with logs from this time.

**Comment by northis** [comment]
@im3or it would be nice if you gave us a Telegram contact or something and we could view this problem via AnyDesk

**Comment by im3or** [comment]
> 
> 
> @im3or it would be nice if you gave us a Telegram contact or something and we could view this problem via AnyDesk

My telegram username is the same as here (im3or). I will install AnyDesk (only available as 14-day trial).

**Comment by northis** [comment]
@im3or this is a real strange issue, but we will update the UI in one of the further nightly versions, this may fix your problem. We will write when this version will be released.

**Comment by im3or** [comment]
Installed both VPN 1.0 Beta 1 &  1.0 nightly 2. Interface now only hangs when i open settings or any other tabs.

After installing, signing in & only using the 'Home' tab, interface is not hanging. Been using it for hours now. But as soon as i open exclusion or settings, the interface becomes unresponsive.
