### ISSUE TITLE
An unexpected error occurred everyday

### ISSUE THREAD

**Issue by freezewind** [AdguardTeam/AdGuardVPNForWindows#450]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.1.882.0

### Operating mode

VPN

### Environment

```markdown
- OS: Windows 11, 22H2, build 22621.1778
- Other network-level software: 
Netdrive3 v3.17.960
Adguard for windows v7.13 nightly 14
```

### Issue Details

I am not sure how to reproduce this error, but it happens several times a day.
![image](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/3954389/fe6a647b-ad97-4ec3-a2aa-60d899037f19)
Showing the error above, and have to click the "Try to recover" button to recover manually.

I am going to send the log to [devteam@adguard.com](mailto:devteam@adguard.com) after the issue created.
The email will include this GitHub issue number in the subject.
Edit: Sent the email

### Expected Behavior

Don't happens error or recover from error automatically 

### Actual Behavior

Vpn is disconnected and need to recover manually 

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/3954389/fe6a647b-ad97-4ec3-a2aa-60d899037f19)

</details>

**Comment by AlexandrPkhm** [comment]
@freezewind Hi!

Could you please let us know if you are using any anti-virus software on your device. Also pleas try installing the latest AdGuard VPN Nightly build available via this [link](https://agrd.io/windows_vpn_nightly) and let us know if the issue persists after that.

**Comment by freezewind** [comment]
The latest nightly build fixed this issue. Thank you for your quick response.
