### ISSUE TITLE
Changelog page blank when new update is available

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNForWindows#455]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.1.903.0 nightly

### Operating mode

VPN

### Environment

```markdown
- OS: Windows 10
```

### Issue Details

Steps to reproduce:
1. Click the `Update` button

### Expected Behavior

Changelog page shouldn't be blank. It should show the changes.

### Actual Behavior

Changelog page is blank now.

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/35523759/13369700-19d7-411e-8098-caf2211567ee)
</details>

**Comment by AlexandrPkhm** [comment]
Hi @gork7777!

We apologize for the delayed response.

Unfortunately, we have not been able to reproduce the problem on our end. Please let us know if you are still experiencing this issue with 2.1.903.0 or later nightly builds.

**Comment by AlexandrPkhm** [comment]
Hi @gork7777 

We will close the issue as we have not been able to reproduce it on our end. If you encounter this issue again, please contact us and we'll continue to investigate.
