### ISSUE TITLE
Using VPN without unblocking "svchost.exe"?

### ISSUE THREAD

**Issue by oep42** [AdguardTeam/AdGuardVPNForWindows#457]
I found out that I had to unblock `C:\Windows\System32\svchost.exe` in my firewall, to be able to use the AdGuard VPN Windows app. Unblocking this, creates a security risk, because malware may use `svchost.exe` to connect to the internet. Is there a way to use the AdGuard VPN Windows app, without having to unblock `C:\Windows\System32\svchost.exe`?
(AdGuard VPN for Windows, Version 2.0.847.0.)

**Comment by AlexandrPkhm** [comment]
Hi @oep42!

AdGuard VPN for Windows uses our own `adguardsvc.exe` process and therefore does not require `svchost.exe` to be added to the firewall exclusions. If you have problems running AdGuard VPN without `svchost.exe` added to the firewall exclusions, please let us know.

**Comment by AlexandrPkhm** [comment]
Hi @oep42 

Could you please let us know if you were able to use AdGuard VPN without adding svchost.exe to your firewall exclusions?

**Comment by oep42** [comment]
I had this problem with a Windows 8.1. system. I didn't do anything with this problem for a while. In the meantime, I installed the newest version of AdGuard VPN on a new Windows 11 system, and now my earlier problem does not exist anymore.
