### ISSUE TITLE
Access denied at auth.riotgames.com

### ISSUE THREAD

**Issue by AhnJaeHoon-0512** [AdguardTeam/AdGuardVPNForWindows#479]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.1.1 

### Operating mode

VPN

### Environment

```markdown
- OS: Windows 11, 22H2, build 22621.2134
- Other network-level software: Adguard, Windows defender

Note: Access is blocked on all devices.
```

### Issue Details

When I turn on Adguard VPN and go to auth.riotgames.com, the page where I log in to my Riot account, I'm denied access. This is true whether I'm on a server in the US, Japan, or South Korea, and it happens on my tablet and phone as well. I've tried pointing my DNS to Google or Cloudflare, but I'm still denied access.

Note that I use the VPN to bypass blocked pages on my Wi-Fi, so it's hard to disable the VPN on those pages because they're blocked on my Wi-Fi.

It may be difficult to solve because it is an access denial problem and not another problem, but if so, I would like to know if it is an unsolvable problem.

### Screenshots

<details><summary>Screenshot 1:</summary>
![image](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/61960352/7fca6126-31e4-4e07-a3d5-b8e9bef8e9b7)
</details>

**Comment by AlexandrPkhm** [comment]
Hi @AhnJaeHoon-0512 

Unfortunately, some websites, including riotgames.com, intentionally detect the use of VPN services and deny the connection. Our team is constantly working to mitigate this issue as much as possible.

We will add auth.riotgames.com to the list of inaccessible websites and do our best to resolve the issue.
