### ISSUE TITLE
VPN reconnects on AdGuard AdBlocker stop-start protection

### ISSUE THREAD

**Issue by northis** [AdguardTeam/AdGuardVPNForWindows#483]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.2.0n2

### Operating mode

None

### Environment

```markdown
- OS:Windows 11
```

### Issue Details

Steps to reproduce:
1. Establish a VPN connection
2. Stop the protection in AdGuard app
3. See the reconnect in AdGuard VPN app

### Expected Behavior

No reconnects

### Actual Behavior

AdGuard VPN reconnects almost every time when the protection of AdGuard restarts

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Alex-302** [comment]
Video [vpn.zip](https://github.com/AdguardTeam/AdGuardVPNForWindows/files/12422766/vpn.zip)
VPN reconnects after ~15 seconds after turning on AdGuard for Windows protection.

**Comment by adbuker** [comment]
It's "by design" behaviour: enabling protection must refresh all the handled connection, and once AdGuard filters the AdGuard VPN it closes the AdGuard VPN connections too and therefore forces its reconnecting
