### ISSUE TITLE
Bing Chat blocked

### ISSUE THREAD

**Issue by IanMoyes** [AdguardTeam/AdGuardVPNForWindows#497]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN Browser Extension version

2.1.1 (981)

### Environment

```markdown
- OS:Windows 11 64-bit
- Browser: Firefox 117.0 (64-bit) and Microsoft Edge 16.0.1938.62 (64-bit)
```

### Issue Details

Bing Chat does not work if Adguard VPN is engaged. Upon entering a query the message "Sorry, looks like your network settings are preventing access to this feature." is returned. Adding Bing as an exclusion doesn;'t work either - it makes most of Bing's functionality fail to load. The only way to get all of Bing Search and Chat to work is to completely disconnect the VPN.

### Expected Behavior

Bing Chat query to be processed and returned.

### Screenshots

![bing](https://github.com/AdguardTeam/AdGuardVPNExtension/assets/55648322/209c97d5-03c9-4e3a-bba4-0ee02075c305)

**Comment by AlexandrPkhm** [comment]
Hi @IanMoyes 

Please accept our apologies for the delayed response. Unfortunately, some websites are able to detect the use of VPN and restrict access to certain features. We have added Bing Chat to the list of sites that require our attention and will do our best to allow full access to the site with our VPN enabled.
