### ISSUE TITLE
Cloud synchronization of settings

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardVPNForWindows#500]
### Issue Details

https://github.com/AdguardTeam/AdGuardVPNExtension/issues/96

**Comment by AlexandrPkhm** [comment]
Hi @rakleed 

There are plans to implement cloud synchronization of settings, but this feature is not in the works, and we cannot say whether this feature will be implemented in the near future.

**Comment by rakleed** [comment]
@AlexandrPkhm  could you close the issue when this feature will be available in the release version?
