### ISSUE TITLE
Internet connection slows down at random time while Selective mode is enabled

### ISSUE THREAD

**Issue by askold2** [AdguardTeam/AdGuardVPNForWindows#509]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.1.1, 2.1.2, 2.2.0n6

### Operating mode

None

### Environment

```markdown
- OS: Windows10 LTSC 21H2, Windows10 Pro 22H2
- Other network-level software: AdGuard
```

### Issue Details

Не знаю как воспроизвести, происходит не постоянно, а время от времени и без видимых причин

### Expected Behavior

нормальная работа

### Actual Behavior

Замечено а Firefox, но не уверен, что только в нем.
Время от времени происходит зависание связи. Ну т.е. после клика ничего не происходит, всё висит и чего-то ждет. Повторный клик срабатывает нормально. Особенно напрягает когда это происходит при отправке сообщения на форум (метод POST). Если в процессе ожидания выполнить команду «Отключить» в AdguardVPN, то связь восстанавливается и всё проходит успешно, без повторного клика. Самое интересное, что происходит это в выборочном режиме на сайтах связь с которыми происходит НЕ через VPN.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

Всё это повторяется на 2 компутерах, на обоих Win10, но разных версий, железо разное, провайдеры тоже разные. От режима VPN/SOCKS5 и QUIC не зависит. Но при отключенном Adguard VPN, даже запущенном, такого не происходит. Кстати, Adguard VPN 2.2.0n6 на одном из этих компьютеров отказалась работать вообще, а на другом работает так же, как 2.1.2.

**Comment by zubrRB** [comment]
Бывает соединение обрывается, опция Kill Switch блокирует доступ к интернету пока не переподключится.

**Comment by askold2** [comment]
Kill Switch отключена, забыл написать

**Comment by zubrRB** [comment]
Зависание связи происходит в момент подключения или когда соединение рвётся, что периодически имеет место быть?

**Comment by askold2** [comment]
В процессе браузинга на сайтах, где VPN вообще не используется. Я без понятия что там с подключением к VPN серверу происходит. Но судя по тому, что никаких сообщений в центре уведомлений при этом не появляется, ничего.

**Comment by AlexandrPkhm** [comment]
Здравствуйте, @askold2 

Для диагностики и решения Вашей проблемы, нам понадобятся логи приложений AdGuard VPN и AdGuard. Пожалуйста, соберите и отправьте указанные файлы, используя данные инструкции.

AdGuard VPN:

1. Перейдите в Настройки -> Настройки приложения -> Расширенные настройки -> Уровень логирования -> **Записывать все**;
2. Воспроизведите проблему и запомните точное время, в которое она была воспроизведена. Это понадобится нам для поиска соответствующих записей в лог-файле;
3. Откройте вкладку Поддержка -> **Экспортировать логи и информацию о системе**;
4. Отправьте архив по адресу `devteam@adguard.com`, указав в теме письма номер задачи Github. Не забудьте указать время воспроизведения.
5. Установите уровень логирования обратно на **Записывать по умолчанию**.

AdGuard:

1. Соберите логи [согласно данной инструкции](https://adguard.app/kb/ru/adguard-for-windows/solving-problems/adguard-logs/).
2. Запомните точное время воспроизведения проблемы. Оно понадобится нам, чтобы найти соответствующие записи в лог-файле;
3. Отправьте полученный архив по адресу `devteam@adguard.com`. Также укажите номер задачи Github и время воспроизведения проблемы.

**Comment by askold2** [comment]
отправил

**Comment by askold2** [comment]
Обнаружил еще одно проявление вероятно того же самого бага. На этот раз со 100% повторяемостью. Режим работы у меня выборочный не только по сайтам, но и по приложениям. Так вот при подключенном VPN происходит зависание FTP соединения в Total Commander, которого нет в списке программ, работающих через VPN, с сервером, которого тоже нет в этом списке. При отключении VPN происходит разрыв FTP соединения, но потом можно соединиться снова уже без проблем. Логи нужны?

**Comment by adbuker** [comment]
@askold2 , не могли бы вы проверить повторяемость проблемы с использованием последней найтли версии. Если проблема повторится - просьб отправить "трейсовы" логи (инструкция [тут](https://kb.adguard.com/windows/solving-problems/adguard-logs)) на почту devteam@adguard.com со ссылкой на эту задачу. Просьба также указать время возникновения проблемы, а также обстоятельства воспроизведения

**Comment by askold2** [comment]
Лог отправил

**Comment by askold2** [comment]
Не понял где fixed-то? ftp как не работало, так и не работает. в том числе в сегодняшней ночной сборке

**Comment by adbuker** [comment]
@askold2 , шалит флоу, проблема фиксится, лучше следите за статусом задачи - если она открыта, значит проблема не пофикшена (в процессе)

**Comment by AlexandrPkhm** [comment]
Hi @askold2 

Пожалуйста, сообщите нам, повторяется ли проблема с подключением к FTP в последней найтли версии AdGuard VPN for Windows, которая доступна по следующей [ссылке](https://static.adtidy.net/windows/nightly/installer-2.2.1139.0.exe)?

Если проблема все еще сохраняется, попробуйте выключить блокировщик рекламы AdGuard и выполнить подключение. Пожалуйста, дайте нам знать о результатах.

**Comment by askold2** [comment]
Ну если это та же версия, что устанавливается при обновлении из программы (nightly 34(113)), то ничего не изменилось, всё повторяется, в том числе и без adguard. А по ссылке не ставится, говорит, что уже установлен. Сейчас уже и 35(114) поставилась с тем же результатом.
Еще из интересного про ftp. Если сначала соединиться с ftp, а потом с VPN, то ftp продолжает работать нормально.

**Comment by AlexandrPkhm** [comment]
@askold2 

По всей видимости обычных логов в данном случае недостаточно для диагностики данной проблемы. Пожалуйста, запишите для нас Трейсовые логи приложения AdGuard VPN. 

Для этого:
1. Откройте консоль (наберите `cmd` в стартовой панели).
2. Запустите приложение командой `C:\"Program Files (x86)"\AdguardVPN\AdguardVPN.exe /trace` (если вы используете 64-битный Windows) или `C:\"Program Files"\AdguardVPN\AdguardVPN.exe /trace` (если вы используете 32-битный).
3. Воспроизведите ошибку. Запомните точное время воспроизведения проблемы. Оно понадобится нам, чтобы найти соответствующие записи в лог-файле.
4. Экспортируйте полученные логи при помощи кнопки Экспортировать логи.
5. Отправьте полученный архив по адресу `devteam@adguard.com`. Также укажите номер задачи Github и время воспроизведения проблемы.

**Comment by askold2** [comment]
Отправил. (nightly 37)

**Comment by Refreezer** [comment]
@askold2 Добрый день, пожалуйста обновитесь до последней nightly версии и проверьте повторяется ли описанное в issue поведение.

**Comment by askold2** [comment]
Ничего не изменилось. Насчет зависаний в браузере я не уверен, оно происходит эпизодически, но ftp по-прежнему зависает в 100% случаев.

**Comment by askold2** [comment]
Кстати, рекомендую обратить внимание: v2.1 вела себя на двух компьютерах совершенно одинаково, но v2.2 и все ее nightly - по-разному (см. issues #595, #596)

**Comment by Refreezer** [comment]
@askold2 подскажите пожалуйста какую версию Total Commander вы используете?
Повторяется ли поведение при использовании консольного ftp клиента?

**Comment by askold2** [comment]
TC 8.51a, но это не важно - в консольном ftp то же самое, о чем и написано выше. ТС зависает в момент передачи команды PORT. Консольный ftp соединяется, но зависает при вводе команды ls. При отключенном соединении с VPN сервером оба работают нормально.

**Comment by askold2** [comment]
Похоже, вы поторопились объявить багу пофиксенной. Точнее, видимо это все-таки было 2 отдельных бага, а не один. Зависание FTP действительно вылечили. А вот рандомные подвисания в браузере остались, но что-то изменилось. Насчет подвисаний при загрузке страниц судить трудно, а вот при отправке сообщений они точно бывают, но раньше отключение от vpn сервера приводило к размораживанию, а теперь к разрыву  соединения. Напомню, что речь о связи с сайтом, связь с которым должна быть не через vpn и на нее отключение от vpn сервера влиять никак не должно.

**Comment by vankos** [comment]
@askold2, добрый день, спасибо за обратную связь!

Знаю мы уже просили вас не раз, но не могли бы вы собранные на последней найтли и повторно отправить логи в соответствии с инструкцией, описанной здесь:  https://kb.adguard.com/windows/solving-problems/adguard-logs на почту [devteam@adguard.com](mailto:devteam@adguard.com) со ссылкой на эту задачу. 

Также, пожалуйста, укажите шаги и время воспроизведения, а также сайт, на котором воспроизводилась проблема. 

Последний раз логи именно по проблеме с замедлением присылали аж в сентябре, с тех пор в приложении много что поменялось и те логи стали не актуальными, поэтому мы вынуждены попросить собрать их снова. 
Заранее спасибо

**Comment by askold2** [comment]
Вам трейсовые нужны или обычные?

**Comment by vankos** [comment]
Трейсовые, пожалуйста

**Comment by askold2** [comment]
Ой, сразу не заметил, у вас ссылка на получение логов adguard, а не adguardVPN. Это вы ошиблись или вам именно логи adguard понадобились?

**Comment by vankos** [comment]
Извините, моя ошибка, действительно, логи нужны с adguardVPN,  вот сообщение с инструкцией: 
https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/509#issuecomment-1838896320

**Comment by askold2** [comment]
Ох, тяжело большие трейсовые логи по емейл слать, пришлось через gmail.
В общем, на этот раз воспроизвести случайное зависание мне не удалось. Возможно, вы их таки починили, а то, что было на прошлой неделе было связано с проблемами сети, а не с вашей программой. Но вот что осталось - это разрыв соединения с сайтом, связь с которым идет не через VPN, при отключении от VPN сервера. (опция kill switch выключена).

**Comment by vankos** [comment]
Добрый день! 
Рад слышать, что замедление больше не воспроизводится. 
По поводу разрыва соединения с сайтом: 
Это ожидаемое поведение - мы закрываем соединения на уровне приложений, то есть, если само приложение браузера не в исключениях, то при подключении/отключении от ВПНа мы будем разрывать все соединения этого браузера, включая соединения сайтов в исключениях. 
Если для вас это критично,  могу предложить использовать этот сайт в отдельном браузере, добавленном в исключения приложений. 

Если у вас появятся еще проблемы, смело создавайте новые  ишью, спасибо!
