### ISSUE TITLE
Add optional connection obfuscation

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardVPNForWindows#518]
### Issue Details

Nowadays it is often not possible to connect to your servers from Russia.

### Proposed solution

Add optional obfuscation when connecting, for example using V2Ray or Xray or Shadowsocks.

**Comment by ameshkov** [comment]
See my response here: https://github.com/AdguardTeam/AdGuardVPNForMac/issues/259#issuecomment-1717082122
