### ISSUE TITLE
The connection disappears in Chrome after disabling the VPN

### ISSUE THREAD

**Issue by zubrRB** [AdguardTeam/AdGuardVPNForWindows#519]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.1.2 (1000)

### Operating mode

VPN

### Environment

```markdown
- OS: Windows 7 Ultimate
- Other network-level software: Chrome 109.0.5414.149, AdGuard 7.15 Beta 1, IDM 6.41.20, Norton 360, dnscrypt-proxy
```

### Issue Details

Steps to reproduce:
1. Запустить браузер Google Chrome.
2. Подключить VPN (основной Румыния) и использовать браузер. Могут быть автоматические переподключения.
3. Отключить VPN. После чего в браузере ничего не открывается. 

### Expected Behavior

Браузер продолжает штатно функционировать. 

### Actual Behavior

Восстановить соединение возможно лишь после полного перезапуска Google Chrome, причём в такой ситуации после его стандартного закрытия через крестик в диспетчере задач Windows всегда продолжают висеть несколько процессов `chrome.exe`, которые сами при этом окончательно не выгружаются. Приходится принудительно завершать один из тяжеловесных, чтобы полностью выгрузить Chrome. Если завершить самый тяжелый, то при следующем запуске Chrome будут потеряны (закрыты) все открытые при закрытии вкладки, если же закрывать самые лёгкие, то это ничего не даст. 

### Screenshots

<details><summary>Screenshot 1:</summary>

![диспетчер](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/50718960/5eb8dc93-5f65-4928-b2c2-f3a720f21574)

</details>

**Comment by Aydinv13** [comment]
@zubrRB Здравствуйте! 
Пока что не можем воспроизвести эту проблему. Влияет ли отключение антивируса на поведение впна?

**Comment by zubrRB** [comment]
Проблема проявилась примерно в одно время с проблемой расширения CyberGhost VPN Free Proxy, которое при попытке подключения вдруг стало выдавать в браузере ошибку `ERR_PROXY_CONNECTION_FAILED`. На воспроизведение проблемы с AdGuard VPN, вероятно, сказывается периодический разрыв и автоматическое переподключение.

**Comment by zubrRB** [comment]
Ещё и такая ошибка после включения CyberGhost стала появляться `ERR_TUNNEL_CONNECTION_FAILED`.

**Comment by zubrRB** [comment]
Эффект будто отключение VPN расценивается как обрыв соединения и Kill Switch блокирует доступ к интернету... 
Страницы вообще не грузятся, сплошной белый фон без указания на ошибки, а на вкладке просто крутится лоадер.

**Comment by Aydinv13** [comment]
Последняя версия расширения CyberGhost VPN Free Proxy v7.0.0 выдает `сonnectPage.error` при попытке коннекта на всех устройствах.
Пожалуйста, соберите подробные логи и укажите точное время воспроизведения проблемы.

**Comment by zubrRB** [comment]
ZenMate объявил о слиянии с CyberGhost, после чего у юзеров сначала перестал работать первый, а вскорости и второй.

**Comment by zubrRB** [comment]
После обновлений на подверсии 3/4 разрывы свелись к минимуму или  отсутствуют, но проблема иногда возникает.  
И проявились другие проблемы с попеременным зависанием то службы, то UI, о чём подробнее описал в иных ветках.

**Comment by zubrRB** [comment]
После длительного веб-сёрфинга запустил приложение и подключил VPN, в процессе его получасового использования произошли разрыв и переподключение, затем закрыл браузер, который выгрузился мгновенно. Снова запустил Chrome, затем отключил в трее VPN, сразу после чего попытался закрыть браузер, но остались висеть 5 процессов в диспетчере.

**Comment by Aydinv13** [comment]
@zubrRB подскажите, на последней [версии](https://agrd.io/vpn_windows) проблема актуальна? Если да, то просьба записать [Debug](https://adguard-vpn.com/kb/adguard-vpn-for-windows/solving-problems/logs/) логи и отправить на devteam@adguard.com.

**Comment by zubrRB** [comment]
Проблема всё ещё повторяется, но после отключения приложение уже не функционирует и даже логи не экспортирует.

**Comment by zubrRB** [comment]
Не знаю, есть ли взаимосвязь, но ночью тестировал минут пятнадцать, то проблема не воспроизвелась, а утром на установленном приложении добавил несколько сайтов в исключения и эта проблема тут же снова воспроизвелась.

**Comment by zubrRB** [comment]
Повторилось сейчас на версии 2.1.9 даже без отключения, при переключении с Румынии на Германию. Логи отправил.

**Comment by Aydinv13** [comment]
@zubrRB извините за долгий апдейт, не могли бы вы записать трейсовые логи, если такое возможно? На данный момент нет прогресса в выявлении причины, а дебаг логов не достаточно.

**Comment by Aydinv13** [comment]
В таком случае задачу закрываю. Дайте знать, если снова столкнетесь с проблемой, пожалуйста.
