### ISSUE TITLE
VPN connection issue

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/AdGuardVPNForWindows#52]
@rubeng70 commented on [Thu Feb 11 2021](https://github.com/AdguardTeam/AdguardForWindows/issues/3690)

Since yesterday the AG VPN for Windows is not working when I try to access any website in any of the common web browsers (Google Chrome, Firefox, EDGE), the app show every available server to connect but when the connection is established appear the message "ERR_NAME_NOT_RESOLVED". Please help me to resolve this issue. Thanks in advance.

---

@adbuker commented on [Thu Feb 11 2021](https://github.com/AdguardTeam/AdguardForWindows/issues/3690#issuecomment-777697833)

@rubeng70 , what version of VPN do you use. Also, could you provide us with the detailed logs (you can send them to devteam@adguard.com)

---

@rubeng70 commented on [Thu Feb 11 2021](https://github.com/AdguardTeam/AdguardForWindows/issues/3690#issuecomment-777700150)

> @rubeng70 , what version of VPN do you use. Also, could you provide us with the detailed logs (you can send them to [devteam@adguard.com](mailto:devteam@adguard.com))

I use Adguard VPN Version 0.0.128.0

Also, I will send the logs to the email address you provide...

---

@rubeng70 commented on [Thu Feb 11 2021](https://github.com/AdguardTeam/AdguardForWindows/issues/3690#issuecomment-777707339)

> @rubeng70 , what version of VPN do you use. Also, could you provide us with the detailed logs (you can send them to [devteam@adguard.com](mailto:devteam@adguard.com))

Adguard VPN Version 0.0.128.0

Also, I will send the logs to the email address you provide...

---

@adbuker commented on [Thu Feb 11 2021](https://github.com/AdguardTeam/AdguardForWindows/issues/3690#issuecomment-777709058)

> > @rubeng70 , what version of VPN do you use. Also, could you provide us with the detailed logs (you can send them to [devteam@adguard.com](mailto:devteam@adguard.com))
> 
> Adguard VPN Version 0.0.128.0
> 
> Also, I will send the logs to the email address you provide...

Thanks a lot, we'll check it tomorrow

---

@rubeng70 commented on [Thu Feb 11 2021](https://github.com/AdguardTeam/AdguardForWindows/issues/3690#issuecomment-777709239)

[adg_logs_0.0.128.0_0211_1333.zip](https://github.com/AdguardTeam/AdguardForWindows/files/5967759/adg_logs_0.0.128.0_0211_1333.zip)

I tried to send this attach through my email program but exceed the limit of 4 mb in size and was rejeted...

**Comment by rubeng70** [comment]
I look forward hearing from you soon...

Thanks in advance...

**Comment by adbuker** [comment]
@rubeng70 , could you please update to the latest version and check whether the issue still exists

**Comment by adbuker** [comment]
Issue closed, please reopen it if issue come back
