### ISSUE TITLE
Conflicting information when checking and accessibility of a new version

### ISSUE THREAD

**Issue by zubrRB** [AdguardTeam/AdGuardVPNForWindows#527]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.1.4 (1013)

### Operating mode

VPN

### Environment

```markdown
- OS:Windows 7
```

### Issue Details

Steps to reproduce:
1. После выхода новой версии в разделе "О программе" нажать на кнопку "Проверить обновления".
2. После появления в окне программы информации о доступности новой версии нажать вверху "Обновить". 

### Expected Behavior

В окне программы и во всплывающем в системном трее уведомлении сообщается о доступности новой версии.
После нажатия на кнопку "Обновить" непосредственно происходит процесс обновления на новую версию программы. 

### Actual Behavior

В окне сообщается о доступности новой версии; во всплывающем уведомлении об использовании последней версии. 
После нажатия на кнопку "Обновить" не происходит обновление, а снова появляется кнопка "Проверить обновления".
Обновление на новую версию программы происходит лишь после повторного выполнения соответствующих действий.

### Screenshots

<details><summary>Screenshot 1:</summary>

![update](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/50718960/37ec1885-b6ec-4668-91bd-f30027130565)
</details>

**Comment by Aydinv13** [comment]
@zubrRB Здравствуйте!

Спасибо за обращение, исправится в последующих найтли версиях.
