### ISSUE TITLE
Message about the program stopping when exiting AdGuard VPN

### ISSUE THREAD

**Issue by zubrRB** [AdguardTeam/AdGuardVPNForWindows#528]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.1.4 (1013)

### Operating mode

VPN

### Environment

```markdown
- OS:Windows 7 Ultimate
```

### Issue Details

Steps to reproduce:
1. В меню команд системного трея выбрать "Выйти из AdGuard VPN".
2. Дождаться остановки службы и выгрузки в диспетчере задач процесса UI.

### Expected Behavior

Происходит штатный процесс выхода без сообщения о прекращении работы программы. 

### Actual Behavior

Появляется сообщение о прекращении работы программы из-за возникшей проблемы.

### Screenshots

![close](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/50718960/298d04b9-9ef6-482c-8282-da8c6c164ead)

**Comment by Aydinv13** [comment]
@zubrRB 

Стабильно происходит ошибка? Процессы программы в итоге завершаются? Пришлите дебаг логи, пожалуйста.

**Comment by zubrRB** [comment]
Да, после каждого выхода из приложения. Первой останавливается служба, затем выгружается UI и уже после вылазит.

**Comment by zubrRB** [comment]
Логи стандартные или расширенные?

**Comment by zubrRB** [comment]
@Aydinv13 отослал!

**Comment by Aydinv13** [comment]
Спасибо, посмотрим.

**Comment by northis** [comment]
@zubrRB Не получается воспроизвести, к сожалению. У вас все обновления стоят на Windows 7?
Как вариант, можете попробовать [этот билд](https://uploads.adguard.org/AdGuardVpn.2.2.1052.4.exe)

**Comment by zubrRB** [comment]
Ежемесячные наборы исправлений качества системы безопасности для Windows 7 плюс обновления безопасности и исправления для .NET Framework 3.5.1 и 4.8. Два месяца назад производил обновление с загрузочного диска для сброса разрешений и прав доступа до заводских значений, может, как-то повлияло, а чисто удалить (переустановить) штатной утилитой не могу из-за запрета запрошенного доступа к реестру.  Но с предсотавленным билдом пока что не вылазит.

**Comment by zubrRB** [comment]
Эта проблема снова проявилась у меня после обновления на версию (x64) 2.4.1475. Подробные логи, если надо, записал.

![sshot-2](https://github.com/user-attachments/assets/cc1d606a-42ac-4762-b294-5d5b4d4177be)
