### ISSUE TITLE
Adguard VPN freezes when navigating through the application itself

### ISSUE THREAD

**Issue by Radionucleid** [AdguardTeam/AdGuardVPNForWindows#529]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.1.4

### Operating mode

None

### Environment

```markdown
- OS:Windows 10 Pro 22H2 build 19045.3448
- Other network-level software: Windows Defender, Adguard 7.14
```

### Issue Details

Steps to reproduce:
1. After the first launch and acceptance of license agreements, Adguard VPN immediately freezes at the authorization stage in the application
2. After waiting about 5 minutes, when the program hangs, it is possible to complete authorization in the application.
3. Further navigation inside the application by tabs is also accompanied by the application hanging.

### Additional Information

*Logs were saved locally and deleted from public access*

**Comment by adbuker** [comment]
@Radionucleid , could you please send the memory [dump](https://adguard.com/kb/adguard-for-windows/solving-problems/dump-file/) for hung process to the devteam@adguard.com with the reference to the current GitHub task. Also could you please try to update to the latest 2.1.4 version and check whether the issue persist

**Comment by Radionucleid** [comment]
[adbuker](https://github.com/adbuker), I installed a new version, but still the same. Dumps sent.

**Comment by Batman2814** [comment]
It's also happening to me too. I have also sent logs to the email with details on what is happening. I hope it helps you guys fix the problem.

**Comment by adbuker** [comment]
@Radionucleid , @Batman2814 , thanks for the data you've sent, but I need to clarify some points:
1. Is the app frozen totally or just hangs for a couples (maybe more) of minutes?
2. could you please uninstall the app with advanced [uninstall tool](https://adguard.app/kb/adguard-for-windows/installation/#advanced), install the [new one build](https://uploads.adguard.org/AdGuardVpn-bug_AG-25920.exe), enable [trace logs]((https://adguard.app/kb/adguard-for-windows/solving-problems/adguard-logs/#trace-logs)), repro the issue (will be great, if you specify all the time-moments for each step you did) and send the logs to the devteam@adguard.com again
3. could you please grab dumps for both processes - adguard.exe and adgardsvc.exe once the hang occurs
4. could you please check whether the issue is reproducible with the 2.1.3?

**Comment by Batman2814** [comment]
1.) It's frozen totally by where I cannot click except for when clicking connect but then it just says "connecting" the whole time. I'm not able to exit AdGuard VPN at all. Stays open in the popup taskbar.

**Comment by zubrRB** [comment]
У меня то служба зависнет, из-за чего зависает на стадии подключения... Остановка через администрирование/службы приводит к тому, что становятся неактивными все опции запуска/перезапуска. Очухивается лишь после выхода из сна. 
Сегодня уже несколько раз зависал UI, в том числе непосредственно сейчас. Завершение процесса через Диспетчер задач приводит к тому, что оболочка уже полноценно не запускается. При этом продолжают работать служба и VPN.

**Comment by Radionucleid** [comment]
Removed Adguard VPN and Adguard using the uninstall tool in advanced mode.
Installed the version of AdGuardVpn-bug_AG-25920
The problem is the same - Adguard VPN freezes at the authorization stage in the application. I sent a dump with a hung process.

**Comment by adbuker** [comment]
@Radionucleid , unfortunately, didn't receive your second dump and logs. Could you please resend it

**Comment by Radionucleid** [comment]
I have updated the program to version 2.2.1031.0
The problem with the program interface hanging persists. I forwarded the dumps and logs again.

**Comment by adbuker** [comment]
@Radionucleid @zubrRB @Batman2814, could you please test [this build](https://uploads.adguard.org/AdGuardVpn-feature_AG-26060.exe). We've made a couple of fixes, which can fix the issue

**Comment by Radionucleid** [comment]
[adbuker](https://github.com/adbuker) I removed the previous versions and installed AdGuardVpn-feature_AG-26060. At the first launch, the authorization window was frozen again. Immediately deleted the program. Then I decided to put it again and from the second time it did not slow down at any of the stages. Further, when navigating through the windows, no braking was also noticed

**Comment by Batman2814** [comment]
Last time, when I downloaded the build directly from here for Adguard VPN for Windows, my Anti-virus security, Bitdefender, blocked a threat that said it was malware trying to steal my information.

**Comment by Radionucleid** [comment]
Something developers are quiet about this problem. I put this VPN on the second computer with W10, the result is the same.

**Comment by zubrRB** [comment]
@Radionucleid сразу над вами смотрите перебитые метки.

**Comment by Radionucleid** [comment]
Я к тому говорю, что про дампы и логи молчат, не спрашивают больше никакой информации, вобщем притихли.

**Comment by Refreezer** [comment]
@Radionucleid 
Hello, try this build, please
https://uploads.adguard.org/installer.exe

**Comment by Radionucleid** [comment]
> @Radionucleid Здравствуйте, попробуйте эту сборку, пожалуйста https://uploads.adguard.org/installer.exe

После того, нажал войти с помощью гугл всё зависло как всегда. Другие способы входа аналогично.

**Comment by Refreezer** [comment]
@Radionucleid, работаем над решением проблемы, попробуйте еще [вот этот билд](https://uploads.adguard.org/installer-2.exe)

**Comment by Refreezer** [comment]
> @Radionucleid, работаем над решением проблемы, попробуйте еще [вот этот билд](https://uploads.adguard.org/installer-2.exe)

@Radionucleid если у вас будет возможность, дайте пожалуйста обратную связь по последней сборке

**Comment by Radionucleid** [comment]
> > @Radionucleid, работаем над решением проблемы, попробуйте еще [вот этот билд](https://uploads.adguard.org/installer-2.exe)
> 
> @Radionucleid если у вас будет возможность, дайте пожалуйста обратную связь по последней сборке

К сожалению зависает как обычно сразу на этапе авторизации

**Comment by Radionucleid** [comment]
Обновил до версии 2.2.0 nightly 22(107) ничего не изменилось. Дамп высылаю на почту разработчика.

**Comment by Radionucleid** [comment]
Adguard VPN 2.2.0 nightly 25 (108)
зависает при навигации по меню, особенно часто зависает в меню настройка и главное меню. Дамп выслал.
