### ISSUE TITLE
Emails Blocked,  Ping / DNS routing issues. 

### ISSUE THREAD

**Issue by joetimmy** [AdguardTeam/AdGuardVPNForWindows#531]
### Issue Details

**Email Issue**

Steps to reproduce:
1. Open apple mail (with all privacy features disabled) 
2. Adguard VPN with default dns blocks emails from arriving to inbox. 
3. Disabling VPN allows emails in. 
Similar issue on IOS. 

No trouble shooting steps fix this.
Possible issue due to ipblacklisting for spam on adguard servers. 

**Ping / DNS issues** 

Im in downtown toronto, the toronto server has higher ping than montreal and chicago - this is clearly a problem ping to toronto from my locations should be improved. 

Investigating the ping issue i noticed that NYC DNS is being used for the toronto location instead of a Toronto DNS location, the adguard VPN dns is having routing issues using the wrong or poor locations. Please investigate the DNS routing and ping issues.**

IP (Adguard VPN Toronto) 
185.24.9.66
Provider
Datacamp Limited
DNS Server(s)
193.148.18.30 (us-nyc-dns-601)

**Comment by Aydinv13** [comment]
@joetimmy, hi and sorry for a late reply.

Could you re-check the behaviour with the latest release?

**Comment by Aydinv13** [comment]
Closed due to no answer.
