### ISSUE TITLE
Provide x64 version of AdGuard VPN for Windows

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardVPNForWindows#534]
### Issue Details

https://github.com/AdguardTeam/AdguardForWindows/issues/2831

**Comment by AlexandrPkhm** [comment]
Hi @rakleed 

We are currently already working on the x64 version of the AdGuard VPN as a part of [#2831](https://github.com/AdguardTeam/AdguardForWindows/issues/2831), and it should be released in the near future.
