### ISSUE TITLE
Very high ping

### ISSUE THREAD

**Issue by sultan150** [AdguardTeam/AdGuardVPNForWindows#538]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.1.5

### Operating mode

VPN

### Environment

```markdown
- OS: 10
- Other network-level software: Kaspersky & AdGuard
```

### Issue Details

Steps to reproduce:
1. the VPN app never had issues of a high ping now for neighboring countries
2. Now the neighboring countries have a high ping, sometimes 1.15 sec
3. I almost have no option for any country, all of them have high ping (most of the time)

### Actual Behavior

N/A

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/57029904/ccde3259-39bb-4f36-b9ce-2b87b6fff592)
![image](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/57029904/c296844a-e22f-4a0e-84b5-f24d8fd72f00)

</details>

### Additional Information

N/A

**Comment by Aydinv13** [comment]
@sultan150, hello!

Could you check the latest release?

**Comment by sultan150** [comment]
I updated to 2.1.6 and it looks good to me
