### ISSUE TITLE
Can't exit from the app while connecting via tray

### ISSUE THREAD

**Issue by AlexandrPkhm** [AdguardTeam/AdGuardVPNForWindows#539]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.1.5

### Operating mode

VPN

### Environment

```markdown
- OS: Windows 10
```

### Issue Details

Steps to reproduce:
1. Select endpoint and press Connect
2. Try to exit AdGuard VPN via tray while it still connects

### Expected Behavior

AdGuard VPN app is closed

### Actual Behavior

AdGuard VPN app is not closed

**Comment by zubrRB** [comment]
Опция не выделяетcя пока не произойдёт отключение VPN.
