### ISSUE TITLE
Unable to verify the publisher of the file `AdguardVpn.UI.resources.ru.dll`

### ISSUE THREAD

**Issue by TovRom** [AdguardTeam/AdGuardVPNForWindows#544]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.1

### Operating mode

None

### Environment

```markdown
- OS: Windows 11 22H2 
- Other network-level software: windows defender
```

### Issue Details

Steps to reproduce:
1. Не запускается Adguard Vpn
2. Не удается подтвердить издателя файла AdguardVpn.UI.resources.ru.dll (есть скриншот)

![a1](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/146085344/f7dbcef3-413e-490d-b293-17acd31effbc)
![a2](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/146085344/3fd0d3dc-c0f7-45b3-a26c-acbd36a20741)
![a3](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/146085344/18d31971-d5f3-4471-8680-3a5f09cbe19e)

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by adbuker** [comment]
@TovRom , as a quik solution - you can add `%programfiles(x86)%/adguardvpn` to the [windows defender's exclusions](https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26)
