### ISSUE TITLE
Dark theme for the installer (similar to AdGuard)

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/AdGuardVPNForWindows#550]
### Proposed solution

As we have the dark theme for the AdGuard's installer, it's time to share this ability to the AdGuard VPN installer too

**Comment by adbuker** [comment]
Also we have to take into the account problems found with the AdGuard's installer - https://github.com/AdguardTeam/AdguardForWindows/issues/4584

**Comment by rakleed** [comment]
@adbuker it's a duplicate of https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/488

**Comment by adbuker** [comment]
@rakleed , thanks, indeed
