### ISSUE TITLE
The icon in the tray with information about the update should stand out

### ISSUE THREAD

**Issue by antek821** [AdguardTeam/AdGuardVPNForWindows#551]
### Issue Details

At this point, it's hard to see the difference in the tray icon between connected status and update information. Now, at first glance, it's hard to see that there's an update to install

Icons now:
Update available:
![update](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/77172951/c4c884f3-f9ee-429a-8320-334bb10a58a3)
Connected:
![connected](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/77172951/a53cb77c-dbd6-4445-8090-238422264852)
Disconnected:
![disconnected](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/77172951/ed3b40ce-1775-42df-8cd4-b41592ae096e)

### Proposed solution

I think the update information/icon should somehow stand out from the connected and disconnected statuses, such as a different color (red? blue?).

**Comment by Aydinv13** [comment]
@antek821 Hello!

We'll see what we can do about it, thanks.
