### ISSUE TITLE
AdGuard Ad blocker filters update causes VPN to reconnect

### ISSUE THREAD

**Issue by githubuser013** [AdguardTeam/AdGuardVPNForWindows#552]
Hi,
   As the title says I use adguard for windows and adguard VPN the VPN disconnect and reconnect after every adguard for windows filter update, for security reasons is this normal behavior?  for the time of update is my IP leaking during the update? and if yes is there way to block the leaking?

Thanks

**Comment by Aydinv13** [comment]
@githubuser013 Hello!

To troubleshoot this issue, we need to get the app logs.
Here's what we need you to do:
1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/windows/solving-problems/adguard-logs).
2. Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file.
3. Send the archive to `devteam@adguard.com` and mention this issue number in the subject.

**Comment by githubuser013** [comment]
@Aydinv13 
The logs have been sent.

**Comment by mahara** [comment]
I think I'm having this issue as well. I just realized it's the filters update that cause this issue.

In my case, I have AdGuard filters saved locally in local drive.
Every time I modify any filter file locally, it triggers AdGuard VPN disconnection and reconnection issue.

The other thing is that AdGuard seems to randomly modify the local filter files even though there's no changes made in AdGuard Filter Editor. But this seems AdGuard issue. I have created a separate issue (https://github.com/AdguardTeam/AdguardForWindows/issues/4905).

**Comment by Aydinv13** [comment]
@mahara @githubuser013 
We have made some significant changes in the latest Nightly versions, so could you please check it out again? Ad blocker [Nightly](https://agrd.io/windows_nightly), AG VPN [Nightly](https://agrd.io/windows_vpn_nightly).

If you still have the same problem please collect the Trace logs and send them to us:
<details><summary>Instruction:</summary>

1. Go to VPN's Settings -> App settings -> Advanced settings -> Choose _Record everything_
2. Close AdGuard VPN via tray menu
3. Open Command line with Admin rights and run this command `C:\"Program Files (x86)"\AdGuardVpn\AdGuardVpn.exe /trace`. It will make the program open
4. Reproduce the problem and remember the exact time it happened 
5. Collect the logs via Support tab -> _Export logs and system info_ 
6. Send the resulting archive with the timestamp to devteam@adguard.com and specify the number of this issue.

</details>

**Comment by mahara** [comment]
@Aydinv13 I haven't tried any latest AdGuard VPN beta, but as suggested here (https://github.com/AdguardTeam/AdguardForWindows/issues/4905), I've tried the latest AdGuard beta (7.16.x) and I observe that any filter related actions don't seem to trigger VPN reconnection issue anymore so far. The VPN connection seems stable enough.

I'll just wait until both apps stable versions are released for now.

**Comment by githubuser013** [comment]
@Aydinv13 
I'm outside on vacation, can't confirm right now but as @mahara confirmation the issue is fixed.
If not i will update you guys later.
Thank you
