### ISSUE TITLE
Outbound proxy feature

### ISSUE THREAD

**Issue by Eollone** [AdguardTeam/AdGuardVPNForWindows#553]
### Issue Details

In some cases, some applications such as adguard vpn that connect to external networks need to go through a specified proxy address. And it is not possible to configured a global proxy in the system settings, as then other application won't be able to use.

### Proposed solution

Is it possible to include an outbound proxy feature to facilitate users in chained proxy scenarios?

**Comment by Aydinv13** [comment]
@Eollone Hi there!

Could you be more specific about the feature? In which cases and why should we use it?
>In some cases, some applications such as adguard vpn that connect to external networks need to go through a specified proxy address.

**Comment by Aydinv13** [comment]
@Eollone any news?

**Comment by Aydinv13** [comment]
The issue has been closed due to no reply. Can be reopened if relevant.

**Comment by supermagicianck** [comment]
> @Eollone any news?

Assume that a server of Adguard VPN is blocked or limited.(A usual scence in China,Iran or some company.)
Web traffic--->Adguard VPN Client--~~Great~~Firewall-->Adguard VPN Server

And I have my own proxy that can bypass the firewall. So I need a **dual-proxy** aka chain proxy.If AdguardVPN can set up an outbound proxy( just like [what Adguard did](https://adguard.com/kb/adguard-for-android/solving-problems/outbound-proxy/) ) it would be more easy to do so.

Web traffic--->Adguard VPN Client----**SOCKS5 or other proxy protocol**----->My Proxy Client--~~Great~~Firewall-->My Proxy Server--->Adguard VPN Server
