### ISSUE TITLE
Windows Updates downloads are being blocked by AdGuard VPN.

### ISSUE THREAD

**Issue by Anteecs** [AdguardTeam/AdGuardVPNForWindows#554]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.2.0 nightly 25 (108)

### Operating mode

VPN

### Environment

```markdown
- OS: Windows 11 22H2 build 23565
- Other network-level software: Windows Defender
```

### Issue Details

Steps to reproduce:
1. Open VPN app, connect to any server.
2. Go to Windows Updates, click on Check for Updates and when any update is available click on Download
3. The download immediately disappears, and you won't be able to download and install an update unless AdGuard VPN is disconnected from any server.

### Expected Behavior

You should be able to download and install updates in your Windows Updates whether you're connected to the VPN or not.

### Actual Behavior

Download of an updates gets interrupted when you're connected to AdGuard VPN server.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by northis** [comment]
@Anteecs We can't reproduce the problem, updates are downloaded via VPN as normal. You may be talking about a special "insider version" type update. Microsoft may roll out these updates gradually, and your current IP address may not yet qualify.
Are you experiencing similar problems now?

**Comment by realkot** [comment]
> @Anteecs We can't reproduce the problem, updates are downloaded via VPN as normal. You may be talking about a special "insider version" type update. Microsoft may roll out these updates gradually, and your current IP address may not yet qualify. Are you experiencing similar problems now?

What version? Last year I cant receive MS updates.
На какой версии вы проверяли? Минимум год с вашим ВПН обновления не приходят. Подключаю другой ВПН (локация Нидерланды, что у вас, что в другом) - сразу все обновления находятся.

**Comment by northis** [comment]
@realkot Речь про последние nightly версии. Можете проверить на ней. Речь идёт об обычных обновлениях или Insider Preview? Без VPN обновления, как я понимаю, тоже не находятся?

**Comment by northis** [comment]
@realkot  Пока закрываю, если будет повторяться на последних nightly версиях - можете переоткрыть, прислав подробные логи и время, в которое воспроизвелось.

**Comment by realkot** [comment]
Просьба переоткрыть. Воспроизводится. 
Версия 2.2.0 nightly 40 (1177). Время московское, примерно 21:10-21:15.

[adg_logs_2.2.1177.0_1209_2118.zip](https://github.com/AdguardTeam/AdGuardVPNForWindows/files/13625296/adg_logs_2.2.1177.0_1209_2118.zip)

**Comment by realkot** [comment]
@northis откройте тикет пжлста

**Comment by Aydinv13** [comment]
@realkot не могли бы вы прислать подробные логи, так как последние присланные - обычные. Спасибо!
<details ><summary>Подробная инструкция:</summary>

Соберите и отправьте указанные файлы, используя данную инструкцию:
1. Зайдите в Настройки --> Основные --> Расширенные настройки --> Уровень логирования --> **Записывать все**;
2. Воспроизведите проблему и запомните точное время её воспроизведения. Оно понадобится нам, чтобы найти соответствующие записи в лог-файле;
3. Зайдите в Настройки --> Основные --> Выберите **Экспортировать логи**;
4. Отправьте полученный архив по адресу `devteam@adguard.com`. Также укажите номер задачи в Github и время воспроизведения проблемы.
5. Не забудьте вернуть значение уровня логирования на **Записывать по умолчанию**.
 </details>

**Comment by Aydinv13** [comment]
@realkot нет ли новостей по сбору логов?

**Comment by northis** [comment]
`Версия 2.2.0 nightly 40 (1177). Время московское, примерно 21:10-21:15.`

В это время VPN был подключён менее минуты (21:12:34-21:13:12), сам факт смены сети мог повлиять на обновления Windows.

**Comment by realkot** [comment]
@Aydinv13, добрый день! Сорри за задержку с ответом, информацию направил на почту.

П.С. Мне не критично, но в инструкции у вас пункты некорректно указаны. Для "слабых" пользователей это может стать "проблемой".

**Comment by northis** [comment]
@realkot спасибо за логи, но есть пробема - воспроизвелось в 10:22, а логи заканчиваются в 10:18. Такое бывает, программа не сразу скидывает логи на диск из памяти для улучшения производительности. Можете перезапустить программу, чтобы логи точно скинулись на в файл, и ещё раз выслать архив?
