### ISSUE TITLE
Locations sorting

### ISSUE THREAD

**Issue by TheSatelliteSP** [AdguardTeam/AdGuardVPNForWindows#556]
### Issue Details

Free users are often forced to scroll the location list to find free location

### Proposed solution

Don't occupy three slots in the "Fastest Location" list with premium ones and fill it with fastest free locations if user does not have premium

### Alternative solution

Or insert free locations before premium in the "All Locations" list below "Fastest Locations" if user does not have premium

**Comment by Aydinv13** [comment]
@TheSatelliteSP Hello!

Locations are placed in this section based on their ping, so when the ping of a location is low, it goes there.

<details>
<summary> Screenshot </summary>
<img width="797" alt="fastest locations" src="https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/73467237/3ffbbc88-2311-44e1-93d5-d1b0808c9c22">

</details>
