### ISSUE TITLE
Crash after enabling Wintun driver

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardVPNForWindows#564]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.2.0 n28 (111)

### Operating mode

VPN

### Environment

```markdown
- OS: Windows 10 x64
- Other network-level software: not running
```

### Issue Details

Steps to reproduce:
1. Enable Wintun
2. Wait few seconds

### Actual Behavior

Crash/unsuccessful recovering

<details>
<summary>Details</summary>

![image](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/8361299/83c98100-9627-40b1-bc2d-de3ae14fcde0)

</details>

Logs in `VPN_2.2.0n28_#564.zip` in the windows chat.

---

In my case caused by routes of `VMware Virtual Ethernet Adapter for VMnet8` adapter. Works fine when it is temporary turned off.

**Comment by awdrifter** [comment]
this is not resovled. I still have this issue.

**Comment by adbuker** [comment]
@awdrifter, what AdGuard version do you use? if it is not the latest nightly version, please try to repro this issue with it. Also please grab and send the "trace" logs (instruction for AdG similar the AdG VPN[here](https://kb.adguard.com/windows/solving-problems/adguard-logs)) to the devteam@adguard.com with the issue number in the letter's label. Please specify "timestamp" when the problem occurred

**Comment by awdrifter** [comment]
> @awdrifter, what AdGuard version do you use? if it is not the latest nightly version, please try to repro this issue with it. Also please grab and send the "trace" logs (instruction for AdG similar the AdG VPN [here](https://kb.adguard.com/windows/solving-problems/adguard-logs)) to the [devteam@adguard.com](mailto:devteam@adguard.com) with the issue number in the letter's label. Please specify "timestamp" when the problem occurred

I'm using the Windows app AdGuard VPN 2.2.4. I don't see the Logging Level - Debug or the Export Logs options. Can you update the screenshot in the guide? Thanks.

Whenever I turn on the Wintun option, it just give me the "Unknown error" with the ninja ¯\_(ツ)_/¯.
