### ISSUE TITLE
 Error in operation

### ISSUE THREAD

**Issue by Skywawe** [AdguardTeam/AdGuardVPNForWindows#567]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

latest version

### Operating mode

VPN

### Environment

```markdown
- OS: Windows 10 21H2
- Other network-level software: AdGuard
```

### Issue Details

Steps to reproduce:
when I set the application mode to work with sites / applications that I have to enter, the vpn seems to turn off, but when I set it to work in all applications / sites, it starts working, how to fix it?
P.S. I use Google translator there may be errors

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by AlexandrPkhm** [comment]
Hi @Skywawe 
 
We believe you are experiencing a problem with Selective mode. Please note that if you are using selective mode for websites or applications, you must add the required websites or applications to the Selective list by pressing `+ Add website' or `+ Add application'.

Let us know if the issue persists after adding sites or applications to the list.

**Comment by AlexandrPkhm** [comment]
@Skywawe 

Could you please let us know if you have been able to try our suggestions and if they have been effective.

**Comment by AlexandrPkhm** [comment]
Hi @Skywawe 

We will close this issue. However, if you encounter this issue again, please reopen it and we will continue our investigation.
