### ISSUE TITLE
Exclusion URL strings

### ISSUE THREAD

**Issue by Smithienious** [AdguardTeam/AdGuardVPNForWindows#57]
### Issue Details

- **AdGuard VPN version:**
  - 0.0.138.0
- **VPN mode:**
  - Local VPN
- **Operating system and version:**
  - Windows 10 19042.844
- **Other network-level software:**
  - AdGuard, cFosSpeed

### Expected Behavior

IP addresses or strings with more than 3 characters of set `*` and `.` should work
~~~
192.168.1.1
192.168.*
aaa.bbb.ccc.ddd.com
*.ccc.ddd.com
*.hcmut.edu.vn
~~~

### Actual Behavior

`The domain name is not valid`

### Additional Information

The strings work as expected in the Chrome extension

**Comment by Smithienious** [comment]
This is still a problem on 0.0.138.0

**Comment by Aydinv13** [comment]
@Smithienious There is CIDR notation in Exclusions, we don't support wildcard. It's not a problem on the desktop version it's different from extension by its validation system. We'll work on it later
