### ISSUE TITLE
App won't open

### ISSUE THREAD

**Issue by osaka1234** [AdguardTeam/AdGuardVPNForWindows#580]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

latest

### Operating mode

VPN

### Environment

```markdown
- OS: Windows 10, 22H2, build 19045.3693
- Other network-level software: Windows Defender
```

### Issue Details

It only shows up in background processes in task manager but won't open even after uninstalling and reinstalling

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by mitheshge** [comment]
I have the same issue with absolutely no reply from their end. its been 3-4 days. Their website says to contact "support@adguard-vpn.com" but i just googled this issue and their github page opened. Adguard support is the worst. Had to create a github account just to tell ADGUARD that there is an ISSUE/bug.
The above details mentioned by [osaka1234] are correct.

I installed Adguard VPN in Windows 10 and a desktop shortcut is created. Double Clicking on the shortcut doesn't open anything. But the task manager says that Adguard VPN is working. But no other window is open. 
1. I have tried Uninstalling, using the uninstall utility from the support pages, and restarting the laptop AND reinstalling it. It didn't work.
2. I have used the desktop shortcut, the start menu shortcut, and via program files, all actions lead to the same action. It shows as though it loads, but the main adguard app doesn't open.

**Comment by KolbasovAnton** [comment]
@mitheshge Hello! Please, answer this questions for better understanding:
1. Which version of AG VPN do You trying to use?
2. Did I get You right - there's only one background process running in task manager? Is it "release" process or "service" process (You can just send a screenshot)?
3. No signs of AF VPN in system tray?

**Comment by mitheshge** [comment]
1.  Version - 2.1.1046.0
2 & 3.  Please check attached screenshot. 
![drjTHpQEUo](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/152974466/aec6a402-29a7-4a15-ae82-90b4f55a34c2)

Nope. No sign of AG VPN in system tray. double clicking just starts the service..

**Comment by mitheshge** [comment]
Yes. The problem still exists. Uninstalled via the utility, restarted and then installed the beta 2.2 beta 2. 
Exactly same as the above gif..

**Comment by mitheshge** [comment]
Hi,

Please check the attached logs.

Regards.

**Comment by KolbasovAnton** [comment]
@mitheshge @osaka1234 Please, try this manipulations:

1. Uninstall AG VPN with our [special tool](https://adguard.info/kb/adguard-for-windows/installation/#advanced) (choose **Advanced Uninstall** and **Delete AdGuard VPN**, restart your PC after uninstallation).
2. After the restart, install [latest version of AG VPN](https://github.com/AdguardTeam/AdGuardVPNForWindows/releases/tag/v2.2.0-beta-2).
3. Send the [installation logs](https://adguard.info/kb/adguard-for-windows/solving-problems/installation-logs/).
4. Send the [trace logs](https://adguard.info/kb/adguard-for-windows/solving-problems/adguard-logs/#trace-logs). Even if program didn't run, You still can find logs in C:/ProgramData/AdguardVpn/Logs.

Remember the exact time when the issue was reproduced and write it in the letter. Send the archive to devteam@adguard.com and mention this issue number in the subject.

**Comment by mitheshge** [comment]
I have sent the Installation and Trace Logs to ***@***.*** Please
check attached. I have sent them here too..

**Comment by mitheshge** [comment]
Fortunately or unfortunately, my system crashed yesterday and was
unbootable and was stuck on automatic startup repair(not related to the
current adguard issue).
So, I had to reset my system and installed adguard in my newly formatted
system and it worked fine. Just after installation, it directly took me to
the login screen. As of now, it is working fine.
I think you have to follow it up with @osaka1234
<https://github.com/osaka1234> going forward.

If  @osaka1234 <https://github.com/osaka1234> is not available, and if you
still require my contribution in this, please let me know. Although I doubt
it is pointless to ask me as the issue cannot be reproduced, I am glad to
help in any way.

**Comment by KolbasovAnton** [comment]
@mitheshge Glad to hear that! Thank You for assistance. If something will go wrong, let us know.

@osaka1234 So, it seems, that its some sort of system's conflict in common, that not depends on our VPN application. Try to reinstall your OS, if its unacceptable for You but problem is still actual, please, send us trace logs, following the instruction I wrote [here](https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/580#issuecomment-1845135955).
