### ISSUE TITLE
Old directories are not deleted from AppData directory

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardVPNForWindows#581]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.1...2.2

### Operating mode

VPN

### Environment

```markdown
- OS: Windows 10 x64
- Other network-level software: no
```

### Issue Details

Steps to reproduce:
1. Install old version and update the app few times

### Expected Behavior

Old directories must be removed.

### Actual Behavior

Old directories are not deleted from `%UserProfile%\AppData\Local\Adguard_Software_Limited\AdGuardVpn.exe_StrongName_***`

<details>
<summary>Details</summary>

![image](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/8361299/2ce76f12-3da2-47f0-993b-d9ef3262f58f)

</details>

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by zubrRB** [comment]
`AppData\Local\Adguard_Software_Limited` — очищается.
`AppData\Roaming\Adguard Software Limited` — не очищает.

![old](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/50718960/c05ef2e2-62f6-4904-a80d-333fe6facf90)
