### ISSUE TITLE
VPN On Router! HOW!!

### ISSUE THREAD

**Issue by WiReLaD** [AdguardTeam/AdGuardVPNForWindows#582]
### Issue Details

Support says to go to my router and enable VPN and add all the settings created in option 3. Option 3 being as created on AdGuard VPN/ devices page/Add Router.
I've done this and got a load of figures and username & Password etc. 
Where do I put this info???
Do I create VPN connection within Windows settings and if so... what values go in which boxes? Eg, Server name & address? where do I get that from? Is it the IP address or Remote server ID
Any help be much appreciated
Thanks Mike

**Comment by Aydinv13** [comment]
@WiReLaD Hi there!

Unfortunately, this is not the right repository in which such kind of issues are discussed. Setup instructions can be found [here](https://adguard-vpn.com/en/router/overview.html). For further questions please contact support@adguard-vpn.com.
The current issue will be closed.
