### ISSUE TITLE
Conflicts with cFosSpeed

### ISSUE THREAD

**Issue by Smithienious** [AdguardTeam/AdGuardVPNForWindows#59]
### Issue Details

Internet is slow when `cFosSpeed for faster Internet connections (NDIS 6)` is enabled.
Using `ping` in the command prompt works.

- **AdGuard VPN version:**
  - 0.0.138.0
- **VPN mode:**
  - Local VPN
- **Operating system and version:**
  - Windows 10 19042.844
- **Other network-level software:**
  - AdGuard, cFosSpeed

### Expected Behavior

Adguard VPN wraps all traffic thus does not conflict with cFosSpeed

### Actual Behavior

Internet is very slow, usually stalls

### Steps to reproduce

1. Install cFosSpeed
2. Restart Windows. The stall might take several minutes to happen.

### Screenshots

<details><summary>Screenshot:</summary>

![Screenshot (2)](https://user-images.githubusercontent.com/10150902/109376530-aa0a7780-78f7-11eb-9ee5-3b8104822734.png)

</details>

### Additional Information

Can also be reproduced by

1. Disable `cFosSpeed for faster Internet connections (NDIS 6)` in the network adapter's properties
(Optional) Restart Windows
2. Browse a site to confirm working internet
3. Enable cFosSpeed

**Comment by Smithienious** [comment]
Is there any update on this? Or this is out of AVPN's scope?

**Comment by Aydinv13** [comment]
@Smithienious no update yet. We are working on it at the moment. Sorry for a big delay

**Comment by Aydinv13** [comment]
@Smithienious can you please check behaviour now? But before doing this follow these steps:
1) Turn off cFosSpeed (uncheck in Ethernet properties)
2) Install the latest AdGuard VPN nightly build
3) Go to AdGuard VPN's  Settings-> General and turn off "Auto-connect on app launch"
4) Reboot your computer
5) Open AdGuard VPN then go to Settings-> General-> Advanced settings-> Tunneling exclusions and add cFosSpeed to apps exclusions (normally it's C:\Program Files\cFosSpeed\spd.exe and C:\Program Files\cFosSpeed\cfosspeed.exe)
6) Connect to any VPN server and make sure it works properly
7) Turn on cFosSpeed (checkbox in Ethernet properties)
8) Try surfing the browser
As a result, you shouldn't face any troubles with the internet connection. Don't forget to turn on "Auto-connect on app launch" if needed

**Comment by Smithienious** [comment]
@Aydinv13 It is working as expected on 1.0.290.0
