### ISSUE TITLE
VPN Selective mode does not work in Twitch

### ISSUE THREAD

**Issue by DexfromAntarctica** [AdguardTeam/AdGuardVPNForWindows#590]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.1.10 (latest)

### Operating mode

VPN

### Environment

```markdown
- OS: Windows 10, 22H2, build 19045.3693
- Other network-level software:Just Adguard and Adguard VPN
```

### Issue Details

Steps to reproduce:
0. buy 5600x and Radeon 6600 PC
1. Add Twitch and AWS's Link at Selective mode
2. Run at chrome 
3. Not working!

### Expected Behavior

only Twitich works vpn 

### Actual Behavior

Not working
I have 3 machines, one is MS Surface GO3, one is SAMSUNG S23 Ultra, last this.
3 use same internet BUT only doesn't working at this PC.
This feature is not available at Twitch, chrome browser. Is just problem of AMD system? Please fix it.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by KolbasovAnton** [comment]
@DexfromAntarctica Hello, try our fresh [pre-prelease version of VPN](https://github.com/AdguardTeam/AdGuardVPNForWindows/releases/tag/v2.2.0-rc), maybe it will fix Your problem.

**Comment by KolbasovAnton** [comment]
@DexfromAntarctica new [release version](https://github.com/AdguardTeam/AdGuardVPNForWindows/releases/tag/v2.2.0) is also ready. Is Your problem still actual?

**Comment by DexfromAntarctica** [comment]
@KolbasovAnton using pre-release version and problem is solved 👍 Thx for your answer
