### ISSUE TITLE
Reworked account requirements and enhance security of users.

### ISSUE THREAD

**Issue by DotaFSS** [AdguardTeam/AdGuardVPNForWindows#594]
### Issue Details

Adguard team still require email address for accounts. This is not safety and serious threat for anonymity.

### Proposed solution

Adguard team should to stop require email address for creating accounts and for already existing accounts. 
And for already existing accounts  give opportunity for removing e mail address.

**Comment by zubrRB** [comment]
Адрес электронный почты донора также требуется для активации VPN на устройствах других пользователей, что в результате приводило к попыткам взлома личного кабинета донора, массовому спаму о таких попытках на почтовый ящик, его полному удалению, отказу от купленной лицензии и использования приложения.

**Comment by KolbasovAnton** [comment]
@DotaFSS @zubrRB Greetings! Which way of authorization would suit you?

**Comment by DotaFSS** [comment]
> @DotaFSS @zubrRB Greetings! Which way of authorization would suit you?
Hi!
Generate random id for each account and require password more then 18 charaters includes a combination of symbols, numbers, and upper- and lowercase letters or other ascii, etc. And TOTP as 2fa and whith out TOTP user must have no possibility for create accounts.

Only id+password+TOTP=Account.
After this user can generate random codes for others devices in created account.

**Comment by KolbasovAnton** [comment]
Thank You, we'll keep this idea in mind! But we do not envisage reworking the authorization process in the near future.
