### ISSUE TITLE
AdguardVPN v2.2 & cForSpeed conflict

### ISSUE THREAD

**Issue by askold2** [AdguardTeam/AdGuardVPNForWindows#595]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.2.0 (1162)

### Operating mode

VPN

### Environment

```markdown
- OS: Windows 10
- Other network-level software: cFosSpeed (https://www.cfos.de/en/download/download.htm)
```

### Issue Details

Steps to reproduce:
1. Install cFosSpeed (I have licensed version ealier)
2. Install AdguardVPN v2.2 (or update from v2.1, where no problem)
3. Connect to VPN server

### Expected Behavior

угадайте

### Actual Behavior

Вообще ничего не работает, невозможны никакие соединения ни в каком броузере (проверял firefox и edge). Выйти из AdguardVPN не помогает, при этом в диспетчере задач остаются процессы AdguardVPN. Их прибитие вручную, а также остановка сервиса не помогает тоже. Только перезагрузка.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

Угадал, что проблема в конфликте с cFosSpeed, поскольку это единственное сетевое отличие от другого компьютера, а там такой проблемы нет. Есть другая (см. Issue #509). А на этом компьютере я nightly не ставил, обновился сразу на релиз 2.2 с таким вот результатом. При отключении cFosSpeed эта проблема исчезает. А про следующую, я напишу отдельно.

**Comment by KolbasovAnton** [comment]
@askold2 Hello! Unfortunately, I can't reproduce Your bug, everything works fine on my Win 10 & 11. So, we'll need logs from You, but first, try this:

1. Install latest nightly version.
2. Or install AG VPN ver. 2.2 "from scratch".
3. Reset AG VPN settings to default.

Также, что конкретно Вы имеете в виду под "вообще ничего не работает"? ВПН подключается к локации, но нет сети, сайты в браузерах недоступны?

**Comment by askold2** [comment]
Похоже, что дело не в cForSpeed, поскольку после удаления AG VPN вместе с настройками и установки заново он не работает уже и при отключенном cForSpeed. Не знаю тогда в чем разница с моим рабочим компьютером, где такого нет, может в провайдере. Где не работает - Ростелеком.  Отправил на devteam@adguard.com 2 лога - из nightly версии и из релиза. После чистой установки я только отключал Kill Switch и автоматическую загрузку и автоматическое подключение. Симптомы одинаковые. После перезагрузки сеть работает нормально, после запуска AG VPN тоже, но стоит подключиться к VPN серверу, как всякая связь пропадает. При отключении от VPN связь не восстанавливается. Повторно ни к тому же, ни к другому серверу не подключается. Если выйти из AG VPN, окошко программы закрывается, но в диспетчере задач остаются висеть 2 процесса - adguardvpn.exe и adguardvpnsvc.exe. Повторно AG VPN не запускается. Если прибить adguardvpn.exe в диспетчере задач, то запускается и висит на заставке с подпрыгивающей маской. Если попытаться перезапустить службу, то висит на остановке. В общем, восстановить работоспособность сети удается только после перезагрузки.

**Comment by KolbasovAnton** [comment]
@askold2 Недавно вышла [новая найтли](https://static.adtidy.net/windows/nightly/installer-2.2.1188.0.exe), попробуйте установить её с нуля.

**Comment by askold2** [comment]
Установил. Всё вернулось в состояние на момент создания запроса. При запущеном cForSpeed не работает вообще. Т.е. при соединении с сервером всякая связь пропадает и больше не восстанавливается. Без cForSpeed не работает в режиме по-умолчанию, вероятно, поэтому  в прошлый раз я и написал, что уже и без cForSpeed не работает. НО если включить QUIC, то начинает работать с багами, описанными в issue #596.

**Comment by KolbasovAnton** [comment]
@askold2 Здравствуйте! По всей видимости, нам потребуются трейсовые логи, записанные на [последней найтли](https://static.adtidy.net/windows/nightly/installer-2.2.1188.0.exe). Пожалуйста, попробуйте воспроизвести баги и в письме обязательно укажите время всех этих манипуляций. Как записать трейсовые логи:

1. Завершаем все AG VPN процессы.
2. Запускаем консоль (печатаем cmd в стартовой панели Виндоус).
3. Скорее всего, изначальная строка будет выглядеть как C:\Users\ваше имя пользователя. Меняем директорию, набрав C:\Program Files (x86)\AdGuardVpn и нажав Enter. Если Вы устанавливали программу в другое место, соответственно, вбиваем этот путь.
4. Теперь активная строка имеет вид C:\Program Files (x86)\AdGuardVpn, просто печатаем AdGuardVpn.exe /trace и нажимаем Enter.
5. Запускается VPN, трейсовые логи пишутся. После воспроизведения всех багов, идём в C:\ProgramData\AdguardVpn\Logs. Сохраните все логи в один архив и отправьте нам на devteam@adguard.com, указав в качестве заголовка номер Вашей задачи (595). Пожалуйста, не забудьте подписать время воспроизведения бага.

**Comment by askold2** [comment]
Отправил

**Comment by KolbasovAnton** [comment]
@askold2 Добрый день! Подскажите, пожалуйста, актуальна ли всё ещё ваша проблема на последних версиях приложения? Например, в этой - https://github.com/AdguardTeam/AdGuardVPNForWindows/releases/tag/v2.2.4.

**Comment by askold2** [comment]
Возвращаться к 2.2.4 для проверки в лом, а более последняя 2.3.0n16 (1311) на данный момент не работает на этом компе вообще, ни без cForSpeed, ни с включенной ни с выключенной QUIC. Не знаю связано это с обновлением версии или с увеличением злобности провайдера. Всё висит в состоянии "Проверка..." серверов. На другом компе та же версия работает, по-прежнему с багом из Issue #509, но там провайдер другой.

**Comment by KolbasovAnton** [comment]
@askold2 Спасибо за ответ! А запишите, пожалуйста debug-логи на последней найтли и мы разберёмся уже с этим.

**Comment by KolbasovAnton** [comment]
@askold2 Спасибо, смотрим.

**Comment by Refreezer** [comment]
@askold2 пожалуйста проверьте на последней найтли, если проблема повторяется, просьба прислать логи

**Comment by askold2** [comment]
Логи отправил. Ничего существенного не изменилось, разве что теперь висело в состоянии "Сеть потеряна...". В этом состоянии из него по крайней мере можно нормально выйти. А если включить QUIC, то при выходе служба не останавливается и если ее прибить, то нормально уже не перезапускается.

**Comment by askold2** [comment]
Всё заработало, в том числе с cForSpeed и без ipv6 . Спасибо!
