### ISSUE TITLE
No connections with "not VPN" sites In selective mode

### ISSUE THREAD

**Issue by askold2** [AdguardTeam/AdGuardVPNForWindows#596]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.2.0 (1162)

### Operating mode

VPN

### Environment

```markdown
- OS:Windows 10
- Other network-level software:
```

### Issue Details

Steps to reproduce:
1. Внесите сайт в список исключений 
2. подключитесь к VPN
3. 

### Expected Behavior

Связь с сайтами из списка идет напрямую, а с остальными через VPN

### Actual Behavior

Связь только через VPN, сайты их списка исключений недоступны. В альтернативном случае, если выбран режим VPN только для сайтов из списка, доступны сайты из списка, остальные недоступны.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

Опция kill switch выключена.
В v.2.1 были проблемы иногда см. (issue #509), в v2.2 выборочный режим нормально не работает вообще, по крайней мере на этом компьютере. На другом у меня nightly версии и там я такого не замечал, не уверен как соотносятся nightly с релизом.

**Comment by askold2** [comment]
I think you should combine this issue and #595. The causes of the problems in them are obviously common. And I'm already tired of sending you logs from different versions and to different issues without any result. Why don't you look at the one I sent for issue #595 first?

**Comment by Refreezer** [comment]
Здравствуйте, @askold2! Мы обнаружили некорректное поведение на текущей найтли при отключенном ipv6, благодаря предоставленным вами логам по теме #595.

Мы уже внесли исправление, которое скорее всего будет в следующем обновлении, однако, к сожалению, логи, которые вы предоставили, не отражают описанную вами проблему, так как в основном содержат информацию о другой ошибке (описанной выше), которая не связана с проблемой VPN-соединения, что не позволяет установить причину, т.к. проблема не воспроизводится.

Если у вас есть возможность включить ipv6, отключить cForSpeed и предоставить логи с актуальной версии, они помогут нам более точно изучить проблему, описанную в этой теме, и внести соответствующие исправления (если в такой конфигруации ваша проблема повторится).

**Comment by askold2** [comment]
ipv6 не поддерживается провайдером и была отключена за бесполезностью. Ньюанс, однако, в том, что на другом компьютере, где всё работает, и где вы недавно исправили ошибку #509, ipv6 тоже отключена и никаких проблем это не вызывало. На этом же компьютере на данный момент AdGuard VPN не работает вообще, ни с включенным ipv6, ни с выключенным, но по-разному. Поведение с выключенным описано в #595, а с включенным у меня сейчас даже с сервером соединилось, только никакой связи с сайтами не было. Подожду, пожалуй, следующей найтли с вашим исправлением и если и она не заработает, буду делать новые логи.

**Comment by askold2** [comment]
Всё заработало и с cForSpeed и без ipv6 и селективный режим тоже. Спасибо!

**Comment by floydback** [comment]
Багу уже год. Включаешь выборочный режим для приложений и для сайтов - не включается VPN когда должно. Включаешь режим везде и добавляешь исключения и VPN включается там, где не надо. Воспроизвести проблему легко по описанию, логи уже предоставляли, как я вижу. Толку нет
