### ISSUE TITLE
AdGuard VPN for Windows is detected as Malware from Bitdefender Total Security

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardVPNForWindows#597]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.2.0

### Operating mode

VPN

### Environment

```markdown
- OS: Windows 11 23H2
- Other network-level software: Bitdefender Total Security
```

### Issue Details

Steps to reproduce:
1.
2.
3.

### Screenshots

![20231217_12524966_Edited](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/96619913/dd1461fd-87b8-424f-89eb-ed277d22cedf)
![20231217_12574635_Edited](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/96619913/2df73620-f557-494f-add8-4273ba1b9082)

### Additional Information

Show its Malware for all three releases of Stable, beta, and Nightly.

**Comment by Aydinv13** [comment]
@Batman2814 Hi there.

False positive report was sent to https://www.bitdefender.com/consumer/support/answer/29358/.
