### ISSUE TITLE
Exclusions tab loads very slowly when there's no internet connection

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardVPNForWindows#61]
Steps to reproduce:

1. Close AdGuard VPN
2. Change system DNS settings to some non-existing DNS server (i.e. 1.2.3.4)
3. It will be loading VERY slowly (which is expected - there's no internet connection)
4. Try to switch to Exclusions tab

Expected: quickly open Exclusions
Actual result: it takes a minute to open it

**Comment by Aydinv13** [comment]
The issue doesn't persist anymore
