### ISSUE TITLE
No Internet with WinTUN

### ISSUE THREAD

**Issue by RainmakerRaw** [AdguardTeam/AdGuardVPNForWindows#612]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.2.1 (1233)

### Operating mode

VPN

### Environment

```markdown
- OS: Windows 11, 23H2, build 22631.3007
- Other network-level software: HyperV virtual switch (if that counts)
```

### Issue Details

Steps to reproduce:
1. Install AdGuard VPN using the binary from the website.
2. Enable WinTUN (no other tweaks).
3. Connect to a server.
4. No Internet. 
5. App occasionaly says network not found, or else crashes (unhandled exception).
6. Disable WinTUN, reconnect. Internet now works again. 

### Expected Behavior

The Internet should be accessible via the VPN as in the 'regular' mode.

### Actual Behavior

No Internet. The Windows connection icon turns to a globe, all apps say offline. The WinTUN adapter properties shows a `172.` local IP address and a DNS server, but no default gateway (not sure if expected behaviour or not). I have tried with QUIC enabled and disabled, with custom DoT for DNS, and a complete removal (Geek Uninstaller) of the app and a reboot, then a reinstall. Same issue.

### Additional Information

[adg_logs_2.2.1233.0_0122_0446.zip](https://github.com/AdguardTeam/AdGuardVPNForWindows/files/14005324/adg_logs_2.2.1233.0_0122_0446.zip)

**Comment by KolbasovAnton** [comment]
@RainmakerRaw Greetings! Please, try one of this actions:

 - Choose another DNS server: Settings -> App Settings -> DNS Servers.
 - Switch off HyperV virtual switch, that You've mentioned.
 - Or simply download and install the latest [nightly version](https://static.adtidy.net/windows/nightly/installer-2.2.1237.0.exe) of AG VPN.

Please, let me know, if any of these helps. Also, at what time approximately the error occurs? We must know it to search the logs You sent.
