### ISSUE TITLE
Nameserver issues with WSL2

### ISSUE THREAD

**Issue by Smithienious** [AdguardTeam/AdGuardVPNForWindows#62]
### Issue Details

- **AdGuard VPN version:**
  - 0.0.143.0
- **VPN mode:**
  - Local VPN
- **Operating system and version:**
  - Windows 10 19043.844
- **Other network-level software:**
  - AdGuard 7.6 nightly 21

### Important

1. Looking up `no internet on wsl2 while on vpn` do show a lot of similar problems. I also found an upstream thread https://github.com/microsoft/WSL/issues/4275. I have not looked into any of these yet, but if this looks like an upstream problem, I will close this issue.
2. Windows must be freshly booted up, like restarted but not fresh install.
3. `ping`ing using an IP address always works.
4. I have only tested on Debian based distros

### Behaviors

Basically WSL cannot contact a nameserver if VPN has _never_ been dropped after WSL has _ever_ been started.

<details><summary>If VPN is never disconnected</summary>

0. Freshly booted Windows.

1. Connect to VPN.

2. Start any WSL distro and do `ping github.com -c 4`. You should get `ping: github.com: Temporary failure in name resolution`.

3. Using command line do `wsl --shutdown`.

4. Start any WSL distro and do `ping github.com -c 4`. You should get `ping: github.com: Temporary failure in name resolution`.

</details>

<details><summary>If VPN is disconnected after any WSL session has been started</summary>

0. Freshly booted WIndows.

1. Connect to VPN.

2. Start any WSL distro and do `ping github.com -c 4` to confirm error

3. Using command line do `wsl --shutdown`

4. Disconnect and reconnect VPN. It could be the same or different server, does not matter.

5. Start any WSL distro and do `ping github.com -c 4`. It should work now.

</details>

<details><summary>If VPN is disconnected before any WSL session</summary>

0. Freshly booted Windows.

1. Connect to VPN.

2. Disconnect and reconnect VPN. It could be the same or different server, does not matter. Repeat this as many times as you like.

3. Start any WSL distro and do `ping github.com -c 4`. You should get `ping: github.com: Temporary failure in name resolution`.

</details>

### Additional Information

1. Tested in the latest version of [Pengwin](https://www.microsoft.com/store/productId/9NV1GV1PXZ6P) and [Ubuntu](https://www.microsoft.com/store/productId/9NBLGGH4MSV6).
2. Tested with Vietnam and Hong Kong servers.

**Comment by Smithienious** [comment]
Upstream problem.

**Comment by Xottab-DUTY** [comment]
@ameshkov sorry for ping, but maybe you're the best person to ping :D
This issue isn't fixed, can the AdGuard Team reopen it and make a fix?

**Comment by AlexandrPkhm** [comment]
@Xottab-DUTY The issue is related to the way our VPN driver handles WSL connections. At the moment we do not plan to change this behavior. However, we have already implemented an alternative - the Wintun driver, which you can enable in the Advanced Settings section. It allows for trouble-free operation with WSL.
