### ISSUE TITLE
VPN UI locks after clicking premium server

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNForWindows#621]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.2.0 nightly 50
sciter vpn version is 4.4.8.38

### Operating mode

VPN

### Environment

```markdown
- OS: Windows 11
```

### Issue Details

Steps to reproduce:
1. Go to the home page
2. Click any premium server and UI will be locked

### Expected Behavior

UI shouldn't be locked when I click on any premium servers.
PLUS I don't want this offer to be shown all the time, I'm sure other users are annoyed by this. I think it should only be shown when we open the app for the first time. 

### Actual Behavior

Whenever I click on one of the premium servers, the UI locks and I can't click anywhere. When I press X and open it again from the tray menu, the offer screen is shown. 
PLUS every time we minimize the app to task manager and open it again from task manager or tray menu, this offer is always shown! I don't want to be shown this offer over and over again.

### Screenshots

<details><summary>UI Locking:</summary>

https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/35523759/ef74a856-74a8-4b33-8c42-818d3ee3b4b5
</details>

<details><summary>Offer screen:</summary>

https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/35523759/5ddf840a-4947-4adb-982f-7292f8467117
</details>

**Comment by Aydinv13** [comment]
@gork7777 thanks for reporting. Will be fixed.

**Comment by gork7777** [comment]
@Aydinv13 Update for 2.3.0 nightly 4. When I click any premium server, offer shows up and no more UI gets lock. I can click the buttons. But while this offer is in the window, if we minimize the app to the task manager or close and reopen it by pressing X, another offer window overlaps on top of it. Thus, there're two offer windows in the app after these.
