### ISSUE TITLE
Wintun driver fails 

### ISSUE THREAD

**Issue by deathline94** [AdguardTeam/AdGuardVPNForWindows#623]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.2.1

### Operating mode

VPN

### Environment

```markdown
- OS:windows 10
- Other network-level software: N/A
```

### Issue Details

Steps to reproduce:
1.Go to settings
2.Check VPN mode
3.Turn wintun on

### Expected Behavior

Easy and simple ! VPN getting routed through wintun !

### Actual Behavior

![1](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/11331137/e42c9c74-df59-4f58-a6e5-cdabe0c55376)

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

Also i would like an MTU option for windows client like we have one for android !

**Comment by Aydinv13** [comment]
@deathline94 Hello!

- install the latest [Nightly](https://agrd.io/windows_vpn_nightly) and check if it's still reproducible
- collect [extended](https://adguard-vpn.com/kb/adguard-vpn-for-windows/solving-problems/logs/#collecting-and-sending-extended-logs) logs and send to devteam@adguard.com please

**Comment by Aydinv13** [comment]
As for MTU option, could you please create a new task because it's not related to this one.

**Comment by deathline94** [comment]
Same problem is the nightly app too … will try to send some logs. Thanks !

**Comment by awdrifter** [comment]
I have the same issue.

**Comment by shamarin** [comment]
Mine is ok, but Adguard Wintun adapter is not compatitble with OpenVPN Wintun adapter. If to enable Wintun in Adguard then OpenVPN can't connect via Wintun. In this case i need to install OpenVPN Wintun adapter (driver) again via Windows device manager. Seams that the problem is in the same name of the adapter.
