### ISSUE TITLE
Its impossible to change e-mail in settings

### ISSUE THREAD

**Issue by dvoot** [AdguardTeam/AdGuardVPNForWindows#638]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.2.4 (1271)

### Operating mode

None

### Environment

```markdown
- OS: Windows 10 Pro 22H2 build 19045.4046
- Other network-level software:
```

### Issue Details

Steps to reproduce:
1. Go to settings https://my.adguardvpn-help.com/ru/account/settings
2. Select "Change e-mail"
3. Enter new email and password for curent AdGuard account
4. Click on "Change email"

### Expected Behavior

E-mail is changed

### Actual Behavior

Error: "Check one more time: password looks
![Impossible to change email](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/65017666/430a7187-fe10-482b-a88f-2ce3c21e2a28)
 incorrect"

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/65017666/7113706e-052b-475a-a2b9-76f52d379e11)

</details>

**Comment by AlexandrPkhm** [comment]
Hi @dvoot,

We have not been able to reproduce the issue. Please make sure you are using a correct password for your currently selected AdGuard account. If the issue persists, please let us know if you are connected to a VPN or using any other network related app/browser extension.

**Comment by adbuker** [comment]
@dvoot , does the issue related to the Windows AdGuard VPN application, have you any troubles with it?

**Comment by dvoot** [comment]
Hello,
 
No, issue is related to web-page  AdGuard Account | Settings (adguardvpn-help.com)
 
Screenshot is atteched
 
Best Regards,
 
Dmitry
  
>Среда, 6 марта 2024, 11:53 +03:00 от adbuker ***@***.***>:
> 
> 
>@dvoot , does the issue related to the Windows AdGuard VPN application, have you any troubles with it?
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you were mentioned. Message ID:  <AdguardTeam/AdGuardVPNForWindows/issues/638/1980372057 @ github . com> 
 
 
--
Дмитрий Воронцов
Отправлено из Почты  Mail.ru

**Comment by dvoot** [comment]
Hello.
 
I am absolutely sure that password I use is correct one. I am authorized in AdGuard with Google account ***@***.*** So I enter the password of the mentioned account when trying to change the e-mail. See screenshots attached. The problem occurs both with VPN (via desktop Windows application) and without VPN connection.
 
Best egards,
 
Dmitry
  
>Понедельник, 4 марта 2024, 17:59 +03:00 от Alexandr ***@***.***>:
> 
> 
>Hi  @dvoot ,
>We have not been able to reproduce the issue. Please make sure you are using a correct password for your currently selected AdGuard account. If the issue persists, please let us know if you are connected to a VPN or using any other network related app/browser extension.
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you were mentioned. Message ID:  <AdguardTeam/AdGuardVPNForWindows/issues/638/1976776976 @ github . com> 
 
 
--
Дмитрий Воронцов
Отправлено из Почты  Mail.ru
