### ISSUE TITLE
Stuck on the servers check

### ISSUE THREAD

**Issue by deathline94** [AdguardTeam/AdGuardVPNForWindows#639]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.3.0 nightly 19 (1318)

### Operating mode

VPN

### Environment

```markdown
- OS: Windows 11
- Other network-level software: N/A
```

### Issue Details

Steps to reproduce:
1.open the app
2.thats it !

### Expected Behavior

We expect that after opening the app and few seconds, the servers are done checking with their pings and ready to connect

### Actual Behavior

After the opening, the app stays in perpetual checking mode which in turn doesn't allow selecting or connecting.

### Screenshots

<details><summary>Screenshot 1:</summary>

![1](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/11331137/8b6c1b4e-9e73-4527-bceb-c914122ddf8e)

</details>

### Additional Information

Here are some logs for your troubles :

*Logs were removed due to privacy reasons*

**Comment by deathline94** [comment]
should i upload here or email it ?

**Comment by Aydinv13** [comment]
@deathline94 received your logs thank you. By the way, do you have any other programs enabled that may affect network traffic? For example: DNS/ VPN service, Antivirus, Firewall

**Comment by deathline94** [comment]
it wouldnt have mattered . i've tested with and without other vpns . and im sure there is nothing interfering with the app.

**Comment by Aydinv13** [comment]
@awdrifter could you please share your logs as well https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/639#issuecomment-1988076753

**Comment by Danila-Arg** [comment]
@deathline94 Hi! Can you can check this problem on the last nightly, just on it we solved the problem with ping update, a related problem with another task

**Comment by deathline94** [comment]
Hey there ! Happy to report that the problem is fixed in the latest nightly (2.3.0 nightly 26 1364)
But also a few more little problem arose. The ping check takes about 30 seconds. Also, the locations are not sorted based of ping
and the “Fastest Locations” part doesn't work properly. It just shows a few offline servers.
Other than those few small issues, everything else works just fine
Thank you !

**Comment by Danila-Arg** [comment]
@deathline94 I'm glad to hear that. We do not provide sorting by ping, we basically sort by name, we put the fastest ones in the top 3, but I see this function does not work correctly for you, you can create a task on github and we will also consider it.

**Comment by awdrifter** [comment]
Yes, I forgot I posted this question on github. I updated the app and it works now. Thanks.

Sent from Yahoo Mail on Android 
 
  On Thu, Mar 28, 2024 at 2:59, Argastsev ***@***.***> wrote:   


@deathline94 Hi! Can you can check this problem on the last nightly, just on it we solved the problem with ping update, a related problem with another task
