### ISSUE TITLE
Add ChatGPT to the list of known services

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardVPNForWindows#644]
### Issue Details

In order for the ChatPGT website and [the authorization page](https://chat.openai.com/auth/login) to open correctly, you need to add the domains `openai.com`, `chatgpt.com` and `oaistatic.com`, which is not so easy for an ordinary user to find out.

### Proposed solution

Add ChatGPT to the list of known services like Microsoft, Google, Spotify, etc.

**Comment by Aydinv13** [comment]
@rakleed 

Will be added, thank you.

**Comment by bogachenkove** [comment]
Also `oaiusercontent.com`
