### ISSUE TITLE
All servers stuck on checking...

### ISSUE THREAD

**Issue by awdrifter** [AdguardTeam/AdGuardVPNForWindows#649]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.3 Beta 2 (1346)

### Operating mode

VPN

### Environment

```markdown
- OS:Windows 10 21H2
- Other network-level software:NOD32
```

### Issue Details

Steps to reproduce:
1. Install Adguard VPN
2. Run it
3. ???
4. Stuck on checking... forever

### Expected Behavior

Some servers actually available for connection after checking

### Actual Behavior

All servers stuck at checking... forever

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/31308679/8f834132-e59e-48a7-b958-34b37a8d3250)
</details>

### Additional Information

I also tried the regular non-beta version of the app, still not working.

**Comment by Aydinv13** [comment]
@awdrifter Hello!

The issue has already created https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/639, I'm closing this one as a duplicate
