### ISSUE TITLE
Create separate network device on Windows

### ISSUE THREAD

**Issue by cxen** [AdguardTeam/AdGuardVPNForWindows#656]
### Issue Details

Most VPNs create a new virtual network device and divert traffic through it. This can be useful for software that support restricting their own access only to specific network devices. This way, they can act as an extra level of safety, in case the VPN software malfunctions and leaks.

However, Adguard VPN does not do that, which means the security feature of those software cannot be used.

### Proposed solution

Create a separate virtual network device when installing/updating Adguard VPN.

**Comment by AlexandrPkhm** [comment]
Hi @cxen,

Could you please let us know if you are talking about a virtual network interface? 
If this is a correct assumption, all recent versions of AdGuard VPN for Windows support creating a virtual network interface using the Wintun driver. To enable it, please open `AdGuard VPN` → `Settings` → `App settings` → `Advanced settings` → and enable `Use Wintun` option. 

If this option is enabled, AdGuard VPN will automatically create a Wintun virtual network interface for each connection.
<img width="269" alt="Screenshot 2024-04-08 at 11 25 24" src="https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/109953785/3559da92-388d-49f8-8d13-da3be548019f">

**Comment by cxen** [comment]
Yes, this is exactly what I was looking for!
I did not realise that this is what Wintun stands for and I was confused that Adguard was not doing this by default (although I think I can understand why).

Thanks for the help.

**Comment by shamarin** [comment]
> Hi @cxen,
> 
> Could you please let us know if you are talking about a virtual network interface? If this is a correct assumption, all recent versions of AdGuard VPN for Windows support creating a virtual network interface using the Wintun driver. To enable it, please open `AdGuard VPN` → `Settings` → `App settings` → `Advanced settings` → and enable `Use Wintun` option.
> 
> If this option is enabled, AdGuard VPN will automatically create a Wintun virtual network interface for each connection. <img alt="Screenshot 2024-04-08 at 11 25 24" width="269" src="https://private-user-images.githubusercontent.com/109953785/320411386-3559da92-388d-49f8-8d13-da3be548019f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNDg4MzYsIm5iZiI6MTcxNDE0ODUzNiwicGF0aCI6Ii8xMDk5NTM3ODUvMzIwNDExMzg2LTM1NTlkYTkyLTM4OGQtNDlmOC04ZDEzLWRhM2JlNTQ4MDE5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNlQxNjIyMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOGRkMTgyMzYxYTgzNzQ0N2Y2ZWE0YjczYzdlMmQ2NTljNjU4MjgyOGM4ZDNlZjlhZWQ4MzM0ZjFkNjUyOTMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Yr40ghBX_sUS52ACX0yd_bUmmqrxStTXzd6umn1sg0Q">

No such behavior, standard Wintun adapter became available in device manager, but with Wintun name, not an AdguardVPN and also it dissapier after disconnection of the Adguard VPN and as the name is the same as for the OpenVPN Wintun there is incompatibility #661 . Tested today with the latest stable update version 2.2.5
