### ISSUE TITLE
AdguardVPN and Fritz!box

### ISSUE THREAD

**Issue by frepke** [AdguardTeam/AdGuardVPNForWindows#658]
### Issue Details

The settings provided on the Adguard's website for the IPsec router setup are not working on a Fritz!box.

Setting up the Fritz!box is asking for:
- vpn username (key-id):
- vpn username (preshared key):
- name for the connection:
- internetaddress from remote site:
- remote network IP: xxx.xxx.xxx.xxx
- subnetmask: 255.255.255.0
- permanent vpn-connection: yes/no

comodo.crt can't be used

### Proposed solution

no clue

### Alternative solution

waiting for the wireguard implementation

**Comment by KolbasovAnton** [comment]
@frepke Greetings!
Please, can You take a screenshot of router's configure window, which fields exactly You can't fill?
"comodo.crt can't be used" - it is some kind of error? In which way it can't be used?

**Comment by PavelParkhomenko** [comment]
Thank you for providing the screenshot.
Please make sure that you are selecting "IPsec-client (IKE)" and not "L2TP/IPsec." Generally, IKEv2/IPsec does not require a Pre-Shared Key, so it is not provided in the credentials generated in your AdGuard account. Additionally, there's no need for a certificate when setting up our VPN on your router.
For detailed setup instructions for AdGuard VPN on your router, you can refer to [our blog post](https://adguard-vpn.com/en/blog/adguard-vpn-for-routers.html](https://adguard-vpn.com/en/blog/adguard-vpn-for-routers.html).

**Comment by frepke** [comment]
Hi Pavel,

Thanks for your reply. I think my Fritz!Box only supports L2TP/IPSec 😟

The only option now is to wait till AdGuard's WireGuard implementation is ready 😊
