### ISSUE TITLE
Inaccurate license details

### ISSUE THREAD

**Issue by Smithienious** [AdguardTeam/AdGuardVPNForWindows#66]
### Issue Details

- **AdGuard VPN version:**
  - 0.0.143.0
- **VPN mode:**
  - Local VPN
- **Operating system and version:**
  - Windows 10 19043.844
- **Other network-level software:**
  - AdGuard, cFosSpeed

### Expected Behavior

License details matches the account manager

### Actual Behavior

They don't

### Screenshots

<details><summary>Screenshot:</summary>

![Screenshot 2021-03-10 075524](https://user-images.githubusercontent.com/10150902/110559313-8e646400-8176-11eb-9a93-d41be790fcb5.png)

</details>

**Comment by Smithienious** [comment]
Logs sent

**Comment by TimusBel** [comment]
@Smithienious , Hello. Could you please check it now (license info locally in Adguard Vpn app and in the personal account)?

**Comment by Smithienious** [comment]
@TimusBel Yes, they match now. I think it is better to keep it as Feb 9 instead of 2/9.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10150902/110945232-034ebe00-8370-11eb-8abb-19eb1da146ef.png)

</details>

**Comment by TimusBel** [comment]
@Smithienious  Thanks. I'll give your proposal to our designer
