### ISSUE TITLE
PrimeVideo blocking USA servers, currently the VPN doesnt work with prime.

### ISSUE THREAD

**Issue by Mr-McMuffin** [AdguardTeam/AdGuardVPNForWindows#660]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.2.4

### Operating mode

VPN

### Environment

```markdown
- OS: Windows 11 Latest 2024-04-13
- Other network-level software: Adguard home
```

### Steps to Reproduce
1. Launch AdGuard VPN application.
2. Connect to any server, including servers in the USA.
3. Attempt to access Amazon Prime video content.

### Expected Behavior

Users should be able to connect to Amazon Prime video content without issues while using AdGuard VPN with USA servers, however having additional locations function would be ideal too. 

### Actual Behavior

Attempting to access Amazon Prime video content while connected to AdGuard VPN results in failure, regardless of the server location - amazon detects im using a VPN.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by AlexandrPkhm** [comment]
@Mr-McMuffin Hi!

We have not been able to reproduce the problem. Could you please check to see if it is still occurring on your end and let us know?
