### ISSUE TITLE
Not compatitble with OpenVPN Wireguard Wintun

### ISSUE THREAD

**Issue by shamarin** [AdguardTeam/AdGuardVPNForWindows#661]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2

### Operating mode

None

### Environment

```markdown
- OS:
- Other network-level software:
```

### Issue Details

Steps to reproduce:
1.
2.
3.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by shamarin** [comment]
If to enable Wireguard in Adguard VPN client for Windows when Wireguard Wintun from OpenVPN stops working and connecting to vpn. Seams that the problem is in the same driver of Wireguard Wintun but different versions. Maybe it's better to make your self driver based on Wireguard Wintun as it is made in Kaspersky Secure Connection (Kasperskry-VPN driver name of network bu it using Wireguard Wintun).

**Comment by AlexandrPkhm** [comment]
Hi @shamarin 

Could you please clarify which version of AdGuard VPN for Windows you are using on your device, and also if you are using the AdGuard WinTun implementation available in the application's Advanced settings section? 


Please try to install the latest beta version of AdGuard VPN for Windows, available from the following [link](https://github.com/AdguardTeam/AdGuardVPNForWindows/releases/tag/v2.3.0-beta-2). If the issue still persists with the latest beta, please send us the exact steps to reproduce it as well as application logs.

Here's what you need to do to send us the application logs:

1. Go to Settings → App settings → Logging level → **Record everything**;
2. Reproduce the problem and remember the exact time it was reproduced at. We will
need it to find the corresponding entries in the log file;
3. Open Support tab → **Export logs and system info**;
4. Send the archive to `devteam@adguard.com` and mention this issue number in the subject. Don't forget to include the time of reproduction.
5. Set the logging level back to **Record by default**.

**Comment by shamarin** [comment]
Checked with the latest beta, the same. will collect log data today and send you.

**Comment by shamarin** [comment]
Sended with reproduction of this issue and also of #663

**Comment by shamarin** [comment]
Why not to make just as Kaspersky do - the separate adapter in device manager (Kaspersky VPN adapter)?
<img width="231" alt="Снимок экрана 2024-04-26 203811" src="https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/24771090/c9e0fbb6-fff8-4aec-a3df-e3d2f2ba502e">

**Comment by shamarin** [comment]
Adguard doesn't do that even with Wintun turned on in settings.

**Comment by northis** [comment]
@shamarin Do you have this one when connected via WinTun?
![image](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/20269126/a262f571-9f02-43cb-b607-d7a490e284e1)

**Comment by shamarin** [comment]
> @shamarin Do you have this one when connected via WinTun? ![image](https://private-user-images.githubusercontent.com/20269126/331538180-a262f571-9f02-43cb-b607-d7a490e284e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MzgyODcsIm5iZiI6MTcxNTkzNzk4NywicGF0aCI6Ii8yMDI2OTEyNi8zMzE1MzgxODAtYTI2MmY1NzEtOWYwMi00M2NiLWI2MDctZDdhNDkwZTI4NGUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDA5MjYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4NzBiZTIwYjg0MTNkODc3MWQxZjZkYWFhYjE0ZDEzODRkZmE0NGM3YzVhNDNjZGNiY2JhNGVmYmE4NjE1ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JfBxLCYnUaOOPphG1ynQDCQbJxF5gPJPr7ieAawYg9M)

Yes, but if to dissonect any connected VPN server via Adguard when this Wintun driver dissapear from device manager. And in this is the problem because OpenVPN using just the same name and the same Wintun.
To resolve incompatibility Wintin tunnel must not dissapear each time when VPN is disconnected and it must use another name for example just as with Kaspersky "Adguard Wintun VPN" or something like this.

**Comment by shamarin** [comment]
Суть проблемы состоит в том, что OpenVPN и Adguard VPN используют одно и тоже имя драйвера wintun и Adguard как только отключаешь VPN соединение удаляет драйвер (адаптер) как на фото выше из списка адаптеров. Поэтому OpenVPN не может соединиться через Wintun.
Поэтому необходимо сделать так чтобы Wintun не исчезал из списка адаптеров как только Adguard отключает VPN соединение и необходимо как у Касперского сделать свое уникальное имя адаптера, например "Adguard Wintun VPN" чтобы не было конфликтов с такими приложениями как OpenVPN

**Comment by northis** [comment]
Скорее всего дело не в конфликте имён, а в том, что установлен Kaspersky VPN и это каким-то образом ломает подключение. Обратите внимание на [этот комментарий](https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/663#issuecomment-2117578659) в соседней ветке, скорее всего у вас в исключениях не тот процесс Kaspersky VPN.

>Поэтому необходимо сделать так чтобы Wintun не исчезал из списка адаптеров как только Adguard отключает VPN соединение

Такое поведение сделано намеренно, в том числе чтобы уменьшить риск конфликтов, когда AdGuard VPN отключён.

**Comment by shamarin** [comment]
Причем тут Касперский и Wintun OpenPVN???
Если я проверил поэкспериментировав и проблема как раз в одинаковых адаптерах (имя) от OpenVPN и Adguard VPN. Как я и написал выше Adguard как только отключаешь соединение, то Wintun адаптер пропадает из устройств сетевых. Если вручную добавить его через установку адаптера в ручную по типу, то тогда OpenVPN сразу и без проблем соединяется. Поэтому и написал, что надо сделать чтобы адаптер не пропадал при отключении и имя другое дать, чтобы если одновременно подключаешься чтобы IP адрес выдаваемый AdguardVPN не влиял на OpenVPN.

**Comment by shamarin** [comment]
> Скорее всего дело не в конфликте имён, а в том, что установлен Kaspersky VPN и это каким-то образом ломает подключение. Обратите внимание на [этот комментарий](https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/663#issuecomment-2117578659) в соседней ветке, скорее всего у вас в исключениях не тот процесс Kaspersky VPN.
> 
> > Поэтому необходимо сделать так чтобы Wintun не исчезал из списка адаптеров как только Adguard отключает VPN соединение
> 
> Такое поведение сделано намеренно, в том числе чтобы уменьшить риск конфликтов, когда AdGuard VPN отключён.

Так зато OpenVPN тот же самый адаптер использует когда в нём выбрано использовать Wintun (тоже имя и тот же драйвер)

**Comment by northis** [comment]
@shamarin Касперский тут при том, что он мог влиять на ситуацию неявным образом.
Можно вас попросить сделать скриншот диспетчера при подключенном OpenVPN? Исчезание адаптера - это общая практика, можете проверить, исчезает ли из списка адаптер OpenVPN при дисконнекте.

**Comment by shamarin** [comment]
> @shamarin Касперский тут при том, что он мог влиять на ситуацию неявным образом. Можно вас попросить сделать скриншот диспетчера при подключенном OpenVPN? Исчезание адаптера - это общая практика, можете проверить, исчезает ли из списка адаптер OpenVPN при дисконнекте.

Не исчезает. Я его не использую в конфиге. В конфиге прописано использовать адаптер Wintun, а он исчезает при дисконнекте Adguard VPN. От сюда и проблема, OpenVPN при соедиении и выдает ошибку как раз, что нет ни одного адаптера Wintun.

**Comment by northis** [comment]
OpenVPN должен создавать его каждый раз при подключении. Пожалуйста, пришлите  скриншот диспетчера устройств при подключенном OpenVPN.

**Comment by shamarin** [comment]
> OpenVPN должен создавать его каждый раз при подключении. Пожалуйста, пришлите скриншот диспетчера устройств при подключенном OpenVPN.

Не создает он, как и Касперский и все остальные. Он всегда остается в диспетчере задач.  Исчезновение только у Adguard сделано зачем-то, отсюда и проблема выплывает. А скриншот диспетчера устройств я уже выше присылал.

**Comment by northis** [comment]
В вашем скриншоте выше нет адаптера, имя которого совпадало бы с тем, который использует AdGuardVPN.

**Comment by shamarin** [comment]
> В вашем скриншоте выше нет адаптера, имя которого совпадало бы с тем, который использует AdGuardVPN.

Как же нет, я уже писал, что это wintun Tunnel. Adguard VPN его использует и OpenVPN если в OpenVPN конфиге указано использовать Wintun. Wintun так же у меня включен в настройках Adguard VPN, о чем тоже указано.

**Comment by shamarin** [comment]
Еще раз прикладываю скриншоты из диспетчера устройств
<img width="249" alt="Снимок экрана 2024-05-20 155816" src="https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/24771090/f93249e7-3f7b-4e81-8fea-3a1983539596">
На первом фото когда в Adguard VPN выбрана настройка использовать Wintun и после соединения с любым VPN сервером отключится, то драйвер wintun Tunnel исчезает из диспетчера устройств (действие по умолчанию программы Adguard).
На втором фото окно соединения OpenVPN, когда в нём тоже стоит настройка использовать Wintun.
<img width="437" alt="Снимок экрана 2024-05-20 155909" src="https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/24771090/140c72b6-bffa-4641-b0d2-e6e03312b2e9">

**Comment by shamarin** [comment]
Ошибка сама за себя говорит.
Если теперь в диспетчере устройств выбрать установить старое устройства, выбрать в списке сетевых адаптеров wintun и установить, то OpenVPN соединится без проблем
<img width="242" alt="Снимок экрана 2024-05-20 160340" src="https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/24771090/96495752-ddd6-4c1b-842b-021389125bd3">
<img width="428" alt="Снимок экрана 2024-05-20 160517" src="https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/24771090/b4b212df-7c39-4812-a9c2-3c25786bf1f4">
<img width="442" alt="Снимок экрана 2024-05-20 160554" src="https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/24771090/bfda51e4-f19f-4983-977b-3ef4be5c8c8d">
<img width="446" alt="Снимок экрана 2024-05-20 160629" src="https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/24771090/5f7377b4-967c-4dc9-819b-d66680bb20da">
<img width="440" alt="Снимок экрана 2024-05-20 160751" src="https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/24771090/e618ff41-b60d-4f89-b1da-2f1a33d556ad">
<img width="256" alt="Снимок экрана 2024-05-20 160837" src="https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/24771090/9ef8154d-505b-47c3-8c28-5cf3b214120b">
<img width="256" alt="Снимок экрана 2024-05-20 160837" src="https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/24771090/7f2ba6b1-1100-4a51-92a3-dd90ac526893">
<img width="308" alt="Снимок экрана 2024-05-20 160905" src="https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/24771090/379e3f0e-c913-40f5-aff0-d50510511c47">
<img width="436" alt="Снимок экрана 2024-05-20 161008" src="https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/24771090/a3fbdc04-9f46-4539-9d43-74cd74507d10">

**Comment by shamarin** [comment]
Так что никакой Касперский тут не причем, а проблема как я и описал в том что имя адаптера Wintun у Adguard и у OpenVPN одно и тоже, плюс Adguard после разрыва соединения с VPN сервером зачем то удаляет Wintun адаптер из диспетчера устройств, поэтому OpenVPN после этого подключится не может. 
Поэтому чтобы конфликтов не было предлагают в Adguard VPN для Wintun другое имя адаптера назначить (Adguard VPN wintun например как у Касперского) и не удалять адаптер из диспетчера устройств каждый раз при отключении соединения.

**Comment by northis** [comment]
>Как же нет, я уже писал, что это wintun Tunnel.

То есть если подключить только OpenVPN (не включая AdGuard VPN), то адаптер с таким именем (`wintun Tunnel`) появится в диспетчере устройств? На вашем скриншоте нет адаптера с таким именем.

**Comment by shamarin** [comment]
> > Как же нет, я уже писал, что это wintun Tunnel.
> 
> То есть если подключить только OpenVPN (не включая AdGuard VPN), то адаптер с таким именем (`wintun Tunnel`) появится в диспетчере устройств? На вашем скриншоте нет адаптера с таким именем.

Я же написал, что его нет после отключения от Adguard VPN. OpenVPN он никогда не исчезает из диспетчера устройств. Если он там есть, то OpenVPN подключается, как только его нет там, то OpenVPN выдает ошибку как на изображении.

**Comment by shamarin** [comment]
Т.е я к тому, что установил я OpenVPN в диспетчере устройств появился адаптер wintun Tunnel. OpenVPN соединяется без проблем через wintun. Установил AdguardVPN, там по умолчанию использование Wintun отключено. Включаешь в Adguard Wintun, подключаешься к любому серверу, отключаешься от сервера. После отключения Wintun Tunnel адаптер исчезает из диспетчера задач. Пытаешься подключиться после этого к OpenVPN и там эта ошибка. Вот что на моих изображениях симметировано, с чем я столкнулся. Ну а далее вручную устанавливаешь через диспетчер устройств wintun Tunnel и сразу OpenVPN подключается. Так понятнее???

**Comment by northis** [comment]
При подключённом OpenVPN адаптер действительно не удаляется при дисконнекте, но имя у него не `wintun Tunnel`.
![image](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/20269126/d027c2c3-771b-4582-a47f-17ada86c3457)

**Comment by shamarin** [comment]
> При подключённом OpenVPN адаптер действительно не удаляется при дисконнекте, но имя у него не `wintun Tunnel`. ![image](https://private-user-images.githubusercontent.com/20269126/332171436-d027c2c3-771b-4582-a47f-17ada86c3457.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMzIyNjEsIm5iZiI6MTcxNjIzMTk2MSwicGF0aCI6Ii8yMDI2OTEyNi8zMzIxNzE0MzYtZDAyN2MyYzMtNzcxYi00NTgyLWE0N2YtMTdhZGE4NmMzNDU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDE5MDYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlZDFmOTQ0YmY4MTg2ZWY5NGYyNTU2OGI0NGNjMjc3MWE3YTYwYTBjMWNmMmZmM2E1NWU5NjE4OTZmOTEwMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.01kq67eBPElVRXIFoJSgBajspZ-6AjkbXd_28QGreIM)

Опять не внимательно прочитали, я указал, что в конфиге подключения к серверу OpenVPN необходимо указать использование Wintun, доступно в OpenVPN начиная с версии 2.4.0 если не ошибаюсь. 
У вас сейчас используется стандартная схема подключения используя TAP драйвер OpenVPN. Но они советуют использовать Wireguard Wintun.
В конфиге необходимо прописать следующее:
`windows-driver wintun`

**Comment by shamarin** [comment]
В OpenVPN по умолчанию TAP драйвер используется для подключений (на скриншоте TAP-Windows Adapter V9)

**Comment by northis** [comment]
Адаптеры OVPN и AG VPN разные
![image](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/20269126/aefb40a8-2d81-44d4-b25b-6ac1a20625d7).
Проверили отключение AdGuard VPN - пропадает `wintun Tunnel`, OpenVPN потом нормально подключается, адаптер  `Wintun Userspace Tunnel` на месте.
Однако если по какой-то причине `Wintun Userspace Tunnel` пропадает, то повторяются симптомы, описанные вами. Мы поисследуем на предмет возможной связи с AdGuard VPN. Как временное решение, вы можете принудительно добавить wintun-адаптер Open VPN через ярлык `Add a new Wintun virtual network adapter`

**Comment by shamarin** [comment]
> Адаптеры OVPN и AG VPN разные ![image](https://private-user-images.githubusercontent.com/20269126/332195749-aefb40a8-2d81-44d4-b25b-6ac1a20625d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODk1MjIsIm5iZiI6MTcxNjI4OTIyMiwicGF0aCI6Ii8yMDI2OTEyNi8zMzIxOTU3NDktYWVmYjQwYTgtMmQ4MS00NGQ0LWIyNWItNmFjMWEyMDYyNWQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDExMDAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNDhhZGI0YmFiY2QyZDBjM2ZiNTY2M2E3YTFmN2MzMmRkNmVkMWQ2OWEyZDI2N2ZiZThiNzk2ZWJlNGQxMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1U8UmXuylbFp9EHR2cr166J8y93q2Mke9IsnsEdfVUc). Проверили отключение AdGuard VPN - пропадает `wintun Tunnel`, OpenVPN потом нормально подключается, адаптер `Wintun Userspace Tunnel` на месте. Однако если по какой-то причине `Wintun Userspace Tunnel` пропадает, то повторяются симптомы, описанные вами. Мы поисследуем на предмет возможной связи с AdGuard VPN. Как временное решение, вы можете принудительно добавить wintun-адаптер Open VPN через ярлык `Add a new Wintun virtual network adapter`

Да, действительно так. Вчера присутствовал Wintun Userspace Tunnel, прописал использовать его в конфиге OpenVPN, но он почему то потом один раз исчез после подключения и отключения Adguard VPN, добавил его опять, пока вроде всё нормально.

**Comment by shamarin** [comment]
После перезагрузки системы при запуске сервера VPN в Adguard он удаляет первый попавшийся wintun адаптер в диспетчере устройств, свой wintun Tunnel не создает. И так несколько раз пока все Wintun userspace Tunnel не удалит. Все видимо лучше реализовать чтобы при отключении Adguard VPN он не удалял wintun адаптер из диспетчера устройств. В обще проблема не решена и сохраняется каждый раз после перезагрузки системы.

**Comment by shamarin** [comment]
И еще в такой ситуации при попытке отключить VPN приложение показывает Отключение, а отключения не происходит. Приходится приложение удалять принудительно через Диспетчер задач

**Comment by northis** [comment]
>свой wintun Tunnel не создает

это происходит только при подключении

> VPN в Adguard он удаляет первый попавшийся wintun адаптер в диспетчере устройств

если это так, то это баг, проверим

**Comment by shamarin** [comment]
> > свой wintun Tunnel не создает
> 
> это происходит только при подключении
> 
> > VPN в Adguard он удаляет первый попавшийся wintun адаптер в диспетчере устройств
> 
> если это так, то это баг, проверим



> > свой wintun Tunnel не создает
> 
> это происходит только при подключении
> 
> > VPN в Adguard он удаляет первый попавшийся wintun адаптер в диспетчере устройств
> 
> если это так, то это баг, проверим

Это так, проверил несколько раз. Как и писал выше, что создаешь в OpenVPN через консоль несколько Wintun туннелей, в диспетчере устройств они появляются. Сразу после этого если подключать Adguard то он соединяется без проблем и свой включает Wintun в диспетчере. Стоит только перезагрузить систему и сразу потом попробовать соединиться в Adguard с любым VPN, то Adguard удаляет сначала первый Wintun адаптер из диспетчера устройств, который был создан в OpenVPN, потом при попытке отсоединиться от сервера VPN в Adguard он выдает что идет отключение и ничего не происходит. Удаляешь из диспетчера задач его и запускаешь заново и потом он при попытке соединиться опять удаляет последний адаптер Wintun, потом так же зависает при попытке отключится от сервера VPN и вот только после еще одного перезапуска Adguard он соединяется как нужно, но уже только свой адаптер Wintun создает. И тогда уже OpenVPN не может соединиться. 
Плюс по Wintun соединение очень не стабильное у Adguard, показывает часто что есть соединение спустя какое то время, но на любой веб ресурс не зайди, ошибку браузер соединения выдает. Плюс по Wintun скорость соединения в разы ниже (20-30 Мбит вместо 80-90 Мбит), плюс скорость совсем низкая становится если при этом еще торрент клиент запущен и он активно раздает и принимает данные на раздачах активно. В AdguardTeam/VpnLibs#54 указал об этом. Задумка хорошая, но реализация пока слишком сырая и не пригодна для практического использования.

**Comment by northis** [comment]
@shamarin Мы переименовали адаптер на `AdGuard VPN Tunnel`, попробуйте, пожалуйста, на последней найтли https://agrd.io/windows_vpn_nightly

**Comment by shamarin** [comment]
> @shamarin Мы переименовали адаптер на `AdGuard VPN Tunnel`, попробуйте, пожалуйста, на последней найтли https://agrd.io/windows_vpn_nightly

Хорошо, попробую сегодня. Отпишусь по результатам.

**Comment by shamarin** [comment]
Проверил. При обновлении во-первых удаляет все Wintun адаптеры из диспетчера устройств и плюс после перезагрузки удаляет тоже. Думаю может все же стоит вам не удалять его каждый раз из диспетчера устройств, а пускай будет, как у Касперского и как у OpenVPN сделано. Думаю что в этом причина.

**Comment by northis** [comment]
@shamarin Вряд ли AdGuard VPN причастен к удалению чужих адаптеров, мы используем стандартные функции библиотеки wintun, которая предполагает создание и удаление адаптера под каждое использование.

**Comment by shamarin** [comment]
> @shamarin Вряд ли AdGuard VPN причастен к удалению чужих адаптеров, мы используем стандартные функции библиотеки Wireguard, которая предполагает создание и удаление адаптера под каждое использование.

OpenVPN использует в данном случае тоже адаптер Wintun от Wireguard. И Adguard удаляет все адаптеры Wintun, а не только Adguard VPN tunnel, в этом то и проблема. Видимо у вас настроено так что все Wintun адаптеры удаляются. И как выше писал для того чтобы OpenVPN воспользоваться то каждый раз приходится перед этим вручную установить адаптер Wintun userspace tunnel. Это крайне не удобно. Или аы считаете, что это нормально???

**Comment by northis** [comment]
@shamarin Безусловно это ненормально.
>Видимо у вас настроено так что все Wintun адаптеры удаляются

Удаляется только адаптер, созданный нами.

Можете сделать видеодемонстрацию с воспроизводством проблемы? Есть ощущение, что мы упустили что-то важное, что могла бы прояснить такая демонстрация. Вот наша демонстрация - подключение и отключение OpenVPN и AdGuardVPN - адаптер OpenVPN на месте: https://uploads.adguard.org/win-northbkg7d.mp4

Также, пожалуйста, перед этой демонстрацией включите расширенные логи программы и отправьте их на почту devteam@adguard.com. Заранее спасибо.

**Comment by shamarin** [comment]
> @shamarin Безусловно это ненормально.
> 
> > Видимо у вас настроено так что все Wintun адаптеры удаляются
> 
> Удаляется только адаптер, созданный нами.
> 
> Можете сделать видеодемонстрацию с воспроизводством проблемы? Есть ощущение, что мы упустили что-то важное, что могла бы прояснить такая демонстрация. Вот наша демонстрация - подключение и отключение OpenVPN и AdGuardVPN - адаптер OpenVPN на месте: https://uploads.adguard.org/win-northbkg7d.mp4
> 
> Также, пожалуйста, перед этой демонстрацией включите расширенные логи программы и отправьте их на почту [devteam@adguard.com](mailto:devteam@adguard.com). Заранее спасибо.

Хорошо. Но как снять логи, если для воспроизведения необходимо перезагрузить систему??? Потому что я указывал, что все адаптеры Wintun исчезают сразу после перезагрузки системы и при обновлении Adguard.

**Comment by shamarin** [comment]
> @shamarin Безусловно это ненормально.
> 
> > Видимо у вас настроено так что все Wintun адаптеры удаляются
> 
> Удаляется только адаптер, созданный нами.
> 
> Можете сделать видеодемонстрацию с воспроизводством проблемы? Есть ощущение, что мы упустили что-то важное, что могла бы прояснить такая демонстрация. Вот наша демонстрация - подключение и отключение OpenVPN и AdGuardVPN - адаптер OpenVPN на месте: https://uploads.adguard.org/win-northbkg7d.mp4
> 
> Также, пожалуйста, перед этой демонстрацией включите расширенные логи программы и отправьте их на почту [devteam@adguard.com](mailto:devteam@adguard.com). Заранее спасибо.

Компьютер перезагружали после этого??? Это очень важный момент, так как я указывал, что удаление всех адаптеров происходит сразу после перезагрузки системы.

**Comment by shamarin** [comment]
По видео вашему посмотрел, что не перезагружали. До перезагрузки системы у меня все тоже самое как и у вас на видео. О чем я писал ранее выше. **_Но как только стоит перезагрузить систему (или перезагрузить систему и попытаться подключить Adguard VPN к любому VPN серверу) то все адаптеры Wintun userspace будут удалены (хоть их два три и т.д создать). Вот этот момент вы и упустили._**

**Comment by shamarin** [comment]
Воспроизвел проблему. Первое видео до перезагрузки системы, когда после отключения соединения в Adguard адаптер остается. И второе видео **_сразу после перезагрузки системы и там сразу ни одного адаптера нет в диспетчере устройств_**. Соответственно и два лога пришлю, один до перезагрузки системы, второй после.

**Comment by shamarin** [comment]
Заодно на видео видно что когда работает торрент клиент, то даже если он в исключениях, то приложение Adguard VPN при соединении к любому серверу сразу начинает загружать процессор (CPU) очень сильно (40-80 процентов). Это к ошибке #693

**Comment by shamarin** [comment]
На указанную почту отправил ссылку для скачивания видео и журнала приложения, так как почта не позволяет такой объём на прямую отправить.

**Comment by northis** [comment]
В результате таких действий можно заключить, что удаление OpenVPN tun-адаптера не зависит от наличия AdGuard VPN на машине:

```
1. Удалить AdGuard VPN
2. Перезагрузить
3. OVPN адаптера нет
4. Переустановить OVPN, адаптер появился, коннект успешный
5. Перезагрузить
6. Адаптера нет
```

Тест на второй машине показал, что адаптер не пропадает при перезагрузке даже если AdGuard VPN установлен. 
Скорее всего, такое поведение OpenVPN связано с настройками конкретной системы. 

Как обходное решение, можете добавить [команду из ярлыка](https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/661#issuecomment-2121184792) `Add a new Wintun virtual network adapter` в автозагрузку

**Comment by shamarin** [comment]
Причина открытия заново???

**Comment by northis** [comment]
> Причина открытия заново???

Мы смогли воспроизвести проблему, так что задача пока в работе.

**Comment by shamarin** [comment]
> > Причина открытия заново???
> 
> Мы смогли воспроизвести проблему, так что задача пока в работе.

Это хорошо, надеюсь, что скоро исправление выйдет. В работу будут брать ошибку #693?
На видео отчетливо видно, что когда торрент клиент работает активно на компьютере и даже если он в исключениях в Adguard VPN добавлен, то Adguard VPN с включенным использованием Wintun потребляет слишком много системных ресурсов (загрузка процессора 70-90%) и при этом спустя небольшое количество времени пропадает соответственно соединение с VPN сервером любым, т.е программа отображает что соединение есть, но по факту если попытаться открыть любой веб сайт в любом браузере, то выдаст ошибку соединения. Плюс само по себе скорость соединения перед этим очень низкая через VPN.
В журнале ошибок там получается это тоже попал этот случай. И тем более тоже с Wintun связано как и эта ошибка.

**Comment by northis** [comment]
@shamarin причина конфликта в том, что и OpenVPN и AdGuard VPN в режиме Wintun пользуются одним драйвером `wintun.sys`. OpenVPN используют модифицированную библиотеку, мы - оригинальную `wintun.dll` от WireGuard, в которую вшит драйвер `wintun.sys`. 
На данный момент наша политика состоит в том, что мы не модифицируем библиотеку `wintun.dll`, соответственно и название драйвера, которое в ней зашито, поменять не можем. Однако это могут сделать в OpenVPN, так как они всё равно используют модифицируют код этой библиотеки у себя. Как вариант, вы можете обратиться к ним с тем, чтобы они поменяли имя файла.
Мы же со своей стороны возможно будем изменять оригинальную библиотеку, и в рамках этих изменений поменяем и название файла драйвера. Это решит конфликт с OpenVPN.

**Comment by northis** [comment]
See https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/722

**Comment by shamarin** [comment]
> @shamarin причина конфликта в том, что и OpenVPN и AdGuard VPN в режиме Wintun пользуются одним драйвером `wintun.sys`. OpenVPN используют модифицированную библиотеку, мы - оригинальную `wintun.dll` от WireGuard, в которую вшит драйвер `wintun.sys`. На данный момент наша политика состоит в том, что мы не модифицируем библиотеку `wintun.dll`, соответственно и название драйвера, которое в ней зашито, поменять не можем. Однако это могут сделать в OpenVPN, так как они всё равно используют модифицируют код этой библиотеки у себя. Как вариант, вы можете обратиться к ним с тем, чтобы они поменяли имя файла. Мы же со своей стороны возможно будем изменять оригинальную библиотеку, и в рамках этих изменений поменяем и название файла драйвера. Это решит конфликт с OpenVPN.

Хорошо, понял. Напишу им сославшись на данный пост.

**Comment by shamarin** [comment]
> @shamarin причина конфликта в том, что и OpenVPN и AdGuard VPN в режиме Wintun пользуются одним драйвером `wintun.sys`. OpenVPN используют модифицированную библиотеку, мы - оригинальную `wintun.dll` от WireGuard, в которую вшит драйвер `wintun.sys`. На данный момент наша политика состоит в том, что мы не модифицируем библиотеку `wintun.dll`, соответственно и название драйвера, которое в ней зашито, поменять не можем. Однако это могут сделать в OpenVPN, так как они всё равно используют модифицируют код этой библиотеки у себя. Как вариант, вы можете обратиться к ним с тем, чтобы они поменяли имя файла. Мы же со своей стороны возможно будем изменять оригинальную библиотеку, и в рамках этих изменений поменяем и название файла драйвера. Это решит конфликт с OpenVPN.

OpenVPN ответили следующее:
"

    The author of wintun has requested to only ship the binaries of wintun that he builds himself and use the installation way that the current binaries have builtin. We respect his intents and have never updated to the newer versions of wintun as consequence. Instead we are focusing on ovpn-dco-win for windows.

    Our wintun driver is not patched or modifed. Where did you get the idea that we are patching it? It is just an older version/last version before breaking changes in upstream. The observed behaviour of deleting all wintun interfaces is by design by the newer wintun driver version/dll.

    From my understanding, the license of the new version also only allows using the wintun driver only if you use the signed binaries. So that means that you cannot build the wintun driver yourself and use/distribute OpenVPN with a driver that is built from soure as GPL is incompatible with Apache2 license that is used by OpenSSL in OpenVPN. OpenVPN itself has an exception for this."
Т.е их библиотека не патченная, а оригинальная от разработчика Wireguard.

**Comment by ameshkov** [comment]
Это проблема, код wintun распространяется под GPLv2 (в отличие от DLL и драйвера) и патчить так просто мы ее не можем, лицензия накладывает ограничения.

**Comment by shamarin** [comment]
> Это проблема, код wintun распространяется под GPLv2 (в отличие от DLL и драйвера) и патчить так просто мы ее не можем, лицензия накладывает ограничения.

Понимаю. Тогда может быть есть смысл что-то своё для ускорения придумать на базе открытой части того же Wireguard? OpenVPN сейчас предлагает ovpn-dco ( OpenVPN Data Channel Offload) для ускорения трафика VPN.

**Comment by shamarin** [comment]
У Wireguard еще появился проект WireGuardNT, где большая часть всего перенесена в ядро WindowsNT. Может его на перспективу использовать? Тем более там ускорение многих операций по работе с трафиком и криптографией.

**Comment by ameshkov** [comment]
Да, но придумывание своего это приличная такая задача по времени:)
