### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by acornsoft** [AdguardTeam/AdGuardVPNForWindows#662]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.2.4

### Operating mode

VPN

### Environment

```markdown
Windows 10, AdGuard and AdGuard VPN
```

### Issue Details

Steps to reproduce:
1. Trying to Connect to AdGuard VPN servers
2. Disconnected
3. There are no locations
4.

### Expected Behavior

Unable to run purchased software

### Actual Behavior

Can't connect to Server

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/3299918/f5da1d44-52a0-4acc-a30f-3d92d62fd056)
![image](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/3299918/c993528d-ba65-40d6-bdcf-8119e41bd8c7)

</details>

**Comment by KolbasovAnton** [comment]
@acornsoft Greetings! Please, try our latest [beta](https://github.com/AdguardTeam/AdGuardVPNForWindows/releases/download/v2.3.0-beta-2/AdGuardVpn-2.3-Beta-2-.1346.exe) or [nightly](https://static.adtidy.net/windows/nightly/installer-2.3.1373.0.exe) version. The problem still exists on them?
