### ISSUE TITLE
After system restart my IPv6 routers remain from Adguard

### ISSUE THREAD

**Issue by shamarin** [AdguardTeam/AdGuardVPNForWindows#664]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.3 beta

### Operating mode

VPN

### Environment

```markdown
- OS: Windows 11 Pro x64
- Other network-level software: Kaspersky Plus
```

### Issue Details

Steps to reproduce:
1. Connected to Adguard VPN server Germany Franfurt
2. Restarted my system
3. All my IPv6 routes remains the same from Adguard VPN (Adguard VPN is disconnected)

### Expected Behavior

IPv6 routes must be from my ISP provider

### Actual Behavior

IPv6 routes (addresses) are from Adguard VPN even if it disconnected, but my network addapter showing IP6 addresses from my ISP provider. So now i can't access sites via IPv6 because Adguard IPv6 IP's are not available. Uninstall Adguard without saving any settings and situation is the same even after system restart.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by shamarin** [comment]
Can't get access to sites via IPv6 (Windows says that resource is not available via tracert -6 command) and also with Adguard connected there is no access via IPv6 (no response from sites via tracert -6 command). My ISP provider supports access via IPv6 and my router and Windows network adapter get it.

**Comment by shamarin** [comment]
Seams that this is a problem of my router new FW.

**Comment by shamarin** [comment]
And Adguard at this situation seams that it getting IPv6 routes throur 4to6 service at this case.

**Comment by KolbasovAnton** [comment]
@shamarin Greetings! Yesterday we released the [new version of AG VPN](https://github.com/AdguardTeam/AdGuardVPNForWindows/releases/tag/v2.3.1).
Is Your problem still relevant in it?

**Comment by shamarin** [comment]
> @shamarin Greetings! Yesterday we released the [new version of AG VPN](https://github.com/AdguardTeam/AdGuardVPNForWindows/releases/tag/v2.3.1). Is Your problem still relevant in it?

Not actual, the broblem was with the FW of my router and now it is solved. We can close this issue.
But #661 issue is actual, logs sended by me, but no response from your side.
