### ISSUE TITLE
Adguard VPN not functioning

### ISSUE THREAD

**Issue by brf9717** [AdguardTeam/AdGuardVPNForWindows#668]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

can not verify

### Operating mode

VPN

### Environment

```markdown
- OS:
- Other network-level software:
```

### Issue Details

Steps to reproduce:
1. For past few days I cannot use my Adguard VPN
2. All I get is a block stating "Unknown Error"
3.

### Expected Behavior

Adguard VPN is not working and I cannot get any information to fix it.

### Actual Behavior

I wish I knew what is happening.  What is the "UNKNOWN ERROR"?

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by KolbasovAnton** [comment]
@brf9717 Greetings! First of all, try such actions:
1. Reinstall the app.
2. Install latest version of AG VPN ([nightly](https://static.adtidy.net/windows/nightly/installer-2.3.1403.0.exe), [beta](https://github.com/AdguardTeam/AdGuardVPNForWindows/releases/download/v2.3.0-beta-2/AdGuardVpn-2.3-Beta-2-.1346.exe) or [RC](https://github.com/AdguardTeam/AdGuardVPNForWindows/releases/download/v2.3.0-rc/AdGuardVpn-2.3.0-RC-.1390.exe)).

If it didn't help, please, answer the following questions:
1. Which AG VPN You have? Check "**Settings**" -> "**About**". If AG won't start, You can still recognize it by clicking with right mouse button on AG VPN shortcut (**Properties** -> **Details**) at the directory where You have installed it.
2. Which OS You have?

**Comment by KolbasovAnton** [comment]
@brf9717 Sorry for inconveniences, errors like this happens sometimes.
