### ISSUE TITLE
Random disconnection issue: Can't connect to server

### ISSUE THREAD

**Issue by mahara** [AdguardTeam/AdGuardVPNForWindows#671]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.3.0 (1400)

### Operating mode

VPN

### Environment

```markdown
- OS: Windows 11 23H2
- Other network-level software: AdGuard (7.17.1 (4709)), ESET Internet Security (17.1.11.0)
```

### Issue Details

Steps to reproduce:
1. Just connect to any nearest VPN server
2. After several hours, the VPN connection got randomly disrupted with error message "Can't connect to server"

### Expected Behavior

A robust and stable VPN connection without random disconnection issue, as there's no underlying internet connection issue.

Even if any internet connection issue occurs, the AdGuard VPN service should automatically reconnect.

### Actual Behavior

Random disconnection issue occurs with just "Can't connect to server" error message.

And there's no clear message in the UI describing why the VPN connection got disconnected.

This additionally also causes DNS resolving issue.

### Screenshots

<details>
<summary>Screenshot 1:</summary>

![Screenshot 2024-05-09 190251](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/238332/a374abb0-0c16-4d9c-b777-339dc4b2e62a)

![Screenshot 2024-05-09 190311](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/238332/e062bdec-2e8f-4b34-becf-464424c05023)

</details>

### Additional Information

Settings

- DNS server = AdGuard DNS DoH HTTP/3 (h3://d.adguard-dns.com/dns-query/xxxxxxxx)
- Use QUIC = On
- Use Wintun = On

**Comment by mahara** [comment]
I also think this has something to do which VPN reconnection strategy/algorithm/etc.

Especially in the case when AdGuard VPN fails to reconnect, it should as at least give a clear description in the UI **WHY** it fails to reconnect.

**Comment by Vitalik93** [comment]
После недавнего обновления тоже стал постоянно отваливаться. До этого все было хорошо...
![Снимок экрана 2024-05-10 094144](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/34383288/e207d021-3d3b-4871-80c4-f640fbfe7ced)

**Comment by mahara** [comment]
Sent the logs from the app.

But this is maybe the interesting and possibly related part:

```
WARNING, AdGuardVpnSvc.exe, Logger, 57, 10.05.2024 19:00:18.170, Backend client exception: cannot invoke GetVpnToken
WARNING, AdGuardVpnSvc.exe, Logger, 57, 10.05.2024 19:00:18.172, Backend client exception "Timed out"(SocketError) has been wrapped
WARNING, AdGuardVpnSvc.exe, Logger, 54, 10.05.2024 19:00:18.175, OS_TUNNEL_WIN protect_with_bind: GetBestRoute2(): The network location cannot be reached. For information about network troubleshooting, see Windows Help
ERROR, AdGuardVpnSvc.exe, gNM3VYbB9YjkM8p5GF4t, 57, 10.05.2024 19:00:18.179, Cannot update vpn token and credential because backend domain is unavailable, error AdGuardVpn.Commons.Backend.Exceptions.BackendDomainUnavailableException: Backend client exception "Timed out"(SocketError) has been wrapped
Source: AdGuardVpn.Service
Stack trace:    at AdGuardVpn.Service.Backend.BackendClientService.sqrbgW4DeDx[Dbfr5xbgEcPiwr71BKWN](Func`1  , String methodName)
   at AdGuardVpn.Service.Backend.BackendClientService.GetVpnToken()
   at AdGuardVpn.Service.Backend.BackendClientService.UpdateVpnToken()
   at AdGuardVpn.Service.Auth.AuthenticationService.xc6FWrDQSf8qkufKGXhO(Object )
   at AdGuardVpn.Service.Auth.AuthenticationService.xeLbHboWfKj()

    Adguard.Vpn.BackendApi.Exceptions.VpnBackendClientException: Timed out
    Source: Adguard.Vpn
    Stack trace:    at Adguard.Vpn.BackendApi.VpnBackendClient.VpnBackendClient.Hhf0vucfl8(RequestCode  , VpnBackendClientResponseStatus  , Object  )
   at Adguard.Vpn.BackendApi.VpnBackendClient.VpnBackendClient.peLSqfZyrCIwmIWpLqx(RequestCode  , VpnBackendClientResponseStatus  , Object )
   at Adguard.Vpn.BackendApi.VpnBackendClient.VpnBackendClient.PerformRequest(RequestCode requestCode, Byte[] request)
   at Adguard.Vpn.BackendApi.Service.BaseApiMediator.R4h0VCy2xk[Xs0Qdb0KA4pj5tM0WN3,v4Xuax0DnlsE8H5t8hU](Xs0Qdb0KA4pj5tM0WN3 qeFvIo03rGURCNHV2yg, String  )
   at Adguard.Vpn.BackendApi.Service.BaseApiMediator.PerformRequestAction[TRequest,TResponse](TRequest request, String methodName)
   at Adguard.Vpn.BackendApi.Service.Impl.ProductsApi.GetVpnProductLicenses()
   at y5DVpBbRyo00o350ONxM.ycEbE69PxTc(Object , y5DVpBbRyo00o350ONxM )
   at AdGuardVpn.Service.Backend.BackendClientService.AbebgPBmhsS()
   at AdGuardVpn.Service.Backend.BackendClientService.sqrbgW4DeDx[Dbfr5xbgEcPiwr71BKWN](Func`1  , String methodName)
```

**Comment by Vitalik93** [comment]
У меня на версии 2.2.5 все хорошо. Похоже все же косяк с последним релизом.

**Comment by mahara** [comment]
> У меня на версии 2.2.5 все хорошо. Похоже все же косяк с последним релизом.

Do you use both QUIC and Wintun options in Advanced Settings?


Actually I'm having much more random disconnection issues along with DNS resolving issue in version 2.2.5.

2.3.0 has been much more stable so far, but maybe there are still some edge cases not handled yet, I presume.

**Comment by Vitalik93** [comment]
> Do you use both QUIC and Wintun options in Advanced Settings?

Нет, не включал эти опции. Почти все настройки по умолчанию.

**Comment by Chaos0xff** [comment]
Было тоже самое, после обновления до версии 2.3 на двух PC. Откатил VPN до 2.2.5 пока все OK.

**Comment by shamarin** [comment]
The same with Wintun on and HTTP/3

**Comment by zubrRB** [comment]
У меня тоже не работает релизная 2.3.0. QUIC задан в настройках, Wintun не используется...

**Comment by adbuker** [comment]
Now we are working hard on it, so we publish a fix as soon it'll be found

**Comment by zubrRB** [comment]
У меня начал подключаться (перестав отключаться) после отключения в настройках опции Использовать QUIC.

**Comment by zubrRB** [comment]
При этом практически при каждом запуске запрашивает купить или продолжить использовать бесплатную версию VPN.

**Comment by vankos** [comment]
Hi! Could you please try this test build: https://uploads.adguard.org/AdGuardVpn-bugfix_monitoring_revert.exe and let me know if it helps?

RU:
Здравствуйте!  Не могли бы обновиться на тестовый билд: https://uploads.adguard.org/AdGuardVpn-bugfix_monitoring_revert.exe и отписаться помогло ли это или нет?

**Comment by Chaos0xff** [comment]
> Hi! Could you please try this test build: https://uploads.adguard.org/AdGuardVpn-bugfix_monitoring_revert.exe and let me know if it helps?

Не помогло, то же самое
![01](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/169487119/b5f8f4da-3072-4b91-8e87-eb65046323c6)

**Comment by Chaos0xff** [comment]
Так же долго с глюками обновляется список серверов, и вот в таком стиле
### ![001](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/169487119/d8932501-c60c-4bc4-97be-87aeef982b70)

**Comment by mahara** [comment]
> Не помогло, то же самое, буквально в течении пол часа

@Chaos0xff and everyone else having the "Unknown error" message, I've encountered that issue as well before.

What I did to solve the issue is by clean uninstalling AdGuard VPN: uninstall AdGuard VPN, tick the checkmark to delete all settings (don't forget to do this), restart Windows, and then install AdGuard VPN back.

A temporary workaround would be by restarting AdGuard VPN service in Service Manager. But I usually have the issue back after restarting Windows.

**Comment by Chaos0xff** [comment]
Снова то же самое., Теперь еще стало периодически выскакивать сообщение, Соединение... отключен/подключен, типа переподключается. 2.2.5 все ровно работает.
Может логи собрать какие нибудь?

**Comment by shamarin** [comment]
У меня пока без разрывов, надо только подольше понаблюдать.

**Comment by vankos** [comment]
@mahara , @Vitalik93 , @Chaos0xff , @shamarin , @zubrRB 
И снова спасибо за помощь, подготовили еще одно потенциальное исправление: https://uploads.adguard.org/AdGuardVpn-bug_AG-32659_4.exe

Thanks for the help, again, we prepared another potential fix: https://uploads.adguard.org/AdGuardVpn-bug_AG-32659_4.exe

**Comment by shamarin** [comment]
С предыдущим у меня даже без подключения к VPN выдало через какое то время, что произошла ошибка.

**Comment by shamarin** [comment]
С новой версией вышибает так же

**Comment by mahara** [comment]
Just installed, still testing and observing. No issue yet so far, but let's see later.

**Comment by mahara** [comment]
OK, now it's not showing any server after I restart Windows.

![Screenshot 2024-05-15 013809](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/238332/a418d51a-a90f-4555-b790-b0c4092d1b56)

**Comment by mahara** [comment]
@vankos Which version is that: https://uploads.adguard.org/AdGuardVpn-bug_AG-32659_4.exe?

It's showing 2.3.0 nightly 30 (1401) on mine.
Does it auto-update to the latest nightly version? I've already disabled auto-update in settings.

**Comment by shamarin** [comment]
In released version 2.3.1 this issue is fixed???

**Comment by vankos** [comment]
@mahara This is a special technical build that will not be published on the nightly channel. It will check for updates on the nightly channel and update to the next nightly version when it becomes available.

To return to the release channel, please reinstall the release build. We have published a new version, 2.3.1, with the fix - https://github.com/AdguardTeam/AdGuardVPNForWindows/releases/tag/v2.3.1 . You can install it and check.

Thanks a lot for helping us.

@shamarin
Yes, in 2.3.1 it should be fixed.

**Comment by shamarin** [comment]
Will try today new build.

**Comment by mahara** [comment]
OK, thanks!

It seems it works more reliable and more robust in 2.3.1 now.
