### ISSUE TITLE
The download speed of torrents slows down significantly when using AdGuard VPN

### ISSUE THREAD

**Issue by davele739** [AdguardTeam/AdGuardVPNForWindows#677]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.3.1 RC and 2.3.1 (Stable)

### Environment

```markdown
- OS: Windows 11, 23H2 (OS build 22631.3593)
- Other network-level software: AdGuard ad blocker
```

### Which DNS server do you use?

AdGuard DNS

### Custom DNS

quic://4d21975e.d.adguard-dns.com

### Use Wintun

- [ ] yes, I do

### Issue Details

Steps to reproduce:
1. Torrent with a torrent client
2. Check speeds and connection to trackers
3.

### Expected Behavior

AdGuard VPN should allow for optimal torrenting speeds and connection to torrent trackers. 

### Actual Behavior

Torrenting speeds have become consistently slow since the recent update, and sometimes, I cannot connect to torrent trackers at all when using AdGuard VPN. This was not an issue previously, and I am unsure of the cause.

### Screenshots

<details><summary>Screenshot 1</summary>

 
![Screenshot 2024-05-26 192455](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/62356159/3823d6ac-f6bb-4255-9d70-b65d46cf04e8)
![Screenshot 2024-05-26 192250](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/62356159/8aa6d70f-bb7a-4cc7-a95e-c18713b5969f)

</details>

### Additional Information

The "Use QUIC" setting in AdGuard VPN does not affect the issue,regardless of whether it is enabled or disabled. WinTUN is  disabled due to a previously reported IP leak issue. While torrenting functions correctly with WinTUN enabled, this exposes my actual IP address to the torrent tracker, defeating the purpose of using a VPN. Disabling or exiting AdGuard adblocker does not resolve the issue either. Please investigate and resolve this issue promptly.

**Comment by davele739** [comment]
Unfortunately, this doesn't seem to be a bug. AdGuard acquired a new server to handle torrent traffic, but the new server doesn't actually support it. Their previous server, located in Ukraine, worked perfectly, but their new server in the Netherlands does not allow P2P traffic it seems.

**Comment by Aydinv13** [comment]
@davele739 Hi and sorry for a huge delay.

We had some issues with the speed of torrents. Could check it out now?

**Comment by davele739** [comment]
Works perfectly, thanks! Another issue I've discovered is that enabling the "Use QUIC" option in AdGuard VPN limits torrenting speeds to around 3 Mbps. Disabling this option restores normal torrenting speeds.

**Comment by Aydinv13** [comment]
>Works perfectly

We're glad to hear that, thank you for the feedback.

>enabling the "Use QUIC" option in AdGuard VPN limits torrenting speeds to around 3 Mbps

We'll see what we can do about that later, thanks for noticing. At the moment, the speed is decent anyway.

I'm closing the issue as completed.
