### ISSUE TITLE
X button is in the incorrect position

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNForWindows#683]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.4.0 nightly 3

### Environment

```markdown
- OS: Windows 11
```

### Which DNS server do you use?

Default

### Use Wintun

- [ ] yes, I do

### Issue Details

Steps to reproduce:
1. While adding Exclusions, for apps and websites.
2. While adding custom DNS server).
3. While switching to SOCKS5 operating mode.
4. While adding IP subnet.
5. Check Diagnostic data.

### Expected Behavior

The X button to close warning windows should be at the top right.

### Actual Behavior

The X button is at the top left for all waning windows.

### Screenshots

<details><summary>Exclusions:</summary>

![image](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/35523759/b210e800-ce56-43b9-aa40-35c37e8e8c06)
</details>

<details><summary>Custom DNS server:</summary>

![image](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/35523759/7e076272-5859-4fb8-8c92-3a8514a55047)
</details>

<details><summary>SOCKS5 operating mode:</summary>

![image](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/35523759/7eeb77c2-f0d9-4b85-a232-bb3204b28614)
</details>

<details><summary>IP subnet</summary>

![image](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/35523759/f5190c33-b12a-4d19-ad16-91c7d91eb30d)
</details>

<details><summary>Diagnostic data:</summary>

![image](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/35523759/a2088281-7023-479d-b03f-ffb2a375f006)
</details>

**Comment by Aydinv13** [comment]
@gork7777 Hello.

It's a known bunch of UI bugs, thanks for reporting. Will be fixed in the near future.

**Comment by gork7777** [comment]
Fixed in 2.4.0 nightly 4.
