### ISSUE TITLE
Pen shifts downwards in the Exclusions

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNForWindows#684]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.4.0 nightly 3

### Environment

```markdown
- OS: Windows 11
```

### Which DNS server do you use?

Default

### Use Wintun

- [ ] yes, I do

### Issue Details

Steps to reproduce:
1. Go to Exclusions and select app or website (same for both field)

### Expected Behavior

The pen shouldn't be shift downwards, should be next to the texts.

### Actual Behavior

- For website: `Selectively` the pen next to the text shifts downwards.
- For apps: `Everywhere` the pen next to the text shifts downwards.

### Screenshots

<details><summary>English:</summary>

https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/35523759/aff3304b-672b-4887-9ed7-a994d6c8b9b9
</details>

<details><summary>Turkish:</summary>

https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/35523759/576a9276-f24e-4d1c-ba21-8b9060c02c43
</details>

**Comment by KolbasovAnton** [comment]
@gork7777 Greetings! Thank You for reporting, will be fixed in the upcoming versions.

**Comment by gork7777** [comment]
@KolbasovAnton Hi! In the new update, the ‘Info’ icon also shifts downwards when the VPN is running on the selected ones in both apps and websites in the exclusions.

<details><summary>Video:</summary>

https://github.com/user-attachments/assets/d7d54fe4-fb68-4135-8c10-4e6cda667bea
</details>

**Comment by gork7777** [comment]
Looks like fixed in the nightly.
