### ISSUE TITLE
Servers shifts to the right

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNForWindows#685]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.4.0 nightly 3

### Environment

```markdown
- OS: Windows 11
```

### Which DNS server do you use?

Default

### Use Wintun

- [ ] yes, I do

### Issue Details

Steps to reproduce:
1. Go to the Exclusions -> Apps -> Add app and open the `Add app` window.
2. Go to the home tab and look at the servers.

### Expected Behavior

Servers shouldn't be shift to the right when you open the `Add app` window.

### Actual Behavior

When you open the Add app window, the servers shifts to the right at the home tab. You need to restart the VPN app to solve this.

### Screenshots

<details><summary>Servers</summary>

https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/35523759/29ed4cd8-18ef-45d4-b70a-cdf0f5fb0985
</details>

**Comment by gork7777** [comment]
Looks like fixed in 2.4.0 nightly 4.

**Comment by AlexandrPkhm** [comment]
@gork7777 

Thank you for letting us know. Indeed, a server view was reworked in the latest nightly and the issue was fixed.
