### ISSUE TITLE
Rectangular message visible in dark theme

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNForWindows#686]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.4.0 nightly 3

### Environment

```markdown
- OS: Windows 11
```

### Which DNS server do you use?

Default

### Use Wintun

- [ ] yes, I do

### Issue Details

Steps to reproduce:
1. While adding new website or app and deleting website or app

### Expected Behavior

The rectangular message should be visible in dark theme like in the light theme.

### Actual Behavior

When adding and deleting websites or apps in Exclusions tab, the following rectangular message is not visible in dark theme but visible in light theme.

### Screenshots

<details><summary>Dark theme</summary>

![dark](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/35523759/19350aea-dad5-4819-9238-150e5d76018a)
</details>

<details><summary>Light theme</summary>

![light](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/35523759/ef58bc7a-f6f1-4f6c-b6ea-7cc5df3b9c92)
</details>

**Comment by KolbasovAnton** [comment]
@gork7777 Thanks for Your remarks. Our design team will take care of it.

**Comment by gork7777** [comment]
Looks like fixed in the nightly.
