### ISSUE TITLE
IP address blocked Poland

### ISSUE THREAD

**Issue by zubrRB** [AdguardTeam/AdGuardVPNForWindows#688]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.3.1

### Environment

```markdown
OS: Windows 7
```

### Which DNS server do you use?

Default

### Use Wintun

- [ ] yes, I do

### Issue Details

1. Задать локацию Польши.
2. Зайти для просмотра HTML5. https://belsat.eu/ru/programs/07-06-2024-rossiya-eto-bezumnyj-tramvaj-bez-tormozov 

### Expected Behavior

Видео доступно для просмотра при выбранной локации — Польша.

### Actual Behavior

Access Denied - Sucuri Website Firewall

### Screenshots

<details><summary>Screenshots</summary>

![1](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/50718960/9304f333-704e-4518-8ab7-a436243eb156)
![2](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/50718960/0dd8592f-561e-4fed-8cd9-bbe342e53031)
</details>

### Additional Information

На сайте польского телеканала для некоторых видео установлена геоблокировка, просмотр возможен с ip-адреса Польши.

**Comment by KolbasovAnton** [comment]
Добрый день, установите последнюю [найтли-](https://static.adtidy.net/windows/nightly/installer-2.4.1442.0.exe) или [бета-версию](https://github.com/AdguardTeam/AdGuardVPNForWindows/releases/tag/v2.4.0-beta-2) AG VPN и отключите сторонние приложения и антивирусы.

**Comment by zubrRB** [comment]
С другими локациями это проблемы с блокировкой Firewall нет, но с ними и не отдаёт видео. C польской локацией и серверами того же провайдера в другом VPN тоже блокировки не произошло и удалось получить доступ к видео.

**Comment by zubrRB** [comment]
С другими локациями этой проблемы с блокировкой Firewall нет, но с ними и не отдаёт видео. С польской локацией и серверами от того же провайдера в другом VPN тоже блокировки не произошло и удалось получить доступ к видео.

**Comment by KolbasovAnton** [comment]
@zubrRB в итоге, проблема повторяется на последних версиях приложения?
Если да, пожалуйста, воспроизведите её со включенным расширенным логированием, архив логов отправьте нам на devteam@adguard.com, в заголовке указав номер 688, а в теле письма - точное время воспроизведения. Заранее спасибо.

**Comment by zubrRB** [comment]
Я так понимаю, что проблема в конкретном ip-адресе, который даже спустя три недели не меняется при подключении.

**Comment by KolbasovAnton** [comment]
Проверим, нужны логи.

**Comment by zubrRB** [comment]
Отправил логи c `2.4 beta 3`, с которой всё то же самое.

**Comment by Aydinv13** [comment]
@zubrRB похоже, что на сайте технические проблемы?

**Comment by zubrRB** [comment]
«Опять власть меняется!» (с) https://nashaniva.com/ru/348363

**Comment by Aydinv13** [comment]
В таком случае данную задачу закрываю.

**Comment by zubrRB** [comment]
Сайт снова стал доступен, но он уже выглядит иначе.
