### ISSUE TITLE
With Wintun CPU usage of the app is very high

### ISSUE THREAD

**Issue by shamarin** [AdguardTeam/AdGuardVPNForWindows#693]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.4 beta 2

### Environment

```markdown
- OS:22635.3785
- Other network-level software:
```

### Which DNS server do you use?

Default

### Use Wintun

- [X] yes, I do

### Issue Details

Steps to reproduce:
1. Enable Wintun in settings
2. Load bittorrent client with active torrents (load and upload) so that they use traffic at current time
3. Connect to any VPN server with Adguard VPN app
4. Load to different web resources with video (Youtube, Vimeo or etc)

### Expected Behavior

CPU usage must be low (15-20% is normal)

### Actual Behavior

CPU usage after some time will be 70-85%. It's too high. Sometimes it will be 50-60% even just after the connection to any VPN server. 

### Screenshots

<details><summary>Screenshot 1</summary>
![изображение](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/24771090/ce424a0d-5c7b-4fa9-95fa-342cc09d5dd9)

</details>

### Additional Information

Torrent at the same time is working, but it's in exaptions.

**Comment by shamarin** [comment]
<img width="673" alt="Снимок экрана 2024-06-15 105630" src="https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/24771090/f023b090-b760-457d-b749-59ab5b35aaf3">

**Comment by shamarin** [comment]
Link to the logs [link removed for privacy purposes]
Reproduced today at 21:35 - 21:39 Moscow time.

**Comment by shamarin** [comment]
Seams that the problem is in Wintun buffer.

**Comment by shamarin** [comment]
And after some time (about 5-10 minutes) any web resource will be anavailable. Soo Adguard VPN loose connection.

**Comment by shamarin** [comment]
Torrent client added to exclusions
![изображение](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/24771090/e472cb29-77e8-4fbd-b149-fed78f681dc1)

**Comment by shamarin** [comment]
If Wintun use is off in settings then it's ok. CPU usage by the app is normal and no loss of the connection. It's a bug.

**Comment by shamarin** [comment]
Похоже что еще приложение не правильно как-то отрабатывает исключение торрент клиента, так как если для qbittorrent убрать исключение, то нагрузка пониже идет на процессор, но зато трафик не весь в статистике отображает приложения Adguard. Видимо какой-то трафик идет в таком случае через VPN, а какой-то напрямую.

**Comment by shamarin** [comment]
Но всё равно аномалия есть, когда Wintun включен и запущен торрент клиент с активными раздачами.

**Comment by zalupakonya** [comment]
лол, я с этим багом 3 года сижу, написывая в техпо, удачи чел, разрабам плевать, ты занес бабки, дальше не их дело.

**Comment by shamarin** [comment]
> лол, я с этим багом 3 года сижу, написывая в техпо, удачи чел, разрабам плевать, ты занес бабки, дальше не их дело.

Пока что баги исправляют, критические оперативно. Видно что продукт допиливают и улучшают.

**Comment by northis** [comment]
@shamarin Воспроизвели у себя, разберёмся.

**Comment by shamarin** [comment]
> @shamarin Воспроизвели у себя, разберёмся.

Спасибо!

**Comment by shamarin** [comment]
Заметил, что если статистику отключить в приложении, то использование ресурсов процессора становится меньше, вылетов нет в соединении. Но в целом все равно использование ресурсов процессора порой высокое даже при этом.

**Comment by shamarin** [comment]
Когда примерно можно ожидать исправления?

**Comment by adbuker** [comment]
@shamarin, в релиз 2.4, к сожалению, не войдёт, но в рамках найтли версий 2.5 будем делать в приоритетном порядке. Если коротко, то втечение месяца

**Comment by shamarin** [comment]
> @shamarin, в релиз 2.4, к сожалению, не войдёт, но в рамках найтли версий 2.5 будем делать в приоритетном порядке. Если коротко, то втечение месяца

Отлично, на ночной сборке как раз сижу пока что.

**Comment by shamarin** [comment]
И еще подметил, что когда торрент клиент работает активно по трафику, то скорость VPN соединения сильно падает, проседает до нескольких мегабит, хотя у торрент клиента ограничения выставлены по максимальной загрузке интернет канала. С тем же Касперским проблем нет, сколько у канала остается ширина (в моем случае 20 Мбит где-то), то он всю полосу использует, у Adguard же сильно прям проседает. Видимо нужно приоритет соединения у вас верно выставлять. Посмотрите на эту особенность тоже, потому что проседает прям катастрофически, что тот же Youtube не возможно смотреть и сайты медленно открываются. С Касперсим в таких же условиях проблем не наблюдается.

**Comment by shamarin** [comment]
Что-то новое слышно насчет исправления?

**Comment by adbuker** [comment]
@shamarin , пока еще не пофиксили, но ряд улучшений в работе wintun есть в недавно выпущенном релизе 2.4

**Comment by shamarin** [comment]
> @shamarin , пока еще не пофиксили, но ряд улучшений в работе wintun есть в недавно выпущенном релизе 2.4

В последней ночной сборке?

**Comment by adbuker** [comment]
@shamarin, можете поставить ночную, но и релиз 2.4 выпустили не так давно

**Comment by shamarin** [comment]
> @shamarin, можете поставить ночную, но и релиз 2.4 выпустили не так давно

Уже на ночной сижу давно, так как жду исправления данной ошибки. Вроде в течении месяца обещали, но пока до сих пор нет исправления.

**Comment by shamarin** [comment]
@adbuker что-то новое слышно насчет исправления? вообще планируется исправление или нет? уже месяц прошел, в ночной сборке так и нет исправления.

**Comment by adbuker** [comment]
@shamarin , прошу прощения за слишком оптимистичную оценку, данную мною выше. Исправление конечно же планируется, точной даты вам назвать сейчас не смогу, к сожалению

**Comment by shamarin** [comment]
> @shamarin , прошу прощения за слишком оптимистичную оценку, данную мною выше. Исправление конечно же планируется, точной даты вам назвать сейчас не смогу, к сожалению

Похоже что еще не скоро.

**Comment by shamarin** [comment]
> @shamarin , прошу прощения за слишком оптимистичную оценку, данную мною выше. Исправление конечно же планируется, точной даты вам назвать сейчас не смогу, к сожалению

В октябре хотя бы можно ожидать исправление?

**Comment by adbuker** [comment]
@shamarin , постараемся

**Comment by shamarin** [comment]
Смотрю уже судя по смене статуса процесс пошел. В ближайшее время планируется выпуск обновления с исправлением?

**Comment by northis** [comment]
@shamarin да, вы правы. У нас есть тестовый билд, который мы бы хотели проверить у вас https://uploads.adguard.org/AdGuardVpn-v2.4.1589.11.exe 
Посмотрите, пожалуйста.

**Comment by shamarin** [comment]
> @shamarin да, вы правы. У нас есть тестовый билд, который мы бы хотели проверить у вас https://uploads.adguard.org/AdGuardVpn-v2.4.1589.11.exe Посмотрите, пожалуйста.

Проверю сегодня вечером после работы. Отпишусь по результатам.

**Comment by shamarin** [comment]
> @shamarin да, вы правы. У нас есть тестовый билд, который мы бы хотели проверить у вас https://uploads.adguard.org/AdGuardVpn-v2.4.1589.11.exe Посмотрите, пожалуйста.

@northis Лучше стало, но всё равно еще нагрузка на процессор высокая. Максимальная в районе 40-50%, особенно это заметно если сначала подключиться к серверу VPN, когда qBittorrent не запущен еще. Потом запустить qBittorrent клиент, добавить в него побольше одновременных торрент раздач (я добавлял 54 одновременно), плюс огромное количество не принудительно на раздаче из прошлых висит. Тогда нагрузка высокая становится на процессор и приложение в диспетчере задач отображает что трафик интернет активно потребляет 30-50 Мбит, хотя торрент клиент в исключения добавлен. Если отключится в этот момент и заново подключится к тому же серверу, то нагрузка на процессор меньше становится.
<img width="1087" alt="Снимок экрана 2024-10-18 175152" src="https://github.com/user-attachments/assets/1a2f2324-b33b-417a-b33d-e19d843c52e1">

**Comment by shamarin** [comment]
Да, у меня максимальный интернет канал 100 Мбит по тарифу и физический, подключение ПК проводное к маршрутизатору Keenetic Peak. По Wi-Fi заметил что вообще в плане скорости Adguard на всех моих ПК и ноутубках работает шустро в плане скорости. В торрент клиенте ограничение стоит в 70-75 Мбит на раздачу и на прием.

**Comment by shamarin** [comment]
И спустя пару минут использования скорость VPN соединения с 20 Мбит падает до 3-4 Мбит по данным speedtest (от сервера Дания до Ростелеком Ярославль измеряю)

**Comment by shamarin** [comment]
Даже до 60-70% доходит. В общем еще улучшать нужно.

**Comment by shamarin** [comment]
Логи снял  https://cloud.mail.ru/public/Wm4h/XjNrwT27g (время воспроизведения проблемы с 18:04-18:09)

**Comment by shamarin** [comment]
![Screenshot 2024-10-18 at 18-05-38 Speedtest by Ookla - The Global Broadband Speed Test](https://github.com/user-attachments/assets/10e081d7-8243-4f63-8174-620cf416299c)

**Comment by shamarin** [comment]
Печально как-то, с июля исправить все никак не можете. Похоже, что и в октябре не исправлена ошибка будет. Что-то слишком много ошибок в приложении, вот и подумаешь, а стоит ли лицензию продлевать.

**Comment by shamarin** [comment]
С Wintun скорость очень низкая на загрузку, на Ютуб если отключить QUIC скорость совсем низкая (2-4 Мбит) даже без работающего торрент клиента. Описал здесь подробно AdguardTeam/AdGuardVPNForWindows#726

**Comment by shamarin** [comment]
@northis почему в командной строке Windows не отображается трассировка до какого нибудь адреса (например, yandex.ru) хоть с Wintun хоть без него? это норма или нет? с другими VPN сервисами трассировку отображает. А тут:
```
tracert -6 yandex.ru

Трассировка маршрута к yandex.ru [2a02:6b8:a::a]
с максимальным числом прыжков 30:

  1     *        *        *     Превышен интервал ожидания для запроса.
  2     *        *        *     Превышен интервал ожидания для запроса.
  3     *        *        *     Превышен интервал ожидания для запроса.
  4     *        *        *     Превышен интервал ожидания для запроса.
  5     *        *        *     Превышен интервал ожидания для запроса.
  6     *        *        *     Превышен интервал ожидания для запроса.
  7     *        *        *     Превышен интервал ожидания для запроса.
  8     *        *        *     Превышен интервал ожидания для запроса.
  9    92 ms    89 ms    88 ms  yandex.ru [2a02:6b8:a::a]
```
```
tracert yandex.ru

Трассировка маршрута к yandex.ru [5.255.255.77]
с максимальным числом прыжков 30:

  1     *        *        *     Превышен интервал ожидания для запроса.
  2     *        *        *     Превышен интервал ожидания для запроса.
  3     *        *        *     Превышен интервал ожидания для запроса.
  4     *        *        *     Превышен интервал ожидания для запроса.
  5     *        *        *     Превышен интервал ожидания для запроса.
  6     *        *        *     Превышен интервал ожидания для запроса.
  7     *        *        *     Превышен интервал ожидания для запроса.
  8     *        *        *     Превышен интервал ожидания для запроса.
  9     *        *        *     Превышен интервал ожидания для запроса.
 10    91 ms    99 ms   105 ms  yandex.ru [5.255.255.77]
```

**Comment by shamarin** [comment]
С тестовой версией максимум до 60-70% загрузка процессора доходит.
Успел поймать момент
![изображение](https://github.com/user-attachments/assets/b478a62e-5737-4fef-9371-a08bfa77690c)

**Comment by shamarin** [comment]
Получается проблема существует еще.

**Comment by shamarin** [comment]
И почему-то хоть торрент клиент и в исключениях, но в самом начале раздачи для Adguard диспетчер задач показывает что трафик идет в районе 50-60 Мбит, хотя в тот момент трафик в системе потребляет только торрент клиент. Такое ощущение что часть трафика идет всё же через VPN, лтбо моё предположение что что-то типа мультикаст шторма происходит.

**Comment by shamarin** [comment]
![изображение](https://github.com/user-attachments/assets/f403a287-ff61-4e9b-91f3-76c6730e82af)

**Comment by shamarin** [comment]
Если торрент клиент убрать из исключений, то картина не лучше и судя по диспетчеру трафик идет всё равно не через VPN.

**Comment by shamarin** [comment]
Если Wintun отключить и торрент клиент убрать из исключений, то тогда скорость высокая и в торрент клиенте и на остальных ресурсах

**Comment by shamarin** [comment]
![изображение](https://github.com/user-attachments/assets/17dd44ce-9de0-4195-9508-6cb1d1b075be)

**Comment by shamarin** [comment]
![изображение](https://github.com/user-attachments/assets/baeef570-f988-4704-9a13-dcaab5428fb4)

**Comment by shamarin** [comment]
![изображение](https://github.com/user-attachments/assets/4180204c-ef7e-478b-91bd-13759f64a070)

**Comment by shamarin** [comment]
![изображение](https://github.com/user-attachments/assets/5957f7cf-99e0-4a2d-a1cc-118262d84abd)

**Comment by shamarin** [comment]
![изображение](https://github.com/user-attachments/assets/858910c7-0d61-44a1-becf-247457d77713)

**Comment by shamarin** [comment]
В статистике данных о торрент клиенте как потребителе трафика информация отсутствует. Значит трафик идет напрямую.

**Comment by shamarin** [comment]
Высокая скорость на других ресурсах сохраняется максимум пару минут и потом опять в районе 4-5 Мбит максимум становится. Торрент клиент при этом на максималках скорость (70 Мбит).

**Comment by shamarin** [comment]
Спустя очень большое время в статистике qbittorrent появился, но там всего в районе 160 МБ данных в оба направления, хотя за это время пару гигабайт должно быть. В общем странно работает пропуск трафика от торрент клиентов.

**Comment by shamarin** [comment]
Если торрент клиент убрать из исключений, то и без Wintun иногда загрузка до больших значений доходит на короткое время.
![изображение](https://github.com/user-attachments/assets/2563c86d-0c2f-414e-a554-4dfae38c1ca8)

**Comment by shamarin** [comment]
@vankos  @northis  Не понятно мне почему статус выставили в Решено, если проблема сохраняется?

**Comment by shamarin** [comment]
Сегодня вышло обновление 2.4.1 nightly 4. С Wintun исправлено, скорость в начале подольше стала держаться высокая. Потом спустя минут 5-10 низка становится. Использую Wintun и QUIC, на раздаче 14 активных торрентов.
Сначала подключаюсь к VPN потом запускаю торрент клиент. В начале еще особенность - диспетчер задач Windows показывает что Adguard VPN использует активно сеть (60-70 Мбит), но при этом торрент клиент в исключениях и других источников обращения к сети в данный момент нет. Вот когда спустя время в диспетчере уже перестает показывает это, то тогда скорость VPN соединения низкая становится.

**Comment by shamarin** [comment]
@northis С включенным QUIC спустя короткое время теряет соединение полностью, т.е ни на один ресурс не зайти и отклик (задержка) дикого высокий становится. И периодически загрузка все равно высокая становится, особенно с выключенным QUIC. В общем какая-то проблема с маршрутизацией трафика совместно в торрент клиентом есть, т.е когда пиринговая сеть есть. Если торрент клиент убрать из исключений, то трафик все равно не через VPN идет.

**Comment by shamarin** [comment]
Может лучше реализовать поддержку Wireguard на альтернативных и более современных решениях - https://github.com/cloudflare/boringtun или https://git.zx2c4.com/wireguard-nt/about/ в режиме kernel. Судя по всему там производительность выше.

**Comment by shamarin** [comment]
<img width="1039" alt="Снимок экрана 2024-11-01 223033" src="https://github.com/user-attachments/assets/7a36e8a0-e6b2-404f-b60d-502118bfb426">
HTTP/2 и Wintun. Последняя ночная сборка. Проблема не устранена.

**Comment by shamarin** [comment]
@KolbasovAnton мне не понятно только поведение исключения трафика торрент клиента Adguard VPN.
Путь воспроизведения проблемы:
1. Подключиться к любой локации Adguard VPN
2. Торрент клиент не запущен, другие потребители трафика тоже не активны. Убедиться в этом через диспетчер задач Windows посмотрев напротив запущенного приложения Adguard VPN. Оно трафик не потребляет. 
3. Запустить торрент клиент с активными раздачами.
4. Как только торрент клиент начинает использовать сеть, то хоть оно и в исключениях Adguard, то Adgurad VPN потреблять трафик начинает порядка 40 Мбит, иногда больше.
Может в этом и причина что c включенным Wintun потребление системных ресурсов (процессора) приложением становится огромным и плюс скорость соединения (хоть и должна быть полоса порядка 40 Мбит доступна, так как для торрент клиента сделано ограничение в 60 Мбит максимум и ограничение по служебному трафику и по трафику UDP тоже и для локальных пиров) становится рекордно низкой, что с Wintun, что без него (WFP драйвер).

Скриншот без запущенного торрент клиента:
<img width="1109" alt="Снимок экрана 2024-11-04 171739" src="https://github.com/user-attachments/assets/848844a2-edc7-468b-b2b7-3eedeae068ee">
Скриншот с запущенным торрент клиентом, сразу после запуска его:
<img width="1159" alt="Снимок экрана 2024-11-04 171828" src="https://github.com/user-attachments/assets/9bd0f612-858e-4dc5-842f-ce75243896a1">
<img width="716" alt="Снимок экрана 2024-11-04 171916" src="https://github.com/user-attachments/assets/8a918e6d-ccab-4f38-88c1-2e55fcacf35c">
Может по это причине просто тупо канал забивается Adguard VPN не понятно от куда берущимся трафиком и соответственно спустя пару минут скорость соединения резко падает.
Насчет нагрузки на процессор это к задаче AdguardTeam/AdGuardVPNForWindows#693 которая так и не ушла с последней ночной сборкой.
Скриншоты приводил с версии 2.4.1 nightly 4. Локация Финляндия, проверял еще на Германия (Франкфурт) и Дания, QUIC отключен, так как с ним соединение совсем рвется, приложение отображает, что соединение есть, а если на любой сайт зайти попытаться, то выдает ошибку соединения. В торрент клиенте запущено 12 раздач активных. Такой эффект возникает когда скорость закачки торрента 50 и выше Мбит, в моем случае когда торрент клиент максимальную свою полосу разрешенную начинает использовать (ограничение в 70 Мбит максимум).
Похоже что с буфером у Adguard VPN какая-то проблема.

**Comment by fdezsergio02** [comment]
I am on Adguard VPN 2.5.0 and this problem keeps happening: I have noticed that when Wintun is enabled and there is no exception added to the VPN, it works correctly. The problem occurs as soon as I add an exception from any page to Adguard VPN, which starts consuming CPU in an uncontrolled way.
![Image](https://github.com/user-attachments/assets/c343a729-3ea6-4ef3-bb5a-ed2a370e3b30)

**Comment by shamarin** [comment]
> I am on Adguard VPN 2.5.0 and this problem keeps happening: I have noticed that when Wintun is enabled and there is no exception added to the VPN, it works correctly. The problem occurs as soon as I add an exception from any page to Adguard VPN, which starts consuming CPU in an uncontrolled way. ![Image](https://github.com/user-attachments/assets/c343a729-3ea6-4ef3-bb5a-ed2a370e3b30)

Maybe to open a new one issue? Seams that devs will not reopen this one.

**Comment by shamarin** [comment]
> I am on Adguard VPN 2.5.0 and this problem keeps happening: I have noticed that when Wintun is enabled and there is no exception added to the VPN, it works correctly. The problem occurs as soon as I add an exception from any page to Adguard VPN, which starts consuming CPU in an uncontrolled way. ![Image](https://github.com/user-attachments/assets/c343a729-3ea6-4ef3-bb5a-ed2a370e3b30)

Got the same on latest nightly version, but CPU became normal after minute from connection event. And at that moment there is no connection if to go to any web site for example.

**Comment by shamarin** [comment]
> I am on Adguard VPN 2.5.0 and this problem keeps happening: I have noticed that when Wintun is enabled and there is no exception added to the VPN, it works correctly. The problem occurs as soon as I add an exception from any page to Adguard VPN, which starts consuming CPU in an uncontrolled way. ![Image](https://github.com/user-attachments/assets/c343a729-3ea6-4ef3-bb5a-ed2a370e3b30)

Created a new issue https://github.com/AdguardTeam/VpnLibs/issues/61 you can add your comments to it.
