### ISSUE TITLE
Malwarebytes detecting Adguard VPN  as Trojan

### ISSUE THREAD

**Issue by IslandApps** [AdguardTeam/AdGuardVPNForWindows#694]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.3.1

### Environment

```markdown
- OS: Win 11
- Other network-level software: Nope

I know this is a false alarm and that it's really their problem and not yours, but I thought I should still  let you know that this popped up today. I was not using VPN and never launched the program.
```

### Which DNS server do you use?

Cloudflare DNS

### Use Wintun

- [ ] yes, I do

### Issue Details

Steps to reproduce:
1. Powered computer on
2. Noticed alert from Malwarebytes Premium

### Actual Behavior

False Alarm - Malwarebytes Premium 

### Screenshots

<details><summary>Screenshot 1</summary>

![Screenshot 2024-06-15 160902](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/108380065/76508029-0dfc-4489-849a-560c0a618c51)

</details>

**Comment by Eugene-Savenko** [comment]
Hello! Thank you for reporting this issue. We are aware of the false positive and are currently working with our suppliers to replace the faulty IP address.
