### ISSUE TITLE
Add support for Xbox One X / One S / Series X / Series S through Microsoft Store

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardVPNForWindows#696]
### Issue Details

I'm in a very specifically narrow situation where Microsoft Store Xbox One/Series support would make perfect sense:

1. My secretary has a subscription to HBO-Discovery Max, which I borrow so I can watch Teen Titans GO and FIA WEC.
2. My smart-TV is (according to Max) too old (2016 LG model) to even be allowed to install Max.
3. Despite Max bragging about 4K on supported devices, they don't like web browsers (Chrome or Firefox) or Telenor Norway's *T-We Boks* set-top boxes very much, which they limit to 720p, which made Le Mans look a little like porridge.
4. Disney+ hates me on a personal level, because they block all publicly known Tor server IPs (of which I run one or two) even at my home in supported countries like Norway.
5. Netflix complains to me about "not being in the correct household" on my LG TV and *T-We Boks* for my secretary's subscription as well. (Web browsers and PS3 can however handle 1080p with no household limits, but not 4K without massive loopholes.)
7. My pa's PlayStation 5 can't handle 50Hz livestreams correctly, resulting in easily noticeable jarring on Max's European simulcasts with Eurosport of sports events, incl. Le Mans. (Xbox consoles have had support for native 50Hz since 2014)
9. I don't really want to buy a Chromecast, Amazon Fire TV, or a new TV, because their remote controls all have "very old people or toddlers" buttons that have Netflix and Prime instant entry buttons, but very often not any normal buttons like Play/Pause or Settings.
10. For me to commit to 130€〜650€ for an Xbox 2016-onwards model (with second-hand prices included in  the calculation) would therefore have required https://github.com/AdguardTeam/AdGuardVPNForWindows to extend support to Microsoft Store.

The request bears similarity to #498, but has an entirely different environment and proposed solution. There are also similarities to https://github.com/AdguardTeam/AdGuardVPNForiOS/issues/369, for which this report is proposed as plan B.

### Proposed solution

https://github.com/AdguardTeam/AdGuardVPNForWindows should be extended to support Xbox One/Series on Microsoft Store.

### Alternative solution

https://apps.apple.com/ie/app/adguard-vpn-unlimited-fast/id1525373602 should be extended to support tvOS, which'd allow me to commit to my only viable plan B (Apple TV 4K 128GB).

As a 3rd option, I would be able to run a proxy from my *AdGuard (VPN) for Windows* paid subscription with some difficulty, but it feels imfeasibly impractical to me, and doesn't feel like something I'd commit to before buying any devices.

**Comment by AlexandrPkhm** [comment]
Hi @DandelionSprout,

Please accept our apologies for the delay in getting back to you. We wanted to let you know that we are already planning on publishing AdGuard VPN in Microsoft store, though the exact timeframe isn't quite set. 

So, the good news is, if regular AdGuard VPN for Windows from the Microsoft store is going to be able to run on Xbox, you'll have no problems using it. But if not, unfortunately, there are no plans to develop a separate AdGuard VPN for Xbox version at this time.
