### ISSUE TITLE
There are no locations 

### ISSUE THREAD

**Issue by Lufan** [AdguardTeam/AdGuardVPNForWindows#698]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

Starting from the 12-06-2024 vpn not works - it shows the message that There are no locations. 
<img width="592" alt="image" src="https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/1502162/951fa8d4-4627-4f0e-8dab-e7585fa64f82">

I am using it from Belarus. 

question - do you stop working with Belarus permanently or not and this issue will be resolved?

**Comment by shamarin** [comment]
What version do you have installed?

**Comment by Lufan** [comment]
version 2.3.1 (1403)
<img width="564" alt="image" src="https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/1502162/e8ff0d61-e2d8-4b14-9dca-0ed888496240">
<img width="292" alt="image" src="https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/1502162/54cf4ecb-40b0-4eaf-a827-b9e9af558a6a">

**Comment by shamarin** [comment]
Try new beta.

**Comment by shamarin** [comment]
https://github.com/AdguardTeam/AdGuardVPNForWindows/releases/download/v2.4.0-beta-2/AdGuardVpn-2.4.0-Beta-2-.1443.exe

**Comment by Lufan** [comment]
beta2 - the same result: There are no locations.

tried to log out -> log in, and for now unable to login on the windows vpn app. It freezing after providing password - already 15 minutes showing progress 
<img width="221" alt="image" src="https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/1502162/118d9fdf-4b56-4384-b4c7-31f0b9a80d12">

still able to login to the browser 
<img width="414" alt="image" src="https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/1502162/14c7a37f-57b9-4453-95d3-23f8a15ec879">

**Comment by zubrRB** [comment]
У меня в бесплатной версии доступен список локаций и они все подключаются. Видимо, это общая проблема с Win 11.

**Comment by shamarin** [comment]
> У меня в бесплатной версии доступен список локаций и они все подключаются. Видимо, это общая проблема с Win 11.

У меня платная и Win 11, локации есть. Пропадают только когда приложение выгрузил и заново запустил. Но стоит нажать обновить и все норм.

**Comment by zubrRB** [comment]
Последние дни жалобы пользователей блокировщика и VPN о проблеме с запуском, отвязкой лицензий — у всех Win 11.

**Comment by Lufan** [comment]
после того как я разлогинился в приложении - теперь не могу залогиниться снова.  

проверил виндовс апдейт - как раз 12, как перестал работать впн, было установлено обновление KB5039212
<img width="604" alt="image" src="https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/1502162/03f91857-16df-4d9e-aa51-6be408af5000">

**Comment by AlexandrPkhm** [comment]
Здравствуйте @Lufan 

Пожалуйста, попробуйте установить последнюю Nigthly версию AdGuard VPN, которая доступна по данной [ссылке](https://agrd.io/windows_vpn_nightly) и проверьте сохранится ли данная проблема.  

В случае, если проблема сохраняется, пожалуйста, запишите логи приложения. Соберите и отправьте указанные файлы, используя данную инструкцию:

1. Зайдите в Настройки -> Настройки приложения -> Расширенные настройки -> Уровень логирования -> **Записывать все**;
2. Воспроизведите проблему и запомните точное время её воспроизведения. Оно понадобится
нам, чтобы найти соответствующие записи в лог-файле;
3. Зайдите в Настройки -> Поддержка -> Выберите **Экспортировать логи и информацию о системе**;
4. Отправьте полученный архив по адресу `devteam@adguard.com`. Также укажите номер задачи в Github и время воспроизведения проблемы.
5. Не забудьте вернуть значение уровня логирования на **Записывать по умолчанию**.

**Comment by Lufan** [comment]
К сожалению не могу зайти в настройки - так как оно останавливается на логине - после ввода пароля.

то же самое происходит с ночной версией. Дополнительно после запуска выскочило сообщение 
<img width="307" alt="image" src="https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/1502162/690f8d74-2d14-4ca2-a65f-c1e967900c91">


Существует ли возможность включить подробные логи без логина и входа в настройки?

**Comment by AlexandrPkhm** [comment]
@Lufan 

Пожалуйста, попробуйте выполнить продвинутое удаление AdGuard VPN с помощью данного [инструмента удаления](https://cdn.adtidy.org/distr/windows/Uninstall_Utility.zip). После этого, вновь установите Nightly версию и сообщите повторяется ли данная проблема.

**Comment by Lufan** [comment]
Проверил на другом ноуте - там то же стоит впн - то же не работает. Я там не разлогинился но логи не создает - после нажатия на кнопку Экспортировать логи и информацию о системе он некоторое время висит потом закрывается. Буду пробовать удалять

**Comment by Lufan** [comment]
применение данной утилиты успеха не принесло - точно так же зависает после ввода пароля;

**Comment by northis** [comment]
@Lufan пожалуйста, запустите `"C:\Program Files\AdGuardVpn\AdGuardVpn.exe" /trace` (это включит трейсовые логи), попробуйте залогиниться, а потом сохраните логи из папки `C:\ProgramData\AdguardVpn\Logs\` и отправьте нам.

**Comment by Lufan** [comment]
Проблема была с конфигурацией ДНС - я использовал на роутере adguard DNS. После того как я его убрал - впн заработал. 

Так что данную ишью можно закрывать к работе впн она не имеет отношения скорее всего

**Comment by AlexandrPkhm** [comment]
@Lufan Проблема, с которой вы столкнулись была связана с недоступностью наших ресурсов в Беларуси. Вчера вечером мы устранили ее и теперь все должно работать нормально. 

С практически полной уверенностью можно сказать, что она заключалась не в конфигурации ДНС. Пожалуйста, попробуйте восстановить ее и проверьте повторится ли проблема с отсутствием локаций. Дайте нам знать о результатах.

**Comment by Lufan** [comment]
да - если включаю на роутере днс адгуард, то не работает впн - не запускается. и пинг не проходит 
```
> Ipconfig /flushdns

Windows IP Configuration

Successfully flushed the DNS Resolver Cache.
> nslookup [domain]
Server:  UnKnown
Address:  192.168.1.1

Non-authoritative answer:
Name:    [domain]
Addresses:  2a06:98c1:3121::3
          2a06:98c1:3120::3
          188.114.97.3
          188.114.96.3

> ping [domain]

Pinging [domain] [188.114.97.3] with 32 bytes of data:
Request timed out.
Request timed out.
```

когда выключаю
```
> Ipconfig /flushdns

Windows IP Configuration

Successfully flushed the DNS Resolver Cache.
> nslookup [domain]
Server:  UnKnown
Address:  192.168.1.1

Non-authoritative answer:
Name:    [domain]
Addresses:  2a06:98c1:3121::b
          2a06:98c1:3120::b
          188.114.96.11
          188.114.97.11

> ping [domain]

Pinging [domain] [188.114.96.11] with 32 bytes of data:
Reply from 188.114.96.11: bytes=32 time=29ms TTL=52
Reply from 188.114.96.11: bytes=32 time=28ms TTL=52
Reply from 188.114.96.11: bytes=32 time=28ms TTL=52
```

**Comment by AlexandrPkhm** [comment]
@Lufan 

По всей видимости проблема на стороне вашего оператора связи, ввиду которой ни один из валидных IP адресов для этого домена не может быть разрешен.

К сожалению, на данный момент мы можем только порекомендовать использовать AdGuard VPN без AdGuard DNS настроенного на роутере.
