### ISSUE TITLE
AdGuard VPN (x64) remains in `Program Files (x86)`

### ISSUE THREAD

**Issue by zubrRB** [AdguardTeam/AdGuardVPNForWindows#700]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.4 beta 3

### Environment

```markdown
- OS:Windows 7 (x64)
- Other network-level software:
```

### Which DNS server do you use?

Default

### Use Wintun

- [ ] yes, I do

### Issue Details

Steps to reproduce:
1. Скачать инсталлятор https://agrd.io/windows_vpn_beta.
2. Поверх релизной `2.3.1` установить версию `2.4 beta 3`. 

### Expected Behavior

Приложение должно перенестись в директорию `C:\Program Files`.

### Actual Behavior

Новая версия с заявленной поддержкой (x64) установилась и осталось в директории `C:\Program Files (x86)`.

### Screenshots

<details><summary>Screenshot</summary>

![AdGuard (x64)](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/50718960/cc37e4ab-e5b3-454a-bd44-c4644d677984)

</details>

### Additional Information

Запускается в диспетчере задач AdGuard VPN (x64).

**Comment by Danila-Arg** [comment]
@zubrRB Добрый день, можете подсказать подсказать, при установке начисто в какую папку по дефолту ставится приложение? 
И можете еще пожалуйста посмотреть в реестре HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion есть ли у вас параметр ProgramW6432Dir

**Comment by Danila-Arg** [comment]
Еще заметил, что у вас папка установочная называется AdGuardVPN у нас по дефолту она должна быть AdGuardVpn, при переносе мы учитываем регистр и расположение этой папки, так как если папка имеет другое наименование или расположение мы считаем, что юзер сам выбрал где ей находиться и менять расположение мы не должны.
Попробуйте пожалуйста поставить 2.3.1 в дефолтную папку, ничего не трогая и затем обновиться на бету или найтли 2.4

**Comment by zubrRB** [comment]
Я переустанавливал систему в конце прошлого года на x64, с того момента и папка с оригинальным именем AdGuardVPN.
Параметр `ProgramW6432Dir` имеет значение `C:\Program Files`. Блокировщик при обновлении на (x64) перенёсся, а VPN так и остался.  Мне нужно перед тем предварительно удалить существующую бета 2.4?

**Comment by Danila-Arg** [comment]
Да, можете удалить существующую бету

**Comment by Danila-Arg** [comment]
Сейчас подредактировал этот момент, теперь если отличается только регистр папка все равно будет переноситься

**Comment by zubrRB** [comment]
После переустановки и обновления поверх перенеслось правильно.

**Comment by Danila-Arg** [comment]
Ага, спасибо за информацию, дело в нейминге папки было ) В любом случае уже релизная версия не будет обращать внимание на регистр
