### ISSUE TITLE
Intrusive offer to purchase a subscription

### ISSUE THREAD

**Issue by zubrRB** [AdguardTeam/AdGuardVPNForWindows#701]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.3 - 2.4 beta 3

### Environment

```markdown
- OS:Windows 7
```

### Which DNS server do you use?

Default

### Use Wintun

- [ ] yes, I do

### Issue Details

Использовать бесплатную версию без подписки.

### Actual Behavior

При взаимодействии с клиентом постоянно вылазит назойливое предложение купить либо остаться в бесплатной версии, которое повторно вылазит даже при вызове опции «Экспортировать логи и информацию о системе».  

### Screenshots

<details><summary>Screenshot</summary>

![](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/50718960/9d5083c6-761a-4ef4-9102-595ec5300034)

</details>

**Comment by AlexandrPkhm** [comment]
@zubrRB Здравствуйте,

Данная частота показа экрана покупки лицензии — ожидаемое поведение. Как и любому сервису, нам нужны платные пользователи, однако мы проанализируем статистику и возможно изменим частоту показа данного экрана.

Относительно показа экрана при вызове опции «Экспортировать логи и информацию о системе». Вероятнее всего это совпадение, так как данное действие не является условием для показа экрана. Мы проверили показ экрана при экспорте логов на последней Nightly версии AdGuard VPN и нам не удалось повторить данное поведение.

**Comment by zubrRB** [comment]
Возможно, совпадение, произошедшее именно в тот момент, как по вашей просьбе полез тогда экспортировать логи....
По ощущениям, происходит спустя какое-то время, когда вызываешь и начинаешь взаимодействовать с разделами меню (исключений, экспорта и прочими), и тут в самый интересный момент вместо них вылазит экран подписки.)
