### ISSUE TITLE
Issues with application exclusions 

### ISSUE THREAD

**Issue by zubrRB** [AdguardTeam/AdGuardVPNForWindows#703]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.4 beta 3

### Environment

```markdown
- OS:Windows 7
```

### Which DNS server do you use?

Default

### Use Wintun

- [ ] yes, I do

### Issue Details

Раздел исключения приложений содержит дефект в языковых локализациях, которого нет в английском меню.

### Actual Behavior

Одна строка о количестве исключённых приложений вместо трёх.

### Screenshots

<details><summary>English</summary>

![English](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/50718960/3f83884a-0c7d-48d7-84b9-210a67991364)

</details>

<details><summary>Others</summary>

![Other](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/50718960/a60eb0b8-75c3-448c-a90a-1aceb002f838)

</details>

**Comment by zubrRB** [comment]
Ещё и сбрасывает (очищает) через короткое время список исключений в виде приложения (x32) в версии VPN (x64).

**Comment by AlexandrPkhm** [comment]
@zubrRB Здравствуйте,

Нам уже известно о дефекте в локализации и наша команда разработки работает над его устранением. 

Относительно проблемы со сбросом списка исключений. Нам не удалось повторить данную проблему на нашей стороне. Пожалуйста, попробуйте установить последнюю Nightly версию AdGuard VPN для Windows, которая доступна по данной [ссылке](https://agrd.io/windows_vpn_nightly), и попробуйте повторить проблему.

В случае если проблема повторится, нам потребуются логи приложения AdGuard VPN. Соберите и отправьте указанные файлы, используя данную инструкцию:

1. Зайдите в Настройки -> Настройки приложения -> Расширенные настройки -> Уровень логирования -> **Записывать все**;
2. Воспроизведите проблему и запомните точное время её воспроизведения. Оно понадобится
нам, чтобы найти соответствующие записи в лог-файле;
3. Зайдите в Настройки -> Поддержка -> Выберите **Экспортировать логи и информацию о системе**;
4. Отправьте полученный архив по адресу `devteam@adguard.com`. Также укажите номер задачи в Github и время воспроизведения проблемы.
5. Не забудьте вернуть значение уровня логирования на **Записывать по умолчанию**.

**Comment by zubrRB** [comment]
Проблема со сбросом списка исключений воспроизводится не сразу, а спустя несколько часов или сутки, но происходит стабильно. В репорте на скриншоте видно приложение в исключениях, а в комментарии через четыре часа раздел пуст.

**Comment by zubrRB** [comment]
Я понял механизм воспроизведения ошибки со сбросом списка исключений и дефектом локализаций (логи отправил):

Заходим в раздел исключений и добавляем в список приложение, например, IP-TV Player. https://borpas.info/iptvplayer 
После этого в разделе Исключения непосредственно под словом Приложения ничего нет,.. Хотя приложение в списке.
Выгружаем VPN, запускаем его снова и заходим в раздел Исключения, где тройное упоминание 1 приложения, как на сриншоте в заглавном баг-репорте. Подключаем VPN и через короткое время отключаем, после чего выгружаем VPN.
После этого снова запускаем, идём в раздел Исключения и видим, что список исключений приложений уже очистился.

**Comment by AlexandrPkhm** [comment]
@zubrRB К сожалению, нам все также не удается воспроизвести проблему по данным шагам. Пожалуйста, воспроизведите ее и пришлите нам логи. Это очень поможет команде разработки диагностировать проблему.

**Comment by zubrRB** [comment]
Я воспроизвёл и выслал расширенные логи перед своим предыдущим комментарием. Вы с русской локалью повторяете?

**Comment by AlexandrPkhm** [comment]
@zubrRB Спасибо! Да, пытались повторить с русской локалью.

**Comment by zubrRB** [comment]
После переустановки по соседней ошибке с переносом (x64) что-то изменилось. Понаблюдаю, возможно, связано с этим.

**Comment by zubrRB** [comment]
Вот так вот выглядит раздел сразу после добавления приложения в список исключений.


<details><summary>Gif:</summary>

![Video](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/50718960/4676c2e1-cf3b-4702-8a71-54e712481d49)
</details><br/>
