### ISSUE TITLE
AdguardVPN for windows blocked by Symantec because of call to malicious domain rawdifficulty.live

### ISSUE THREAD

**Issue by slimypi** [AdguardTeam/AdGuardVPNForWindows#706]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.3.2 - 1464

### Environment

```markdown
- OS: Windows 11
- Other network-level software:Symantec endpoint Security
```

### Which DNS server do you use?

Default

### Use Wintun

- [ ] yes, I do

### Issue Details

Steps to reproduce:
1. Install Symantec Endpoint protection ( Version 14.3 RU3 anad above).
2. Install adguard vpn for windows
3. try to login to adguard account the connection gets refused and Symantec blocks outgoing request.

### Expected Behavior

Should connect to VPN or to account.

### Actual Behavior

Freeze and notification from Symantec about highly suspicious domain request : **_rawdifficulty.live_**
Please see the attached screenshot

### Screenshots

<details><summary>Screenshot 1</summary>

![image](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/2995246/ea3ed708-f799-407f-9f6a-9be79f9c19f0)

</details>

### Additional Information

Why does AdgaurdVPN query that specific domain at login ? 
**I added an exception for the domain but i want to know why are you calling out supsicous remote domains ?**

**Comment by KolbasovAnton** [comment]
@slimypi Hello! Thank You for reporting. It was false positive alert, message to Symantec is already sent. All domains we using are secure, so don't worry.
