### ISSUE TITLE
Unable to log in to my account

### ISSUE THREAD

**Issue by Gleckus** [AdguardTeam/AdGuardVPNForWindows#712]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

All

### Browser version

Edge

### OS version

Windows 11

### Traffic filtering

- [ ] yes, I do

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

Regular

### Issue Details

Steps to reproduce:
1. Launching AdguardVPN
2. Logging into my account by email at lpflash@mail.ru
3. Catching infinite download and application error

### Actual Behavior

For a long time I used the AdguardVPN VPN service and everything suited me, speed was not cut, usability and other niceties. I bought an annual subscription to my account, registered to the e-mail lpflash@mail.ru and I was really enjoying the VPN. Now, however, I am encountering infinite loading on startup on my laptop. I have already tried everything to fix this. Please help me to fix this situation.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by Aydinv13** [comment]
@Gleckus Hi there!

Please, try the [Nightly](https://agrd.io/windows_vpn_nightly) build.

Could you also collect your logs:
1. Reproduce the problem and remember the exact time it was reproduced at. We will need it to find the corresponding entries in the log file;
2. Go to AdGuard's tray menu -> Support -> **Export logs**;
3. Send the archive to `devteam@adguard.com` and mention this issue number in the subject. Don't forget to include the time of reproduction.

**Comment by Aydinv13** [comment]
As I can see, there was interaction with the support team, so I'm closing the task. If you have any questions, please do not hesitate to contact us.
