### ISSUE TITLE
Correct Wintun driver name and add meaningful description

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardVPNForWindows#716]
### Issue Details

The title has a typo in the word "Adguard" (`g` should be a capital `G`), and an extra word "adapter". And it would be nice to add a meaningful description of the driver.

<details><summary>Screenshots:</summary>

![OnPaste 20240810-191453](https://github.com/user-attachments/assets/01d4e386-bd2d-4967-9fd9-ccfa04a2b587)

![OnPaste 20240810-191624](https://github.com/user-attachments/assets/19322177-fc36-4dd7-9805-45bc9b73d3aa)

</details>

### Proposed solution

The title has a typo in the word "Adguard" (`g` should be a capital `G`), and an extra word "adapter". And it would be nice to add a description of the driver.

<details><summary>Screenshots:</summary>

![OnPaste 20240810-191453](https://github.com/user-attachments/assets/01d4e386-bd2d-4967-9fd9-ccfa04a2b587)

![OnPaste 20240810-191624](https://github.com/user-attachments/assets/19322177-fc36-4dd7-9805-45bc9b73d3aa)

</details>

**Comment by sfionov** [comment]
@rakleed In nightly it looks different:

<img width="372" alt="image" src="https://github.com/user-attachments/assets/233653ca-71c3-4e5d-87ea-816a057c4302">

**Comment by rakleed** [comment]
@sfionov then the only thing that remains relevant is to remove the word "adapter"

**Comment by Aydinv13** [comment]
@rakleed will be corrected, thanks.
