### ISSUE TITLE
Can't login with Google

### ISSUE THREAD

**Issue by Jebiel** [AdguardTeam/AdGuardVPNForWindows#717]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.3.2

### Environment

```markdown
- OS: Windows 11, 24H2 (OS build 26100)
- Other network-level software: None (Fresh Windows install)
```

### Which DNS server do you use?

Default

### Use Wintun

- [ ] yes, I do

### Issue Details

Steps to reproduce:
1.
2.
3.

### Expected Behavior

I tried logging in with my Google account.

### Actual Behavior

Once I logged in using my browser, I got a pop-up, whether to open the app, to which I clicked yes, but the app didn't catch the url for some reason.

I also tried installing Firefox, to see if this was able to redirect to the app, after successful login, but this also failed.

I just installed this on a new laptop, with an ARM processor, don't know if this can have anything to do with it failing?

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by AlexandrPkhm** [comment]
Hi @Jebiel 

Unfortunately, we were unable to reproduce this issue. Could you please let us know if it still persists? 

And if it does, we need to get the app logs, to diagnose and troubleshoot this issue.
Here's what we need you to do in this case:

1. Go to Settings → App settings → Logging level → **Record everything**;
2. Reproduce the problem and remember the exact time it was reproduced at. We will
need it to find the corresponding entries in the log file;
3. Open Support tab → **Export logs and system info**;
4. Send the archive to `devteam@adguard.com` and mention this issue number in the subject. Don't forget to include the time of reproduction.
5. Set the logging level back to **Record by default**.

**Comment by AlexandrPkhm** [comment]
@Jebiel Please let us know if there are any news on the issue?

**Comment by Jebiel** [comment]
Hi @AlexandrPkhm, I'll get back to you on the matter, later this evening.

**Comment by Jebiel** [comment]
I've just tried to login this evening, and I've successfully been able to login. So the problem is now gone/fixed?

By the way, I you need logs from users in future, it might be a good idea, to add a shortcut to the logging settings, from the login screen, as you're not currently able to access any settings, before you've logged in. And since it was the login flow, I had problems with, I wouldn't be able to enable the logging level that you refer to.

Best regards
- Jebiel
