### ISSUE TITLE
App for windows isn`t working

### ISSUE THREAD

**Issue by DonPlaton** [AdguardTeam/AdGuardVPNForWindows#719]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.3

### Environment

```markdown
- OS: Windows 11
- Other network-level software:No
```

### Which DNS server do you use?

Default

### Use Wintun

- [ ] yes, I do

### Issue Details

Steps to reproduce:
1. Start your windows PC
2. Try to open adGuard VPN app for windows
3. App is displaying "Technical issue" and not working.

### Expected Behavior

App is opening and ready to use.

### Actual Behavior

App is displaying "Technical issue" and when I pushing the button "fix problem" - nothing is happening.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>
![image](https://github.com/user-attachments/assets/870af6bb-058c-4d2a-8bec-f3ef806b9a60)

**Comment by AlexandrPkhm** [comment]
@DonPlaton Hi, 

Please let us know if this problem occurs on the latest Beta version of AdGuard VPN for Windows, which is available at this [link](https://agrd.io/windows_vpn_beta). 

If the problem persists, please send us the application logs of AdGuard VPN. They will help us to diagnose and fix the problem. Here's what we need you to do:

1. Go to Settings → App settings → Logging level → **Record everything**;
2. Reproduce the problem and remember the exact time it was reproduced at. We will
need it to find the corresponding entries in the log file;
3. Open Support tab → **Export logs and system info**;
4. Send the archive to `devteam@adguard.com` and mention this issue number in the subject. Don't forget to include the time of reproduction.
5. Set the logging level back to **Record by default**.

Also, please let us know if you are using an antivirus application on your device.

**Comment by AlexandrPkhm** [comment]
@DonPlaton Please let us know if there are any news on this issue?
