### ISSUE TITLE
Disabling the "Start AdGuard VPN when Windows boots" setting does not work

### ISSUE THREAD

**Issue by pdkpv** [AdguardTeam/AdGuardVPNForWindows#721]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.4.0 nightly 10 (1489)

### Environment

```markdown
- OS: Windows 11 Pro 24H2 (26100.1586)
```

### Which DNS server do you use?

Cloudflare for Families - Malware Blocking

### Use Wintun

- [X] yes, I do

### Issue Details

Steps to reproduce:
1. Install AdGuard VPN.
2. Disable the "Start AdGuard VPN when Windows boots" setting.
3. Restart Windows.

### Expected Behavior

AdGuard VPN does not start after restarting Windows.

### Actual Behavior

After rebooting Windows, AdGuard VPN starts automatically, although this behavior is disabled in the settings.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

1. Additional information including extended logs provided to Boris (win lead) in DM.
2. Removing AdGuard VPN using the official Uninstall Utility and reinstalling does not solve the problem.

**Comment by Aydinv13** [comment]
@pdkpv Hi there,

1) could you check what is shown in registry at this path
`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run`
2) Is this reproducible with the latest [Nightly](https://agrd.io/windows_vpn_nightly)?
3) Please send the debug logs if the latest Nightly doesn't help:
<details><summary>Instruction</summary>

1. Go to Settings --> General --> App settings -->Advanced settings --> Logging level --> **Record everything**;
2. Reproduce the problem and remember the exact time it was reproduced at. We will need it to find the corresponding entries in the log file;
3. Go to Support -> **Export logs and system info**;
4. Send the archive to `devteam@adguard.com` and mention this issue number in the subject. Don't forget to include the time of reproduction.
5. Set the logging level back to **Record by default**.
</details>

**Comment by pdkpv** [comment]
@Aydinv13 

Hello, after uninstalling using the official utility and clean installation of the current nightly version, the problem disappeared.

**Comment by Aydinv13** [comment]
@pdkpv thank you for the feedback, feel free to contact us if the problem happens again. I'm closing this issue for now.
