### ISSUE TITLE
Refresh button shifts to the left

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNForWindows#728]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.4.0 nightly 12

### Environment

```markdown
- OS: Windows 11
```

### Which DNS server do you use?

Default

### Use Wintun

- [ ] yes, I do

### Issue Details

Steps to reproduce:
1. Go to another tab and come back to home tab again
2. Click on refresh button on the locations list

### Expected Behavior

The button shouldnt shift anywhere.

### Actual Behavior

After coming to the home tab from another tab and then pressing the refresh button, the button shifts to the left.

### Screenshots

<details><summary>Screenshot 1</summary>

https://github.com/user-attachments/assets/de8a667c-4925-43a0-8466-297a44d2ab12
</details>

**Comment by Aydinv13** [comment]
@gork7777 Hi!  

Thanks for the catch, we will fix it.
