### ISSUE TITLE
AdGuard doesn't filter some sites when VPN is enabled

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardVPNForWindows#729]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.4.0

### Environment

```markdown
- OS: Windows 11 23H2
- Other network-level software: AdGuard
```

### Which DNS server do you use?

Cloudflare DNS

### Use Wintun

- [ ] yes, I do

### Issue Details

Steps to reproduce:
1. Enable autostart in AdGuard and VPN, as well as auto-connection to the server in VPN
2. Restart your computer
3. Open https://dtf.ru

### Expected Behavior

AdGuard completely filters all websites.

### Actual Behavior

AdGuard does not completely filter some websites.

### Screenshots

<details><summary>Screen recording 1</summary>

https://github.com/user-attachments/assets/89ce83d1-ab31-48de-981e-c9e04f7a08e4

</details>

### Additional Information

[adg_logs_2.4.1475.0_0907_1641.zip](https://github.com/user-attachments/files/16918689/adg_logs_2.4.1475.0_0907_1641.zip)

I enable `Enable filtering at system start-up` in AdGuard Advanced Settings.

Related issue in https://github.com/AdguardTeam/AdguardForWindows/issues/5229

**Comment by KolbasovAnton** [comment]
@rakleed Greetings! I've managed to reproduce Your bug on latest versions of both VPN and ADblocker. But it can be fixed with **turning the Wintun on** in VPN settings. Please, try it and let us know about the results. This also applies to the [related issue](https://github.com/AdguardTeam/AdguardForWindows/issues/5229).

**Comment by rakleed** [comment]
@KolbasovAnton yeah, it works. When will you use the Wintun driver by default?

**Comment by KolbasovAnton** [comment]
@rakleed This option is planned in the future.

**Comment by rakleed** [comment]
> @rakleed Greetings! I've managed to reproduce Your bug on latest versions of both VPN and ADblocker. But it can be fixed with **turning the Wintun on** in VPN settings. Please, try it and let us know about the results. This also applies to the [related issue](https://github.com/AdguardTeam/AdguardForWindows/issues/5229).

@KolbasovAnton could you please mention it in knowledge base https://adguard-vpn.com/kb/adguard-vpn-for-windows/solving-problems/common-installer-errors/?
