### ISSUE TITLE
Is there way to take VPN credentials to use with OpenVPN?

### ISSUE THREAD

**Issue by IniUe** [AdguardTeam/AdGuardVPNForWindows#73]
### Problem Description

hi, i'm linux user. i did not see adguard support for this os yet. an issue https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/12
so im asking, is it possible to take VPN credentials so i can install openvpn on linux and use credentials to connect. It does officially by protonvpn and other competitors

![image](https://user-images.githubusercontent.com/81799342/113480538-dd27c400-94be-11eb-8a78-f9cc1ac4c56b.png)

another config files
![image](https://user-images.githubusercontent.com/81799342/113480675-cb92ec00-94bf-11eb-9466-c8c3e4dc8366.png)

**Comment by ameshkov** [comment]
Hi, AdGuard VPN does not use OpenVPN at this moment.

**Comment by IniUe** [comment]
> Hi, AdGuard VPN does not use OpenVPN at this moment.

Sorry, i did not know it so what does agvpn desktop apps use? i have not installed this software
i'm trying to see if it like openvpn, wireguard so we can use them with agvpn credentials till agteam release software for this os.

**Comment by Aydinv13** [comment]
>Sorry, i did not know it so what does agvpn desktop apps use? 
We use our own protocol and servers
