### ISSUE TITLE
TLD rules

### ISSUE THREAD

**Issue by bogachenkove** [AdguardTeam/AdGuardVPNForWindows#730]
### Issue Details

Due to the tense situation in my home country, certain TLD domain names have become unavailable for the entire country, please add the ability to add general rules for filtering.

### Proposed solution

Allow adding rules for top-level domains.
Eg. `*.com`

Also, **in addition to what is described above**, do you not allow the possibility of adding a frivolous top-level domain rule?
Eg `google.*`

**Comment by ameshkov** [comment]
It's already possible to add `com`

**Comment by bogachenkove** [comment]
Hi, Andrey!

Oh, I entered the text `*.com`, taking as an example the basic rules - `*.example.com` and it gave me an error. My fault.  By the way, there is something else that is indirectly related to the first question, when adding `example.com`, is the rule `*.example.com` automatically added/enabled? I create my list for permanent use, so when importing or manually adding, lines appear that I did not want to add. This does not cause me any inconvenience, but how correct is this? If I add `example.com`, then I want to add only it - the second-level domain name, not the second + the third-level domain name.
Similarly with `com`, I added this top-level domain emphasizing it with markup, added with an asterisk - `*.com`, why do I need the `com` rule enabled?

What about the second sentence? I have many mirrors of sites with different top-level domains, only this is changed, but the second-level domain name remains unchanged.

**Comment by KolbasovAnton** [comment]
Hello.

1. TLD domains can be added in the form `com`, `de`, `ru`, etc.
2. Yes, automatic subdomain addition is correct, also it is suitable for most users.
3. Unfortunately, making exclusions like `google.*` as you have indicated, right now is technically impossible.

**Comment by bogachenkove** [comment]
>Yes, automatic subdomain addition is correct, also it is suitable for most users.

A person enters a certain domain and wants the program to work only for him, why extol the program above the person? Why think up something that is not necessary? If hosts.txt worked according to your logic, then your technology would block half of the Internet pages. Can you refer to the thread where people who, like me, use your program, and express an opposing point of view, different from mine?

> TLD domains can be added in the form com, de, ru, etc.

Read above.

> Unfortunately, making exclusions like google.* as you have indicated, right now is technically impossible.

What is the reason for this? I use Proxifier in conjunction with your program, it is implemented there. And many other different features, for example: implemented tunneling of applications by profiles, the ability for the entire system to work only for certain domains, along with another profile that will run all traffic of certain programs (domains that change - mirrors or, for example, this is an IP) through a VPN. And this is the only way to humanize your program, what prevents you from doing the same, and not coming up with unnecessary features that add domains from point 2 in your message?

Here is an elementary, how can I unblock only YouTube (without specifying the name of the executable file) for the entire system, having registered its domains, and at the same time run the Telegram program (with the indication of its executable name - telegram.exe) with its `149.154.167.*` in your program? How can I refuse Proxifier, if such a simple feature cannot be implemented in your program? How to get to torrent file sites whose mirrors (TLD) instantly change twice a day? Enter new ones every time? How is that?
***
the thread closed before it even opened, what's going on?
my neighboring thread with importing rules for this program, for some reason was moved to the AdGuard Ad blocker repository.what the hell is going on here
