### ISSUE TITLE
All servers are offline due to backend server side exception

### ISSUE THREAD

**Issue by Isentin** [AdguardTeam/AdGuardVPNForWindows#735]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

Здравствуйте.
Когда я запускаю адгвард впн все сервера всегда офлайн. С чем это может быть связано?

**Comment by AlexandrPkhm** [comment]
@Isentin Здравствуйте!

Для такого поведения возможно несколько причин. Пожалуйста, сообщите нам, какую версию приложения вы используете? Также сообщите нам, используете ли вы какой-либо антивирус или иное приложение для фильтрации трафика?

**Comment by Isentin** [comment]
Версия приложения: 2.4.0 (1475)
Приложений для фильтрации трафика никаких нету. Брандмауэр отключен. Антивирусов нет.

**Comment by AlexandrPkhm** [comment]
@Isentin В данном случае, для диагностики и решения Вашей проблемы, нам понадобятся логи приложения AdGuard VPN. Соберите и отправьте указанные файлы, используя данную инструкцию:

1. Зайдите в Настройки -> Настройки приложения -> Расширенные настройки -> Уровень логирования -> **Записывать всё.**
2. Воспроизведите проблему и запомните точное время её воспроизведения. Оно понадобится нам, чтобы найти соответствующие записи в лог-файле.
3. Зайдите в Настройки -> Поддержка -> Выберите **Экспортировать логи и информацию о системе.**
4. Отправьте полученный архив по адресу `qa@adguard.com`. В заголовке укажите платформу и номер задачи в формате “[windows]#номер задачи на Github” и время воспроизведения проблемы.
5. Не забудьте вернуть значение уровня логирования на **Записывать по умолчанию**.

**Comment by AlexandrPkhm** [comment]
@Isentin Мы проанализировали логи и, по всей видимости, нам понадобится дополнительная информация. Пожалуйста, запишите трейсовые логи. 

Для этого воспользуйтесь [инструкцией из нашей базы знаний](https://adguardvpn-help.info/kb/ru/adguard-vpn-for-windows/solving-problems/logs/#%D1%82%D1%80%D0%B5%D0%B9%D1%81%D0%BE%D0%B2%D1%8B%D0%B5-%D0%BB%D0%BE%D0%B3%D0%B8) и пришлите полученный архив по адресу qa@adguard.com. В заголовке укажите платформу и номер задачи в формате “[windows]#номер задачи на Github” и время воспроизведения проблемы.

**Comment by AlexandrPkhm** [comment]
@Isentin  Пожалуйста, попробуйте установить тестовый билд, доступный по данной [ссылке](https://uploads.adguard.org/AdGuardVpn-v2.4.1486.3.exe). Сообщите нам, сохраняется ли данная проблема на данном билде, и если сохраняется то нам вновь понадобятся трейсовые логи.

**Comment by AlexandrPkhm** [comment]
@Isentin Логи которые вы прислали, были записаны на старой версии приложения - 2.4.0 (1475). Пожалуйста, установите новый тестовый билд, доступный по данной [ссылке](https://uploads.adguard.org/AdGuardVpn-v2.4.1486.3.exe) и пришлите нам логи.

**Comment by Isentin** [comment]
Здравствуйте. Тестовый билд не помог. НО я разобрался, конфликт был с goodbyedpi. После отключения прекрасно стало работать. Спасибо большое за поддержку! :)
