### ISSUE TITLE
Show endpoint load indicator

### ISSUE THREAD

**Issue by Eksol** [AdguardTeam/AdGuardVPNForWindows#738]
### Issue Details

Когда выбираешь сервер, непонятно много ли там свободного места. 

### Proposed solution

Если над каждым сервером будет стоять маленький индикатор загруженности, клиенты смогут сами распределять нагрузку.

### Alternative solution

Использовать авторежим который выберет наилучший сервер в плане пинг/загруженность

**Comment by AlexandrPkhm** [comment]
@Eksol Здравствуйте, 

Мы уже рассматривали данную идею и пришли к выводу, что не планируем внедрять индикатор загруженности сервера. В нашем случае показатель пинга выступает как индикатор загруженности, так как пинг рассчитывается с учетом загруженности конкретного сервера.
