### ISSUE TITLE
Очень низкая скорость на любом сервере

### ISSUE THREAD

**Issue by Eksol** [AdguardTeam/AdGuardVPNForWindows#739]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.4.0

### Environment

```markdown
- OS: windows 10
- Other network-level software: none
```

### Which DNS server do you use?

AdGuard DNS

### Use Wintun

- [ ] yes, I do

### Issue Details

Steps to reproduce:
1. Запустить speedtest на android  и замерить скорость
2. Запустить speedtest на windows 10 и замерить скорость
3. Сравнить результаты

### Expected Behavior

Скорость должна быть одинаковой, +- в пределах погрешности

### Actual Behavior

Скорость на windows 10 очень низкая по сравнению с andriod

### Screenshots

![Скриншот 22 09 24_23 48 02](https://github.com/user-attachments/assets/f56e125b-8c3f-43f2-9279-7b50cd55b3a9)
![Скриншот 22 09 24_23 47 08](https://github.com/user-attachments/assets/cd7980f1-a4b4-4b30-a982-e8e8df3f6f5f)

</details>

### Additional Information

Такие же проблемы со скоростью наблюдаются в версии для роутеров на базе прошивки от OpenWRT.  adguardvpn-cli

**Comment by shamarin** [comment]
Сеть то физическая одна и та же при этом? И на Windows при этом может что-то типа торрент клиента при этом работает активно и нагружает сеть? Если так то я уже упоминал об этом здесь, с торрентом одновременно скорость низкая очень, с другими VPN такого не наблюдается.

**Comment by shamarin** [comment]
И тест speedtest лучше выбирать конечную точку своего провайдера, а не сервер страны через которую VPN работает. Результаты разные будут.

**Comment by Eksol** [comment]
Проверил на 3 разных компьютерах. Результат на всех трех ПК 5мб. 
Тот же самый тест, на том же сервере, на тех же конечных серверах speedtest но уже на андроиде дает скорость в 100мб. 
Торрент не активен. Баг наблюдается только на ПК версии.

**Comment by shamarin** [comment]
> Проверил на 3 разных компьютерах. Результат на всех трех ПК 5мб. Тот же самый тест, на том же сервере, на тех же конечных серверах speedtest но уже на андроиде дает скорость в 100мб. Торрент не активен. Баг наблюдается только на ПК версии.

Попробуй QUIC включить в расширенных настройках, плюс можно сетевое оборудование еще перезагрузить.

**Comment by Eksol** [comment]
> Попробуй QUIC включить в расширенных настройках,
Помогло поднять скорость до 15мб в браузере google chrome 
В браузере microsoft edge скорость без quic = 50мб, со включенным quic 69мб

**Comment by shamarin** [comment]
> > Попробуй QUIC включить в расширенных настройках,
> > Помогло поднять скорость до 15мб в браузере google chrome
> > В браузере microsoft edge скорость без quic = 50мб, со включенным quic 69мб

Что-то у тебя режет в Chrome значит, расширение какое-то возможно. Антивирус в системе есть?

**Comment by Eksol** [comment]
> Антивирус в системе есть?

касперского. 

Какие то приколы со скоростью начались. На одном из тестов скорость на гугл хром улетела под 180мб.

**Comment by shamarin** [comment]
> > Антивирус в системе есть?
> 
> касперского.
> 
> Какие то приколы со скоростью начались. На одном из тестов скорость на гугл хром улетела под 180мб.

Возможно проверка зашифрованного трафика Касперским как-то влияет. Хотя у меня на версии 21.18.5.438(a) проблем нет.

**Comment by Eksol** [comment]
Самопроизвольно пропали исполняющие файлы adguardvpn на компьютере. Переустанавливаю. Касперского удалил.

**Comment by Eksol** [comment]
Удалил касперского. Проблема со скоростью ушла.

**Comment by Eksol** [comment]
Вопрос. Если у меня на 1 пк был установлен касперский. То почему скорости были низкие на всех пк в моем доме? Даже на тех куда не был установлен касперский?

**Comment by shamarin** [comment]
> Удалил касперского. Проблема со скоростью ушла.

Значит в Касперском внеси приложение Adguard в исключения для проверки.

**Comment by shamarin** [comment]
> Вопрос. Если у меня на 1 пк был установлен касперский. То почему скорости были низкие на всех пк в моем доме? Даже на тех куда не был установлен касперский?

Через приложение или через конфиг в маршрутизаторе?

**Comment by Eksol** [comment]
> > Вопрос. Если у меня на 1 пк был установлен касперский. То почему скорости были низкие на всех пк в моем доме? Даже на тех куда не был установлен касперский?
> 
> Через приложение или через конфиг в маршрутизаторе?

В обеих случаях были тормоза. Скорости были низкие. Только на смартфоне при этом сохранялись скорости 100мб. 
Сейчас вот через винду проверяю скорость впн, получил 245мб. 
Вот токо этой скорости не хватает что бы смотреть ютуб в 4к

**Comment by shamarin** [comment]
Плюс попробуй в настройках приложения включить использование Wintun, маршрутизация пошустрее должна быть и проблем с антивирусом не должно быть.

**Comment by shamarin** [comment]
> > > Вопрос. Если у меня на 1 пк был установлен касперский. То почему скорости были низкие на всех пк в моем доме? Даже на тех куда не был установлен касперский?
> > 
> > 
> > Через приложение или через конфиг в маршрутизаторе?
> 
> В обеих случаях были тормоза. Скорости были низкие. Только на смартфоне при этом сохранялись скорости 100мб. Сейчас вот через винду проверяю скорость впн, получил 245мб. Вот токо этой скорости не хватает что бы смотреть ютуб в 4к

245 Мбит тебе не хватает на 4k Youtube??? Ты серьезно??? У меня 100 Мбит канала хватает для таких видео, 4k видео с 60 кадрами будет требовать 40 Мбит примерно.

**Comment by Eksol** [comment]
> 245 Мбит тебе не хватает на 4k Youtube???

Я не знаю почему, но по спидтесту скорость 245мб. а на ютубе скорость загрузки черепашья

**Comment by Eksol** [comment]
> включить использование Wintun

Это помогло поднять скорости загрузки ютуба. Теперь 4к тянет.
Что делать с антивирусом то? битдефендер не обновляется нормально и ломает работу сайтов. Касперский лезет во все дыры и ломает работу впн.

**Comment by shamarin** [comment]
> > 245 Мбит тебе не хватает на 4k Youtube???
> 
> Я не знаю почему, но по спидтесту скорость 245мб. а на ютубе скорость загрузки черепашья

Потому что HTTP/2, а Ютуб HTTP/3 использует. Я создавал уже запрос по этому поводу https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/734, закрыли, так как реализовывать не будут. Выход я уже написал - Wintun + QUIC, тогда скорость у тебя максимальная на Youtube будет.

**Comment by Eksol** [comment]
> QUIC

разве он не блокируется РКНом?

**Comment by shamarin** [comment]
QUIC использует UDP протокол вместо TCP, поэтому и скорость выше. Плюс Wintun сам по умолчанию через UDP работает.

**Comment by Eksol** [comment]
Как то же самое сделать на роутере? в adguardcli ?

**Comment by shamarin** [comment]
> > QUIC
> 
> разве он не блокируется РКНом?

При чем тут блокируется или нет РКН??? Если ты через VPN трафик гонять будет.

**Comment by shamarin** [comment]
> Как то же самое сделать на роутере? в adguardcli ?

Как в маршрутизаторе QUIC включить не знаю, читай мануалы от них. А может там и не поддерживается этот протокол вовсе.

**Comment by Eksol** [comment]
Я думаю тему эту можно закрывать. Причина тормозов была в касперском. 
С роутером разобраться не удалось. Там так же 5мб даже со включенным QUIC. Кажется для роутера впн еще сыроват...

**Comment by Eksol** [comment]
Если причина низкой скорости была в касперском, то почему на других пк в доме, где не установлен касперский, скорость была низкой?

**Comment by shamarin** [comment]
> Если причина низкой скорости была в касперском, то почему на других пк в доме, где не установлен касперский, скорость была низкой?

Низкая скорость с приложением Adguard VPN и на Ютуб???

**Comment by shamarin** [comment]
> Если причина низкой скорости была в касперском, то почему на других пк в доме, где не установлен касперский, скорость была низкой?

Если речь идет о приложении Adguard VPN и низкая скорость на Ютуб, то без QUIC включенного, что с Wintun, что без него у меня тоже низкая скорость 4-10 Мбит и 4k видео тоже стопорится постоянно https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/734. Если QUIC включить, то тогда скорость высокая на Youtube становится 70 Мбит для 100 Мбит канала.

**Comment by Eksol** [comment]
> Низкая скорость с приложением Adguard VPN и на Ютуб???

На данный момент, по 19:26 по москве, у меня опять проявляется этот баг. 
На пк 3,79мб за загрузку
На андроиде все 140мб 

Я не понимаю почему так? Одни и те же сервера, одна и та же сеть wifi. Но результат разный!

**Comment by shamarin** [comment]
> > Низкая скорость с приложением Adguard VPN и на Ютуб???
> 
> На данный момент, по 19:26 по москве, у меня опять проявляется этот баг. На пк 3,79мб за загрузку На андроиде все 140мб
> 
> Я не понимаю почему так? Одни и те же сервера, одна и та же сеть wifi. Но результат разный!

Так сервер может быть загружен сильно, так как пользователей много подключено. Я вообще заметил, что Финляндия не самый быстрый сервер и пинг там постоянно скачет, если нажать в приложении обновить локации.

**Comment by Eksol** [comment]
> Так сервер может быть загружен сильно, так как пользователей много подключено. Я вообще заметил, что Финляндия не самый быстрый сервер и пинг там постоянно скачет, если нажать в приложении обновить локации.
Я бы тоже подумал, что финский сервер сильно нагружен. 
НО, на телефоне каждый раз скорость свыше 100мб, при каждом мать его тесте скорости! То есть сервер тут не нагружен! 

И вот у меня две картинки, которые не сходятся. На пк скорость маленькая, на телефоне скорость бешеная.

**Comment by shamarin** [comment]
Журнал приложения нужен, отошлите разработчикам, чтобы посмотрели что происходит.

**Comment by shamarin** [comment]
Да и все же лучше проверить скорость на реальных приложениях, а не синтетические тесты проводить.

**Comment by shamarin** [comment]
Есть предположение, что проверка допустимой полосы пропускания физического канала реализована с ошибками. От сюда видимо и баг есть, что когда торрент клиент работает и хоть для него полоса ограничена настройками, то Adguard VPN сильно тормозить начинает - скорость соединения сильно проседает (вместо 10-15 Мбит у меня выдает 1-2 Мбит), хотя в последней версии ночной сборки лучше стало.

**Comment by Eksol** [comment]
> Есть предположение, что проверка допустимой полосы пропускания физического канала реализована с ошибками. От сюда видимо и баг есть, что когда торрент клиент работает и хоть для него полоса ограничена настройками, то Adguard VPN сильно тормозить начинает - скорость соединения сильно проседает (вместо 10-15 Мбит у меня выдает 1-2 Мбит), хотя в последней версии ночной сборки лучше стало.

У меня такие скорости без торрента.

**Comment by Eksol** [comment]
Знаешь до чего я дошел? 
Я раздал интернет от телефона на пк. На телефоне поднят туннель. Следовательно, и интернет на пк через телефон и туннель. 
И, даже так, на пк скорость 20мб. на телефоне 100мб. 
Протестил пропускную способность без туннеля. Скорость под 250мб.

**Comment by shamarin** [comment]
> Знаешь до чего я дошел? Я раздал интернет от телефона на пк. На телефоне поднят туннель. Следовательно, и интернет на пк через телефон и туннель. И, даже так, на пк скорость 20мб. на телефоне 100мб. Протестил пропускную способность без туннеля. Скорость под 250мб.

Смотри в настройках маршрутизатора не ограничена ли скорость для клиента.

**Comment by Eksol** [comment]
> Смотри в настройках маршрутизатора не ограничена ли скорость для клиента.

Не, без впн, скорости под 450мб.

**Comment by Eksol** [comment]
Я ничего не понимаю. То ли обновили программу, скорости на винде под 170мб.

**Comment by Eksol** [comment]
Обновил версию  adguardvpn-cli beta и на роутере скорости очень веселые, 
Будем наблюдать! 
![Скриншот 24 09 24_21 26 43](https://github.com/user-attachments/assets/5b5a1906-98c9-4f88-9467-18a4b6fe105b)

**Comment by Eksol** [comment]
Проверил на ютубе, скорость загрузки маленькая, чего то не хватает. В спидтесте через cli скорости хорошие. На ютубе скорости загрузки маленькие, до 10мб. 2К не тянет. 1080 впритык хватает...

**Comment by shamarin** [comment]
> Проверил на ютубе, скорость загрузки маленькая, чего то не хватает. В спидтесте через cli скорости хорошие. На ютубе скорости загрузки маленькие, до 10мб. 2К не тянет. 1080 впритык хватает...

Я уже писал об этом, у меня тоже самое только с Youtube https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/734 .Но если QUIC включить то скорость отличная.

**Comment by Eksol** [comment]
> > Проверил на ютубе, скорость загрузки маленькая, чего то не хватает. В спидтесте через cli скорости хорошие. На ютубе скорости загрузки маленькие, до 10мб. 2К не тянет. 1080 впритык хватает...
> 
> Я уже писал об этом, у меня тоже самое только с Youtube #734 .Но если QUIC включить то скорость отличная.

В этот раз я пытаюсь впн поднять на роутере. И сейчас скорости опять грохнулись на дно. Даже на спидтесте. 
Заколебало уже это ей богу.

**Comment by Eksol** [comment]
adguardvpn-cli снова сдох. Вначале пару минут скорости были отличные. Сел посмотреть ютуб, смотрю скорости уже упали.

**Comment by shamarin** [comment]
> > > Проверил на ютубе, скорость загрузки маленькая, чего то не хватает. В спидтесте через cli скорости хорошие. На ютубе скорости загрузки маленькие, до 10мб. 2К не тянет. 1080 впритык хватает...
> > 
> > 
> > Я уже писал об этом, у меня тоже самое только с Youtube #734 .Но если QUIC включить то скорость отличная.
> 
> В этот раз я пытаюсь впн поднять на роутере. И сейчас скорости опять грохнулись на дно. Даже на спидтесте. Заколебало уже это ей богу.

Насчет роутера вам ответили же, что может не поддерживаться аппаратное шифрование и тогда скорость низкая будет. Либо прошивка маршрутизатора глючная.

**Comment by Eksol** [comment]
> Насчет роутера вам ответили же, что может не поддерживаться аппаратное шифрование и тогда скорость низкая будет.

Этот роутер новинка 2023 года. Там топовый процессор filogic 820. Прошивка опенврт стабилка.

**Comment by Eksol** [comment]
> Насчет роутера вам ответили же, что может не поддерживаться аппаратное шифрование и тогда скорость низкая будет. Либо прошивка маршрутизатора глючная.

Этот роутер может на vless, shadowsocks зашибать свыше 200мб.

**Comment by shamarin** [comment]
> > Насчет роутера вам ответили же, что может не поддерживаться аппаратное шифрование и тогда скорость низкая будет.
> 
> Этот роутер новинка 2023 года. Там топовый процессор filogic 820. Прошивка опенврт стабилка.

Это не гарантия того, что в прошивке не может быть ошибок. Даже в Keenetic в их прошивках ошибки бывают, но там исправляют их.

**Comment by shamarin** [comment]
Я вам уже писал, что собирайте журнал с повторением ситуации проблемной и присылайте его разработчикам.

**Comment by Eksol** [comment]
> Я вам уже писал, что собирайте журнал с повторением ситуации проблемной и присылайте его разработчикам.

Единственный кто отвечает на мои сообщения это ты! 
Разрабам кажется вообще пофигу...

**Comment by shamarin** [comment]
> > Я вам уже писал, что собирайте журнал с повторением ситуации проблемной и присылайте его разработчикам.
> 
> Единственный кто отвечает на мои сообщения это ты! Разрабам кажется вообще пофигу...

Не правда, отвечают, но бывают задержки. Из поддержки уже вам назначили человека.

**Comment by Eksol** [comment]
> Не правда, отвечают, но бывают задержки. Из поддержки уже вам назначили человека.
А ты откуда знаешь об этом?

**Comment by shamarin** [comment]
> > Не правда, отвечают, но бывают задержки. Из поддержки уже вам назначили человека.
> > А ты откуда знаешь об этом?

![изображение](https://github.com/user-attachments/assets/7b060463-92b3-45a7-9ef7-9a262cf64f58)

**Comment by Eksol** [comment]
А может надо было на англ. оформить проблему?

**Comment by shamarin** [comment]
> А может надо было на англ. оформить проблему?

Без разницы, на русском они тоже отвечают.

**Comment by Eksol** [comment]
Короче, с adguardvpnforwindows ситуация улучшилась, теперь скорости хоть в спидтесте высокие, но на ютубе скорости выше 10мб не подымаются.  
На роутере, имеется ввиду adguardvpn-cli, проблема сохраняется. Скорости чрезвычайно низкие. 
Как временное решение поставлю расширение Юбуст до тех пор пока адгуард непочинят

**Comment by Eksol** [comment]
> Без разницы, на русском они тоже отвечают.

Хочешь прикол? 
![Скриншот 27 09 24_23 25 02](https://github.com/user-attachments/assets/26208839-eb18-478d-a467-111088dd1c48)

Если в смартфоне впн работает прекрасно то почему бы не перебросить его через кабель на компьютер? 
Это было и сделано.... 
Теперь и на ПК есть высокоскоростной впн из смартфона! 
Для этого нужно всего лишь андроид смартфон с рут правами. 
Такой фокус на яблоке невозможно сделать...

**Comment by shamarin** [comment]
> > Без разницы, на русском они тоже отвечают.
> 
> Хочешь прикол? ![Скриншот 27 09 24_23 25 02](https://private-user-images.githubusercontent.com/38662040/371641147-26208839-eb18-478d-a467-111088dd1c48.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NjQ4NzMsIm5iZiI6MTcyNzQ2NDU3MywicGF0aCI6Ii8zODY2MjA0MC8zNzE2NDExNDctMjYyMDg4MzktZWIxOC00NzhkLWE0NjctMTExMDg4ZGQxYzQ4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDE5MTYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4NmM2NTcxMGM4MmZiYWQxYTVlYjU1NjQ0ZTIxYjVlYzU4NTAzMzdhMjA4YWZlZGZkOTBiYmM0ODQzMzRhMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZdB5hzzq3Hm5b6TbvR6bTwqVeJM7CcoGAdAJkOCyXoI)
> 
> Если в смартфоне впн работает прекрасно то почему бы не перебросить его через кабель на компьютер? Это было и сделано.... Теперь и на ПК есть высокоскоростной впн из смартфона! Для этого нужно всего лишь андроид смартфон с рут правами. Такой фокус на яблоке невозможно сделать...

Ping не правильный показывает, так как маршрутизация то идет ведь не до сервера в Хельсинки, а до какого-то провайдера в России. И я уже писал что на Финляндии проблема есть - там пинг постоянно скачет от 30 мс до 80-100 мс по данным самой программы Adguard. Наиболее стабильные сервера Германия и Дания.

**Comment by Eksol** [comment]
> И я уже писал что на Финляндии проблема есть - там пинг постоянно скачет от 30 мс до 80-100 мс по данным самой программы Adguard.

В телефоне финский сервер самый быстрый. Дает под 200мб. 
Проверил сервер дании на пк. Скорость уже по лучше чем финский. Но пинги такие же ужасные 150мс.

**Comment by Eksol** [comment]
Минут через 20 просмотра ютуб, впн отваливается. Программа пишет подключено но скорость загрузки 0
