### ISSUE TITLE
The AdGuard VPN icon when closing the program disappears in the hidden taskbar icons in version 0.0.168.0

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/AdGuardVPNForWindows#74]
The AdGuard VPN icon when closing the program disappears in the hidden taskbar icons in version 0.0.168.0 and the program continues to work.

Starting with the operating system the icon is visible but when opening and closing the program the icon disappears from the taskbar

![image](https://user-images.githubusercontent.com/16819380/113527130-f00bc880-9592-11eb-82bb-774af4cae87d.png)

![Captura de tela 2021-04-04 221507](https://user-images.githubusercontent.com/16819380/113527249-4e38ab80-9593-11eb-8011-2454ecb3e1c0.png)

**Comment by zzebrum** [comment]
@eduardoaddad yep, it's a known bug, thank you! Should be fixed in the next update!
