### ISSUE TITLE
Add protocol and packet loss info to Diagnostic data

### ISSUE THREAD

**Issue by shamarin** [AdguardTeam/AdGuardVPNForWindows#740]
### Issue Details

Сейчас на Андройд в разделе диагностических данных гораздо больше информации отображается, чем в клиенте для Windows.

### Proposed solution

Добавьте туда тоже используемый протокол, количество принятой и полученной информации и уровень потерь пакетов.

**Comment by shamarin** [comment]
![Screenshot_2024-09-24-07-35-21-420_com adguard vpn](https://github.com/user-attachments/assets/4462fc0b-3600-4567-ad16-e8e227c37532)

**Comment by shamarin** [comment]
![IMG_20240924_073751](https://github.com/user-attachments/assets/043fb880-4089-4740-a6dd-9e3618d9eda8)

**Comment by shamarin** [comment]
![IMG_20240924_073918](https://github.com/user-attachments/assets/f81fdc02-1ed5-4cc4-9ec9-f75ece715217)

**Comment by Eksol** [comment]
Зачем это нужно?

**Comment by shamarin** [comment]
> Зачем это нужно?

Чтобы видеть состояние соединения, насколько оно стабильное с той или иной локацией.

**Comment by Aydinv13** [comment]
@shamarin на данный момент не рассматриваем добавление дополнительной информации в Diagnostic data для десктопных приложений, спасибо за предложение.
