### ISSUE TITLE
High ping, low connection speeds

### ISSUE THREAD

**Issue by Eksol** [AdguardTeam/AdGuardVPNForWindows#742]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.4.0

### Environment

```markdown
- OS: Windows 10
- Other network-level software: GoodByeDPI, ADguard
```

### Which DNS server do you use?

AdGuard DNS

### Use Wintun

- [X] yes, I do

### Issue Details

Steps to reproduce: 
1. run ping test on site from win version https://www.meter.net/tools/world-ping-test/
2. run ping test on site from Andriod version https://www.meter.net/tools/world-ping-test/

### Expected Behavior

The average ping result should be similar.

### Actual Behavior

Result difference.
windows version 150ms
android version 80ms

### Screenshots

<details><summary>Screenshot 1</summary>

![Скриншот 26 09 24_00 57 50](https://github.com/user-attachments/assets/9f209cd0-605f-43f5-b1e2-635fc4105f13)
![Скриншот 26 09 24_00 55 57](https://github.com/user-attachments/assets/eba53e34-4b46-44a2-8243-c586687f1016)

</details>

**Comment by shamarin** [comment]
The same network and the same location???

**Comment by Eksol** [comment]
> The same network and the same location?

Yes

**Comment by AlexandrPkhm** [comment]
@Eksol Hello! 

In order to diagnose and troubleshoot this issue, we need to get your application logs.
Here's what we need you to do:

1. Go to *Settings → App settings → Logging level → Record everything*.
2. Reproduce the problem, then remember the exact time it happened.
3. Open *Support tab → Export logs and system info*.
4. Send the archive to [qa@adguard.com](mailto:qa@adguard.com):
		- include `[windows]` keyword and `ISSUE_NUMBER` in the subject of your email
		- specify the exact time when the issue occurred

**Comment by Eksol** [comment]
> we need to get your application logs.

Done

**Comment by AlexandrPkhm** [comment]
@Eksol As we can also see you are using GoodByeDPI. Could you please try to disable it and check if the issue persists without it?

**Comment by Eksol** [comment]
> Could you please try to disable it and check if the issue persists without it?

Tried it. It didn't help. Ping remains high.
The same problem with high ping is observed in the version for openwrt routers. Adguardvpn-cli

**Comment by AlexandrPkhm** [comment]
@Eksol Could you please try to connect to the same server on Windows and Android devices and check **Diagnostic info section** in application settings. After this is done, please send the contents of **Diagnostic info section** for both apps to [qa@adguard.com](mailto:qa@adguard.com). Also include [windows] keyword and ISSUE_NUMBER in the subject of your email.

**Comment by Eksol** [comment]
> **Diagnostic info section** for both apps

Done

**Comment by AlexandrPkhm** [comment]
@Eksol The only difference seems to be IPv6 usage in the Windows version. Could you please try to disable IPv6 in Network connections on your Windows device and check if the speed/ping got better?

**Comment by Eksol** [comment]
> Could you please try to disable IPv6 in Network

I tried disabling ipv6 for Realtek PCIe GbE Family Controller 
Now, after turning on the VPN, I can't open any websites.

**Comment by Eksol** [comment]
> @Eksol The only difference seems to be IPv6 usage in the Windows version. Could you please try to disable IPv6 in Network connections on your Windows device and check if the speed/ping got better?

After several reboots, the Internet started working. I off ipv6 for Realtek PCIe GbE Family Controller. 
Afterwards I ran tests.
Ping is just as bad, 150ms.
The speed 20mbps. 

The problem persists

**Comment by Eksol** [comment]
Success to repeat the problem in android version AdguardVpnForAndriod

If you enable IPv6 interface in the settings apps Adguard VPN, this leads to a speed failure in the android version.
Ping remains low, 55ms, but speeds drop to 20mbps.

**Comment by Eksol** [comment]
![Скриншот 27 09 24_23 25 02](https://github.com/user-attachments/assets/915920c1-837f-4b02-b77f-1771ed9eab5d)

Developers. You have serious problems with the Windows application. As you can see, I was able to transfer the VPN from my smartphone to my computer and still get high connection speeds. This once again confirms that there are problems with the Windows program.

**Comment by Eksol** [comment]
When the smartphone is used as a modem with a VPN running, the ping problem is solved!

![Скриншот 27 09 24_23 32 31](https://github.com/user-attachments/assets/02e1ab19-3ff5-4b71-b5c8-29a37d9569dd)

It's pointless to fight against VPN distribution. Root rights are used.

**Comment by AlexandrPkhm** [comment]
@Eksol One more question. Does enabling `Wintun` driver in Advanced settings affects speed?

**Comment by Eksol** [comment]
> One more question. Does enabling `Wintun` driver in Advanced settings affects speed?

Winton does not affect the speed or ping.
Disabling IPv6 in the adguardvpn tunnel adapter does not help.
The last beta version led to a blue screen. Rolled back to the release version.

Need to disable ipv6 inside adguardvpn

**Comment by AlexandrPkhm** [comment]
@Eksol Could you please open Powershell and run the following commands:
`tracert 141.11.244.151`
`tracert 45.135.181.109`
After this is done please send the result to us.

**Comment by Eksol** [comment]
Трассировка маршрута к 141.11.244.151 с максимальным числом прыжков 30

  1     *        *        *     Превышен интервал ожидания для запроса.
  2     *        *        *     Превышен интервал ожидания для запроса.
  3     *        *        *     Превышен интервал ожидания для запроса.
  4     *        *        *     Превышен интервал ожидания для запроса.
  5     *        *        *     Превышен интервал ожидания для запроса.
  6     *        *        *     Превышен интервал ожидания для запроса.
  7     *        *        *     Превышен интервал ожидания для запроса.
  8     *        *        *     Превышен интервал ожидания для запроса.
  9     *        *        *     Превышен интервал ожидания для запроса.
 10     *        *        *     Превышен интервал ожидания для запроса.


Трассировка маршрута к 45.135.181.109 с максимальным числом прыжков 30

  1     *        *        *     Превышен интервал ожидания для запроса.
  2     *        *        *     Превышен интервал ожидания для запроса.
  3     *        *        *     Превышен интервал ожидания для запроса.
  4     *        *        *     Превышен интервал ожидания для запроса.
  5     *        *        *     Превышен интервал ожидания для запроса.
  6     *        *        *     Превышен интервал ожидания для запроса.
  7     *        *        *     Превышен интервал ожидания для запроса.
  8     *        *        *     Превышен интервал ожидания для запроса.
  9     *        *        *     Превышен интервал ожидания для запроса.
 10     *        *        *     Превышен интервал ожидания для запроса.

**Comment by Eksol** [comment]
> Could you please open Powershell and run the following commands:

Трассировка маршрута к 141.11.244.151 с максимальным числом прыжков 30

1 * * * Превышен интервал ожидания для запроса.
2 * * * Превышен интервал ожидания для запроса.
3 * * * Превышен интервал ожидания для запроса.
4 * * * Превышен интервал ожидания для запроса.
5 * * * Превышен интервал ожидания для запроса.
6 * * * Превышен интервал ожидания для запроса.
7 * * * Превышен интервал ожидания для запроса.
8 * * * Превышен интервал ожидания для запроса.
9 * * * Превышен интервал ожидания для запроса.
10 * * * Превышен интервал ожидания для запроса.

Трассировка маршрута к 45.135.181.109 с максимальным числом прыжков 30

1 * * * Превышен интервал ожидания для запроса.
2 * * * Превышен интервал ожидания для запроса.
3 * * * Превышен интервал ожидания для запроса.
4 * * * Превышен интервал ожидания для запроса.
5 * * * Превышен интервал ожидания для запроса.
6 * * * Превышен интервал ожидания для запроса.
7 * * * Превышен интервал ожидания для запроса.
8 * * * Превышен интервал ожидания для запроса.
9 * * * Превышен интервал ожидания для запроса.
10 * * * Превышен интервал ожидания для запроса.

**Comment by AlexandrPkhm** [comment]
@Eksol Благодарим за предоставленные данные. Мы передадим Вашу проблему команде разработки. 

Как мы понимаем, данная задача связана с https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/739. Мы закроем ее в качестве дубликата, а все работы будут проводиться в данной задаче.

**Comment by shamarin** [comment]
Исправление явно не скоро появится, судя по тому как моё #693  до сих пор не исправлено с лета

**Comment by Eksol** [comment]
> Исправление явно не скоро появится, судя по тому как моё #693 до сих пор не исправлено с лета

да чую что снова забьют...

**Comment by Eksol** [comment]
Подключил свой телефон с включенным впн к компьютеру в режиме модема и запустил. Пока что буду пользоваться так, так как на роутере впн от адгуарда очень плохой. На пк версии тоже скорость очень слабая. Остается только через смартфон.

**Comment by shamarin** [comment]
> > Could you please open Powershell and run the following commands:
> 
> Трассировка маршрута к 141.11.244.151 с максимальным числом прыжков 30
> 
> 1 * * * Превышен интервал ожидания для запроса. 2 * * * Превышен интервал ожидания для запроса. 3 * * * Превышен интервал ожидания для запроса. 4 * * * Превышен интервал ожидания для запроса. 5 * * * Превышен интервал ожидания для запроса. 6 * * * Превышен интервал ожидания для запроса. 7 * * * Превышен интервал ожидания для запроса. 8 * * * Превышен интервал ожидания для запроса. 9 * * * Превышен интервал ожидания для запроса. 10 * * * Превышен интервал ожидания для запроса.
> 
> Трассировка маршрута к 45.135.181.109 с максимальным числом прыжков 30
> 
> 1 * * * Превышен интервал ожидания для запроса. 2 * * * Превышен интервал ожидания для запроса. 3 * * * Превышен интервал ожидания для запроса. 4 * * * Превышен интервал ожидания для запроса. 5 * * * Превышен интервал ожидания для запроса. 6 * * * Превышен интервал ожидания для запроса. 7 * * * Превышен интервал ожидания для запроса. 8 * * * Превышен интервал ожидания для запроса. 9 * * * Превышен интервал ожидания для запроса. 10 * * * Превышен интервал ожидания для запроса.

@AlexandrPkhm впричем такая картина с любым адресом, когда включен Adguard VPN, т.е если набирать 
`tracert yandex.ru`
То ответ будет типа такого:
 ```
1     *        *        *     Превышен интервал ожидания для запроса.
  2     *        *        *     Превышен интервал ожидания для запроса.
  3     *        *        *     Превышен интервал ожидания для запроса.
  4     *        *        *     Превышен интервал ожидания для запроса.
  5     *        *        *     Превышен интервал ожидания для запроса.
  6     *        *        *     Превышен интервал ожидания для запроса.
  7     *        *        *     Превышен интервал ожидания для запроса.
  8     *        *        *     Превышен интервал ожидания для запроса.
  9   110 ms   110 ms   110 ms  yandex.ru [5.255.255.77]
```
По указанным выше адресам у меня трассировка тоже не проходит (сервер Дания, Финляндия), Wintun включен и QUIC тоже.
Трассировка с включенным Kaspersky VPN используя Wintun, сервер Финляндия
```
Трассировка маршрута к yandex.ru [77.88.55.88]
с максимальным числом прыжков 30:

  1    62 ms    62 ms    63 ms  10.234.0.0
  2    62 ms    62 ms    62 ms  172.18.0.1
  3    80 ms    84 ms    77 ms  irb-116.agg2.thg1.nl.m247.ro [2.58.44.37]
  4    65 ms     *       65 ms  be-2-3921.bb1n.ams2.nl.m247.ro [217.138.223.238]
  5    64 ms    64 ms    64 ms  adm-b3-link.ip.twelve99.net [62.115.154.74]
  6    64 ms    64 ms    64 ms  adm-bb1-link.ip.twelve99.net [62.115.136.220]
  7    84 ms    84 ms    84 ms  sto-bb1-link.ip.twelve99.net [62.115.136.150]
  8    90 ms    90 ms    90 ms  hls-b4-link.ip.twelve99.net [62.115.123.27]
  9    93 ms    92 ms    92 ms  80.239.215.42
 10     *      112 ms   112 ms  sas-32z8-lag-2.yndx.net [87.250.239.213]
 11     *        *        *     Превышен интервал ожидания для запроса.
 12   110 ms   110 ms   110 ms  yandex.ru [77.88.55.88]
```
Не понятно почему с Adguard только конечный узел показывает в результатах, обратил на это внимание еще летом, но не стал создавать ошибку, так как может это нормальное поведение?
И плюс на той же Финляндии ping постоянно пляшет - 30 мс, потом через пару секунд уже 90 или 100 мс по данным самой же программы. Плюс пинг тоже увеличивается когда торрент клиент активно работает.

**Comment by Eksol** [comment]
> впричем такая картина с любым адресом, когда включен Adguard VPN, т.е если набирать

только не в том случае когда на ПК впн подается через телефон. В таком случае трассировка отвечает переадресацией на другой ip.  
Я попробовал понасиловать этот впн через телефон. Узнать границы так скажем. Запустил торрент и начал смотреть как быстро он сдохнет. Где то на 8 гб скачанных файлов, впн сдох. На телефоне он работал а на пк нет. торрент видел раздачу но загрузку не мог начать. Предполагаю блокировку ip со стороны самого adguard так как провайдер не может увидеть трафик внутри туннеля, так что провайдер тут ну никак не может блокировать. 

Поэтому если часто начать делать тесты, смотреть ютуб в 4к то можно запросто улететь в бан.

**Comment by Eksol** [comment]
Кстати пинги тоже выросли. Некоторые сайты вообще не пинговались. И это все через смартфон в режиме модема
![Скриншот 30 09 24_22 48 01](https://github.com/user-attachments/assets/fa7e63c0-1617-45c2-826b-7e4772628f5e)

**Comment by Eksol** [comment]
Попробовал версию adguardcli под линукс, результат такой же. Высокий пинг и низкие скорости.

**Comment by Eksol** [comment]
После недавнего обновления серверов, проблема с низкими скоростями ушла. Теперь и на пк пинг 80мс и скорость в спидтесте приличная. 
Правда, показатель пинга в приложении так же показывает попугаи и приходится вручную проверять сервера на пинг.

**Comment by shamarin** [comment]
> После недавнего обновления серверов, проблема с низкими скоростями ушла. Теперь и на пк пинг 80мс и скорость в спидтесте приличная. Правда, показатель пинга в приложении так же показывает попугаи и приходится вручную проверять сервера на пинг.

с Wintun наоборот скорость ниже стала.

**Comment by shamarin** [comment]
#726 интересные наблюдения сделал. Думаю к этому это тоже относится. И вопрос, когда уже наконец разработчики исправят данные ошибки? Со скоростью соединения и с задержками реально беда, как и работа приложения с торрент клиентом одновременно.

**Comment by shamarin** [comment]
> После недавнего обновления серверов, проблема с низкими скоростями ушла. Теперь и на пк пинг 80мс и скорость в спидтесте приличная. Правда, показатель пинга в приложении так же показывает попугаи и приходится вручную проверять сервера на пинг.

Только вот работу одновременно с торрент клиентом не исправили. Wintun нагружает процессор сильно. В последней ночной сборке, которая исправляет данную проблему проблема не ушла полностью. QUIC если включить, то коннект полностью теряет VPN спустя некоторое время. И в любом случае что с Wintun что без него одновременно с торрентом скорость VPN соединения дико падает, хотя ширина канала в моем случае должна быть в таком случае 30-40 Мбит. А она ниже (3-5 Мбит) и таким образом даже видео не посмотреть нормально. Speedtest в таком случае странно себя ведет - скорость скачивания 3-5 Мбит, а скорость закачки (отдачи) 84 Мбит. И чет тишина от разработчиков, поправят или нет данные проблемы.

**Comment by Eksol** [comment]
> > После недавнего обновления серверов, проблема с низкими скоростями ушла. Теперь и на пк пинг 80мс и скорость в спидтесте приличная. Правда, показатель пинга в приложении так же показывает попугаи и приходится вручную проверять сервера на пинг.
> 
> Только вот работу одновременно с торрент клиентом не исправили. Wintun нагружает процессор сильно. В последней ночной сборке, которая исправляет данную проблему проблема не ушла полностью. QUIC если включить, то коннект полностью теряет VPN спустя некоторое время. И в любом случае что с Wintun что без него одновременно с торрентом скорость VPN соединения дико падает, хотя ширина канала в моем случае должна быть в таком случае 30-40 Мбит. А она ниже (3-5 Мбит) и таким образом даже видео не посмотреть нормально. Speedtest в таком случае странно себя ведет - скорость скачивания 3-5 Мбит, а скорость закачки (отдачи) 84 Мбит. И чет тишина от разработчиков, поправят или нет данные проблемы.

У меня и без торрента скорость на ютубе маленькая.

**Comment by shamarin** [comment]
> > > После недавнего обновления серверов, проблема с низкими скоростями ушла. Теперь и на пк пинг 80мс и скорость в спидтесте приличная. Правда, показатель пинга в приложении так же показывает попугаи и приходится вручную проверять сервера на пинг.
> > 
> > 
> > Только вот работу одновременно с торрент клиентом не исправили. Wintun нагружает процессор сильно. В последней ночной сборке, которая исправляет данную проблему проблема не ушла полностью. QUIC если включить, то коннект полностью теряет VPN спустя некоторое время. И в любом случае что с Wintun что без него одновременно с торрентом скорость VPN соединения дико падает, хотя ширина канала в моем случае должна быть в таком случае 30-40 Мбит. А она ниже (3-5 Мбит) и таким образом даже видео не посмотреть нормально. Speedtest в таком случае странно себя ведет - скорость скачивания 3-5 Мбит, а скорость закачки (отдачи) 84 Мбит. И чет тишина от разработчиков, поправят или нет данные проблемы.
> 
> У меня и без торрента скорость на ютубе маленькая.

Если без запущенного торрента, то на последней ночной сборке у меня скорость на Ютуб приличная. С Wintun кстати скорость выше действительно. Сейчас смотрю ускорили сервер Финляндия.

**Comment by Eksol** [comment]
Разрабы вы вообще собираетесь исправлять проблему? Ютуб как тупел так и тупит!

**Comment by shamarin** [comment]
> Разрабы вы вообще собираетесь исправлять проблему? Ютуб как тупел так и тупит!

У меня с последней ночной сборкой отлично всё по скорости даже с HTTP/2

**Comment by adbuker** [comment]
@Eksol , попробуйте, пожалуйста, последнюю найтли. Мы ни в коем случае не забыли и уже влили изменения на этот счёт

**Comment by Eksol** [comment]
> попробуйте, пожалуйста, последнюю найтли.

Попробовал. Дефект ушел. Ютуб теперь можно в FHD смотреть. На планшете android тормоза дикие, качество 144p!!!!

**Comment by adbuker** [comment]
@Eksol , отлично, скоро будет в бете, а потом и в релизе!

**Comment by shamarin** [comment]
> @Eksol , отлично, скоро будет в бете, а потом и в релизе!

Версия 2.5? Если так, то её еще на ночной сборке не было даже.

**Comment by adbuker** [comment]
@shamarin , на ночной 2.4 пока, изменим номер вот-вот

**Comment by shamarin** [comment]
> @shamarin , на ночной 2.4 пока, изменим номер вот-вот

Т.е в ближайшее время выйдет версия 2.5 ночная сборка?

**Comment by adbuker** [comment]
@shamarin , ага, именно так :)

**Comment by Eksol** [comment]
> отлично, скоро будет в бете, а потом и в релизе!

Тормоза вернулись. Ютуб снова в качестве 360p!

**Comment by Eksol** [comment]
Бывает секунд 10 грузится при вот такой скорости. 
![Скриншот 11 12 24_00 50 06](https://github.com/user-attachments/assets/4d5fbf19-d90f-4cf6-8a53-a5c1a78ce57e)
