### ISSUE TITLE
User can't authorize in app

### ISSUE THREAD

**Issue by dksspbuo** [AdguardTeam/AdGuardVPNForWindows#743]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

AdGuardVpn-2.4.1-Beta-1-.1483

### Environment

```markdown
- OS: win10
- Other network-level software:AdGuard ad blocker 7.18.1
сеть Beeline СПб
```

### Which DNS server do you use?

Default

### Use Wintun

- [ ] yes, I do

### Issue Details

Steps to reproduce:
1.Download
2.start
3.enter email
4.enter pass
Что-то пошло не так. Сервер не отвечает

### Expected Behavior

VPN

### Actual Behavior

Даже не логинится.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by dksspbuo** [comment]
AdGuardVpn-2.3.0-.1400 после переустановки работает, но недолго.

**Comment by KolbasovAnton** [comment]
@dksspbuo Здравствуйте. Пожалуйста, переустановите последнюю бету ещё раз и воспроизведите проблему с расширенными логами. Как это сделать:

1. [Как запустить приложение с расширенными логами](https://adguard.info/kb/ru/adguard-for-windows/solving-problems/adguard-logs/#trace-logs).
2. Воспроизведите проблему и запомните точное время её воспроизведения.
3. Найдите и архивируйте папку **Logs** по адресу `C:\ProgramData\AdguardVpn\Logs` (это скрытая папка).
4. Отправьте полученный архив по адресу [qa@adguard.com](mailto:qa@adguard.com): 
	- в теме письма укажите ключевое слово `[windows]` и `НОМЕР_ЗАДАЧИ`
	- укажите точное время, когда возникла проблема.

**Comment by KolbasovAnton** [comment]
> AdGuardVpn-2.3.0-.1400 после переустановки работает, но недолго.

Каким образом приложение перестаёт работать?
