### ISSUE TITLE
All servers are disappeared.

### ISSUE THREAD

**Issue by Vitalik93** [AdguardTeam/AdGuardVPNForWindows#745]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.4.0 (1475)

### Environment

```markdown
- OS: Windows 10, 21H2 (OS build 19044.2006)
- Other network-level software: Kaspersky Standart
```

### Which DNS server do you use?

Default

### Use Wintun

- [ ] yes, I do

### Issue Details

Steps to reproduce:
1. Open Adguard VPN
2. Check locations

### Expected Behavior

Adguard VPN will show you all locations.

### Actual Behavior

There are no locations in Adguard VPN.

### Screenshots

![Снимок экрана 2024-10-03 155527](https://github.com/user-attachments/assets/52c76c36-2af2-4c9b-9cc3-419d1959e14f)

**Comment by mccabedd** [comment]
Happening at my end as well. Windows and Android.

Never mind. Migration maintenance: https://status.adguard.com/

**Comment by Vitalik93** [comment]
Now it works fine!
