### ISSUE TITLE
Make a single location list sorted by ping

### ISSUE THREAD

**Issue by Eksol** [AdguardTeam/AdGuardVPNForWindows#746]
### Issue Details

На выбор дается только первые 3 сервера как самых быстрых, не смотря на то что внизу, в списках могут быть и другие быстрые серверы, но их приходится очень долго искать так как они не отсортированы.

### Proposed solution

Предлагаю УБРАТЬ деление на быстрые локации и все локации, и пусть будет один единый список который будет отсортирован по пингу.
![Скриншот 04 10 24_11 27 22](https://github.com/user-attachments/assets/33095272-4ffe-47d2-9723-8aa851bc96c5)

**Comment by shamarin** [comment]
Еще лучше добавить отметку премиального сервера (локации), так как судя по служебной информации приложения некоторые сервера не премиальные, например, Финляндия.

**Comment by Aydinv13** [comment]
@Eksol 

Текущий принцип был реализован потому, что сортировка в алфавитном порядке лучше воспринимается, а для подключения к быстрейшим локации есть отдельная секция. Поэтому сортировку всех локаций по пингу мы сейчас не рассматриваем.
В будущем мы планируем добавить "Избранные", куда можно будет добавлять нужные юзеру локации.

**Comment by shamarin** [comment]
> @Eksol
> 
> Текущий принцип был реализован потому, что сортировка в алфавитном порядке лучше воспринимается, а для подключения к быстрейшим локации есть отдельная секция. Поэтому сортировку всех локаций по пингу мы сейчас не рассматриваем. В будущем мы планируем добавить "Избранные", куда можно будет добавлять нужные юзеру локации.

А помечать премиальные локации планируете? Сейчас если смотреть на служебную информацию и там некоторые локации помечаются как "premium only: true"
