### ISSUE TITLE
The app shows incorrect pings

### ISSUE THREAD

**Issue by Eksol** [AdguardTeam/AdGuardVPNForWindows#747]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.4.0

### Environment

```markdown
- OS:Windows 10
- Other network-level software: AdGuard For Windows
```

### Which DNS server do you use?

AdGuard DNS

### Use Wintun

- [X] yes, I do

### Issue Details

Perform a comparative analysis of ping indicators with the site https://www.meter.net/tools/world-ping-test/
Because the ping measurement built into the application shows an inaccuracy, you have to check each server manually.

![Скриншот 04 10 24_21 03 08](https://github.com/user-attachments/assets/e65dcf8c-a28b-4c4f-8f15-b7c27101cbaa)
![Скриншот 04 10 24_21 02 36](https://github.com/user-attachments/assets/74f93ca4-928a-46da-9cb4-20f2e36e734f)
![Скриншот 04 10 24_21 01 23](https://github.com/user-attachments/assets/1a8d31bb-0271-40f9-9aa7-29847b89d8d8)
![Скриншот 04 10 24_21 00 57](https://github.com/user-attachments/assets/f72834fb-afd0-4951-a996-7e6324ea23b3)
![Скриншот 04 10 24_21 00 27](https://github.com/user-attachments/assets/ffe5d514-9762-46fc-855c-2019eb331415)
![Скриншот 04 10 24_20 59 49](https://github.com/user-attachments/assets/345821c9-1e43-443e-af90-19cd3e215b43)

### Expected Behavior

The ping values ​​should match.

### Actual Behavior

Ping values ​​vary both up and down.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by Eksol** [comment]
![1001ecc79a5d22d4a7890e28837860e1](https://github.com/user-attachments/assets/bd47bc72-fcdd-4fbd-9be7-300e2ddc1762)

**Comment by Aydinv13** [comment]
@Eksol Hi there!

Could you say what you are comparing and what you are comparing to in your case?

**Comment by Eksol** [comment]
> Could you say what you are comparing and what you are comparing to in your case?

Ping on the site ( https://www.meter.net/tools/world-ping-test/ ) with ping in the application

**Comment by Aydinv13** [comment]
If you want to know the exact ping, you can use the command `ping -c 5 %location_ip% | grep 'avg' | awk -F '/' '{print $5}'`. The site you are using is probably pinging the different servers than in the app.
