### ISSUE TITLE
Adguard not working for Twitter on Edge, in selective mode

### ISSUE THREAD

**Issue by KirbyFan102** [AdguardTeam/AdGuardVPNForWindows#748]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.4.0

### Environment

```markdown
- OS: Windows 10
- Other network-level software: Microsoft Edge
```

### Which DNS server do you use?

Default

### Use Wintun

- [ ] yes, I do

### Issue Details

Steps to reproduce:
1. Enable Selective Mode.
2. Add Twitter, and only Twitter
3. Try to access any Twitter page

### Expected Behavior

Twitter page is successfully accessed.

### Actual Behavior

Twitter page cannot be accessed.

### Additional Information

It only works if I add both the browser itself (Microsoft Edge) _and_ Twitter to the list of exclusions. Otherwise it either doesn't load at all or loads just the interface and not the content.

**Comment by Eksol** [comment]
I have the same problem but only in adguardvpn-cli

**Comment by AlexandrPkhm** [comment]
Hi @Eksol, 

Could you please clarify if Selective mode is enabled only for Websites or for Apps as well as Websites?

**Comment by Eksol** [comment]
> Hi @Eksol,
> 
> Could you please clarify if Selective mode is enabled only for Websites or for Apps as well as Websites?

This problem was solved by adding a few more Twitter domains to the list for routing via VPN.

https://github.com/AdguardTeam/AdGuardVPNCLI/issues/61

**Comment by Eksol** [comment]
*.ggpht.com
*.googleapis.com
*.googlevideo.com
*.twimg.com
*.twitter.com
*.ytimg.com
195.201.201.32
2ip.ru
adguard-vpn.com
api.twitter.com
chatgpt.com
gvt1.com
instagram.com
m.youtube.com
meter.net
rutracker.org
speedtest.net
st.com 
t.co
twitter.com
x.com
youtu.be
youtube-nocookie.com
youtube.com
youtubeeducation.com


this is my exclusions list

**Comment by KirbyFan102** [comment]
> *.ggpht.com *.googleapis.com *.googlevideo.com *.twimg.com *.twitter.com *.ytimg.com 195.201.201.32 2ip.ru adguard-vpn.com api.twitter.com chatgpt.com gvt1.com instagram.com m.youtube.com meter.net rutracker.org speedtest.net st.com t.co twitter.com x.com youtu.be youtube-nocookie.com youtube.com youtubeeducation.com
> 
> this is my exclusions list

Which ones affect Twitter? I would like to try this solution out

**Comment by Eksol** [comment]
> Which ones affect Twitter? I would like to try this solution out

*.twimg.com
*.twitter.com
api.twitter.com
t.co
twitter.com
x.com

**Comment by AlexandrPkhm** [comment]
@Eksol We are glad to hear that the issue was resolved. 
As to lists of additional services related domains. Our desktop and mobile VPN apps allow adding lists of exclusions containing all domains for certain services. To do so, please press `+ Add website` and select `From the list` option. Unfortunately, VPN CLI doesn't have this feature at this time.

**Comment by KirbyFan102** [comment]
> @Eksol We are glad to hear that the issue was resolved. As to lists of additional services related domains. Our desktop and mobile VPN apps allow adding lists of exclusions containing all domains for certain services. To do so, please press `+ Add website` and select `From the list` option. Unfortunately, VPN CLI doesn't have this feature at this time.

Hey, I would just like to point out that my problem is still not solved. I selected Twitter from the list and that didn't work. It was one of the first things I did. Please reopen this issue.

While I'm glad that Eksol solved it on their end, that's not the case for me. And I was the one who opened it to begin with.

**Comment by KirbyFan102** [comment]
@AlexandrPkhm Hello?
