### ISSUE TITLE
Список избранных серверов

### ISSUE THREAD

**Issue by zarif-mironenko** [AdguardTeam/AdGuardVPNForWindows#749]
### Issue Details

Сейчас, чтобы найти нужный сервер, нужно или листать длинный список, или каждый раз вносить в строку поиска название локации.
Хотелось бы иметь возможность добавить список избранных локаций серверов.

### Proposed solution

Было бы удобно, чтобы был и общий список серверов, и список избранных.

Возможно в виде 2 отдельных вкладок в блоке списка серверов на вкладке Главная.
Или в меню в верхней панели сделать вкладку Избранное, как сделана вкладка Исключения.

**Comment by KolbasovAnton** [comment]
@zarif-mironenko Здравствуйте, реализация данной фичи планируется в относительно скором релизе v2.5. Спасибо за советы!
