### ISSUE TITLE
Make application window user resizable and utilize extra space for server list

### ISSUE THREAD

**Issue by peace2000** [AdguardTeam/AdGuardVPNForWindows#750]
### Issue Details

Currently, the window of the AG VPN isn't user resizable. For more flexibility, can you make it work like a typical window in Windows File explorer?

Also, when clicking the application window to go full screen form, there is quite a lot wasted space that could be utilised to show more servers at the same time -> would be quicker to browse through the server list.

Currently it looks this in full screen:

![kuva](https://github.com/user-attachments/assets/851dd687-bf68-4785-84ef-11fd41c24ccd)

### Proposed solution

To make the application window user resizable and utilise wasted space better in full screen form:

![kuva](https://github.com/user-attachments/assets/b93b66c5-0b55-4373-a968-f7b6babe1508)

### Alternative solution

Actually I realized that there is no need to have that much space between the ping value and the server name so I squeezed the view a bit:

![kuva](https://github.com/user-attachments/assets/a65c1223-c037-4513-afe2-332f43ba6c2e)

The unused space in the middle could be used for something else or just enlarge the ninja picture :)

**Comment by Aydinv13** [comment]
@peace2000 Hello!

Actually, the main window is not supposed to be resizable, so we will fix it. I'm gonna create a new issue.
As for the option itself, we are not planning to do it. Thanks for reaching out to us.
