### ISSUE TITLE
Reconnecting when a user is blocked

### ISSUE THREAD

**Issue by Yoojexo** [AdguardTeam/AdGuardVPNForWindows#754]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.4.1 Beta

### Environment

```markdown
- OS: Windows 11, 24H2
- Other network-level software: No
```

### Which DNS server do you use?

AdGuard DNS

### Use Wintun

- [ ] yes, I do

### Issue Details

Steps to reproduce:
1. We connect to any location.
2. Blocking the PC.
3. Unlock the PC.

### Expected Behavior

Continued work, without any problems.

### Actual Behavior

The VPN is disconnected and reconnected. This causes all active connections to stop working.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by Aydinv13** [comment]
@Yoojexo Hi there!

The system may behave unpredictably, which can lead to information leakage. We use a method (reconnection) where connections are dropped before a new channel is established, so this option is the safest in terms of protecting anonymity.
