### ISSUE TITLE
It is impossible to log in after a clean reinstall, on another device where you are logged in, the servers are almost always unavailable.

### ISSUE THREAD

**Issue by ilya-corneli** [AdguardTeam/AdGuardVPNForWindows#756]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.4.1 RC 1498

### Environment

```markdown
- OS: windows 11 24h2 
- Other network-level software: realtek 11.20.0729.2024
```

### Which DNS server do you use?

AdGuard DNS

### Use Wintun

- [ ] yes, I do

### Issue Details

Steps to reproduce:
1.Launching after any possible manipulations (reinstallation, reboot, clean reinstallation)
2. Does not skip authorization, even on old versions. I have no such problems on my smartphone. Sometimes it is possible to connect on another PC, but it is rare and does not depend on anything.
2(1). If you manage to connect on the second device, the Internet works fine, but sometimes a warning appears about a slow connection.  However, such an opportunity to connect to servers is too rare. The VPN simply became unworkable.

### Actual Behavior

![Снимок экрана 2024-10-28 132529](https://github.com/user-attachments/assets/4f03856d-a8fc-4306-a142-5df584c478cc)
![Снимок экрана 2024-10-28 132314](https://github.com/user-attachments/assets/b409cccc-c2c3-41b5-86a2-4fb1dbfdeb15)
![Снимок экрана 2024-10-28 105818](https://github.com/user-attachments/assets/d3bff97a-14eb-4f91-aefe-ec58a88441b1)
![Снимок экрана 2024-10-15 080006](https://github.com/user-attachments/assets/06aba803-f09a-49be-94d1-4bc163b22ecf)
![Снимок экрана 2024-10-24 065759](https://github.com/user-attachments/assets/483abc2b-af33-47bd-8c8d-8d7d9feef026)

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

Saint_Petersburg, SkyNet.

**Comment by AlexandrPkhm** [comment]
@ilya-corneli Hello! 

In order to troubleshoot this issue, we need to get your application logs.
Here's what we need you to do:

1. Go to *Settings -> App settings -> Logging level -> Record everything*.
2. Reproduce the problem, then remember the exact time it happened.
3. Open *Support tab -> Export logs and system info*.
4. Send the archive to [qa@adguard.com](mailto:qa@adguard.com):
	- include `[windows]` keyword and `ISSUE_NUMBER` in the subject of your email
	- specify the exact time when the issue occurred

**Comment by ilya-corneli** [comment]
Sent it off, the situation has improved a bit. 

> @ilya-corneli Hello!
> 
> In order to troubleshoot this issue, we need to get your application logs. Here's what we need you to do:
> 
> 1. Go to _Settings -> App settings -> Logging level -> Record everything_.
> 2. Reproduce the problem, then remember the exact time it happened.
> 3. Open _Support tab -> Export logs and system info_.
> 4. Send the archive to [qa@adguard.com](mailto:qa@adguard.com):
>    
>    * include `[windows]` keyword and `ISSUE_NUMBER` in the subject of your email
>    * specify the exact time when the issue occurred

Sent it off, the situation has improved a bit.

**Comment by AlexandrPkhm** [comment]
@ilya-corneli We have recently identified an issue with login and fixed it in the [recent release of AdGuard VPN for Windows 2.4.1](https://github.com/AdguardTeam/AdGuardVPNForWindows/releases/tag/v2.4.1). Could you please try to install it and let us know if the issue persists?

**Comment by ilya-corneli** [comment]
Пишет не удается получить доступ к сайту, ERR_CONNECTION_RESER, проблема с
авторизацией.

вт, 5 нояб. 2024 г. в 18:26, Alexandr ***@***.***>:

**Comment by ilya-corneli** [comment]
Это после установки приложения, сразу при попытки авторизации через
браузер.

вт, 5 нояб. 2024 г. в 19:01, x x ***@***.***>:

**Comment by ilya-corneli** [comment]
Авторизация прошла, теперь на всех 2 устройствах на windows 11, бесконечное
соединение, на ПК было лучше всё работало, на ноутбуке вобще не работало,
теперь нет соединения нигде хотя список серверов отображается.....
Пожалуйста помогите

вт, 5 нояб. 2024 г., 19:04 x x ***@***.***>:

**Comment by ilya-corneli** [comment]
После второй перезагрузки на ПК, сразу же соединилось, но так же вылез
отчёт об отправке ошибки.

вт, 5 нояб. 2024 г., 19:17 x x ***@***.***>:

**Comment by AlexandrPkhm** [comment]
@ilya-corneli Подскажите, пожалуйста, используете ли вы, какой-либо антивирус?

**Comment by ilya-corneli** [comment]
[image: Снимок экрана 2024-11-05 210624.png][image: Снимок экрана
2024-11-05 210638.png][image: Снимок экрана 2024-11-05 210650.png]
Только эти.
Фаервол отключал, не помогает


вт, 5 нояб. 2024 г. в 19:51, Alexandr ***@***.***>:

**Comment by ilya-corneli** [comment]
может хост файл почистить.

вт, 5 нояб. 2024 г. в 19:51, Alexandr ***@***.***>:

**Comment by ilya-corneli** [comment]
не помогло

вт, 5 нояб. 2024 г. в 19:51, Alexandr ***@***.***>:

**Comment by ilya-corneli** [comment]
При установке процесс авторизации занимал слишком много времени, после чего сервера обновлялись в течение длительного периода, а затем возникали проблемы бесконечного соединения с каждым. На персональных компьютерах и устройствах на базе Android подобных проблем не возникало, в то время как на ноутбуках сталкивались с одними и теми же сложностями.

**Comment by ilya-corneli** [comment]
У меня получилось установить соединение на третьем устройстве вот как. Я запустил приложение, проводились поиски сервера, затем произошло подключение. Перезапускал приложение несколько раз, и, когда сервера не отображались, активно обновлял страницу. В итоге, после нескольких попыток, удалось установить стабильное соединение с сервером. Логи удачной попытки соединения:

**Comment by ilya-corneli** [comment]
Последнее подключение скорее всего было исключением, я так же не могу установить соединение, на всех этапах это длится почти бесконечно.
Помогите, с пк, смартфоном таких проблем нет, только на ноутбуке.

**Comment by ilya-corneli** [comment]
https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/761#issuecomment-2459017641

вот эта версия 1601 значительно ускорила подключение, и мне сейчас удалось подключиться.
Почему мне никто из разработчиков не предложил ее попробовать?
Отпишусь, как дальше будет, поддержка очень медленная..

**Comment by ilya-corneli** [comment]
Nightly, версия помогла, соединение есть. Скиньте пожалуйста ссылку, где скачиваются Nightly, версии, вижу только бета и релиз

**Comment by AlexandrPkhm** [comment]
@ilya-corneli Рады слышать, что Nightly версия разрешила проблему. 

Для скачивания Nightly версий AdGuard VPN for Windows вы можете использовать данную ссылку - https://agrd.io/windows_vpn_nightly. Однако, если у вас уже установлена Nightly версия, то обновления на нее будут приходить именно из Nightly канала.
