### ISSUE TITLE
 Entered the wrong email when purchasing, support does not respond

### ISSUE THREAD

**Issue by DedEugene** [AdguardTeam/AdGuardVPNForWindows#757]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

This is my mistake, I did not enter the correct email when making a purchase, the difference with my real one is one letter, is it possible to do something about it?

**Comment by Nirineya** [comment]
Hello!

Please contact us at: support@adguard.com. Send us the email address you provided, your purchase confirmation, and the email address to which the subscription should be transferred. To help us find your message faster, please include the ticket number here on GitHub.

**Comment by zzebrum** [comment]
@DedEugene re-open the issue if your problem was not solved.
