### ISSUE TITLE
The application on the laptop with windows 11 stopped working.

### ISSUE THREAD

**Issue by hero1ine** [AdguardTeam/AdGuardVPNForWindows#761]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

The application on the laptop with windows 11 stopped working.

Laptops and phones are connected to the same network, everything works from the phones, everything works from the Windows 10 laptop, but the application stopped working from the Windows 11 laptop for no apparent reason. After reinstalling the program, I could not log into my account, after a number of failures I was able to connect to the VPN, I cannot find the reasons for this behavior. Tell me where to look?

**Comment by ilya-corneli** [comment]
тоже самое, только вот пк работает, а ноутбук отказывается работать с впн

**Comment by Aydinv13** [comment]
@hero1ine what do you mean by stopped working? Can you uninstall it using [Utility tool](https://cdn.adtidy.org/distr/windows/Uninstall_Utility.zip) and reinstall the latest [Nightly](https://agrd.io/windows_vpn_nightly), please.

**Comment by Aydinv13** [comment]
@hero1ine any news? Can you also check the latest [Nightly](https://agrd.io/windows_vpn_nightly) version.

**Comment by Aydinv13** [comment]
The issue was closed due to no answer. Can be reopened anytime if needed.
