### ISSUE TITLE
AdGuard VPN Release & Nightly version delete shortcut application after restarting PC Laptop

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardVPNForWindows#762]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

AdGuard VPN Nightly Version 2.4.1 Nightly 4

### Environment

```markdown
- OS: Windows 11 23H2
- Other network-level software: Bitdefender Total Security Anti-Virus
```

### Which DNS server do you use?

Custom DNS

### Use Wintun

- [X] yes, I do

### Issue Details

Steps to reproduce:
1. Having AdGuard VPN Release & Nightly Installed 
2. Then restart the Laptop
3. Once restarted open the VPN then a popup delete shortcut is shown.

### Expected Behavior

should be able to open AdGuard VPN for Windows

### Actual Behavior

The Shortcut for AdGuard VPN for Windows is deleted and can't reopen the VPN without uninstalling to Laptop and installing it again. 

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by Aydinv13** [comment]
@Batman2814 Please update to the latest Nightly. If it persists, please collect the debug logs.
<details><summary>Here's what we need you to do:</summary>

1. Go to Settings --> General --> App settings -->Advanced settings --> Logging level --> **Record everything**;
2. Reproduce the problem and remember the exact time it was reproduced at. We will need it to find the corresponding entries in the log file;
3. Go to Support -> **Export logs and system info**;
4. Send the archive to `qa@adguard.com` and mention this issue number in the subject. Don't forget to include the time of reproduction.
5. Set the logging level back to **Record by default**.
</details>

**Comment by Batman2814** [comment]
It's fixed the the current AdGuard VPN for Windows Release Version 2.4.1
