### ISSUE TITLE
"Slow internet connection" message when trying to use VPN

### ISSUE THREAD

**Issue by rmmQ90** [AdguardTeam/AdGuardVPNForWindows#765]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

Здравствуйте, перестал работать VPN. При подключении пишет что медленный интернет, хотя на speedtest 94mbps. Windows 10 pro. Не знаю даже в каком направлении копать

**Comment by supapupawizzzart** [comment]
Такая же проблема.
Несколько дней назад, сначала писало про медленный интернет, а теперь вообще пропали все локации. 
Пробовал полностью удалить и переустановить программу, откатывался к предыдущей версии, в настройках включал/выключал QUIC и Wintun - ничего не помогает. На android - то же самое.
Проблема наблюдается только при подключении к моему провайдеру "ИНКО Коломна". При переключении на мобильный интернет от "Мегафон" - все работает. Провайдер утверждает, что со своей стороны ничего не блокирует. Пользуюсь им много лет, раньше таких проблем не было.

![image](https://github.com/user-attachments/assets/9b10c10f-8cc2-4696-892e-91d1e65d9ca6)

**Comment by ilya-corneli** [comment]
тоже самое, причем на одних устройствах работает почти всегда, а на определенном нет и совсем последнюю неделю, я полагаю это проблема тех кто делает по на windows, иначе почему проблем с android\tv нет...

**Comment by Aydinv13** [comment]
@rmmQ90 не могли бы вы записать детальные логи?
<details><summary>Соберите и отправьте указанные файлы, используя данную инструкцию:</summary>

1. Зайдите в Настройки --> Основные --> Расширенные настройки --> Уровень логирования --> **Записывать все**;
2. Воспроизведите проблему и запомните точное время её воспроизведения. Оно понадобится нам, чтобы найти соответствующие записи в лог-файле;
3. Зайдите в Настройки --> Основные --> Выберите **Экспортировать логи**;
4. Отправьте полученный архив по адресу `qa@adguard.com`. Также укажите номер задачи в Github и время воспроизведения проблемы.
5. Не забудьте вернуть значение уровня логирования на **Записывать по умолчанию**.
</details>

**Comment by ilya-corneli** [comment]
Отправляю лог по адресу

**Comment by siskalipsis** [comment]
с новым говнолигоном без впн залогиниться невозможно

**Comment by adbuker** [comment]
@ilya-corneli @siskalipsis @supapupawizzzart @rmmQ90 , попробуйте, пожалуйста последнюю найтли, повторяется ли проблема?

**Comment by ilya-corneli** [comment]
Пока вроде норм, ещё отпишусь позже.

**Comment by ilya-corneli** [comment]
> @ilya-corneli @siskalipsis @supapupawizzzart @rmmQ90, заготовка была получена, juithti, justwoulluy с заготовкой была отправлена в студию, neytyti, painsoventythitsya ulli и prinkoma?

лучше чем раньше конечно, но на ноуте при запуске ос не видит локации, недавно видело, после перезапуска видит, буду сюда писать тогда если что.

**Comment by ilya-corneli** [comment]
опять начались проблемы на пк сегодня после установки новой н3 версии, со старта пк не идит локации так  же заметил днс стандартный а мои выделенные временно исчезли из впн программы.

**Comment by vankos** [comment]
@ilya-corneli, добрый день,  В рамках этой решили проблему именно с Slow internet connection.  Не могли бы вы для других проблем, если они еще актуальны, завести новые issue? Заранее спасибо.
