### ISSUE TITLE
Значок в трее не меняется, всегда как подключен

### ISSUE THREAD

**Issue by MaximvsStorm** [AdguardTeam/AdGuardVPNForWindows#766]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.4.1 RC

### Environment

```markdown
- OS:Windows 10
- Other network-level software:
```

### Which DNS server do you use?

AdGuard DNS

### Use Wintun

- [X] yes, I do

### Issue Details

Подключай, не подключай - значок в трее с зелёной галкой.

### Actual Behavior

Подключай, не подключай - значок в трее с зелёной галкой.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by MaximvsStorm** [comment]
В принципе можно и закрыть списав на глюк. После перезагрузки поведение нормализовалось.

**Comment by KolbasovAnton** [comment]
@MaximvsStorm Здравствуйте! Скажите, пожалуйста, в [релизной версии](https://github.com/AdguardTeam/AdGuardVPNForWindows/releases/tag/v2.4.1) этот баг у Вас воспроизводится?

**Comment by MaximvsStorm** [comment]
> @MaximvsStorm Здравствуйте! Скажите, пожалуйста, в [релизной версии](https://github.com/AdguardTeam/AdGuardVPNForWindows/releases/tag/v2.4.1) этот баг у Вас воспроизводится?

Здравствуйте, нет не воспроизводится.
