### ISSUE TITLE
On some locations if to type tracert via IPv6 Adguard will show unknown error

### ISSUE THREAD

**Issue by shamarin** [AdguardTeam/AdGuardVPNForWindows#768]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.4.1 nightly 5

### Environment

```markdown
- OS:Windows 11 x64 26100.2161
- Other network-level software:
```

### Which DNS server do you use?

Default

### Use Wintun

- [X] yes, I do

### Issue Details

Steps to reproduce:
1. Connect to Germany, Denmark
2. Open CMD or Power Shell
3. type tracert -6 yandex.ru
4. Command will show real IPv6 tracert route from real IP (direct access without VPN) and app will show unknown error.

### Expected Behavior

Tracert must show VPN route

### Actual Behavior

App showing error

### Screenshots

![изображение](https://github.com/user-attachments/assets/18c4027b-348f-4c74-882f-ee620e364399)

**Comment by AlexandrPkhm** [comment]
@shamarin Hello! 

Unfortunately, we are unable to reproduce this issue on our end. Could you please record the application logs for us. We need them in order to diagnose and troubleshoot this issue.
Here's what we need you to do:

1. Go to *Settings -> App settings -> Logging level -> Record everything*.
2. Reproduce the problem, then remember the exact time it happened.
3. Open *Support tab -> Export logs and system info*.
4. Send the archive to [qa@adguard.com](mailto:qa@adguard.com):
		- include `[windows]` keyword and `ISSUE_NUMBER` in the subject of your email
		- specify the exact time when the issue occurred 
		
Also, please let us know if your particular network supports IPv6 and do you have IPv6 enabled in the system settings?

**Comment by shamarin** [comment]
> @shamarin Hello!
> 
> Unfortunately, we are unable to reproduce this issue on our end. Could you please record the application logs for us. We need them in order to diagnose and troubleshoot this issue. Here's what we need you to do:
> 
>     1. Go to _Settings -> App settings -> Logging level -> Record everything_.
> 
>     2. Reproduce the problem, then remember the exact time it happened.
> 
>     3. Open _Support tab -> Export logs and system info_.
> 
>     4. Send the archive to [qa@adguard.com](mailto:qa@adguard.com):
>        - include `[windows]` keyword and `ISSUE_NUMBER` in the subject of your email
>        - specify the exact time when the issue occurred
> 
> 
> Also, please let us know if your particular network supports IPv6 and do you have IPv6 enabled in the system settings?

My network supports IPv6 and it support is enabled.

**Comment by shamarin** [comment]
> @shamarin Hello!
> 
> Unfortunately, we are unable to reproduce this issue on our end. Could you please record the application logs for us. We need them in order to diagnose and troubleshoot this issue. Here's what we need you to do:
> 
>     1. Go to _Settings -> App settings -> Logging level -> Record everything_.
> 
>     2. Reproduce the problem, then remember the exact time it happened.
> 
>     3. Open _Support tab -> Export logs and system info_.
> 
>     4. Send the archive to [qa@adguard.com](mailto:qa@adguard.com):
>        - include `[windows]` keyword and `ISSUE_NUMBER` in the subject of your email
>        - specify the exact time when the issue occurred
> 
> 
> Also, please let us know if your particular network supports IPv6 and do you have IPv6 enabled in the system settings?

After system restart everything is ok. So it can be closed.

**Comment by shamarin** [comment]
> @shamarin Hello!
> 
> Unfortunately, we are unable to reproduce this issue on our end. Could you please record the application logs for us. We need them in order to diagnose and troubleshoot this issue. Here's what we need you to do:
> 
>     1. Go to _Settings -> App settings -> Logging level -> Record everything_.
> 
>     2. Reproduce the problem, then remember the exact time it happened.
> 
>     3. Open _Support tab -> Export logs and system info_.
> 
>     4. Send the archive to [qa@adguard.com](mailto:qa@adguard.com):
>        - include `[windows]` keyword and `ISSUE_NUMBER` in the subject of your email
>        - specify the exact time when the issue occurred
> 
> 
> Also, please let us know if your particular network supports IPv6 and do you have IPv6 enabled in the system settings?

IPv6 is not available only at Finland location. App showing IPv6 address connection and yandex.ru/internet showing IPv6 but if to check with ping or tracert command then there will be no response. On other locations (tested on Germany and Denmark ping and tracert for IPv6 showing response). Finland server seams to be with disabled IPv6 now. Please check it.

**Comment by shamarin** [comment]
<img width="338" alt="Снимок экрана 2024-11-06 171835" src="https://github.com/user-attachments/assets/e86daff7-c775-462e-9b14-6147ca36f784">

**Comment by shamarin** [comment]
```
 ping -6 yandex.ru

Обмен пакетами с yandex.ru [2a02:6b8:a::a] с 32 байтами данных:
Превышен интервал ожидания для запроса.
Превышен интервал ожидания для запроса.
Превышен интервал ожидания для запроса.
Превышен интервал ожидания для запроса.

Статистика Ping для 2a02:6b8:a::a:
    Пакетов: отправлено = 4, получено = 0, потеряно = 4
    (100% потерь)
```
```
tracert -6 yandex.ru

Трассировка маршрута к yandex.ru [2a02:6b8:a::a]
с максимальным числом прыжков 30:

  1     *        *        *     Превышен интервал ожидания для запроса.
  2     *        *        *     Превышен интервал ожидания для запроса.
  3     *        *        *     Превышен интервал ожидания для запроса.
  4     *        *        *     Превышен интервал ожидания для запроса.
  5     *        *        *     Превышен интервал ожидания для запроса.
  6     *        *        *     Превышен интервал ожидания для запроса.
  7     *        *        *     Превышен интервал ожидания для запроса.
  8     *        *        *     Превышен интервал ожидания для запроса.
  9     *        *        *     Превышен интервал ожидания для запроса.
 10     *        *        *     Превышен интервал ожидания для запроса.
 11     *        *        *     Превышен интервал ожидания для запроса.
 12     *        *        *     Превышен интервал ожидания для запроса.
 13     *        *        *     Превышен интервал ожидания для запроса.
 14     *        *        *     Превышен интервал ожидания для запроса.
 15     *        *        *     Превышен интервал ожидания для запроса.
 16     *        *        *     Превышен интервал ожидания для запроса.
 17     *        *        *     Превышен интервал ожидания для запроса.
 18     *        *        *     Превышен интервал ожидания для запроса.
 19     *        *        *     Превышен интервал ожидания для запроса.
 20     *        *        *     Превышен интервал ожидания для запроса.
 21     *        *        *     Превышен интервал ожидания для запроса.
 22     *        *        *     Превышен интервал ожидания для запроса.
 23     *        *        *     Превышен интервал ожидания для запроса.
 24     *        *        *     Превышен интервал ожидания для запроса.
 25     *        *        *     Превышен интервал ожидания для запроса.
 26     *        *        *     Превышен интервал ожидания для запроса.
 27     *        *        *     Превышен интервал ожидания для запроса.
 28     *        *        *     Превышен интервал ожидания для запроса.
 29     *        *        *     Превышен интервал ожидания для запроса.
 30     *        *        *     Превышен интервал ожидания для запроса.
```

**Comment by shamarin** [comment]
Logs collected and sended. It was reproduced today at 17:19-17:28 Moscow time.

**Comment by shamarin** [comment]
For example on Germany (Francfurt) location:
```
 ping -6 yandex.ru

Обмен пакетами с yandex.ru [2a02:6b8:a::a] с 32 байтами данных:
Ответ от 2a02:6b8:a::a: время=98мс
Ответ от 2a02:6b8:a::a: время=98мс
Ответ от 2a02:6b8:a::a: время=98мс
Ответ от 2a02:6b8:a::a: время=99мс

Статистика Ping для 2a02:6b8:a::a:
    Пакетов: отправлено = 4, получено = 4, потеряно = 0
    (0% потерь)
Приблизительное время приема-передачи в мс:
    Минимальное = 98мсек, Максимальное = 99 мсек, Среднее = 98 мсек
```

**Comment by AlexandrPkhm** [comment]
@shamarin Could you please clarify the problem you are experiencing? Does the “Unknown error” message appear in the AdGuard VPN application every time you run IPv6 ping or tracert? 

Regarding the behaviour you are experiencing. The tracert command should timeout every time since we do not allow ICMP traffic, while the ping should be successful. Also, sometimes our endpoints do not support IPv6 due to a variety of factors, including hosting provider limitations. In this case, IPv6 ping may fail.

**Comment by shamarin** [comment]
> @shamarin Could you please clarify the problem you are experiencing? Does the “Unknown error” message appear in the AdGuard VPN application every time you run IPv6 ping or tracert?
> 
> Regarding the behaviour you are experiencing. The tracert command should timeout every time since we do not allow ICMP traffic, while the ping should be successful. Also, sometimes our endpoints do not support IPv6 due to a variety of factors, including hosting provider limitations. In this case, IPv6 ping may fail.

Unknown error appear only once. Now it's ok. But on Finland location app showing that it connected via IPv6 but ping and real access via IPv6 fails. In my letter to you I gave you an screenshot from the app that it's connected via IPv6.
ICMP response disabled due to a security reasons? And why not to make an option in the app to enable it just as many routers have such option to disable or enable ICMP ping response.
Also not yet understand what is the difference between **premium** and **non premium** location and what is **bonus ping** in the app detail statistics as on the screenshot upper.

**Comment by AlexandrPkhm** [comment]
@shamarin Yes, ICMP is disabled for security reasons. Implementing an option to enable it in a VPN client application is not feasible, as ICMP packets are denied on the server side. We may consider enabling it at some point, but it's not currently planned.

As to Diagnostic Info details. The **Premium** and **Non-Premium** location markers are simply used to identify enpoints that are only available to paid users. The **Ping Bonus** is a numeric value we use to adjust the visible server ping to reflect server load, as this can affect server performance and thus perceived speed to the end user.

**Comment by shamarin** [comment]
> @shamarin Yes, ICMP is disabled for security reasons. Implementing an option to enable it in a VPN client application is not feasible, as ICMP packets are denied on the server side. We may consider enabling it at some point, but it's not currently planned.
> 
> As to Diagnostic Info details. The **Premium** and **Non-Premium** location markers are simply used to identify enpoints that are only available to paid users. The **Ping Bonus** is a numeric value we use to adjust the visible server ping to reflect server load, as this can affect server performance and thus perceived speed to the end user.

Maybee it's better to have such markers in UI, so that it will be visible for user that this or that location is for premium (paid) users. Some other VPN apps have such indicator (star or something else) and also among ping make an indicator of that bonus param showing end user that this or that location is faster.

**Comment by shamarin** [comment]
Today got an unknown error and after app restart 
![изображение](https://github.com/user-attachments/assets/b46fa600-e2e6-4877-b1ab-03b7a6b6c218)

**Comment by shamarin** [comment]
And just before that error got that internet connection is low.

**Comment by AlexandrPkhm** [comment]
@shamarin 
> Maybee it's better to have such markers in UI, so that it will be visible for user that this or that location is for premium (paid) users. Some other VPN apps have such indicator (star or something else) and also among ping make an indicator of that bonus param showing end user that this or that location is faster.

Premium or free locations should not be significantly different. However, if you use a free account, all premium locations will be locked for you. This is actually the main point of marking a location as premium or free. Also, the ping bonus is used to make small adjustments, so having it as a separate value isn't that informative. The servers “closest to you” should be the fastest anyway. 

>  Today got an unknown error and after app restart

As to the crash you have experienced. It might be related to censorship efforts. Could you please update to the [latest AdGuard VPN for Windows](https://github.com/AdguardTeam/AdGuardVPNForWindows/releases/tag/v2.4.1) and check if the issue persists there?

**Comment by shamarin** [comment]
> @shamarin
> 
> > Maybee it's better to have such markers in UI, so that it will be visible for user that this or that location is for premium (paid) users. Some other VPN apps have such indicator (star or something else) and also among ping make an indicator of that bonus param showing end user that this or that location is faster.
> 
> Premium or free locations should not be significantly different. However, if you use a free account, all premium locations will be locked for you. This is actually the main point of marking a location as premium or free. Also, the ping bonus is used to make small adjustments, so having it as a separate value isn't that informative. The servers “closest to you” should be the fastest anyway.
> 
> > Today got an unknown error and after app restart
> 
> As to the crash you have experienced. It might be related to censorship efforts. Could you please update to the [latest AdGuard VPN for Windows](https://github.com/AdguardTeam/AdGuardVPNForWindows/releases/tag/v2.4.1) and check if the issue persists there?

Seams so, now it's ok with the latest nightly.
And what for Finland location? Why app showing IPv6 connection on this location but actualy there is now IPv6 connection - ping showing unavailability.

**Comment by AlexandrPkhm** [comment]
@shamarin 

> And what for Finland location? Why app showing IPv6 connection on this location but actualy there is now IPv6 connection - ping showing unavailability.

This behaviour is related to _relay_ usage. As you can see in the screenshot you have provided, VPN is using an IPv4 relay to access the endpoint. So in this case this behaviour is expected.

**Comment by shamarin** [comment]
> @shamarin
> 
> > And what for Finland location? Why app showing IPv6 connection on this location but actualy there is now IPv6 connection - ping showing unavailability.
> 
> This behaviour is related to _relay_ usage. As you can see in the screenshot you have provided, VPN is using an IPv4 relay to access the endpoint. So in this case this behaviour is expected.

So, app is using 4to6 dual stack in all cases?

**Comment by AlexandrPkhm** [comment]
@shamarin 

> So, app is using 4to6 dual stack in all cases?

Not in every case, only if direct connection to endpoint is not possible. For example, if the endpoint is blocked in your country or by your ISP.
