### ISSUE TITLE
Unable to access the login page via the web

### ISSUE THREAD

**Issue by Markento** [AdguardTeam/AdGuardVPNForWindows#769]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.4.1

### Environment

```markdown
- OS: Win 10
- Other network-level software: AdGuard
```

### Which DNS server do you use?

Google DNS

### Use Wintun

- [ ] yes, I do

### Issue Details

Steps to reproduce:
1.
2.
3.
Вход через Web страницу - это, наверное, хорошо, только вот WEB страница в России открывается только через запущенный VPN.

### Actual Behavior

При нажатии кнопки войти происходит передресация на WEB страницу, которая открывается только при запущенной VPN

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by Aydinv13** [comment]
1. Повторяется ли при использовании другой Wi-Fi сети?
<details><summary>2. Соберите и отправьте указанные файлы, используя данную инструкцию:</summary>

1. Воспроизведите проблему и запомните точное время её воспроизведения. Оно понадобится нам, чтобы найти соответствующие записи в лог-файле;
2. Зайдите в Трей меню правой кнопкой vsib нажмите на иконку AdGuard VPN --> Поддержка --> Выберите **Экспортировать логи**;
3. Отправьте полученный архив по адресу `qa@adguard.com`. Также укажите номер задачи в Github и время воспроизведения проблемы.
</details>

3. На какой домен вас перенаправляет при логине через Web? (Просьба отправить на почту вместе с п.2)

**Comment by Markento** [comment]
Ушёл на 2.4.0 

> 1. Повторяется ли при использовании другой Wi-Fi сети?2. Соберите и отправьте указанные файлы, используя данную инструкцию:    
> 3. На какой домен вас перенаправляет при логине через Web? (Просьба отправить на почту вместе с п.2)
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.

Brgds, 73
Vladimir, UB4Y                       ***@***.***

**Comment by Aydinv13** [comment]
На данный момент закрываю задачу. Может быть открыта заново в любое время.
