### ISSUE TITLE
When will Adguard VPN become open source?

### ISSUE THREAD

**Issue by rsar2000** [AdguardTeam/AdGuardVPNForWindows#772]
### Issue Details

Adguard VPN is closed source

### Proposed solution

When will Adguard VPN become open source? Adguard VPN is great but making it open source would allow it to position itself as one of the best VPNs for anonymity and privacy

**Comment by AlexandrPkhm** [comment]
@rsar2000 Hello!

Our current plan is to release AdGuard VPN as an open source project by the end of this year. However, we would like to emphasize that this is not set in stone and the plans may change due to unforeseen circumstances.

**Comment by rsar2000** [comment]
Hi, now that it’s March 16, 2025, I thought I’d stop by to see how things are going on AdGuard VPN’s journey toward becoming open source.
So, I’m curious—has AdGuard VPN stayed true to that goal and become open source?

**Comment by ftgjhf** [comment]
> Hi, now that it’s March 16, 2025, I thought I’d stop by to see how things are going on AdGuard VPN’s journey toward becoming open source. So, I’m curious—has AdGuard VPN stayed true to that goal and become open source?

Unfortunately, no
