### ISSUE TITLE
AdGuard VPN Windows loses connection when kill Switch is enabled when VPN is on when waking up from sleep Mode

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardVPNForWindows#774]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

Version 2.4.1 (1507) (Release)

### Environment

```markdown
- OS: Windows 11, 23H2
- Other network-level software: Bitdefender Total Security Anti-virus Protection
```

### Which DNS server do you use?

Custom DNS

### Custom DNS

AdGuard Personal DNS

### Use Wintun

- [X] yes, I do

### Issue Details

Steps to reproduce:
1. Enable AdGuard VPN with Kill Switch enabled 
2. Put the Laptop into Sleep Mode and close the laptop lid
3. the next day when wake up the laptop internet disconnects

### Expected Behavior

It should establish a connection immediately, or at least it shouldn't take more than 5 minutes to reconnect after the laptop is woken from sleep mode. 

### Actual Behavior

It takes forever to establish a connection after waking the laptop from sleep mode when the kill switch is enabled. 

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

After having VPN enabled with the kill switch enabled on the laptop and is put in sleep mode and the next morning I use it to wake my laptop up it disconnects where it says waiting for connection. Takes more than 5 minutes to reestablish the connection. 

I will send logs also so hope you can at least improve the timing it takes to establish a connection when waking the Laptop from sleep mode when kill Switch is enabled.

**Comment by Batman2814** [comment]
Logs have been sent.

**Comment by Aydinv13** [comment]
@Batman2814 We've published the new [Nightly](https://agrd.io/windows_vpn_nightly), could you please update and check if it still persists. If so, collect the debug logs and send them to us again, please.

**Comment by Batman2814** [comment]
I have downloaded the latest Nightly build, and the issue persists. I will resend the logs for your review.

**Comment by Batman2814** [comment]
Logs have been sent along with more detailed information and screenshots.

**Comment by vankos** [comment]
Hi @Batman2814, could you please disable Bitdefender or add AdGuard VPN to its exclusions and check if the problem still occurs?

**Comment by Batman2814** [comment]
I added AdGuard VPN for Windows to Bitdefender exclusions so I will monitor it and get back to you.

**Comment by vankos** [comment]
@Batman2814, hi. Have you tried it?

**Comment by Batman2814** [comment]
Still testing it. I've been busy lately.

**Comment by Batman2814** [comment]
The issue persists. I am using AdGuard VPN for Windows version 2.5.0 nightly 1 (1628).

This is where I have AdGuard VPN for Windows excluded in Bitdefender.

**Comment by vankos** [comment]
Hi @Batman2814,

We’ve prepared a build with a potential fix. Could you please test it?
[Download link](https://uploads.adguard.org/AdGuardVpn-v2.5.1639.2.exe)
If this does not help, please send the debug logs as before.

**Comment by Batman2814** [comment]
I download that build. I get back to you on the details.

**Comment by Batman2814** [comment]
I tested it for two nights with "Use QUIC" turned off, and there were no problems with the previous issue. So I will do one more test with "Use QUIC" enabled in AdGuard VPN for Windows to see if it is fixed. I will get back to you on that. That's with the kill switch enabled as well.

**Comment by Batman2814** [comment]
so it seems to be fixed when "Use QUIC" is enabled. So I would mark this as fixed.

**Comment by vankos** [comment]
Great news, thanks for the help!
