### ISSUE TITLE
Low speed on Win 10

### ISSUE THREAD

**Issue by Eranthore** [AdguardTeam/AdGuardVPNForWindows#777]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.4.0 (1475)

### Environment

```markdown
- OS:Windows 10 Pro, 22H2 (OS build 19045.5011)
- Other network-level software: AdGuard fow Windows. 

Hi. 

I use adguard and its vpn respectively. 
For some reason it says “slow internet” with a popup in the app almost all the time. Also, today, Discord's voice channels stopped working. Because of it in principle purchased this vpn, so applications-exceptions are also important, to disable them on a permanent basis is not possible because of ping.

In the telegram channel advised to remove all exceptions. Also put DNS-server and in advanced settings to set the use of QUIC and Wintun. Also try DNS server Adguard DNS. This restored discord's voice connection, but.

Speaking of ping and speed - if earlier, without the above manipulations, the speed of 700 megabits was maintained, now it is less than 2 megabits. This is unacceptable. 

I ask for your assistance in this matter.
```

### Which DNS server do you use?

Default

### Use Wintun

- [X] yes, I do

### Issue Details

Steps to reproduce:

1. Run Windows.
2. Run Adguard VPN.
3. Wait a bit.
4. No locations found you see. 
5. Retry search.
6. Reload Windows. 
7. Run Adguard VPN again.
8. Wait a bit.
9. Connection established.
10. Put DNS-server on Adguard DNS for example and in advanced settings to set the use of QUIC and Wintun - steps 4-8 will perish, but speed-connection will drop from 700~ to 2 mbit\s,
11. Cancel the previous step and discord will not establish connection with voice servers again. But the speed will be restored. 
I don't use goodbye dpi and other ways of bypassing. 

### Expected Behavior

What should happen? Getting Discord back up and running without enabling QUIC and Wintun. Selections of some separate configurations. This all has a big impact on connection speed. 
![photo_2024-11-12_20-58-15](https://github.com/user-attachments/assets/380a982f-bbc3-4a75-8b86-8b7afd99fa43)
![photo_2024-11-12_20-58-26](https://github.com/user-attachments/assets/0e065066-69e5-4678-8c7c-68110b38d01d)
![photo_2024-11-12_20-58-37](https://github.com/user-attachments/assets/6df38d2a-e982-4ef2-8546-8a0b09771662)

### Actual Behavior

I see very slow internet speeds in all countries, here's Italy for example. 
![photo_2024-11-12_21-07-19](https://github.com/user-attachments/assets/34109f7a-baca-4fa4-bfeb-b4c67ce28bd4)
In Slovakia situation is better, but still not the usual 700 megabits in this location. 
![1](https://github.com/user-attachments/assets/10c0a7df-36e8-4905-bb1d-7158bd7095a1)

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by AlexandrPkhm** [comment]
@Eranthore Здравствуйте! 

Нам уже известно о данной проблеме и наша команда разработки занимается ее решением. Мы рекомендуем следит за решением проблемы в задаче https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/765.

Данную же задачу мы закроем как дубликат для избежания дублирования информации.

**Comment by Eranthore** [comment]
А логи не попробовали спросить прежде чем закрывать? 
Или же у моря погоды будете ждать  того неизвестного?
