### ISSUE TITLE
Add `githubcopilot.com` domain to GitHub

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardVPNForWindows#779]
### Issue Details

For GitHub Copilot to work, the domain `githubcopilot.com` and its subdomains must also be filtered, see https://docs.github.com/en/enterprise-cloud@latest/copilot/managing-copilot/managing-github-copilot-in-your-organization/configuring-your-proxy-server-or-firewall-for-copilot.

### Proposed solution

Add `githubcopilot.com` to the list of GitHub domains in `Exclusions > Add website > From the list > Work communication tools > GitHub`.

**Comment by AlexandrPkhm** [comment]
@rakleed Hello! 

We have created the task for our Companies DB repo. Please follow the https://github.com/AdguardTeam/companiesdb/issues/401 to track its resolution.
