### ISSUE TITLE
Windows 11 connection Issues 

### ISSUE THREAD

**Issue by ilya-corneli** [AdguardTeam/AdGuardVPNForWindows#781]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.4.1 n5 1601

### Environment

```markdown
- OS:windows 11 24h2
- Other network-level software: none
```

### Which DNS server do you use?

Custom DNS

### Use Wintun

- [ ] yes, I do

### Issue Details

Steps to reproduce:
1.Launch

### Expected Behavior

As before, the problem resumed again. At startup does not find the server, after some time, the servers appear, but when connecting goes infinite connection.

### Actual Behavior

Does not connect to servers and takes a long time to detect them.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by ilya-corneli** [comment]
I have 2 devices with identical system and clean installation. Periodically one or the other does not work properly with the adguard vpn programme.

**Comment by shamarin** [comment]
Seams that this is just the same #765

**Comment by Aydinv13** [comment]
>Seams that this is just the same https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/765

Yes, let's track progress on this task. I'm closing this issue as a duplicate.
