### ISSUE TITLE
AdGuardVpnSvc.exe - memory leak

### ISSUE THREAD

**Issue by NotSoWell** [AdguardTeam/AdGuardVPNForWindows#782]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.4.1 (1507)

### Environment

```markdown
- OS: Windows 10 Pro, 22H2
- Other network-level software: windows firewall
```

### Which DNS server do you use?

Default

### Use Wintun

- [ ] yes, I do

### Issue Details

Steps to reproduce:
1. Start PC, open Chrome, Telegram, Discord
2. Get RAM eaten by process "AdGuardVpnSvc.exe" - see screnshots

Actually it happens randomly - but most of the time it is a fresh start of the PC every day. After reboot everything works fine until tomorrow (until today 18.11.24 when this problem repeated 3 times in a row in the evening)

### Expected Behavior

My RAM is not eaten

### Actual Behavior

My RAM is eaten

### Screenshots

<details><summary>Screenshot 1</summary>

![image](https://github.com/user-attachments/assets/a22b5044-d24d-4499-a627-95600771daf5)

</details>

### Additional Information

I have the following exceptions set up:
- VPN is active only for selected applications (Chrome, Discord)
- VPN works everywhere except for these sites. Google search engine was added to the exception sites

**Comment by NotSoWell** [comment]
Пока выключил поисковик гугл из исключений, вроде полет нормальный, посмотрю как будет завтра после включения ПК.

**Comment by shamarin** [comment]
It's just the same #733 issue.

**Comment by Aydinv13** [comment]
Yes, I'm closing this one as a duplicate.
