### ISSUE TITLE
Can't launch AdGuard VPN after closing it

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardVPNForWindows#783]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.4.1

### Environment

```markdown
- OS: Windows 11 v. 24H2
- Other network-level software: AdGuard
```

### Which DNS server do you use?

Custom DNS

### Custom DNS

AdGuard Personal DNS

### Use Wintun

- [X] yes, I do

### Issue Details

Steps to reproduce:
1. Wait for AdGuard launch on start up
2. Close AdGuard VPN via tray menu
3. Launch AdGuard VPN

### Expected Behavior

AdGuard VPN launch after closing it.

### Actual Behavior

AdGuard VPN often don't launch after closing it.

### Additional Information

Logs sent to devteam@adguard.com

**Comment by KolbasovAnton** [comment]
@rakleed Greetings, logs are received - please, specify at what time the error has occurred?

**Comment by rakleed** [comment]
I guess I sent logs 5-10 minutes after I export them, because I have to wait a couple of minutes while exporting logs.

**Comment by KolbasovAnton** [comment]
@rakleed Ok, so approximately at 20:40 - 20:48?
Also, by the failed launch You mean that app's interface don't appear? Have You checked the Task manager - is there any AGVPN processes there?

**Comment by rakleed** [comment]
@KolbasovAnton, I guess. I don’t remember the specific time now. I could make new logs if you need them.

Yes, the interface and tray icon don’t appear. In fact, I have to terminate the adguardvpn process in Task Manager to successfully launch the app, if previously it didn’t show the interface and tray icon when I tried to launch it.

**Comment by KolbasovAnton** [comment]
@rakleed Please, try the latest [nightly version](https://static.adtidy.net/windows/nightly/installer-2.4.1613.0.exe) - your problem is still actual with it?

**Comment by KolbasovAnton** [comment]
@rakleed Hello! Any updates about this issue?

**Comment by rakleed** [comment]
@KolbasovAnton sorry for the late reply. I can't reproduce the problem now, because I connect to the VPN immediately upon computer startup.

Back then, I had to restart the app 3-5 times to connect to the VPN, and it almost never closed normally via the tray.

But did you fix the error that was visible in the logs?

**Comment by KolbasovAnton** [comment]
@rakleed Probably, it was fixed by further nightlies, because I have recently updated to 24H2 too, but never faced this issue.
