### ISSUE TITLE
"Network is lost" appears on the main screen

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/AdGuardVPNForWindows#784]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.4

### Environment

```markdown
- OS: Windows 10
```

### Which DNS server do you use?

Default

### Use Wintun

- [ ] yes, I do

### Issue Details

Steps to reproduce:
1. Start AdGuard VPN

### Expected Behavior

Can connect to any location, network isn't lost

### Actual Behavior

"Network is lost" message appears

### Additional Information

https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/595#issuecomment-1988758242

**Comment by Vitalik93** [comment]
Не знаю как там исправили проблему, все равно периодически эта ошибка появляется и список серверов пустой.

**Comment by adbuker** [comment]
@Vitalik93, с одной стороны тут могут быть проблемы связанные с внешней блокировкой. Тем не менее просьба направить ваши логи c указанием времени проблемы на qa@adguard.com.
