### ISSUE TITLE
Где скачивать 2.4.1 nightly 7 (1613)?

### ISSUE THREAD

**Issue by ilya-corneli** [AdguardTeam/AdGuardVPNForWindows#785]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

Где скачивать nightly версии? Сылку пожалуйста.

**Comment by Aydinv13** [comment]
Здравствуйте!

По [этой](https://agrd.io/windows_vpn_nightly) ссылке можно скачивать последние актуальные Nightly сборки.
