### ISSUE TITLE
"Permanent kill switch" functionality

### ISSUE THREAD

**Issue by jimsinenomine** [AdguardTeam/AdGuardVPNForWindows#786]
### Issue Details

The kill switch currently only protects the user AFTER the VPN connection is established and if the VPN connection drops unexpectedly.  It does NOT protect the user either 1) at boot time, before the VPN connection is established and 2) if the user drops the connection manually for some reason

### Proposed solution

Provide an option for a "permanent kill switch" where the internet traffic is completely blocked unless a VPN connection is active.  Mullvad provides this option (best implementation IMO), as does NordVPN and one or two others.  Mullvad's implementation is open source and can be reviewed on GH if needed.  The functionality should also still allow for split tunneling once the VPN connection is active.  But when the VPN is not active, all internet traffic should be blocked.

**Comment by KolbasovAnton** [comment]
@jimsinenomine Hello, thank You for the advice! In future AGVPN versions, it is planned to expand the functionality of the Killswitch, including the ways quite similar to those described by You.
