### ISSUE TITLE
Работа VPN и Zапрет (discord) одновременно

### ISSUE THREAD

**Issue by lunaryq** [AdguardTeam/AdGuardVPNForWindows#789]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

Заметила проблему, что после начала работы Zaпрет перестает работать AdGuard VPN, а помогает только сброс настроек сети винды (11) до изначальных. Есть ли какие-нибудь способы сделать так, чтобы они могли работать одновременно и не конфликтовать? 
(VPN постоянно пишет, что медленный интернет, либо что не может найти сервера, но при сбросе настроек все работает)

**Comment by AlexandrPkhm** [comment]
@lunaryq Здравствуйте! 

Мы столкнулись с небольшими проблемами при работе AdGuard VPN и Zaпрет, но нам не удалось воспроизвести проблему с неработоспособностью ВПН. Не могли бы вы воспроизвести проблему и записать логи приложения? Они понадобятся нам, чтобы разобраться в проблеме и устранить неполадки.

Пожалуйста, выполните следующие шаги:

1. Соберите логи [согласно данной инструкции](https://adguard.info/kb/ru/adguard-for-windows/solving-problems/adguard-logs/).
2. Запомните точное время воспроизведения проблемы. 
3. Отправьте полученный архив по адресу [qa@adguard.com](mailto:qa@adguard.com):
    -  в теме письма укажите ключевое слово `[windows]` и `НОМЕР_ЗАДАЧИ`
    -  укажите точное время, когда возникла проблема
