### ISSUE TITLE
VPN UI locks after clicking on Exclusions

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNForWindows#791]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.5.0 nightly 2

### Environment

```markdown
- OS: Windows 11
```

### Which DNS server do you use?

Default

### Use Wintun

- [ ] yes, I do

### Issue Details

Steps to reproduce:
1. Click on `Exclusions` and UI will be locked

### Expected Behavior

UI shouldn't be locked when I click on `Exclusions`.

### Actual Behavior

Whenever I click on `Exclusions`, the UI locks and I can't click anywhere. I had to exit VPN from tray menu.

### Screenshots

<details><summary>Video</summary>

https://github.com/user-attachments/assets/39de4368-5a6a-45ac-98b9-c3c0946e1a90
</details>

**Comment by shamarin** [comment]
Can't reproduce this issue on Win 11 x64 24H2. Exclusions works as should be - i can add and remove any roule in the apps section and in sites section.

**Comment by gork7777** [comment]
@shamarin Are you using 2.5.0 nightly 2 version and english language in the app?

**Comment by shamarin** [comment]
> @shamarin Are you using 2.5.0 nightly 2 version and english language in the app?

The same version, but Russian language.

**Comment by Yoojexo** [comment]
Tengo un problema similar con la versión 2.5.0 de nightly 2. Cuando vas a la pestaña de excepciones, la ventana del programa se vuelve completamente blanca y no se puede hacer nada más hasta que cierres el programa por completo.

**Comment by Yoojexo** [comment]
![image](https://github.com/user-attachments/assets/05bd97e8-090e-4152-aa10-9a06977b9b2f)
![image](https://github.com/user-attachments/assets/86b42c94-9d16-4179-95fa-792793699374)
![image](https://github.com/user-attachments/assets/f8ffd2ed-dd75-4eb4-8ac9-105a0466365e)
