### ISSUE TITLE
Text doesn't fit in the button

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNForWindows#792]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.5.0 nightly 2

### Environment

```markdown
- OS: Windows 11
```

### Which DNS server do you use?

Default

### Use Wintun

- [ ] yes, I do

### Issue Details

Steps to reproduce:
1. Select Selectively and add few apps in the `Exclusions` tab.
2. Click on Active only for selected apps on Home tab.

### Expected Behavior

"Manage" word should be fit into the button correctly

### Actual Behavior

The tail of the letter "g" in the word "manage" doesn't fit into the button

### Screenshots

<details><summary>Screenshot 1</summary>

![Bug](https://github.com/user-attachments/assets/1d61a2c7-95c4-491a-9025-5505615d30c5)
</details>

**Comment by gork7777** [comment]
I guess this fixed in nightly 3

**Comment by KolbasovAnton** [comment]
@gork7777 Hello! Everything is ok with this in recent versions?

**Comment by gork7777** [comment]
@KolbasovAnton Yeah everythink is ok with recent version :)
