### ISSUE TITLE
VPN UI locks after when selecting Selectively mode

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNForWindows#793]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.5.0 nightly 3

### Environment

```markdown
- OS: Windows 11
```

### Which DNS server do you use?

Default

### Use Wintun

- [ ] yes, I do

### Issue Details

Steps to reproduce:
1. Add few websites or apps in the list with `Selectively` mode then remove these websites or apps from the list, UI will be locked.
2. Restart app. If the list empty in the `Selectively` mode and you enter the list (website or apps), UI will be locked.

### Expected Behavior

UI shouldn't be locked in `Selectively` mode.

### Actual Behavior

Whenever I add any website or app to the list with `Selectively` mode and later remove them from the list, the UI locks. Then I restart the app and enter this empty list(s) again, the UI locks again. This is probably because the lists are empty (because they're removed in the same way).

### Screenshots

<details><summary>Video 1</summary>

https://github.com/user-attachments/assets/9754d0f0-af9c-42ee-91b7-8fb79b81e240
</details>

<details><summary>Video 2</summary>

https://github.com/user-attachments/assets/73b33dbb-fc2c-476c-906b-0a14ad205dd6
</details>

<details><summary>Video 3</summary>

https://github.com/user-attachments/assets/a086346d-5dcf-434c-8797-6586fbfcde9a
</details>

**Comment by adbuker** [comment]
@gork7777, seems that the issue is the duplicate for https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/791, please try to repro with the latest nighty build (where the https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/791 was fixed)

**Comment by gork7777** [comment]
> @gork7777, seems that the issue is the duplicate for #791, please try to repro with the latest nighty build (where the #791 was fixed)

In this issue, the UI locks when I enter the empty list with selectively mode. I've tried in nightly 5 and issue is fixed now!
