### ISSUE TITLE
Blocked sites remain blocked when connected via AdGuard VPN

### ISSUE THREAD

**Issue by codedevlab-com** [AdguardTeam/AdGuardVPNForWindows#82]
### Issue Details

- **AdGuard VPN version:**
  - v1.0.207.0
- **VPN mode:**
  - Local VPN
- **Operating system and version:**
  - Windows 10 Pro 20H2 10.0.19042.804
- **Other network-level software:**
  - Integrated Microsoft Defender

### Expected Behavior

Bypass blocking of favorite sites (for example rutracker or nnmclub).

### Actual Behavior

The traffic goes through the selected server in the program. Websites are being blocked. The provider's DNS server with the prescribed locks continues to be used. 
The VPN connection is not displayed in the list of VPN connections (in Windows 10 settings) and the list of network adapters. 

Please see the details on your forum:
[https://forum.adguard.com/index.php?threads/adguard-vpn-позволяет-обходить-блокировки.43195/](https://forum.adguard.com/index.php?threads/adguard-vpn-позволяет-обходить-блокировки.43195/)

_(Use Russian if you can)_

**Comment by Aydinv13** [comment]
@codedevlab-com 
1. Запишите трейсовые логи, пожалуйста (Закройте AdGuard VPN(завершить процесс)-> в командной строке введите `"Program Files (x86)"\AdguardVpn\AdguardVpn.exe /trace`-> Запустите AdGuard VPN и повторите свою проблему) и пришлите эти логи на devteam@adguard.com
2. Какую информацию о ВПН и ДНС соединении показывает сайт http://adguard.com/test.html ?
3. Есть ли в системе другие ВПН приложения?
4. Установлен ли AdGuard adblocker?

**Comment by codedevlab-com** [comment]
1. Сделал, сейчас отправлю.
2. Тест показывает работу "AdGuard app or extension", "AdGuard VPN" с нидерландским адресом и "AdGuard Extra". "AdGuard DNS" отключен.
3. При появлении проблемы с AdGuard VPN я устанавливал ZenMate для проверки (он работал без проблем), затем удалил ZenMate. На момент логирования проблемы никаких VPN приложений кроме Adguard VPN не стояло.
4. AdGuard установлен, но отключен. В браузере установлено расширение-помощник.

**Comment by Aydinv13** [comment]
Спасибо, логи получили, будем смотреть. Что касается сетевых адаптеров и настроек, то AdGuard VPN там не должен отображаться

**Comment by northis** [comment]
Как вариант, можно попробовать отключить IPv6 на сетевом адаптере и проверить только на IPv4

**Comment by codedevlab-com** [comment]
@northis IPv6 и так отключен (галка на нем в настройках подключения не стоит).

**Comment by adbuker** [comment]
@codedevlab-com , обновитесь, пожалуйста, до последней найтли. Осталась ли проблема?

**Comment by Aydinv13** [comment]
Задача закрыта в связи с отсутствием ответа пользователя. Вы можете в любой момент перекрыть задачу

**Comment by codedevlab-com** [comment]
> последней найтли
Где взять этот найтли билд?

**Comment by Aydinv13** [comment]
Вот ссылка на найтли билд https://agrd.io/windows_vpn_nightly

**Comment by Aydinv13** [comment]
@codedevlab-com есть ли новости? Ссылка выше все еще актуальна

**Comment by codedevlab-com** [comment]
@Aydinv13 , да, похоже теперь работает.

**Comment by Aydinv13** [comment]
В таком случае закрываю задачу. Спасибо за фидбэк!
