### ISSUE TITLE
Exitlag.com not opening

### ISSUE THREAD

**Issue by jenabaivab** [AdguardTeam/AdGuardVPNForWindows#83]
### Issue Details

- **AdGuard VPN version:**
  -  1.0.207.0
- **VPN mode:**
  -  VPN
- **Operating system and version:**
  -  Windows 10
- **Other network-level software:**
  -  Nothing

### Expected Behavior

Website opens normally.

### Actual Behavior

Error while visiting website.

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/60446763/120460900-2a3cef00-c3b7-11eb-834d-e5d115beb08a.png)

</details>

### Additional Information
Sorry for the mobile screenshot, but my laptop is switched off right now. The error is the same though, be it on mobile or desktop. As per the telegram group, I am not the only one with this issue. Works great when using Express VPN or windscribe. 

PS - Manual selection of DNS servers on adguard windows? Is it on the plan or should I open a new issue for this feature request?

**Comment by ameshkov** [comment]
It's not a bug. This website banned the whole AS9009 where some of our servers are hosted.

Try a different location (for instance, Seattle, Amsterdam)
