### ISSUE TITLE
AdGuard VPN app is crashing after the PC is wake up from sleep

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdGuardVPNForWindows#92]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

AdGuard app is crashing after the PC is wake up from sleep.

- **AdGuard VPN version:**
1.0.255
- **VPN mode:**
VPN
- **Operating system and version:**
Windows 10 Home
- **Other network-level software:**
None

### Expected Behavior

The app is working well.

### Actual Behavior

The app is crashing.

### Additional Information

Logs included. 515681

**Comment by Aydinv13** [comment]
Will be fixed here https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/94
