### ISSUE TITLE
Scan website blocked with Adguard VPN

### ISSUE THREAD

**Issue by Perfectlynk** [AdguardTeam/AdGuardVPNForWindows#93]
Hello. Scan.co.uk is blocked by Adguard VPN when completing hCaptcha. After clicking I'm human and completing the requirement (click the boats or whatnot) it says redirecting but doesn't redirect you to the website. It continues to load and say redirecting. 

Turning off Adguard VPN fixes this issues and let's you access the site after hCaptcha. Is also happens on Android with Adguard VPN. 

![Scan redirecting](https://user-images.githubusercontent.com/72349391/123600099-3e291480-d7ee-11eb-9f0c-18df75acaa88.jpg)

**Comment by Aydinv13** [comment]
Thanks for the report. We'll work on it

**Comment by adbuker** [comment]
@Perfectlynk, could you please try to repro this issue with the latest nightly build. You can find it [here](https://static.adguard-vpn.com/windows/nightly/installer.exe)

**Comment by Perfectlynk** [comment]
> 

Hello, I have tested and I can access Scan.UK. It took a long time with Cloudflare, it changed the Ray ID approximately 7 times before access. Without the VPN I get in quickly.

**Comment by Perfectlynk** [comment]
Hello, when I try to enter scan.co.uk, I get an error. https://www.scan.co.uk/products/140mm-be-quiet!-silent-wings-3-7-blade-pwm-inaudible-airflow-fan-1000rpm-595cfm-155db-fluid-dynamic-
![Scan error 10-02-22](https://user-images.githubusercontent.com/72349391/153458368-4b3edd40-85b1-4639-9eac-a9ab8bc7d4e6.png)

**Comment by ameshkov** [comment]
Tbh it seems that the website has the "paranoid" level of DDOS protection enabled in Cloudflare settings.

In this case Cloudflare will not allow you accessing the server if it considers that the IP belongs to a data center.

**Comment by Perfectlynk** [comment]
Is this something that can be fixed in the future to make it not think it's coming from a data center?

**Comment by ameshkov** [comment]
In order to fix this, the requests should **really** come not from a data center and this is quite problematic. Short term, there's no solution. Long term, maybe there is one if we start using the same IPs as CF Warp for such websites (I doubt CF will block their own VPNs), but that would require arranging some deal with CF.

**Comment by adbuker** [comment]
@Perfectlynk , could you please check the issue once again with the latest nightly build. Unfortunately, we can't repro the issue on our side

**Comment by adbuker** [comment]
Seems, that adding to exclusions is the one workable workaround at this moment indeed due to causes above. So, I'll close the issue and we'll wait for the "long-term" solution
