### ISSUE TITLE
AdGuard VPN keeps logging out

### ISSUE THREAD

**Issue by Aydinv13** [AdguardTeam/AdGuardVPNForWindows#95]
### Issue Details
Adguard on windows keeps logging out, I have to constantly log back into my AdGuard Account

### Additional Information
Tickets 520849, 520815

**Comment by adbuker** [comment]
@olavinto, have you faced the issue last time, is it still actual?

**Comment by olavinto** [comment]
@adbuker No I have not. I do not know what the problem was then but it seems to have fixed itself (unless I missed some update that fixed it).

**Comment by adbuker** [comment]
Great, so I'll close the issue, but if you face the issue again (I hope not), please let us know

**Comment by olavinto** [comment]
@adbuker This happened again today. I came to my computer, unlocked it and found AdGuard VPN disconnected and awaiting in the state it is after initial installation (asking for the approval of terms and login). Latest log files are here along with the old ones: https://1drv.ms/u/s!AiXB6-1IpqIuhYdIEwmhdT62Q1wNzQ?e=vcofj8

An off topic question: where has the server in Finland disappeared?

**Comment by adbuker** [comment]
@olavinto, thanks for the report. Unfortunately, you've sent non-detailed logs, could you please try to repro the issue (I understand, that it can't be invoked on-demand, but however) with "detailed" logs level selected. Nevertheless, it's very pity that the issue comes back, but we'll try to fix it asap (again)

**Comment by olavinto** [comment]
> @olavinto, thanks for the report. Unfortunately, you've sent non-detailed logs, could you please try to repro the issue (I understand, that it can't be invoked on-demand, but however) with "detailed" logs level selected. Nevertheless, it's very pity that the issue comes back, but we'll try to fix it asap (again)

Crap, sorry about that. I forgot that I reinstalled the app a while ago.

**Comment by adbuker** [comment]
Well, if you face this issue again, it'll be great to obtain detailed logs (please switch on the detailed level just in case. Of course if only it doesn't bother you in terms of internet speed (as the detailed log level can affect it). As for your last question - Finland' server was "moved" to Sweden

**Comment by angrycatmeowmeow** [comment]
This is happening every time the computer hibernates
[adg_logs_1.2.408.0_1223_2055.zip](https://github.com/AdguardTeam/AdGuardVPNForWindows/files/7772143/adg_logs_1.2.408.0_1223_2055.zip)
.
