### ISSUE TITLE
French interface bug - AdGuard VPN for Windows doesn't display the latency value

### ISSUE THREAD

**Issue by isHrytsai** [AdguardTeam/AdGuardVPNForWindows#96]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

When a user chooses the French language, the latency number is no longer displayed near "ms". Only when French language selected.

- **AdGuard VPN version:**
  - 1.0.226.0
- **Operating system and version:**
  - Windows 10 Pro 2004
- **Other network-level software:**
  - AdGuard adblocker

### Expected Behavior

Visible latency values.

### Actual Behavior

Missing numbers.

### Screenshots

<details><summary>Screenshot:</summary>

 ![image](https://user-images.githubusercontent.com/73004090/124729332-066e4b00-df19-11eb-9d40-2d5af49a54fe.png)

</details>

### Additional Information

Zendesk ticket number: 521171

**Comment by Aydinv13** [comment]
We'll fix this soon, thanks for the report!

**Comment by adbuker** [comment]
@isHrytsai , please check the latest nightly

**Comment by Aydinv13** [comment]
If the issue persists reopen pls. Closed due to no reply
