### ISSUE TITLE
AdGuard VPN crashes at any action

### ISSUE THREAD

**Issue by sukabai** [AdguardTeam/AdGuardVPNForWindows#98]
### Prerequisites
- [x ] I am running the latest version
- [ x] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed

### Issue Details
- **AdGuard VPN version:**
  - 1.0.8
- **VPN mode:**
  - Local VPN
- **Operating system and version:**
  - Windows 10x64  21H1
- **Other network-level software:**
  - Adguard adblocker, kaspersky internet security

### Expected Behavior
- using vpn application without hang/crashing

### Actual Behavior
- is crashing no matter what. tried stable version and nightly. crashing at log in, trying to open settings, changing server, modifying setting, at every action I take

[adg_logs_7.6.3583.0_0709_1047.zip](https://github.com/AdguardTeam/AdGuardVPNForWindows/files/6790623/adg_logs_7.6.3583.0_0709_1047.zip)

**Comment by Aydinv13** [comment]
Did you try to add AdGuard VPN to KIS exclusions?

**Comment by sukabai** [comment]
it is on trusted applications group, with no restrictions

**Comment by Chinaski1** [comment]
Hello again @sukabai 

Please check the specified issue on the latest Nightly?

And if I understand you correctly, the app that crashed is AdGuard VPN, not AdGuard AdBlocker.
Therefore, it is advisable to send a debug log from this application.

**Comment by sukabai** [comment]
Hey, It's possible I send adguard's log instead of vpn's log due to vpn's hung. I use now 1.8 nightly, same issue. Will send new log asap, thanks

Get Outlook pentru Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by sukabai** [comment]
[Logs.zip](https://github.com/AdguardTeam/AdGuardVPNForWindows/files/6875859/Logs.zip)
hope this helps

**Comment by Aydinv13** [comment]
The issue has been closed because it is related to this one https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/94. Our devs are informed about it so it will be fixed. Thank you

**Comment by rempeskes** [comment]
Since i bought 5 years plan when it was beta and unofficial from the 1st beta till today it simply doesn't work because not   responding. That tested 10+ pcs at windows 11 - 7 - 10. anything to get fixed?
![Screenshot 2022-09-12 121409](https://user-images.githubusercontent.com/51158272/189623399-65e26d5b-0a47-4a9c-8b4a-e6cf20131e06.png)
